### ISSUE TITLE
Use of await can hang NodeJS

### ISSUE THREAD

**Issue by NealWalters** [sidorares/node-mysql2#1005]
I posted this a week or so ago: 
https://github.com/sidorares/node-mysql2/issues/1002

There is one problem that is still haunting me.  I have created a simple example to reproduce. 
If you comment out the connection it works fine, and "The End" message displays and NodeJS ends returning me to the command prompt. 

When I include the connection/await, "The End" message also appears but then nodeJS hangs, and never goes back to the command prompt; I have to hit Cntl-Break to get out of it. 

```
const mysqlSync  = require('mysql2/promise');
parseContent().then(result => {
   console.log("=== The End==="); 
})

async function parseContent()
{
    /*
	var  connection = await mysqlSync.createConnection({
			host: 'localhost',
			user: 'root',
			password: 'password',
			database: 'databaseName'
		});
    */
    console.log("end parseContent"); 
}
```

**Comment by NealWalters** [comment]
Solved by adding: 

> await connection.destroy(); 

Got the idea from this StackOverflow where someone mentioned needing to release his pools: 
https://stackoverflow.com/questions/32850045/node-js-synchronous-queries-with-mysql

**Comment by sidorares** [comment]
yes, node.js process exits only after there is no active handles registered with event loop, when you connect to mysql there is active network connection. See https://stackoverflow.com/questions/17960452/how-can-i-get-a-list-of-callbacks-in-the-node-work-queue-or-why-wont-node-ex/17960793#17960793 for some related explanations
