### ISSUE TITLE
How can I update few fields and escape data?

### ISSUE THREAD

**Issue by HulioEglesias** [sidorares/node-mysql2#1015]
How can I update some unknown fields in a row by ID?
I should use one method for update user
How I do now:
```js
const id = 1;
const fields = {name: 'Hulio', age: 12}; // object what I need to update. It can be { name: 'Hulio' } or { city: 'Chelyabinsk' }
const setStr = Object.keys(fields).map( key => `${key} = '${fields[key]}'` ).join(',')
mysql.query(`UPDATE tablename SET ${setStr}, WHERE id=${id}`);
```
But It's will not escaped data. How Can I use that case with escaping?

**Comment by sidorares** [comment]
have you tried just passing an object?

```js
mysql.query(`UPDATE tablename SET ?, WHERE id=?`, [fields, id]);
```

Also have a play with named placeholders - https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#named-placeholders I'm not 100& sure they'll work correctly with objects but it might work

**Comment by sidorares** [comment]
https://github.com/mysqljs/mysql#escaping-query-values

> Objects are turned into key = 'val' pairs for each enumerable property on the object. If the property's value is a function, it is skipped; if the property's value is an object, toString() is called on it and the returned value is used.
