### ISSUE TITLE
Promise Pool ignores namedPlaceholders on pool.query

### ISSUE THREAD

**Issue by derN3rd** [sidorares/node-mysql2#1018]
Hey there,

When I try to use the following (example) code below, the pool.query function ignores the passed namedPlaceholders option and uses the default from pool config.
```
const BluebirdPromise = require('bluebird')
const mysql = require('mysql2/promise')

const db = mysql.createPool({
  Promise: BluebirdPromise,
  host: dbCredentials.host,
  user: dbCredentials.user,
  password: dbCredentials.password,
  database: dbCredentials.database,
  charset: 'utf8mb4',
  namedPlaceholders: false,
})

db.query({
  sql: `SELECT id, name FROM user WHERE type NOT IN (:userTypes)`,
  values: {
    userTypes: [0, 1, 5, 6],
  },
  namedPlaceholders: true,
})
  .then(console.log)
  .catch(e => console.error(JSON.stringify(e)))
```
response:
```
{
  "message": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':userTypes)' at line 1",
  "code": "ER_PARSE_ERROR",
  "errno": 1064,
  "sqlState": "42000",
  "sqlMessage": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':userTypes)' at line 1"
}

```
I get the error response, where I can see that the placeholders are not replaced. If I change the pool config to `namedPlaceholders: true` it works. I get the same error when I switch to the non-promise version

Node Version: 8.15.1
Mysql2 Version: 1.6.5

**Comment by sidorares** [comment]
same issue with non-promise pool.query()

this line overwrites local options ( which correctly has `namedPlaceholders` set to true )  https://github.com/sidorares/node-mysql2/blob/c460c0fe9c9b47282f573801f6e883913752916f/lib/pool.js#L135

Need to change it to something like 

```js
if (typeof cmdQuery.namedPlaceholders === 'undefined') {
   cmdQuery.namedPlaceholders = this.config.connectionConfig.namedPlaceholders;
}
```

so it only sets parameter to one from global config if there is no local override

Do you want to test this, create unit test and create pr with change @derN3rd ?

**Comment by derN3rd** [comment]
Just fixed it with your proposed changes, but can't get the tests to work.
Should I just make a PR without the tests?

**Comment by sidorares** [comment]
make a PR and I'll help with tests ( or just add them on top of your commits )

**Comment by derN3rd** [comment]
I think something is broken with the pool test I created, so might need a check from you
