### ISSUE TITLE
timezone config validation is broken

### ISSUE THREAD

**Issue by damianobarbati** [sidorares/node-mysql2#1023]
Hey, I just noted that initting a pool with the following config:

```
const options = {
    uri: connectionURI,
    typeCast: true,
    dateStrings: false,
    timezone: 'Europe/Rome',
    namedPlaceholders: true,
};
```

Emits a:
```
Ignoring invalid timezone passed to Connection: Europe/Rome. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
```

But the results are correct and timezone `Europe/Rome` is fine and is properly applied (`Europe/Rome` or whatever IANA timezone passed as string).

What's going on?

**Comment by sidorares** [comment]
This library does not do any complicated timezone mapping or daylight saving calculations, timezone must be just HH:MM offset

Here is how it's captured ( in your case falls back to 'Z' )

https://github.com/sidorares/node-mysql2/blob/c460c0fe9c9b47282f573801f6e883913752916f/lib/connection_config.js#L94-L108

And here is how it is used:

https://github.com/sidorares/node-mysql2/blob/769c0023ed3d662ffc054c576bf2d4899ca48b1c/lib/packets/packet.js#L251-L290

**Comment by damianobarbati** [comment]
Oh I see, thanks @sidorares for linking me with direct code of what's happening behind the scenes!
