### ISSUE TITLE
[QUERY]What is the apropiate form to use the queries in modern versions?

### ISSUE THREAD

**Issue by NervenCid** [sidorares/node-mysql2#1027]
Hello and sorry for the english, i'm trying to run this function with the version 1.7.0 of mysql2:

```js
//Importamos la interfaz
import { Post } from '../interface/Post';

//Creamos una funcion para obtener todos los posts
export async function getPosts(req: Request, res: Response): Promise<Response | void> {
    try {
        //Conectamos
        const conn = await connect();
        //Hacemos la consulta a la base de datos
        const posts = await conn.query('SELECT * FROM posts');
        //Devolvemos la consulta
        return res.json('getPost');
        //res.json(posts[0]);
    }
    catch (e) {
        //devolvemos un error
        console.log('Error en getPosts: ',e)
    }
}
```

But i get this error instead, it seems that the part of the query is the problem and i cannot use post as array.

Error: You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://www.npmjs.com/package/mysql2#using-promise-wrapper, or the mysql2 documentation at https://github.com/sidorares/node-mysql2/tree/master/documentation/Promise-Wrapper.md
at Query.then (C:\Users\nerve\Diego\Programacion\Ejercicios_Typescript\mysql-rest\node_modules\mysql2\lib\commands\query.js:41:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:4960) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or
by rejecting a promise which was not handled with .catch(). (rejection id: 2)

How can i do correctly the query or use the library i'm basing on an older version of the library.

Thank you

**Comment by sidorares** [comment]
you are using `await` with callback-style api ( which is default ). Have a look at https://github.com/sidorares/node-mysql2#using-promise-wrapper

If you are forced to use non-promise version of the client just use callbacks:

```js
//Hacemos la consulta a la base de datos
  conn.query('SELECT * FROM posts', function (err, posts) { 
  res.json(posts[0]);
})
```

**Comment by NervenCid** [comment]
Thank you for your answer @sidorares and sorry for the english, in fact i tried callbacks before as i show in the code below:

`
    //Obtener todos los juegos con metodo GET
    public async list(req: Request, res: Response): Promise<void>{

        //Forzamos la deshabilitacion de la cache para que actualice la pagina
        //inmediatamente despues de presionar el boton
        //REVISAR ESTO EN UN FUTURO
        //res.header("Cache-Control", "no-cache, no-store, must-revalidate");
        //res.header("Pragma", "no-cache");
        //res.header('Expires', '-1');

        //Respuesta del servidor
        //res.json({"message":'Listando juegos'});
        //Consultamos la base de datos 
               
        await pool.query('SELECT * FROM games', (err, games) =>{      
            //En caso de error
            if (err) throw err;
            //Mostramos lo recuperado desde la base de datos
            res.json(games);            
        });              
    }



    //Metodo crear con 'POST'
    public async create(req: Request, res: Response): Promise<void>{
        //Mensaje de consola
        //console.log(req.body);
        //Guardamos dentro de la base de datos (la tabla se llama 'games')
        await pool.query('INSERT INTO games set ?',[req.body]);
        //Respuesta desde el servidor
        res.json({'message': 'Juego Guardado' });
    }

    //Metodo eliminar con 'DELETE'
    public async delete(req: Request, res: Response):Promise<void>{
        //Obtenemos el 'id'
        const {id} = req.params;
        //Eliminamos de la base de datos
        await pool.query('DELETE FROM games WHERE id = ?', [id]);
        await res.json({ 'message': 'Juego Eliminado' });
    }
`

The problem is for example in this code i'm using the most new version of mysql controller, and when i connect to the frontend(Angular), the page is not updating automatically when i use create or delete methods, which it worked with older versions, i tried testing my frontend with older versions of the mysql controller and it worked, but if use the code above the page in the front end must be update manually refreshing the page (besides the database), how can i modify the methods above in order to force the frontend to update automatically after the query is executed? there are an extra step?

Thank you

**Comment by sidorares** [comment]
> the page is not updating automatically when i use create or delete methods, which it worked with older versions

not sure I understand this part

If you are using callback api you can't `await` result, in general try not to mix async/await and callback style code

**Comment by NervenCid** [comment]
Thank you for your answer @sidorares and sorry for the english again:

How can i explain it? i have a frontend where there is a typical delete button and a typical form in order to create posts, in a typical CRUD applications where the posts is represented with a card. When i for example create a post i use the function "create" in order to create a "new card" from a form(req.body) storaging the data into the database (after i press a save button), second the function "list" should show the url with said card (thing that doesn't happen and i i must press refresh to the page), or more easy, when i press the button delete in my frontend the "card" doesn't disapear despite the data is already deleted in my data base... 

Respect the second part, shall i quit the aync await if i use callbacks?

Thank you so much

**Comment by sidorares** [comment]
> when i press the button delete in my frontend the "card" doesn't disapear

this is outside of this library scope. Does it disappear when you reload page? Do you set new state based on response from api request or do optimistic update?

> Respect the second part, shall i quit the aync await if i use callbacks?

yes, and also make sure you send response backe after query is finished, e.i 

```js
 public delete(req: Request, res: Response):Promise<void>{
        //Obtenemos el 'id'
        const {id} = req.params;
        //Eliminamos de la base de datos
        pool.query('DELETE FROM games WHERE id = ?', [id], (err, rows) => {
          res.json({ 'message': 'Juego Eliminado' });
        });
    }
```
