### ISSUE TITLE
SSL does not verify remote certificate

### ISSUE THREAD

**Issue by dougwilson** [sidorares/node-mysql2#103]
@sidorares I believe you contributed the SSL implementation up to the `mysql` library. I discovered it does not actually check the server's certificate. I looked around in the source code for this module and it looks like it also does not check the validity of the server certificate.

I'm fixing it for the `mysql` library, so you may want to port it to this library. Tracking ticket: https://github.com/felixge/node-mysql/issues/816

**Comment by sidorares** [comment]
@KevinMartin  - see progress in #171
