### ISSUE TITLE
[QUESTION] Using dotenv as devDependency

### ISSUE THREAD

**Issue by emauricio** [sidorares/node-mysql2#1031]
Hi there, new here :blush:

I would like to know if is possible to use  [dotenv](https://www.npmjs.com/package/dotenv)
to load the environment variables.
I can submit a small PR... the changes are minimal (not in the code, mostly package.json)

---

sadly, after checking out the master branch, I'm not able to make the test pass. do you know if that is normal or did I miss something on the way.  
or I can try to help to fix them when I get some time 

thank you in advance.

**Comment by sidorares** [comment]
> I would like to know if is possible to use dotenv

Not sure how it's useful here. I'd expect calling code to use dotenv or any other library t read config, and pass it explicitly to this module


> do you know if that is normal or did I miss something on the way.

hard to tell. You need to provide us what have you tried, what you see and how it's different from what you expect

**Comment by emauricio** [comment]
@sidorares , thank you for your prompt reply,
about the dotenv, the nice part is that you can run 
`node -r dotenv/config ./test/run.js`  and it will load the content on the .env file without changing anything on the code, instead of doing `export`.  

---

about what I have done, I just cloned the repo and run `npm test` after following the steps listed on the `Contributing.md` 
I created the test db, and set those env variables, nothing else.
I run it on Windows Pc using the WSL, I will try in a different machine but I guess should be the same result.
I will update this message once I try it.

**Comment by sidorares** [comment]
you mean using dotenv for just for tests? yeah, might be a bit easier then setting vars from command line parameters

**Comment by emauricio** [comment]
@sidorares, yes is for the test part, I think that way everyone will have the same env settings, or at least will be easy to add or remove without affecting the host.
I made this commit to add the dotenv, and the MySQL (since I don't have it on my local)

https://github.com/emauricio/node-mysql2/commit/a82dfa76ad11c294774c0ec847c985dda4f343f2

but sadly I still can't make the test pass (i just updated to the latest master)

it creates the tables and so on, but it ends in error.
![image](https://user-images.githubusercontent.com/7945345/66799803-97cfa980-ef4d-11e9-9cea-9c5620bdd024.png)

one of the errors is this one 
--- 
```
[0:00:15 0 38/102 37.3% node test/integration/connection/test-datetime.js]              
  
  Ignoring invalid timezone passed to Connection: utc. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
  assert.js:89
    throw new AssertionError(obj);
    ^
  
  AssertionError [ERR_ASSERTION]: 8 == 17
      at process.<anonymous> (/Projects/node-mysql2/test/integration/connection/test-datetime.js:234:10)
      at process.emit (events.js:203:13) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: 8,
    expected: 17,
    operator: '=='
  }
```

**Comment by sidorares** [comment]
tests rely on local timezone, need to address this. Might help If you set TZ to UTC

**Comment by emauricio** [comment]
yes, that was it, now it passes. (i commented the local tz test and it works)
the only remaining things are some warnings  like:
```
[0:00:40 0 72/102 70.6% node test/integration/connection/test-then-on-query.js] 
  
  You have tried to call .then(), .catch(), or invoked await on the result of query that is not a promise, which is a programming error. Try calling con.promise().query(), or require('mysql2/promise') instead of 'mysql2' for a promise-compatible version of the query interface. To learn how to use async/await or Promises check out documentation at https://www.npmjs.com/package/mysql2#using-promise-wrapper, or the mysql2 documentation at https://github.com/sidorares/node-mysql2/tree/master/documentation/Promise-Wrapper.md
```
thank you.

---

if you think the commit to add the dotenv and docker for testing is ok, I can try to add a PR once I update the  `Contributing.md` to describe how to use it.
