### ISSUE TITLE
information_schema, columns returned as null in mysql8

### ISSUE THREAD

**Issue by joeyhub** [sidorares/node-mysql2#1042]
When I select a row from ROUTINES I get: ROUTINE_DEFINITION: null,

It is a longtext column. The mysql client shows it as not null but instead the routine's code.

It is not only mysql in node affected. HeidiSQL is unable to read most of the tables in information_schema. Something has changed with mysql 8.

**Comment by joeyhub** [comment]
* EVENTS
* PARAMETERS
* ROUTINES
* TRIGGERS

These changed to "views" in mysql 8.

**Comment by sidorares** [comment]
Hi @joeyhub can you prepare simple self contained example including schema and initial data so I can run it on my side locally?

**Comment by joeyhub** [comment]
The schema is built in to MySQL, information_schema. If you try with mysql 8.

```SELECT ROUTINE_DEFINITION FROM information_schema.ROUTINES```

Yields null for me in mysql2.

There's usually something in there already but if not you can create a function...

```
DELIMITER //
CREATE FUNCTION `afunc`()
RETURNS VARCHAR(255) CHARACTER SET 'ascii' COLLATE 'ascii_bin'
LANGUAGE SQL
DETERMINISTIC
NO SQL
SQL SECURITY INVOKER
COMMENT ''
BEGIN
	RETURN "TEST STRING";
END
//
```

**Comment by joeyhub** [comment]
MySQL 8 has a lot of breakages and bugs with information_schema. It seems to have an issue with the length if I try to put it into a temp table and then shorten it. It complains that I'm truncating data even though the contents are only a few hundred bytes and I'm switching it to varchar(10k).

**Comment by joeyhub** [comment]
I think I found it. It's turning it to null because of perms that the application account doesn't have. The perms must have changed for mysql8 as I didn't have this with 5.7.

**Comment by sidorares** [comment]
works for me no issues ( mysql 8.0.17 from docker, mysql2 1.7.0 and 2.0.0-alpha1 )

```js
const db = await mysql.createConnection({
    user: 'root',
    password: 'root',
    database: 'information_schema'
  });

const [result] = await db.query(
    'SELECT ROUTINE_DEFINITION,ROUTINE_NAME FROM ROUTINES'
  );

console.log(result)
```

```
  TextRow {
    ROUTINE_DEFINITION: 'BEGIN\n\tRETURN "TEST STRING";\nEND',
    ROUTINE_NAME: 'afunc' } ]
```

**Comment by sidorares** [comment]
> I think I found it. It's turning it to null because of perms that the application account doesn't have.

oh, that might explain it (though I'd expect error returned back if permissions aren't right and not NULL for the fileds user don't have access to )

**Comment by sidorares** [comment]
@joeyhub please reopen if you do believe it's an issue in this library. From above comments it looks like on server configuration / user permissions side

**Comment by oscareli** [comment]
Hi guys,

 I have same problem, my user (in MySql 8.0.11) in client WorkBench its ok.

```
SELECT 
      'procName' as ROUTINE_NAME,
      routine_definition
   FROM
      INFORMATION_SCHEMA.ROUTINES
   WHERE
      ROUTINE_SCHEMA = 'dbName'
          AND ROUTINE_TYPE = 'PROCEDURE'
          AND ROUTINE_NAME = 'procName'
```

`{ROUTINE_NAME: "acumuladoSaldoConta", ROUTINE_DEFINITION: null}`
