### ISSUE TITLE
Question: 2.0.0 is stable?

### ISSUE THREAD

**Issue by iolo** [sidorares/node-mysql2#1051]
In npmjs, version `2.0.0` is avaiable.
but `2.0.0-alpha1` is latest in here github.

Which is correct? May I use 2.0.0 from npm?

**Comment by sidorares** [comment]
this is strange, I'm pretty sure I tagged `2.0.0-alpha1` as 'beta' and `2.0.0` as latest

Two changes from `1.7.0` - initial authentication plugin mechanics was redesigned and `LOAD DATA INFILE` no longer writes lo local fs (security measure).

**Comment by sidorares** [comment]
<img width="791" alt="Screen Shot 2019-11-05 at 10 13 57 am" src="https://user-images.githubusercontent.com/173025/68166037-32536380-ffb5-11e9-8044-dbfeeb9b7647.png">

**Comment by sidorares** [comment]
sorry misread your question. Looks like I forgot to push changes to package.json but published to npm! I'll fix that

**Comment by sidorares** [comment]
this is fixed now, thanks for bringing attention to this @iolo !
