### ISSUE TITLE
bug: ER_ACCESS_DENIED_ERROR when connect to server via TCP/IP

### ISSUE THREAD

**Issue by codinggirl** [sidorares/node-mysql2#1053]
## What's the problem

Use `mysql2` 2.0.0, connect to  a server thant run via TCP/IP, get ERR_ACCESS_DENIED_ERROR error.

First, let's write a mini program using `mysql2`.

```js
// index.js
const mysql = require('mysql2')

function main() {
    const con = mysql.createConnection({
        host: '<secure>',
        user: 'meimei',
        password: 'meimei',
        database: 'test',
        charset: 'UTF8_GENERAL_CI',
        flags: '-RESERVED',
        port: 3306,
        debug: true
    })

    con.query('SELECT NOW();', function (err, rows, fileds) {
        console.log(err, rows, fileds)
    })
}

main()
```
Let's run it in the following env:

```
$ node --version
v12.3.1
$ npm --version
6.9.0
```

`mysql2` version:

```
 "dependencies": {
    "mysql2": "^2.0.0"
  }
```

MySQL Server:
```
5.0.90-community-nt
<secure host> via TCP/IP
protocol version: 10
```
Yes, it's old. But the MySQL C/S Protocol still remain 10, so no problem with it.

Now, we run our node.js program:

```
node index.js
```
We see the some messages on the console. Just paste any:

```js
 {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  sqlMessage: "Access denied for user 'meimei'@'<secure>' (using password: YES)"
} undefined undefined
```
Is this message tell us the server site user and grants incorrectly?

**NO!**

## Why this is NOT a grants configure issue

let's check the C/S communication.

### Initial handshake packet (pkt 1)

When a TCP accepted, the server return the Server Greeting Packet, aka, initial handshake packet.

The packet hex & ASCII dump here:

```hex
0000   41 00 00 00 0a 35 2e 30 2e 39 30 2d 63 6f 6d 6d   A....5.0.90-comm
0010   75 6e 69 74 79 2d 6e 74 00 2b 00 00 00 67 77 43   unity-nt.+...gwC
0020   25 30 61 79 5d 00 2c a2 08 02 00 00 00 00 00 00   %0ay].,.........
0030   00 00 00 00 00 00 00 00 46 26 28 36 78 78 74 5d   ........F&(6xxt]
0040   52 65 25 28 00                                    Re%(.                                             .
```

And a readable one here:

```
MySQL Protocol
    Packet Length: 65
    Packet Number: 0
    Server Greeting
        Protocol: 10
        Version: 5.0.90-community-nt
        Thread ID: 42
        Salt: TT*q~DwN
        Server Capabilities: 0xa22c
        Server Language: latin1 COLLATE latin1_swedish_ci (8)
        Server Status: 0x0002
        Extended Server Capabilities: 0x0000
        Authentication Plugin Length: 0
        Unused: 00000000000000000000
        Salt: _r@&<>`H)2^c
```
### The login request packet (pkt 2)

Hex dump:

```
0000   57 00 00 01 cf b3 aa 00 00 00 00 00 21 00 00 00   W...........!...
0010   00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ................
0020   00 00 00 00 6d 65 69 6d 65 69 00 14 58 90 08 f6   ....meimei..X...
0030   d8 5c 1c 1e a2 07 3f 9d 4a 86 bd 72 5d 95 5e bd   .\....?.J..r].^.
0040   74 65 73 74 00 6d 79 73 71 6c 5f 6e 61 74 69 76   test.mysql_nativ
0050   65 5f 70 61 73 73 77 6f 72 64 00                  e_password.
```

Readable one:

```
MySQL Protocol
    Packet Length: 87
    Packet Number: 1
    Login Request
        Client Capabilities: 0xb3cf
        Extended Client Capabilities: 0x00aa
        MAX Packet: 0
        Charset: utf8 COLLATE utf8_general_ci (33)
        Username: meimei
        Password: 589008f6d85c1c1ea2073f9d4a86bd725d955ebd
        Schema: test
        Client Auth Plugin: mysql_native_password
```

### Response error (pkt 3)

Hex dump:
```
0000   4f 00 00 02 ff 15 04 23 32 38 30 30 30 41 63 63   O......#28000Acc
0010   65 73 73 20 64 65 6e 69 65 64 20 66 6f 72 20 75   ess denied for u
0020   73 65 72 20 27 6d 65 69 6d 65 69 27 40 27 __ __   ser 'meimei'@'_ _
0030   __ __ __ __ __ __ __ __ __ __ __ __ 27 20 28 75   _ _ _ _ _ _ _ _ _ _ _ _' (u
0040   73 69 6e 67 20 70 61 73 73 77 6f 72 64 3a 20 59   sing password: Y
0050   45 53 29                                          ES)
```
Note: `__` `_` is IP address, and hidden for secure reason.

Readable one:
```
MySQL Protocol
    Packet Length: 79
    Packet Number: 2
    Response Code: ERR Packet (0xff)
    Error Code: 1045
    SQL state: 28000
    Error message: Access denied for user 'meimei'@'<secure>' (using password: YES)
```

According the 3 packets, we know:

- The server & the client use `mysql_native_password` as a auth method, aka, `auth_41`.
- The password is `meimei`
- The scramble part 1 is string `gwC%0ay]`, hex is `67 77 43 25 30 61 79 5d`, 8 bytes.
- The scramble part 2 is string `F&(6xxt]Re%(`, hex is `46 26 28 36 78 78 74 5d 52 65 25 28`, 12 bytes, trailing zero deleted.

We calculate the auth token through AUTH_41.

The AUTH 41 method is:

```
SHA1( password ) ^ SHA1( seed + SHA1( SHA1( password ) ) )
```
^: XOR
+: CONCAT

Let's write a program to do it:

```js
const auth41 = require('mysql2/lib/auth_41')

let password = 'meimei'
let scramblePart1 = 'gwC%0ay]'
let scramblePart2 = 'F&(6xxt]Re%('

const buffer = auth41.calculateToken(password, scramblePart1, scramblePart2)

console.log(buffer)
```

Run it, we get the auth token:

```
<Buffer bf e2 07 ea 84 11 8b e9 6d d2 cf d6 99 3d e7 2b d8 03 fe 90>
```
But what the client send to server is:

```
589008f6d85c1c1ea2073f9d4a86bd725d955ebd
```

Not the correct one:

```
bfe207ea84118be96dd2cfd6993de72bd803fe90
```

## Conclusion

Send a WRONG AUTH TOKEN to server, it's absolutely get the error like `ER_ACCESS_DENIED_ERROR`.

No matter how you configure the server side grants, it NOT works ever.

**Comment by sidorares** [comment]
great job, thanks for this amazing investigation.

I'm trying to test this and with first 5.0 version I tried ( `reducible/mysql:5.0.95` ) the error is completely different - receive AuthSwitch request with undefined as plugin name ( probably because we incorrectly assume server understands plugin auth by default )

I'll try to see If I can find exact mysql version in docker hub and try with it ( If you can provide instruction or have an image you tested let me know )

**Comment by sidorares** [comment]
ok looks like I can make it (current master) fail with `datagrip/mysql:5.1` and it works fine with your branch.  Would you be able to add it to travis build matrix? I guess we need to change `mysql:$DOCKER_MYSQL_VERSION` to full repo+tag names as it's no longer only using official mysql repo

**Comment by codinggirl** [comment]
OK. I would try it.

**Comment by codinggirl** [comment]
This issue occurs on some server that not support `CLIENT_PLUGIN_AUTH` or `CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA`.

The difference protocol `mysql 5.7` vs `mysql 5.0` is, 5.7 handshake's `mysql.auth_plugin.length` is set, and 5.0 keep always `0x00`.

Acturely, the client (mysql2 packet parser) did not parse initial handshake properly.

See:
- <https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeV10>
- <https://dev.mysql.com/doc/internals/en/capability-flags.html#flag-CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA>
- <https://mariadb.com/kb/en/library/connection/#initial-handshake-packet>

**Comment by codinggirl** [comment]
@sidorares now build matrix have added to PR #1054 .

If use the docker image `datagrip/mysql:5.1` to test it, assets too many errors.  
It seems the test cases written before did not check the MySQL versions and the differences between them.

How can we handle this situation?

**Comment by sidorares** [comment]
> How can we handle this situation?

I don't think it's worth fixing all the tests just for old mysql version. I'll check if there is an easy way to filter tests with current setup and try to mark some simple test as "5.1" only
