### ISSUE TITLE
pool connection refresh feature

### ISSUE THREAD

**Issue by samitani** [sidorares/node-mysql2#1059]
When we add new MySQL replica under the load-balancer, connection re-balancing is needed.
We need the function to close pool connection periodically so that balance connection automatically with new MySQL replica.

Currently, PoolConnection.end() can be used for this purpose. We call this function randomly to recconect gradually. But end() will be deprecated.
```
  end() {
    const err = new Error(
      'Calling conn.end() to release a pooled connection is ' +
        'deprecated. In next version calling conn.end() will be ' +
        'restored to default conn.end() behavior. Use ' +
        'conn.release() instead.'
    );
```

How we implement connection re-balance logic after end() will replaced release() ?

**Comment by sidorares** [comment]
if you want to remove from pool + close `.destroy()` might work for you - see https://github.com/sidorares/node-mysql2/blob/106289a07c22a7354771341df559238a33329986/lib/pool_connection.js#L46-L49

**Comment by samitani** [comment]
@sidorares I've confirmed that `.destroy()` works fine. thank you very much!
