### ISSUE TITLE
Connection settings should accept 'collate' as a property

### ISSUE THREAD

**Issue by simontong** [sidorares/node-mysql2#1060]
I'm using mysql2 with knex.

The default connection when using `utf8mb4` seems to pick the first collate in the list (that being `utf8mb4_0900_ai_ci`). 

When I pass in `utf8mb4_general_ci` as `collate` property in connection settings for knex it gets passed down through mysql2 where it logs the following message:

```Ignoring invalid configuration option passed to Connection: collate. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection```

But in order to have the `knex_migrations` table use the correct collate when it intially created it needs to have the `collate` option passed into it.

**Comment by sidorares** [comment]
mysql2 connection constructor only accepts `charset`, not sure why knex passes `collate`, maybe need to be investigated on knex side

Can you test mysql2 directly with same queries and `utf8mb4_general_ci` as charset?

**Comment by simontong** [comment]
My understanding is that whatever you put into knex client connection settings will get passed down to mysql2 connection settings

I tested it using `utf8mb4_general_ci` and am getting an error:

`Unknown character set: 'utf8mb4_general_ci'`

I believe this is because `utf8mb4` is a character set while `utf8mb4_general_ci` is a collation.

**Comment by sidorares** [comment]
for mysql server `utf8mb4_general_ci` is a combo of charset + collation. mysql2 only cares about charset part of it to be able to translate in case client and server charsets are different. It uses iconv + mapping from constant name in https://github.com/sidorares/node-mysql2/blob/master/lib/constants/charsets.js + mapping from mysql charset to iconv charset in https://github.com/sidorares/node-mysql2/blob/master/lib/constants/charset_encodings.js

Charset name is case sensitive and should be one from https://github.com/sidorares/node-mysql2/blob/master/lib/constants/charsets.js, can you try with `UTF8MB4_GENERAL_CI`?

**Comment by simontong** [comment]
Appears to be giving me the same error `Unknown character set: 'UTF8MB4_GENERAL_CI'`.

**Comment by sidorares** [comment]
could you show stack trace?

**Comment by simontong** [comment]
OK, appears to only happen when I'm using knex and mysql2 together. If I use mysql2 on its own the error does not appear. I stepped through the code and `getCharsetNumber` in `connection_config.js` thinking that was throwing an error.

It appears to be a knex issue, its trying to create the table with `character set utf8mb4_general_ci` when it should be `character set utf8m4 collate `utf8mb4_general_ci`.

Thank you, feel free to close the issue as it does not relate to mysql2.

**Comment by sidorares** [comment]
no problems, reopen if you need more help
