### ISSUE TITLE
authPlugins support not complete in 2.0.0 package

### ISSUE THREAD

**Issue by kspierson** [sidorares/node-mysql2#1061]
It seems as though some files were not included in the packaged version of mysql2@2.0.0 on NPM that enable support for the authPlugins API, specifically `connection_config.js` and `auth_switch.js`.  Should I install directly from the Github repo master branch, this feature works as expected with my custom authentication plugin for mysql_clear_password.

**Comment by sidorares** [comment]
Can this be related to https://github.com/sidorares/node-mysql2/pull/1052 ? It's merged to master but not published yet, I can publish it as 2.0.1
If not this, can you describe exactly what issue you are having? ( what you do, what was expected, what you actually  see )

**Comment by kspierson** [comment]
Yes this is the same issue; having 2.0.1 on NPM would be fantastic. Other than that the feature is working as expected.

**Comment by sidorares** [comment]
v2.0.1 is in npm, let us know if you have any issues
