### ISSUE TITLE
Create new pool on demand. [Help]

### ISSUE THREAD

**Issue by FantasticSWT** [sidorares/node-mysql2#1064]
![image](https://user-images.githubusercontent.com/38369131/69239064-5a0d1300-0bd4-11ea-9566-a45e4c0acb98.png)

I am new to mysql and trying my best to correctly establish the connection on my API. I have reached a bottleneck where I have a situation that hardly make me progress.

Situation: Firstly, client accesses to my created pool connection as shown in the picture. Then after the connection, I get to know which other databases that I need to form the connection with. (Means the first connection created is just to get to know the exact database that my client wish to interact with.)

With such scenario, can I on demand create new pool connection every time in my API for each of my clients. May I know how's the file structure going to be arranged?

**Comment by sidorares** [comment]
Is that just one "dynamic" database? If so, create first pool ( or single connection) to get it's details and only after create second pool. Could you be a bit more specific with what stops you here?

**Comment by mdierolf** [comment]
Two options:
1) Use one pool and multiple statements:
pool.query("USE otherDB; SELECT * FROM myTable");
You will need to add 'multipleStatements: true' to your connection options

2) Query the table explicitly:
pool.query("SELECT * FROM otherDB.myTable");

It's very common to maintain one pool of connections in an application, and switch or query from other DBs as necessary.

**Comment by sidorares** [comment]
in addition to what @mdierolf said, also

```js
const conn = await pool.getConnection();
await conn.query('use otherDB');
await conn.query('SELECT * FROM myTable);
conn.release();
```
