### ISSUE TITLE
PoolCluster#restoreNodeTimeout

### ISSUE THREAD

**Issue by mintuhouse** [sidorares/node-mysql2#1066]
Since [PoolCluster#Options](https://github.com/mysqljs/mysql#poolcluster-options) are not implemented, what it a recommended way to reconnect after a db restart
I keep getting `Pool does Not exists. `, until I restart my application

**Comment by sidorares** [comment]
honestly not sure, I never personally used PoolCluster myself. IMO this feature is too big to be in the low level driver, it is there only for better compatibility with mysqljs/mysql
Happy to fix what's missing but that's low priority for me

**Comment by anchel** [comment]
> Since [PoolCluster#Options](https://github.com/mysqljs/mysql#poolcluster-options) are not implemented, what it a recommended way to reconnect after a db restart
> I keep getting `Pool does Not exists. `, until I restart my application

did you have a solution?

**Comment by mintuhouse** [comment]
Not really.

**Comment by mintuhouse** [comment]
> > Since [PoolCluster#Options](https://github.com/mysqljs/mysql#poolcluster-options) are not implemented, what it a recommended way to reconnect after a db restart
> > I keep getting `Pool does Not exists. `, until I restart my application
> 
> did you have a solution?

Not really
