### ISSUE TITLE
Query in error objects (err.sql)

### ISSUE THREAD

**Issue by abney317** [sidorares/node-mysql2#1068]
Node MySQL looks like it has an `sql` property in the [error objects](https://github.com/mysqljs/mysql#error-handling) that shows the query that was being run.

> err.sql: String, contains the full SQL of the failed query. This can be useful when using a higher level interface like an ORM that is generating the queries.

Looks to be missing from mysql2 unless there's some config required that I haven't seen.

```
Error: Unknown column 'test' in 'field list'
    at Packet.asError (C:\example\node_modules\mysql2\lib\packets\packet.js:712:17)
    at Query.execute (C:\example\node_modules\mysql2\lib\commands\command.js:28:26)
    at PoolConnection.handlePacket (C:\example\node_modules\mysql2\lib\connection.js:408:32)
    at PacketParser.onPacket (C:\example\node_modules\mysql2\lib\connection.js:70:12)
    at PacketParser.executeStart (C:\example\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\example\node_modules\mysql2\lib\connection.js:77:25)
    at Socket.emit (events.js:200:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'test' in 'field list'"
}
```

Should this property be added?

**Comment by sidorares** [comment]
Yes, would be good to add. Do you want to volunteer @abney317 ? Looks like a good first contribution

**Comment by abney317** [comment]
I could just update the `command.js` file with this:
```
const err = packet.asError(connection.clientEncoding);
err.sql = connection._command.sql;
```

But I assume it should probably be added to the `asError` function itself which I could quite figure out.

**Comment by sidorares** [comment]
sql is not part of the response, we add it from the input we sent earlier that caused the error

**Comment by abney317** [comment]
I'm not entirely sure what you mean by that. It looked like updating the packet.js file would be how it should be done but I couldn't really figure it out other than just doing what I had above there (which worked).

**Comment by sidorares** [comment]
`packet.asError(connection.clientEncoding)` decodes what's in the server error response - code, text message etc. sql that caused that error is not there, driver adds it just for convenience:

```
query("SELECT foo from bar were id = ?", [123])
  -> send "SELECT foo from bar where id = '123'" to server
 <- Error object: code 12345, text: "you have error in you sql
call callback with err set top data from error packet + original sql sent "SELECT foo from bar where id = '123'" 
```

**Comment by abney317** [comment]
So would my suggestion to edit the command.js file be the preferred way to implement this then?

**Comment by sidorares** [comment]
yes, adding to command.js should do it ( also a unit test )

**Comment by mscdex** [comment]
I just noticed this incompatibility as well in the latest version of `mysql2`.

**Comment by erkage** [comment]
Wow, I almost open a ticket for this, found it just before click on the "submit new issue" button.
Any ETA when will be a new release with this in it?
