### ISSUE TITLE
Potential promise leak with promise wrapped connectionPool.query 

### ISSUE THREAD

**Issue by devillexio** [sidorares/node-mysql2#1071]
While investigating a memory leak we discovered that there were large number of promises not being released, all related to a SQL query being called on a connection obtained from a promise wrapped pool.

Here is the related code:
```js
const mysql = require('mysql2')

const connectionLimit = Number(process.env.MYSQL_CONNECTION_LIMIT) || 10 // number of connections
const {
  MYSQL_HOST: host,
  MYSQL_USER: user,
  MYSQL_PASSWORD: password,
  MYSQL_DATABASE: database
} = process.env
const timeout = Number(process.env.MYSQL_TIMEOUT) || 10000 // ms

const pool = mysql.createPool({
  connectionLimit,
  host,
  user,
  password,
  database,
  charset: 'UTF8MB4'
})
const promisePool = pool.promise()

/**
 * Fetch a widget from the database
 * @param  {number} id The id of the widget to search for
 * @return {object} The widget config
 */
async function getWidget (
  id,
  // istanbul ignore next
  { pool = promisePool } = {}
) {
  const sql = 'CALL getWidget(?);'

  const [[row]] = await pool.query({ sql, timeout }, [id])

  if (!row.length) throw new Error(`Widget not found for id '${id}'`)

  const [widget] = row

  return widget
}
```

Here is the screenshot of the promise count growing over time:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/11049609/69594743-29512300-0fb2-11ea-9901-af82e3a716f6.png">

When I took the heap dump there were about 15k promises, but the promises count keeps increasing until the application eventually is killed with an out of memory error.

**Comment by sidorares** [comment]
Would it be easy for you to try this with non-promise client and see if there is any difference?

Alternatively, try to change max parser cache here (currently hard coded) - https://github.com/sidorares/node-mysql2/blob/769c0023ed3d662ffc054c576bf2d4899ca48b1c/lib/parsers/parser_cache.js#L6 and see if that gives different result

**Comment by devillexio** [comment]
Thanks for the suggestions @sidorares. I'll give it a try and revert back.

**Comment by devillexio** [comment]
After testing a while I'm no longer sure that mysql2 is the major problem with our memory/promise leaks currently. If I find anything more detail indicating that mysql2 may be the culprit I'll reopen the issue.
