### ISSUE TITLE
When rerunning test suites in Jest, connections are not released

### ISSUE THREAD

**Issue by marnixhoh** [sidorares/node-mysql2#1088]
Hi,
I noticed that every time Jest test suites are 'rerun' (without restarting jest), the number of connections (Threads_connected) keeps increasing till a "Too many connections" error. I use a connection pool with 'mysql2/promise' and all my queries are made using pool.execute() directly (i.e. no explicit pool.getConnection(), etc.).

When running the Node application normally, this doesn't happen.

When Jest is shutdown, most connections close, however some remain open...

I am not sure if this behavior is expected or not. Please let me know if it's not and if I can provide additional information.

Node version: v12.13.1
MySQL version: Ver 8.0.18 for osx10.14 on x86_64 (Homebrew)
MySQL2 version: 2.0.1
Jest version: 24.9.0

**Comment by marnixhoh** [comment]
Upon further investigation I found that the connections that remain open even after Jest shutdowns are from MySQL WorkBench... Not Jest... Whoops my bad!

However, more connections being opened and none being closed until shutting down of Jest does still happen. It's not too big of a deal since simply restarting Jest solves this, but I thought I'd mention it anyway...

**Comment by sidorares** [comment]
you might be leaking pool somewhere in jest setup code and need to add `await pool.end()` in teardown ( just a guess )

**Comment by marnixhoh** [comment]
Thank you that solved it!

For anyone who might be interested in the snippet:

`afterAll(async (done) => {
    await mysqlPool.end()
    done()
})`
