### ISSUE TITLE
Please make PROTOCOL_CONNECTION_LOST a non-fatal error

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [sidorares/node-mysql2#1090]
I don't think I'm the only one who wants their entire server to crash just because a connection to a database terminated, probably when it wasn't even needed anymore.

**Comment by sidorares** [comment]
non-fatal means "connection still alive, it's just this command failed and its possible to try to send other command". `PROTOCOL_CONNECTION_LOST` is definitely fatal as per this definition. Can you describe a bit more what problem you are trying to solve @MelerEcckmanLawler  ?

**Comment by MelerEcckmanLawler** [comment]
My app connects to a database to perform a single write then it never uses the connection.  So when the connection is lost like a minute later that isn't an error.  Yet it crashes the entire app if not handled as an "error".

**Comment by sidorares** [comment]
> My app connects to a database to perform a single write then it never uses the connection again

In your case probably better to close connection after write. Handling errors with single connection is a bit tricky, you need to attach handler to connection object and also check error in write callback. Because of this I usually suggest using pool even for single command
