### ISSUE TITLE
es module support? Node 13

### ISSUE THREAD

**Issue by zsolt-dev** [sidorares/node-mysql2#1093]
Hi,

First, thank you for maintaining this great library.

I would like to use node 13 without babel.

I have a file index.***mjs*** in which I am trying to do:
```
import mysql from 'mysql2/promise';
```

and I am getting this error:
```
(node:27011) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:96
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /Users/zsoltszabo/coding/media-app/node_modules/mysql2/promise imported from /Users/zsoltszabo/coding/media-app/server/db/reset/index.mjs
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:96:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
    at link (internal/modules/esm/module_job.js:40:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by joeyhub** [comment]
Any luck with the full path IE `import mysql from 'mysql2/promise.js';` ?

**Comment by sidorares** [comment]
@zsolt-dev can you try adding https://nodejs.org/api/esm.html#esm_package_exports to package.json? If that works happy to accept pr

**Comment by pubmikeb** [comment]
@sidorares, I'm currently facing an issue with importing `mysql2/promise` to ES module/MJS, but it doesn't work. Could you, please, give some hint how to cope with such issue?

Thanks.

**Comment by jaydenseric** [comment]
For the benefit of people tracking this issue, I've left some comments on the topic here: https://github.com/sidorares/node-mysql2/pull/1100#issuecomment-616126810 .
