### ISSUE TITLE
donations

### ISSUE THREAD

**Issue by poseidonCore** [sidorares/node-mysql2#1094]
Hi

Do you have a mechanism for the public to make donations? 

I have started to make minor donations to other projects via opencollective.com when important progress has been made in a project and it might be helpful for this project too.

Many thanks for all your great work to date.

**Comment by sidorares** [comment]
Thank you @poseidonCore ! You can donate to me personally at https://github.com/sponsors/sidorares
Unfortunately I don't know an easy way to donate to all contributors to github project at once, you can see all contributors here: https://github.com/sidorares/node-mysql2/graphs/contributors

**Comment by poseidonCore** [comment]
Thanks & have a great New Year!
