### ISSUE TITLE
[help] can't connect to mysql

### ISSUE THREAD

**Issue by aprilmintacpineda** [sidorares/node-mysql2#1099]
I created a virtual machine, using VirtualBox, running ubuntu 18.04, I installed mysql there using `sudo apt-get install mysql-server` then I installed nvm for node, I'm using the latest version of node which is 13.x.

When I run:

```js
/** @format */

if (process.env.NODE_ENV !== 'production') {
  require('dotenv').config({
    path: require('path').join(__dirname, '.env')
  });
}

const chalk = require('chalk');
const mysql = require('mysql2/promise');
const tables = require('./tables');

(async () => {
  const connection = await mysql.createConnection({
    host: process.env.db_host,
    user: process.env.db_user,
    password: process.env.db_pass,
    database: process.env.db_name
  });
  //... rest of the code
});
```

It throws `Error: Access denied for user 'root'@'localhost'`. But I can connect to mysql with `sudo mysql -u root -p` and there's no password. I also installed zabbix, and it seems that it has no problem connecting to the mysql server.

I configured mysql bind-address to `0.0.0.0` instead of `127.0.0.1`. Not sure if that changes anything.

**Comment by aprilmintacpineda** [comment]
Seems it has to do with the user, I'm unsure of the cause.

So, I have two users: `'root'@'localhost'` and `'remote'@'%'`. When I used the user `remote`, it was able to connect successfully. Why though?

My env variables for the database:

```
db_host=localhost
db_user=remote
db_pass=
db_name=sandbox-db
```

**Comment by sidorares** [comment]
If `remote` works that means no issues with connectivity, you need to configure access for root user
Try first to change access to match `'root'@'%'` , maybe it does not see connection as coming from localhost

**Comment by aprilmintacpineda** [comment]
Thanks @sidorares!
