### ISSUE TITLE
Pool connection does not get properly released

### ISSUE THREAD

**Issue by danieljuhl** [sidorares/node-mysql2#110]
I have a simple setup with pooled connections, but for some reason the connection does not get released, unless I call .release() twice on the connection.

Anybody else, who has had the same issue?

**Comment by parkr** [comment]
@sidorares Has this been fixed?

**Comment by sidorares** [comment]
@parkr I believe so, but if not a reproducible test case would help a lot

**Comment by danieljuhl** [comment]
@sidorares I'll try and make a simple test case, based on my previous failing code, to see if I can reproduce it.

**Comment by sidorares** [comment]
thanks @danieljuhl !

**Comment by danieljuhl** [comment]
@sidorares So far, I've not been able to reproduce using the latest versions. Let's close it for now..
