### ISSUE TITLE
way to release connection in catch block in case of error in query

### ISSUE THREAD

**Issue by juttameerhamza** [sidorares/node-mysql2#1110]
This is simple testing code to get callbacks. I just want to ask how to release connection in case of error and because code goes to catch block.

Here is my code:

```
const express = require('express');
const mysql = require('mysql2');

const app = express();
const pool = mysql.createPool({
  host: 'localhost',
  user: 'root',
  database: 'mydb',
  connectionLimit: 10 
}).promise();

pool.getConnection()
  .then(() => console.log('DB connected'))
  .catch((err) => console.log(err));

app.get('/api/v1', async (req, res) => {
  try {
    const connection = await pool.getConnection();
    const [rows, fields] = await connection.query('SELECT * FROM users WHERE is_active = ?', 'Y');
    connection.release();

    res.status(200).json({
      message: 'success',
      data: rows
    });
  } catch(error) {
    res.status(400).json({
      message: 'error',
      error: error
    });
  }
});

app.listen(3000, console.log('Listening to 3000'));
```

**Comment by theirongiant** [comment]
I've been declaring the connection outside of the try block and releasing in a finally block like this:

`const express = require('express');
const mysql = require('mysql2');

const app = express();
const pool = mysql.createPool({
  host: 'localhost',
  user: 'root',
  database: 'mydb',
  connectionLimit: 10 
}).promise();

pool.getConnection()
  .then(() => console.log('DB connected'))
  .catch((err) => console.log(err));

app.get('/api/v1', async (req, res) => {
  let connection;
  try {
    connection = await pool.getConnection();
    const [rows, fields] = await connection.query('SELECT * FROM users WHERE is_active = ?', 'Y');
    res.status(200).json({
      message: 'success',
      data: rows
    });
  } catch(error) {
    res.status(400).json({
      message: 'error',
      error: error
    });
  } finally {
    connection.release()
  }
});

app.listen(3000, console.log('Listening to 3000'));`

**Comment by sidorares** [comment]
@juttameerhamza what @theirongiant suggests is correct, also if you only need to perform single query on a connection (you don't rely on a given connection state, e.i transaction or state variables) then you can use `pool.query()` / `pool.execute()` helper - it'll borrow and release connection automatically for you (or discard it in case of fatal error such es network disconnect)
