### ISSUE TITLE
db error { Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by ahab4ik** [sidorares/node-mysql2#1111]
I have a website that exchanges player’s items from Steam service for other items from the same service. I have started 4 Nodes JS server, under different Redis tables. The problem is the following: 1 of the servers closes the connection approximately every 6-8 hours, an error is written in the logs:

```
    error: [Classic] Error SteamCommunity Polling: Error: Fail
    0|classic  | db error { Error: Connection lost: The server closed the connection.
    0|classic  |     at Protocol.end (/etc/opt/bot/node_modules/mysql/lib/protocol/Protocol.js:109:13)
    0|classic  |     at Socket.<anonymous> (/etc/opt/bot/node_modules/mysql/lib/Connection.js:115:28)
    0|classic  |     at Socket.emit (events.js:203:15)
    0|classic  |     at endReadableNT (_stream_readable.js:1145:12)
    0|classic  |     at process._tickCallback (internal/process/next_tick.js:63:19) fatal: true, code: 'PROTOCOL_CONNECTION_LOST' }
    0|classic  | (node:9600) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
```

As I understand it, the problem is that there are no database queries and therefore the server is shutting down. 

And the other Node JS servers work, but they have another problem. Server uptime is now 40 hours and when I throw a request to the bot to exchange items, nothing happens. He does not see theexchange items request in the Steam service, nothing, he is doesn't online in Steam service, although it should be online.

But as soon as I restart the server, the bot starts working, sees everything and accepts exchanges. What could be the problem? I suspect that all the same due to the fact that the servers are idle for a long time and freeze.

How to solve a problem? Maybe it needs to be done, for example, so that once every 30 minutes the server in the database enters some random data, or so that it switches to Steam?

**Comment by sidorares** [comment]
First - looks like you are using https://github.com/mysqljs/mysql and not this module

Your code needs to be able to handle closed connections, things may and do happen - network is down for some time, mysql server rebooted, server kills idle connection etc etc

Idle timeout as you mentioned is indeed very common reason why you can see 'The server closed the connection' error, to prevent it from happening you can either increase timeout on server side or have so me kind of heartbeat using [ping](https://github.com/sidorares/node-mysql2/blob/a0ea513b0d4929e6ee61639a09f38a85ac01f7fa/lib/connection.js#L663) command for example every few seconds
