### ISSUE TITLE
Too many connections

### ISSUE THREAD

**Issue by samuelail** [sidorares/node-mysql2#1112]
Hi, I'm a little new to Node JS and I am running into some issues with mysql crashing after I refresh a page a number of times.

The entry point for my web app is app.js and this is where I connect to the mysql database:
// Create connection with MySQL database
 app.use((req, res, next) => {

//     	// Define connection globally to use it anywhere in this project
        global.pool = mysql.createPool({
			connectionLimit : 10,
			host:  'localhost',
			port: 'PORT',
            user:  'root',
            password:  ' ',
			database:  'test',
			debug    :  false
        });

        // create connection
        pool.getConnection((err, connection) => {
			// Check if there is any error
		
            if (err){
				
                const error = new Error(err.message);
                error.status = 500; // internal server error
                next(error); // forward it to the error handler

            }else{
				
                next(); // forward is to next
				connection.release();
            }
        });

}); 

and then I call It in whatever file I need like this.
  pool.query(
                        "SELECT *  FROM  users WHERE userID = ?",
                         [req.session.userId],
                        (error, result, fields) => {
                       
                            // check if there is any error
                            if (error){
                                res.status(500).json({
                                   error: error
                                });
                            }else{
                                if (result.length > 0) {
                                  const user = result;
                                  console.log(user);
                                  res.render('index', {username: req.session.name, userData: user});
                                }
                            }
                            
                        }
                    ); 

after I reload the page a number of times, It crashes. Please help

**Comment by PolymathWhiz** [comment]
The issue is your database keeps creating new connection pools.

Use this -

`function connection() {
  try {
    const mysql = require("mysql2");

    const pool = mysql.createPool({
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DATABASE,
      timezone: "utc",
      connectionLimit: 10,
      waitForConnections: true,
      queueLimit: 0
    });

    const promisePool = pool.promise();

    return promisePool;
  } catch (error) {
    return console.error(`Could not create database connection - ${error}`);
  }
}

const pool = connection();

module.exports = {
  connection: async () => pool.getConnection(),
  execute: (...params) => pool.execute(...params)
};`

**Comment by PolymathWhiz** [comment]
The issue is your database keeps creating new connection pools.

Use this -
`function connection() {
  try {
    const mysql = require("mysql2");

    const pool = mysql.createPool({
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DATABASE,
      timezone: "utc",
      connectionLimit: 10,
      waitForConnections: true,
      queueLimit: 0
    });

    const promisePool = pool.promise();

    return promisePool;
  } catch (error) {
    return console.error(`Could not create database connection - ${error}`);
  }
}

const pool = connection();

module.exports = {
  connection: async () => pool.getConnection(),
  execute: (...params) => pool.execute(...params)
};
`

**Comment by sidorares** [comment]
@samuelail yes, what @PolymathWhiz says☝️

you are basically create new pool on each request and borrowing connection from that new pool. Even if you return this connection back to the pool in won't be reused as on next request you create fresh new pool

**Comment by Kennytian** [comment]
`SET GLOBAL wait_timeout = 60; `

run this command in mysql client command terminal, the timeout unit is seconds
