### ISSUE TITLE
Pooling: Is there a way to, say, prime the pool with 1 connection but create up to 2 additional connections?

### ISSUE THREAD

**Issue by terrisgit** [sidorares/node-mysql2#1114]
The connection pool seems to create all connectionLimit connections up front. I instead want the pool to create a few connections initially and allow additional connections to be created (up to the connectionLimit) under unusually heavy loads. Please confirm that this is not currently possible. Or maybe I have not read the documentation in enough detail. Thank you.

**Comment by terrisgit** [comment]
No, the pool doesn't create all connections up front and I don't need this. Sorry.

**Comment by sidorares** [comment]
yep, correct. Sorry I didn't get back to you earlier
