### ISSUE TITLE
1.x.x RDS SSL Update

### ISSUE THREAD

**Issue by jhoscar1** [sidorares/node-mysql2#1117]
I use Sequelize which depends on this for handling its MySQL dialect and I have been using the `Amazon RDS` profile for tls connections. However the certs have since expired and the 1.x.x release has not received the updated certs that are in the 2.x.x releases. Is there a way that this can be updated in a 1.x.x release? I was going to make a PR but I didn't see any branch where there was any 1.x.x maintenance happening or an obvious place to contribute.

**Comment by sidorares** [comment]
I didn't plan maintaining 1.x line but it is possible to publish few more extra 1.x versions

Is there any specific reason you don't wan to upgrade to 2.x ? There is almost no breaking changes, you likely don't need to change anything in your code to upgrade

**Comment by charlie-s** [comment]
@sidorares Sequelize has a requirement of mysql2 ^1.6.5. I'm not sure if it would work with the 2.x line. Is the API consistent? I'm surprised there's not more chatter about this in the relevant issue queues. Either no one uses Sequelize with RDS, or a lot of folks are going to be unhappy in a few days. Or I'm mistaken about the dependency chain :)

**Comment by jhoscar1** [comment]
Thanks @charlie-s. That was essentially going to be my response. Given breaking changes in this package from 1.x to 2.x, despite there being few, asking for Sequelize to update their dependency could potentially lead to breaking changes on their end and require major version upgrade just to get a new static file of a cert chain. Updating here seemed to be an easier route although I'm sympathetic to not wanting to maintain the 1.x release of mysql2.

It seems to me like a good short-medium term solution, if it's amenable to @sidorares of course, would be a new 1.x release with the new cert which will lead to functioning apps for Sequelize users using RDS followed by a push to move Sequelize 6.x to use mysql2 2.x

**Comment by charlie-s** [comment]
+1 on Sequelize 6.x to use mysql2 2.x line. It's still in beta no? 

We can also download the certificate ourselves into repository or env and specify mysql2 "dialect options": https://sequelize.org/master/manual/dialect-specific-things.html.

Perhaps other RDS / Sequelize users aren't using SSL or have the certs configured by hand or something. In any event, updating certs in 1.x would be easiest for all involved. 

@sidorares open to a pull request for 1.x with addtl certs?

**Comment by jhoscar1** [comment]
Yup I believe it is in beta so there'd hopefully still be time to get that among the changes

**Comment by sidorares** [comment]
> open to a pull request for 1.x with addtl certs?

Yep, happy to publish more 1.x release. Just branch of latest 1.x tag and create PR

**Comment by jhoscar1** [comment]
@sidorares created a PR but not sure where to base it against this repo given there's only a tag at that commit and 1.x can't be released from master. Maybe I'm missing something?

**Comment by sidorares** [comment]
this is published as `v1.6.6` now

**Comment by jhoscar1** [comment]
@sidorares Thanks so much for responding to this quickly and facilitating the release!
