### ISSUE TITLE
Unable to install mysql2 on first try

### ISSUE THREAD

**Issue by DatMayo** [sidorares/node-mysql2#1121]
Hey,

I'm having a hard time trying to install mysql2 via npm. When I run `npm i mysql2` (or simmilar) I'm getting the following error:
> npm install --save mysql2
> npm WARN sequelize-typescript@1.1.0 requires a peer of @types/bluebird@* but none is 
> installed. You must install peer dependencies yourself.
> npm WARN sequelize-typescript@1.1.0 requires a peer of @types/validator@* but none is installed. You must install peer dependencies yourself.
> npm WARN node-typescript-boilerplate@0.0.0 No repository field.
> 
> npm ERR! code ENOENT
> npm ERR! syscall rename
> npm ERR! path D:\Coding\dcc\server\node_modules\ansicolors
> npm ERR! dest D:\Coding\dcc\server\node_modules\.ansicolors.DELETE
> npm ERR! errno -4058
> npm ERR! enoent ENOENT: no such file or directory, rename 'D:\Coding\dcc\server\node_modules\ansicolors' -> 'D:\Coding\dcc\server\node_modules\.ansicolors.DELETE'        
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\dat_m\AppData\Roaming\npm-cache\_logs\2020-03-01T06_46_46_552Z-debug.log

After 5-8 retries it's working... but its awefull to do it that often :/

I'm using npm **6.12.0**

Please tell me which additional info you need to assist me

**Comment by Markshall** [comment]
Strange. I've just installed it in a new project and it worked first time for me. May just be an NPM issue you were facing at the time.

**Comment by sidorares** [comment]
@DatMayo definitely feels like some interaction with previous installations or permissions issue. Could you try installing it as local module in a fresh empty folder? ( e.i `mkdir testinstall && cd testinstall  && npm init -y && npm install mysql2` )

**Comment by Markshall** [comment]
> @DatMayo definitely feels like some interaction with previous installations or permissions issue. Could you try installing it as local module in a fresh empty folder? ( e.i `mkdir testinstall && cd testinstall && npm init -y && npm install mysql2` )

This is precisely what I did and it worked first time for me.
