### ISSUE TITLE
can't connect to Amazon RDS

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [sidorares/node-mysql2#1125]
With my old SQL database I was using this code:

    const mysql = require('mysql2');
    const mysql_credentials = { host: 'host.com', user: 'user', password: 'password', database: 'database' };

    const pool = mysql.createPool(mysql_credentials);
    const promisePool = pool.promise();

But I get an access denied error when I try to connect to my Amazon RDS database using this same code with the correct credentials (I've quadruple-checked, it's the correct master username and password and everything).

Googling around I see some people using fancy convoluted code like [here](https://stackoverflow.com/questions/58067254/node-mysql2-aws-rds-signer-connection-pooling).

Do I have to do that too?  Why can't I just use the same simple credentials that work in the web browser and in the HeidiSQL client?   If that client can login surely I don't need any fancy extra stuff in Node.

**Comment by sidorares** [comment]
>  work in the web browser

The browser can't connect directly to mysql, are you using some kind of web frontend like phpMyAdmin? 

> Why can't I just use the same simple credentials that work in the web browser and in the HeidiSQL client

You absolutely should be able to connect with same credentials as HeidiSQL client, we just need to figure out what are exactly the settings HeidiSQL is using. Does it use TLS? 

Also not quite clear what's "my old SQL database ". Are you comparing code connecting to your local mysql server with RDS based db?

**Comment by MelerEcckmanLawler** [comment]
I was using the wrong password.
