### ISSUE TITLE
does createServer require local instance of mysql running

### ISSUE THREAD

**Issue by sbansal6** [sidorares/node-mysql2#1127]
not able to run createServer example on my localhost, does it require a local copy of MySQL servers. 
Can you please provide info on how it works(conceptually) and how to run it on localhost.

**Comment by sidorares** [comment]
`createServer()` is used to talk server side of mysql network protocol. You don't need local or remote running server to use it. This is similar how in node with `http` module `createServer` you don't need nginx or apache running - your script is a server. It's a bit low level currently, you need to handle all the state logic and send required packets manually ( but at the same time this allows to script scenarios you won't be able with regular server )

**Comment by sidorares** [comment]
@sbansal6 feel free to ask more in a new issue but please be more specific. Would be great if we improve docs as a result of this questions
