### ISSUE TITLE
Unhandled exception in Packet.readLengthCodedNumber

### ISSUE THREAD

**Issue by matthew-dean-hp** [sidorares/node-mysql2#113]
This issue was first reported for node-mysql (see http://github.com/felixge/node-mysql/issues/867 for the exact setup) but is also present in this library. Basically when connected to two nodes of a galera cluster if I repeatedly call a stored procedure that returns multiple result sets an unhandled exception sometimes occurs.

The debug output for a test case is as follows:

~~~
Add command: Connection
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
Add command: Connection
 <== query#start(0,,62)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
Add command: Connection
 <== query#start(0,,62)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
Add command: Connection
 <== query#start(0,,62)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,39)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: Connection
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,39)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> query#resultsetHeader(1,maybeOK,7)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: Connection
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,39)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
Add command: Connection
 <== query#start(0,,62)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: Connection
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,39)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,39)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
Add command: Connection
 <== query#start(0,,62)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,39)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,39)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,40)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,40)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: Connection
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,40)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,40)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
Add command: Connection
 <== query#start(0,,62)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: Connection
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,40)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> query#resultsetHeader(1,maybeOK,7)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,40)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> query#resultsetHeader(1,maybeOK,7)
 ==> Connection#handshakeInit(0,,102)
 <== Connection#handshakeInit(1,,73)
 ==> query#resultsetHeader(1,,1)
 ==> query#readField(2,,52)
 ==> query#readField(3,,56)
 ==> query#fieldsEOF(4,EOF,5)
 ==> query#row(5,,40)
 ==> query#row(6,EOF,5)
 ==> query#resultsetHeader(7,maybeOK,7)
 ==> Connection#handshakeResult(2,maybeOK,7)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: query
 <== query#start(0,,62)
Add command: Connection
 ==> query#resultsetHeader(1,,40)
 ==> query#readField(2,,40)
 ==> query#readField(3,EOF,5)
Trace
    at Packet.readLengthCodedNumber (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\packets\packet.js:135:12)
    at Packet.readLengthCodedString (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\packets\packet.js:264:18)
    at new ColumnDefinition (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\packets\column_definition.js:6:26)
    at Query.readField (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\commands\query.js:92:17)
    at Query.Command.execute (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\commands\command.js:34:20)
    at PoolConnection.Connection.handlePacket (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\connection.js:274:28)
    at PacketParser.onPacket (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\connection.js:68:65)
    at PacketParser.execute (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\packet_parser.js:37:14)
    at Socket.<anonymous> (c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\connection.js:80:31)
    at Socket.emit (events.js:95:17)

c:\Users\deanmat\galeraTest\node_modules\mysql2\lib\packets\packet.js:136
   throw "Should not reach here: " + byte1;
                                   ^
Should not reach here: undefined

~~~

**Comment by sidorares** [comment]
for 0.15.1 release: add as much as possible "wrong" protocol behaviour examples and make sure client never crashes and always communicate error in expected way (callback, "error" event or "end" with `fatal` flag)

**Comment by danieljuhl** [comment]
@sidorares Any idea of when this will land on npm?

**Comment by sidorares** [comment]
Interesting. This might be a 0.15 packet parser bug and not actual protocol errors as in @matthew-dean-hp case ( it was completely rewritten in #140 ). One way to try to capture bug: add a line "console.log(data.toString('hex'))" before https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L95 - this will log all data coming from server. Once errored, save some history up to error and I'll be able to debug it.

You might also just try to copy lib/packet_parser.js from 0.14 to 0.15 ( new one is api compatible with old ) and see if error occurs

**Comment by sidorares** [comment]
@danieljuhl if you going to do that make sure mysql server does not send sensitive data to client ( or use private gist and email it to me )

**Comment by danieljuhl** [comment]
@sidorares I'll have a look at the different thinks you are suggesting, so that we can narrow down the bug.

**Comment by danieljuhl** [comment]
Hmm... The error occurred on a remote database (haven't tested it on a local), but now I can't reproduce. The only change is that right now I'm sitting at home and yesterday I was at the office. I'll have to wait till monday, where I can test at the office again.

**Comment by sidorares** [comment]
This might be caused by different chunk length (if that was actually packet parser bug)
If you manage to reproduce - I don't need full chunk content, only first 3 bytes (or less if chunk < 3 butes), chunk length + parser state name. Add something like this after https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L95

```js
connection.packetParser.execute(data);
console.log("Incoming chunk: ", data.slice(-3).toString('hex'), connection.packetParser.execute.name); 
```

**Comment by devoidfury** [comment]
I ran into this during some load testing. Using pool (with execute calls), up to 10 connections. It's really intermittent, and sometimes takes hours of high-load before the issue appears.

Node 0.10.32
node-mysql: master @ 2559b3a7544c460a0c99380f7ab961b9aa4354c5

With the requested logging change here https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L95
```js
    this.stream.on('data', function(data) {
      console.log("Incoming chunk: ", data.slice(-3).toString('hex'), data.length, connection.packetParser.execute.name);
      connection.packetParser.execute(data);
    });
```

    -- snipped, let me know if you need more -- 
    Incoming chunk:  002200 4298 
    Incoming chunk:  002200 3668 
    Incoming chunk:  002200 4550 
    Incoming chunk:  002200 13653 
    Incoming chunk:  002200 4172 
    Incoming chunk:  002200 13222 
    Incoming chunk:  002200 11958 
    Incoming chunk:  002200 13588 
    Incoming chunk:  002200 10836 
    Incoming chunk:  002200 4046 
    Incoming chunk:  002200 4172 
    Incoming chunk:  002200 4424 
    Incoming chunk:  002200 4046 
    Incoming chunk:  002200 13576 
    Incoming chunk:  002200 12572 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 10954 
    Incoming chunk:  002200 13511 
    Incoming chunk:  002200 12885 
    Incoming chunk:  002200 3920 
    Incoming chunk:  002200 2534 
    Incoming chunk:  002200 2660 
    Incoming chunk:  002200 4676 
    Incoming chunk:  002200 3794 
    Incoming chunk:  002200 14645 
    Incoming chunk:  002200 11580 
    Incoming chunk:  002200 9177 
    Incoming chunk:  002200 14137 
    Incoming chunk:  002200 11279 
    Incoming chunk:  002200 2660 
    Incoming chunk:  002200 3668 
    Incoming chunk:  002200 4802 
    Incoming chunk:  002200 3542 
    Incoming chunk:  002200 4424 
    Incoming chunk:  002200 12531 
    Incoming chunk:  002200 16251 
    Incoming chunk:  002200 11775 
    Incoming chunk:  002200 14267 
    Incoming chunk:  002200 11462 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 3920 
    Incoming chunk:  002200 3668 
    Incoming chunk:  002200 4676 
    Incoming chunk:  002200 4550 
    Incoming chunk:  002200 3794 
    Incoming chunk:  002200 9791 
    Incoming chunk:  002200 11775 
    Incoming chunk:  002200 12271 
    Incoming chunk:  002200 15820 
    Incoming chunk:  010000 16384 
    Incoming chunk:  7a0000 16384 
    Incoming chunk:  002200 10978 
    Incoming chunk:  000000 16384 
    Incoming chunk:  002200 4046 
    Incoming chunk:  002200 6806 
    Incoming chunk:  002200 3920 
    Incoming chunk:  002200 2912 
    Incoming chunk:  443835 16384 
    Incoming chunk:  344642 16384 
    Incoming chunk:  364143 16384 
    Incoming chunk:  0074cd 16384 
    Incoming chunk:  002200 3542 
    Incoming chunk:  303333 16384 
    Incoming chunk:  414435 16384 
    Incoming chunk:  443435 16384 
    Incoming chunk:  354443 16384 
    Incoming chunk:  374341 16384 
    Incoming chunk:  354444 16384 
    Incoming chunk:  424135 16384 
    Incoming chunk:  002200 7437 
    Incoming chunk:  002200 11958 
    Incoming chunk:  002200 13576 
    Incoming chunk:  002200 8604 
    Incoming chunk:  002200 3416 
    Incoming chunk:  002200 3794 
    Incoming chunk:  002200 3920 
    Incoming chunk:  002200 4550 
    Incoming chunk:  002200 12230 
    Incoming chunk:  002200 4298 
    Incoming chunk:  002200 14958 
    Incoming chunk:  002200 14503 
    Incoming chunk:  002200 12454 
    Incoming chunk:  002200 14084 
    Incoming chunk:  002200 4424 
    Incoming chunk:  002200 3542 
    Incoming chunk:  002200 4424 
    Incoming chunk:  002200 3542 
    Incoming chunk:  002200 11527 
    Incoming chunk:  002200 10222 
    Incoming chunk:  002200 16381 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 14893 
    Incoming chunk:  002200 14019 
    Incoming chunk:  002200 3164 
    Incoming chunk:  002200 3542 
    Incoming chunk:  002200 3290 
    Incoming chunk:  002200 4298 
    Incoming chunk:  002200 3416 
    Incoming chunk:  002200 13393 
    Incoming chunk:  002200 12088 
    Incoming chunk:  002200 14751 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 11840 
    Incoming chunk:  002200 12649 
    Incoming chunk:  002200 3416 
    Incoming chunk:  002200 4550 
    Incoming chunk:  002200 2786 
    Incoming chunk:  002200 3290 
    Incoming chunk:  002200 3416 
    Incoming chunk:  002200 12779 
    Incoming chunk:  002200 13275 
    Incoming chunk:  002200 11462 
    Incoming chunk:  002200 9478 
    Incoming chunk:  002200 3794 
    Incoming chunk:  002200 3038 
    Incoming chunk:  002200 2786 
    Incoming chunk:  002200 6062 
    Incoming chunk:  002200 14072 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 4046 
    Incoming chunk:  002200 14580 
    Incoming chunk:  002200 12389 
    Incoming chunk:  002200 13783 
    Incoming chunk:  002200 11905 
    Incoming chunk:  010000 16384 
    Incoming chunk:  7a0000 16384 
    Incoming chunk:  000000 16384 
    Incoming chunk:  002200 3542 
    Incoming chunk:  002200 4034 
    Incoming chunk:  002200 3542 
    Incoming chunk:  002200 5306 
    Incoming chunk:  304439 16384 
    Incoming chunk:  314534 16384 
    Incoming chunk:  423746 16384 
    Incoming chunk:  383241 16384 
    Incoming chunk:  423436 16384 
    Incoming chunk:  002200 15259 
    Incoming chunk:  029c02 16384 
    Incoming chunk:  373145 16384 
    Incoming chunk:  373641 16384 
    Incoming chunk:  464636 16384 
    Incoming chunk:  443841 16384 
    Incoming chunk:  002200 4172 
    Incoming chunk:  002200 14397 
    Incoming chunk:  002200 11775 
    Incoming chunk:  303331 16384 
    Incoming chunk:  002200 15064 
    Incoming chunk:  002200 9279 
    Incoming chunk:  002200 3542 
    Incoming chunk:  002200 3794 
    Incoming chunk:  002200 3920 
    Incoming chunk:  002200 2660 
    Incoming chunk:  002200 9596 
    Incoming chunk:  002200 13653 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 13706 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 10222 
    Incoming chunk:  002200 11409 
    Incoming chunk:  002200 4046 
    Incoming chunk:  002200 5306 
    Incoming chunk:  002200 3668 
    Incoming chunk:  002200 3164 
    Incoming chunk:  002200 3920 
    Incoming chunk:  002200 13706 
    Incoming chunk:  002200 13458 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 11840 
    Incoming chunk:  002200 15141 
    Incoming chunk:  000200 896 
    Incoming chunk:  002200 12466 
    Incoming chunk:  002200 5054 
    Incoming chunk:  020000 16384 
    Incoming chunk:  002200 3794 
    Incoming chunk:  002200 3416 
    Incoming chunk:  002200 4298 
    Incoming chunk:  7a0000 16384 
    Incoming chunk:  000000 16384 
    Incoming chunk:  002200 2774 
    Incoming chunk:  464430 16384 
    Incoming chunk:  00000a 16384 
    Incoming chunk:  453338 16384 
    Incoming chunk:  005f15 16384 
    Incoming chunk:  304238 16384 
    Incoming chunk:  002200 10287 
    Incoming chunk:  002200 11462 
    Incoming chunk:  002200 12767 
    Incoming chunk:  002200 13393 
    Incoming chunk:  393434 16384 
    Incoming chunk:  343130 16384 
    Incoming chunk:  384643 16384 
    Incoming chunk:  454638 16384 
    Incoming chunk:  002200 4046 
    Incoming chunk:  002200 4172 
    Incoming chunk:  002200 4298 
    Incoming chunk:  002200 3416 
    Incoming chunk:  434239 16384 
    Incoming chunk:  009107 16384 
    Incoming chunk:  423743 16384 
    Incoming chunk:  002200 4676 
    Incoming chunk:  010000 16384 
    Incoming chunk:  7a0000 16384 
    Incoming chunk:  000000 16384 
    Incoming chunk:  002200 1766 
    Incoming chunk:  060040 16384 
    Incoming chunk:  00009f 16384 
    Incoming chunk:  002200 15625 
    Incoming chunk:  002200 11787 
    Incoming chunk:  002200 13092 
    Incoming chunk:  383433 16384 
    Incoming chunk:  002200 10405 
    Incoming chunk:  002b13 16384 
    Incoming chunk:  363243 16384 
    Incoming chunk:  303446 16384 
    Incoming chunk:  002200 4802 
    Incoming chunk:  002200 4928 
    Incoming chunk:  b08123 16384 
    Incoming chunk:  002200 5180 
    Incoming chunk:  002200 3416 
    Incoming chunk:  353501 16384 
    Incoming chunk:  454538 16384 
    Trace
        at Packet.readLengthCodedNumberExt (node_modules/mysql2/lib/packets/packet.js:137:12)
        at Packet.readLengthCodedNumber (node_modules/mysql2/lib/packets/packet.js:109:15)
        at Packet.readLengthCodedString (node_modules/mysql2/lib/packets/packet.js:266:18)
        at new BinaryRow (evalmachine.<anonymous>:26:33)
        at Execute.row (node_modules/mysql2/lib/commands/execute.js:117:11)
        at Execute.Command.execute (node_modules/mysql2/lib/commands/command.js:34:20)
        at PoolConnection.Connection.handlePacket (node_modules/mysql2/lib/connection.js:309:28)
        at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:83:65)
        at PacketParser.executePayload (node_modules/mysql2/lib/packet_parser.js:73:10)
        at PacketParser.executeHeader3 (node_modules/mysql2/lib/packet_parser.js:100:15)

    node_modules/mysql2/lib/packets/packet.js:138
       throw "Should not reach here: " + byte1;
                                     ^
    ReferenceError: byte1 is not defined
        at Packet.readLengthCodedNumberExt (node_modules/mysql2/lib/packets/packet.js:138:38)
        at Packet.readLengthCodedNumber (node_modules/mysql2/lib/packets/packet.js:109:15)
        at Packet.readLengthCodedString (node_modules/mysql2/lib/packets/packet.js:266:18)
        at new BinaryRow (evalmachine.<anonymous>:26:33)
        at Execute.row (node_modules/mysql2/lib/commands/execute.js:117:11)
        at Execute.Command.execute (node_modules/mysql2/lib/commands/command.js:34:20)
        at PoolConnection.Connection.handlePacket (node_modules/mysql2/lib/connection.js:309:28)
        at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:83:65)
        at PacketParser.executePayload (node_modules/mysql2/lib/packet_parser.js:73:10)
        at PacketParser.executeHeader3 (node_modules/mysql2/lib/packet_parser.js:100:15)

**Comment by devoidfury** [comment]
Also - the tests run a randomized text search on a large dataset, which has other fields containing binary data.

Here's the trace:

```
-- cut --
Incoming chunk:  002200 4676 executeStart
Incoming chunk:  002200 3920 executeStart
Incoming chunk:  002200 9909 executeStart
Incoming chunk:  002200 9478 executeStart
Incoming chunk:  002200 13015 executeStart
Incoming chunk:  002200 12820 executeStart
Incoming chunk:  000200 896 executeStart
Incoming chunk:  002200 10157 executeStart
Incoming chunk:  002200 3794 executeStart
Incoming chunk:  002200 4802 executeStart
Incoming chunk:  002200 2912 executeStart
Incoming chunk:  002200 3668 executeStart
Incoming chunk:  002200 3920 executeStart
Incoming chunk:  002200 14763 executeStart
Incoming chunk:  002200 11279 executeStart
Incoming chunk:  002200 13275 executeStart
Incoming chunk:  002200 13694 executeStart
Incoming chunk:  002200 12271 executeStart
Incoming chunk:  002200 3416 executeStart
Incoming chunk:  002200 3668 executeStart
Incoming chunk:  002200 3038 executeStart
Incoming chunk:  002200 3416 executeStart
Incoming chunk:  002200 4046 executeStart
Incoming chunk:  002200 13145 executeStart
Incoming chunk:  002200 11970 executeStart
Incoming chunk:  002200 10848 executeStart
Incoming chunk:  000000 16384 executeStart
Incoming chunk:  002200 245 executePayload
Incoming chunk:  002200 4928 executeStart
Incoming chunk:  002200 3038 executeStart
Incoming chunk:  002200 3290 executeStart
Incoming chunk:  002200 3164 executeStart
Incoming chunk:  002200 15702 executeStart
Incoming chunk:  010000 16384 executeStart
Incoming chunk:  7a0000 16384 executePayload
Incoming chunk:  000000 16384 executePayload
Incoming chunk:  002200 128 executePayload
Incoming chunk:  002200 13653 executeStart
Incoming chunk:  002200 12519 executeStart
Incoming chunk:  002200 15141 executeStart
Incoming chunk:  002200 13328 executeStart
Incoming chunk:  453334 16384 executeStart
Incoming chunk:  323334 16384 executePayload
Incoming chunk:  040096 16384 executePayload
Incoming chunk:  393537 16384 executePayload
Incoming chunk:  443830 16384 executePayload
Incoming chunk:  002200 3038 executeStart
Incoming chunk:  002200 5180 executeStart
Incoming chunk:  002200 4802 executeStart
Incoming chunk:  000040 16384 executePayload
Incoming chunk:  002200 2534 executeStart
Incoming chunk:  383444 16384 executePayload
Incoming chunk:  333501 16384 executePayload
Incoming chunk:  314444 16384 executeHeader3
Trace
    at Packet.readLengthCodedNumberExt (node_modules/mysql2/lib/packets/packet.js:137:12)
    at Packet.readLengthCodedNumber (node_modules/mysql2/lib/packets/packet.js:109:15)
    at Packet.readLengthCodedString (node_modules/mysql2/lib/packets/packet.js:266:18)
    at new BinaryRow (evalmachine.<anonymous>:26:33)
    at Execute.row (node_modules/mysql2/lib/commands/execute.js:117:11)
    at Execute.Command.execute (node_modules/mysql2/lib/commands/command.js:34:20)
    at PoolConnection.Connection.handlePacket (node_modules/mysql2/lib/connection.js:309:28)
    at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:83:65)
    at PacketParser.executePayload (node_modules/mysql2/lib/packet_parser.js:73:10)
    at PacketParser.executeHeader3 (node_modules/mysql2/lib/packet_parser.js:100:15)

node_modules/mysql2/lib/packets/packet.js:138
   throw "Should not reach here: " + byte1;
                                     ^
ReferenceError: byte1 is not defined
    at Packet.readLengthCodedNumberExt (node_modules/mysql2/lib/packets/packet.js:138:38)
    at Packet.readLengthCodedNumber (node_modules/mysql2/lib/packets/packet.js:109:15)
    at Packet.readLengthCodedString (node_modules/mysql2/lib/packets/packet.js:266:18)
    at new BinaryRow (evalmachine.<anonymous>:26:33)
    at Execute.row (node_modules/mysql2/lib/commands/execute.js:117:11)
    at Execute.Command.execute (node_modules/mysql2/lib/commands/command.js:34:20)
    at PoolConnection.Connection.handlePacket (node_modules/mysql2/lib/connection.js:309:28)
    at PacketParser.onPacket (node_modules/mysql2/lib/connection.js:83:65)
    at PacketParser.executePayload (node_modules/mysql2/lib/packet_parser.js:73:10)
    at PacketParser.executeHeader3 (node_modules/mysql2/lib/packet_parser.js:100:15)
```

**Comment by sidorares** [comment]
thanks @devoidfury !

**Comment by sidorares** [comment]
@devoidfury I think I fixed a problem. Can you please try packet-parser-fix branch ?

**Comment by sidorares** [comment]
@devoidfury this is the code I used to reproduce problem (I'll convert it to be deterministic and move to tests):

```js
var PacketParser = require('mysql2/lib/packet_parser.js');
var assert = require('assert');

var bigBuffer = new Buffer(8708*10000);
var p = new Buffer(8708);
p.fill(0);
p[0] = 0;
p[1] = 0x22;
p[2] = 0;
p[3] = 123;
p[4] = 1;
p[5] = 2;
p[6] = 3;
for (var i=0; i < bigBuffer.length; i+= p.length) {
  p.copy(bigBuffer, i);
}


var pp;
var packets = [];
function reset() {
  pp = new PacketParser(handler);
  packets = [];
}
var handler = function(p) {
  //p.dump();
  //debugger;
  console.log('==== packet! ==== %d ', p.length());
  //console.trace();
  assert.equal(p.sequenceId, 123);
  assert.equal(p.readInt8(), 1);
  assert.equal(p.readInt8(), 2);
  assert.equal(p.readInt8(), 3);
  assert.equal(p.readInt8(), 0);
  assert.equal(p.length(), 8704);
}

var start = 0;
function execute() {
  var len = Math.floor(500+Math.random()*100);
  var end = start + len;
  if (end > bigBuffer.length) {
    start = 0;
    end = len;
    reset();
  }
  console.log(pp.execute.name, pp.bufferLength, pp.length, len);
  pp.execute(bigBuffer.slice(start, end));
  start += len;
}

reset();
while(1) {
  execute();
}
```
the problem only occurred when network frame ends at first or second byte of mysql packet

**Comment by devoidfury** [comment]
@sidorares Thanks! I switched to the packet-parser-fix branch and I'll run my tests a few times overnight.

**Comment by sidorares** [comment]
@devoidfury published as v0.15.2

**Comment by devoidfury** [comment]
@sidorares I haven't been able to reproduce the error with the fix -- looks all good over here. Thanks a ton!

**Comment by sidorares** [comment]
@devoidfury your input helped a lot, thanks!
