### ISSUE TITLE
Connection.connect callback may never be executed

### ISSUE THREAD

**Issue by cressie176** [sidorares/node-mysql2#1136]
I've found a subtle inconsistency between mysql and mysql2...

[mysql](https://github.com/mysqljs/mysql#user-content-connection-options) separates the creation of a Connection object and the establishment of a database connection, i.e.
```js
var mysql = require('mysql');

// Create the connection object
var connection = mysql.createConnection({
  host     : 'example.org',
  user     : 'bob',
  password : 'secret'
});

// Actually establish a database connection
connection.connect(function(err) {
  if (err) {
    console.error('error connecting: ' + err.stack);
    return;
  }

  console.log('connected as id ' + connection.threadId);
});
```
However mysql2 both creates the Connection object and establishes the database connection in the [Connection constructor](https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L22-L129), emitting a [connect](https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L110) event when successful. 

mysql2 attempts to maintain compatibility with mysql by adding a [connect](https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L716-L735) function, which listens for the **connect** event and executes the callback, however this creates a potential race condition where if the **connect** event is emitted before `connection.connect(cb)` is called, the callback will never be executed. The following code demonstrates the problem...

```js
const mysql = require('mysql2');

const connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
});

connection.on('connect', () => {
  console.log('Connection established');

  connection.connect(() => {
    console.log('Connect callback executed'); // <------ NEVER REACHED
  });
})

setTimeout(() => {
  console.log('Timeout');
  process.exit(1);
}, 5000);
```

```
$ node index.js 
Connection established
Timeout
```

I discovered this problem while trying to switch [marv-mysql-driver](https://github.com/guidesmiths/marv-mysql-driver/blob/master/index.js#L30-L38) to mysql2. I can easily rewrite my code to not go async between initiating the connection and calling connect, but thought it was worth mentioning, as it could affect other applications, and could be fixed by executing the callback immediately if the connection was currently active, or with an error if the connection had already been closed.

**Comment by sidorares** [comment]
good catch @cressie176 

There is a couple of ways we can fix this: 1) at the beginning of `connect(cb)` check that connection is already established and not errored, depending on the state call cb with correct parameters or 2) enforce that it's called on the same stack as `createConnection()`, e.i throw error if `connect()` is called after handshake response already received

**Comment by sidorares** [comment]
Something like this:

```js
  connect(cb) {
    if (!cb) {
      return;
    }
    if (this._fatalError) {
       return cb(this._fatalError)
    }
    if ( this._handshakePacket) {
      return cb(null, this._handshakePacket)
    }
    //
  }
```

**Comment by cressie176** [comment]
Hi @sidorares,

Thanks for the quick response. I'd be happy with either approach. I can see the advantage of (1) for compatibility, but also (2) should be only a minor inconvenience for those migrating from mysql to mysql2.

**Comment by sidorares** [comment]
Would you like to create a PR with (1) ?

**Comment by cressie176** [comment]
Will do

**Comment by sidorares** [comment]
If you can please add a unit test. If you need any help let me know

**Comment by cressie176** [comment]
I was thinking about adding two integration tests based on something like [this](https://github.com/sidorares/node-mysql2/blob/master/test/integration/test-pool-connect-error.js)

### Test 1
1. Create connection
2. Wait for connect event
3. Call connect
4. Assert no error

### Test 2
1. Create connection
2. Wait for connect event
3. Either close or break the connection (not sure how yet)
4. Call connect
5. Assert error

**Comment by sidorares** [comment]
> Either close or break the connection (not sure how yet)

One way of doing this is to create "MITM" stream and use it as custom transport via "stream" option - https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#connecting-using-custom-stream  That way you don't need to control real server to kill the connection

Alternatively use `createServer()` and actually kill connection from server side, in that case both client and server live in the same node process
