### ISSUE TITLE
Setting password is missing from the documents

### ISSUE THREAD

**Issue by jaakkouu** [sidorares/node-mysql2#1144]
Setting password is missing from the documents

Add an example how to connect to database with password

`{  host: process.env.DB_URL,
       user: process.env.DB_USER,
       pass: process.env.DB_PASS,
       database: process.env.DB_NAME
}`

but it had to be:

`{  host: process.env.DB_URL,
       user: process.env.DB_USER,
       password: process.env.DB_PASS,
       database: process.env.DB_NAME
}`

I had to check from StackOverFlow how to set one up.

**Comment by sidorares** [comment]
At the moment I only document differences with `mysqljs/mysql` as the aim to be drop-in replacement

Documentation is here - https://github.com/mysqljs/mysql#establishing-connections

I agree, maybe at this stage would be good to have good dedicated page with documentation instead redirecting to mysqljs/mysql ( at the codt of on-going support ). Right now don't have enough time for that but happy to help if anyone volunteers
