### ISSUE TITLE
Error while inserting with `execute`

### ISSUE THREAD

**Issue by aggarwaldev** [sidorares/node-mysql2#1150]
Hey,

I'm receiving the following error when I'm trying to `execute` the following statement:
```js
const [results] = await mysql.execute('INSERT INTO `employee` SET ?', employee);
```
Error: 
```
Bind parameters must be array if namedPlaceholders parameter is not enabled
TypeError: Bind parameters must be array if namedPlaceholders parameter is not enabled
```

If I try the exact statement with `query` method, it gets executed without any errors:
```js
const [results] = await mysql.query('INSERT INTO `employee` SET ?', employee);
```

Can you please help me with this? I prefer to use `execute` for insertion while `query` for everything else.

**Comment by aggarwaldev** [comment]
@sidorares Can you please help? I know you might be busy with other tasks but I am unable to find anything related to this.

**Comment by zhi-k** [comment]
If I am not mistaken, your param needs to be inside an Array. So it would be like:

`const [results] = await mysql.query('INSERT INTO `employee` SET ?', **[employee]**);`

**Comment by sidorares** [comment]
@aggarwaldev sorry, somehow missed that

`.execute()` only supports simple types. `INSERT INTO employee SET ?` works with `.query()` is because in that case it's doing more than just parameter interpolation, it's full query builder: `'INSERT INTO posts SET ?', post` => ``INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'``

**Comment by aggarwaldev** [comment]
@zhi-k I'm trying to escape values with `execute` here

**Comment by aggarwaldev** [comment]
@sidorares It's alright mate.
 So you mean `execute` will work if I expand the query?

**Comment by sidorares** [comment]
> So you mean execute will work if I expand the query?

Yes. you can expand it client side and execute expanded query:
```js
const query = mysql.format('INSERT INTO `employee` SET ?', [{id: 123, name: 'test'}]);
const [results] = await connection.execute(query);
```

but I don't see much point compared to `const [results] = await  connection.query('INSERT INTO `employee` SET ?', [{id: 123, name: 'test'}]);` if you have to interpolate on the client

**Comment by aggarwaldev** [comment]
> I don't see much point compared to `query` if you have to interpolate on the client.

I agree and that's why I am replacing execute with query in my code. Although, this certainly helped in clearing few concepts about mysql2.
