### ISSUE TITLE
Unknown auth plugin, not sha-256?

### ISSUE THREAD

**Issue by consciousweb** [sidorares/node-mysql2#1155]
Trying to connect to mysql server on a user set with default auth responds:

> "Error: Server requests authentication using unknown plugin . See TODO: add plugins doco here on how to configure or author authentication plugins."

Ive seen the treads about sha-256, but my error says just "." not sha-256.

mysql version 5.0.96

**Comment by sidorares** [comment]
Hm, this message comes from https://github.com/sidorares/node-mysql2/blob/ebc2cb438d380d81d57ae6e2d227bfafc684eb2a/lib/commands/auth_switch.js#L47

Either initial AuthSwicth packet is incorrect, or it's a bug in the driver or configured plugin name is actually an empty string.

Is it possible to reproduce this from scratch somehow? Ideally starting from fresh docker mysql server + instructions on setting up users / database / schemas

**Comment by consciousweb** [comment]
Not my server unfortunately and its responsible for running other things as
well right now. I have full access/priveleges though and this was tried
with a new full access account with the same result.

**Comment by sidorares** [comment]
can you show settings for the current user? E.i `select * from mysql.Users where name=...` (blank out password)

**Comment by sidorares** [comment]
also debug log might help ( `debug: true` in connection options )

**Comment by consciousweb** [comment]
> I20200512-02:02:12.286(-6)? Add command: ClientHandshake
> I20200512-02:02:12.287(-6)? 2
> I20200512-02:02:12.287(-6)? 3
> I20200512-02:02:12.287(-6)? Add command: Query
> I20200512-02:02:12.288(-6)? Add command: Quit
> I20200512-02:02:12.387(-6)?  raw: 0a352e302e393500ed000000675c755c49392340002ca208020000000000000000000000000000577772573a5a3744326b475d00
> W20200512-02:02:12.388(-6)? (STDERR) [object Object]
> W20200512-02:02:12.388(-6)? (STDERR)     at Connection.handlePacket (/[redacted]/node_modules/mysql2/lib/connection.js:396:17)
> W20200512-02:02:12.389(-6)? (STDERR)     at PacketParser.Connection.packetParser.p [as onPacket] (/[redacted]/node_modules/mysql2/lib/connection.js:75:12)
> W20200512-02:02:12.389(-6)? (STDERR)     at PacketParser.executeStart (/[redacted]/node_modules/mysql2/lib/packet_parser.js:75:16)
> W20200512-02:02:12.389(-6)? (STDERR)     at Socket.Connection.stream.on.data (/[redacted]/node_modules/mysql2/lib/connection.js:82:25)
> W20200512-02:02:12.389(-6)? (STDERR)     at emitOne (events.js:116:13)
> W20200512-02:02:12.389(-6)? (STDERR)     at Socket.emit (events.js:211:7)
> W20200512-02:02:12.389(-6)? (STDERR)     at addChunk (_stream_readable.js:263:12)
> W20200512-02:02:12.389(-6)? (STDERR)     at readableAddChunk (_stream_readable.js:250:11)
> W20200512-02:02:12.390(-6)? (STDERR)     at Socket.Readable.push (_stream_readable.js:208:10)
> W20200512-02:02:12.390(-6)? (STDERR)     at TCP.onread (net.js:601:20)
> I20200512-02:02:12.390(-6)? 0 undefined ==> ClientHandshake#unknown name(0,,56)
> I20200512-02:02:12.403(-6)? Server hello packet: capability flags:41516=(long flag, connect with db, compress, protocol 41, transactions, secure connection)
> I20200512-02:02:12.403(-6)? Sending handshake packet: flags:11203535=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results, plugin auth, plugin auth lenenc client data, session track)
> I20200512-02:02:12.404(-6)? 0 237 <== ClientHandshake#unknown name(1,,95)
> I20200512-02:02:12.405(-6)? 0 237 <== 5b000001cff3aa0000000000e000000000000000000000000000000000000000000000007a69703931310014f526a1618282f4e42cfad0d0746ff8dd5e2e78d16f70656e73697073006d7973716c5f6e61746976655f70617373776f726400
> I20200512-02:02:12.454(-6)?  raw: fe
> I20200512-02:02:12.454(-6)? 0 237 ==> ClientHandshake#unknown name(2,EOF,5)
> W20200512-02:02:12.455(-6)? (STDERR) [object Object]
> W20200512-02:02:12.455(-6)? (STDERR)     at Connection.handlePacket (/[redacted]/node_modules/mysql2/lib/connection.js:396:17)
> W20200512-02:02:12.455(-6)? (STDERR)     at PacketParser.Connection.packetParser.p [as onPacket] (/[redacted]/node_modules/mysql2/lib/connection.js:75:12)
> W20200512-02:02:12.455(-6)? (STDERR)     at PacketParser.executeStart (/[redacted]/node_modules/mysql2/lib/packet_parser.js:75:16)
> W20200512-02:02:12.455(-6)? (STDERR)     at Socket.Connection.stream.on.data (/[redacted]/node_modules/mysql2/lib/connection.js:82:25)
> W20200512-02:02:12.455(-6)? (STDERR)     at emitOne (events.js:116:13)
> W20200512-02:02:12.455(-6)? (STDERR)     at Socket.emit (events.js:211:7)
> W20200512-02:02:12.456(-6)? (STDERR)     at addChunk (_stream_readable.js:263:12)
> W20200512-02:02:12.456(-6)? (STDERR)     at readableAddChunk (_stream_readable.js:250:11)
> W20200512-02:02:12.456(-6)? (STDERR)     at Socket.Readable.push (_stream_readable.js:208:10)
> W20200512-02:02:12.456(-6)? (STDERR)     at TCP.onread (net.js:601:20)
> W20200512-02:02:13.383(-6)? (STDERR) Error: Server requests authentication using unknown plugin . See TODO: add plugins doco here on how to configure or author authentication plugins.
> W20200512-02:02:13.384(-6)? (STDERR)     at Object.authSwitchRequest (/[redacted]/node_modules/mysql2/lib/commands/auth_switch.js:46:11)
> W20200512-02:02:13.384(-6)? (STDERR)     at ClientHandshake.handshakeResult (/[redacted]/node_modules/mysql2/lib/commands/client_handshake.js:150:22)
> W20200512-02:02:13.385(-6)? (STDERR)     at ClientHandshake.execute (/[redacted]/node_modules/mysql2/lib/commands/command.js:39:22)
> W20200512-02:02:13.385(-6)? (STDERR)     at Connection.handlePacket (/[redacted]/node_modules/mysql2/lib/connection.js:417:32)
> W20200512-02:02:13.385(-6)? (STDERR)     at PacketParser.Connection.packetParser.p [as onPacket] (/[redacted]/node_modules/mysql2/lib/connection.js:75:12)
> W20200512-02:02:13.385(-6)? (STDERR)     at PacketParser.executeStart (/[redacted]/node_modules/mysql2/lib/packet_parser.js:75:16)
> W20200512-02:02:13.385(-6)? (STDERR)     at Socket.Connection.stream.on.data (/[redacted]/node_modules/mysql2/lib/connection.js:82:25)
> W20200512-02:02:13.385(-6)? (STDERR)     at emitOne (events.js:116:13)
> W20200512-02:02:13.385(-6)? (STDERR)     at Socket.emit (events.js:211:7)
> W20200512-02:02:13.386(-6)? (STDERR)     at addChunk (_stream_readable.js:263:12)
> W20200512-02:02:13.386(-6)? (STDERR)     at readableAddChunk (_stream_readable.js:250:11)
> W20200512-02:02:13.386(-6)? (STDERR)     at Socket.Readable.push (_stream_readable.js:208:10)
> W20200512-02:02:13.386(-6)? (STDERR)     at TCP.onread (net.js:601:20)
> => Exited with code: 7


![Untitled](https://user-images.githubusercontent.com/14045421/81658080-b0297900-93f5-11ea-90f2-16bbfe8a1ff8.jpg)

**Comment by consciousweb** [comment]
ive since learned the server is centos 5 and does not support tls 1.2, could this be why? and is there a way to set tls below 1.2?

**Comment by sidorares** [comment]
I don't think it's related but haven't checked yet

> is there a way to set tls below 1.2?

here is where secure connection is created by driver https://github.com/sidorares/node-mysql2/blob/0c913ea965ed5c1eb26ed37064bce6f1e38d2095/lib/connection.js#L859-L872

Which version of tls is supported? Afaik node is usually statically linked with openssl so it's version of node what matters, not version of your os or system level openssl

**Comment by consciousweb** [comment]
i believe 1.1 is the most recent supported tls. it seems this has been discussed on the orginal mysql package as creating issues, cant confirm if its relative to mine yet, but im about to try to integrate this fork to confirm:
https://github.com/alexburley/mysql

if you take a look at the ssl options theyve added min/max tls

**Comment by sidorares** [comment]
https://github.com/alexburley/mysql/blob/e37076a39438e5c98c55db9367ad7b2ca10f5e91/lib/Connection.js#L468-L469

yes, this is something that is missing in mysql2. If you can confirm min/max option helps we can work on adding it to mysql2 as well

**Comment by consciousweb** [comment]
Yeah that didnt solve it, still bad handshake. Open to any suggestions.

**Comment by consciousweb** [comment]
solved. the server had old_passwords=1 in my.cnf overriding and resetting changing this setting per user. disabling this, deleting and recreating the user and it works. Out of curiosity, is there any way to use old_passwords with mysql2?

**Comment by sidorares** [comment]
> Out of curiosity, is there any way to use old_passwords with mysql2?

No, [pre mysql 4.1 auth protocol](https://dev.mysql.com/doc/internals/en/old-password-authentication.html) is not supported. Not sure if worth adding full support for it but having better error message in case server uses it would be definitely very helpful

**Comment by consciousweb** [comment]
> better error message in case server uses it would be definitely very helpful
2 days of my life back helpful haha

thank you for your help though
