### ISSUE TITLE
Is it support typescript?

### ISSUE THREAD

**Issue by hg-pyun** [sidorares/node-mysql2#1157]
I don't see, `@types/mysql2`. Where is type definition?

**Comment by sidorares** [comment]
@hg-pyun see #1028 and #952

**Comment by hg-pyun** [comment]
@sidorares Wow, Thank you for reply. It seems WIP.

**Comment by bradws** [comment]
I went to install the types like:
`npm i -D @types/mysql2`
but npm couldn't find them in the registry.

I read that the API is mostly compatible with mysql, so i did a
`>npm i -D @types/mysql`
which downloaded fine (I've use these types with mysql before on another project). Maybe a @types/mysql2 can be created?

So, I tried to begin to type in the code sample:

`const mysql = require('mysql2');
const conn = mysql.`

but the intellisense didn't work after typing in the dot '.' as I was looking for 'createConnection(...)'
Are you able to assist with getting the intellisense working in Visual Studio Code?

**Comment by bradws** [comment]
As per [#952](https://github.com/sidorares/node-mysql2/issues/952) from @Cl00e9ment I ended up doing the following which worked for me :)

```
{
  ...
  "devDependencies": {
    ...
    "@types/mysql2": "git+https://git@github.com/types/mysql2.git"
  }
}

```

**Comment by LinBoLen** [comment]
personal mark.

1. mysql2 better than mysql
2. mysql2 not written with typescript.
3. prepare statement support
4. difference from official mysql lib
