### ISSUE TITLE
[Question] How to access the `host` value used to connect to server?

### ISSUE THREAD

**Issue by haganbt** [sidorares/node-mysql2#1161]
Firstly, thank you for a fantastic library and your continued open source work.

This may be a strange question :) I would like to access the hostname used to connect to the mysql server created with `mysql.createServer();`. So to be clear this is the `host` value specified by a client.

The reason being, the subdomain used by a clients will be different per user (and will trigger other behavior within the MySQL proxy). So for example, creating the server with:

```
const server = mysql.createServer();
server.listen(4000);
server.on("connection", (conn) => {
  console.log("connection");
...
```

The client then connects using the host of the server (including a subdomain). Is there any way I can access this value?

`conn.config.host` appears to be the server host, rather than the one called by the client connection.

Appreciate any guidance.

**Comment by sidorares** [comment]
If client connects via tcp the original host is lost. You can access to client ip using `conn.socket.address()` - socket is usually regular `Net` socket and is saved [here](https://github.com/sidorares/node-mysql2/blob/0c913ea965ed5c1eb26ed37064bce6f1e38d2095/lib/server.js#L19)
It's probably a good Idea to check if `socket.address()` is a function in case it's not a net socket but some other duplex stream connected to net socket

If your question is "can I have access to host similar to how I access HTTP Host header in http server" the answer is no, client does not send host over network, it resolves ip address locally and then only uses that address not a host

**Comment by haganbt** [comment]
Thank you for the detailed reply, understood; that makes good sense.

**Comment by sidorares** [comment]
if you really want to know server and have access to client - it's possible to send arbitrary key/values pairs during connection - see https://github.com/sidorares/node-mysql2/blob/0c913ea965ed5c1eb26ed37064bce6f1e38d2095/lib/packets/handshake_response.js#L68-L87 and https://github.com/sidorares/node-mysql2/blob/ebc2cb438d380d81d57ae6e2d227bfafc684eb2a/test/integration/test-auth-switch.js#L39 . That way when you connect you can copy cost into something like "connectionHost" attribute

**Comment by haganbt** [comment]
Superb! I was just about to ask that as a follow up i.e. any way to set arbitrary values at connection time. That will work nicely.

All the best.

**Comment by haganbt** [comment]
Is the recommended way to access the `connectAttributes` and the `database` through the `authCallback` of the `serverHandshake`? For example:

```javascript
conn.serverHandshake({
    protocolVersion: 10,
    serverVersion: "node.js rocks",
    connectionId: 1234,
    statusFlags: 2,
    characterSet: 8,
    capabilityFlags: 0xffffff ^ ClientFlags.COMPRESS,
    authCallback:    (data, cb) => {
      console.log('==================>', data.database)
      console.log('==================>', conn.clientHelloReply.connectAttributes)
      cb(null, null)
  }
```
