### ISSUE TITLE
Array in params not handled well

### ISSUE THREAD

**Issue by cohenstyle** [sidorares/node-mysql2#1166]
If I try to execute a statement such as "SELECT id FROM users WHERE x IN ?", [[1,2,3]]
It throws errors rather than translating this to: SELECT id FROM users WHERE x IN (1,2,3) which is the behavior node mysql claims it supports.

**Comment by sidorares** [comment]
Hi @cohenstyle , see https://github.com/sidorares/node-mysql2/issues/1070#issuecomment-557936927

in short - with `.query()` parameters are interpolated on the client side and we have more power over syntax ( essentially we are building sql query ourselves ). With `.execute()` query is prepared first and then only parameters are sent, there must be 1:1 mapping between number of  placeholders in the query and number of parameters sent. Also parameters for `.execute()` are all of "simple" type - string, number, Buffer, boolean, null - no objects or array
