### ISSUE TITLE
Parameterization Enhancement

### ISSUE THREAD

**Issue by steelbrain** [sidorares/node-mysql2#117]
The module is great but it would be great to have the PHP-PDO style parameterization. At the moment an examaple sql query is `Select 1+? as sum`, this becomes confusing with more multiple parameters `Select users.json, EXISTS(Select 1 from moderators where moderators.id = ?) as is_moderator from users where users.id = ? and users.status = ? and users.complete_status = ?`.

However in pdo, it's always simple and you can use the same parameter at multiple locations `Select users.json,EXISTS(Select 1 from moderators where moderators.id = :id) as is_moderator from users where users.id = :id and users.status = :status and users.complete_status = :complete_status`.

**Comment by davehorton** [comment]
This seems to break this feature from the underlying mysql library
```
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
```

I now get an error along the lines of "bind parameters must be an array"

**Comment by sidorares** [comment]
@davehorton I don't think this is related to named placeholders feature
