### ISSUE TITLE
How to use mysql_clear_password?

### ISSUE THREAD

**Issue by MarcDelp** [sidorares/node-mysql2#1175]
Hello,

I am trying to use the option `mysql_clear_password` in my app.   
I am fully aware that it is discussed in several places on this repo but none worked.

The full story: my app is using a MySQL DB and we handle it by using knex over the driver from `node-mysql`. We had to change our  configuration and were asked to add the `mysql_clear_password` option to connect to the DB.  
As it seems not to be possible in `node-mysql`, I've looked for other drivers and had a look at `node-mysql2` (version: ^2.1.0).

My base configuration basically is something like this:
```
{
  connection: "my-connection-url"
}
```

For eveything I tried, I had the error `Error: Server requests authentication using unknown plugin mysql_clear_password. See TODO: add plugins doco here on how to configure or author authentication plugins.`

First thing I tried, following the documentation, was to add the field `authSwitchHandler` in my config:
```
  authSwitchHandler: function ({pluginName, pluginData}, cb) {
    if (pluginName === 'mysql_clear_password') {
      cb(null, Buffer.from(password + '\0');
    }
  }
```

Then, as I rececived the above error, I saw in https://github.com/sidorares/node-mysql2/issues/438#issuecomment-256826880 that I needed to add the `insecureAuth`. So I changed my configuration to have something like:
```
{
  connection: "my-connection-url",
  insecureAuth: true,
  authSwitchHandler: function ({pluginName, pluginData}, cb) {
    if (pluginName === 'mysql_clear_password') {
      cb(null, Buffer.from(password + '\0');
    }
  }
}
```
But still had the same error.

Last, I found https://github.com/sidorares/node-mysql2/issues/1154#issuecomment-627643336, and changed  my config to have: 
```
{
  connection: "my-connection-url",
  insecureAuth: true,
  authPlugins: {
    mysql_clear_password: () => () => {
      return Buffer.from(password + '\0')
    }
  }
}
```
I'm still getting the same error.

Can you please tell me where it went wrong?

Thank you !

**Comment by MarcDelp** [comment]
Nevermind. It was my bad with a wrong configuration given to knex.

Solution:  I changed the connection string to an object instead of a connection string, gave info for host/port/user/password/database as fields of the object and passed the `insecureAuth` and `authPlugins` as fields in the connection object. It now looks like:
```
{
  connection: {
    host:  'host',
    port: 'port',
    user: 'user',
    password: 'password',
    database: 'database',
    insecureAuth: true,
    authPlugins: {
      mysql_clear_password: () => () => {
        return Buffer.from(password + '\0')
      }
    }
  }
}
```

Just to be sure: do we still need to add the `insecureAuth` field now? Or has it changed since you now use `authPlugins` instead of  `authSwitchHandler`?

**Comment by sidorares** [comment]
@MarcDelp `insecureAuth` is currently not used in mysql2 ( need to double check that )
