### ISSUE TITLE
Securing login/password info

### ISSUE THREAD

**Issue by tiofabby** [sidorares/node-mysql2#1177]
Hi,
I am wondering if there is a way to secure the login information being in clear text in the example.

- Would there be a way to hide or hash the login/password in some way so if someone tries to retrieve these by looking at the code he wont be able to?

- Also, when connecting to the MySQL DB, is there a way to retrieve these same info when sniffing traffic on client side?
If so, is there a way to avoid that?

Thank you!!
Fabrice

**Comment by sidorares** [comment]
The best you can achieve is to connect with sha1(password), see example in https://github.com/sidorares/node-mysql2/blob/0c422dd9d88a211015ddf4fcc8531048de9b1340/examples/pass-sha.js#L7 :

```js
const mysql = require('mysql2').createConnection({
  host: 'localhost',
  user: 'root',
  database: 'test',
  passwordSha1: Buffer.from('8bb6118f8fd6935ad0876a3be34a717d32708ffd', 'hex')
});

mysql.execute(
  'select ?+1 as qqq, ? as rrr, ? as yyy',
  [1, null, 3],
  (err, rows, fields) => {
    console.log(err, rows, fields);
  }
);
```

While password itself is somewhat protected this way ( you can't easily compute password knowing sha1 ) access to connection is obviously not. Anyone who knows valid passwordSha1 would be able to connect to your db.

This is further hashed with one time server salt so if you sniff the traffic ( but don't have access to original sha1(password) ) you won't be able to connect again using information you retrieved while looking at the traffic

Can you describe a bit more your use case @tiofabby ?
If the problem "I don't want db secrets stored with my code" then solution is "don't store with your code" - retrieve them from env variables or some secure key vault service

**Comment by tiofabby** [comment]
Thanks a lot for your detailed and quick feedback @sidorares 

My use case is that I am a lazy guy :-) and I dont want to build an API between my Web App application and my MysQL database. So I am looking at the option of having the JS Client directly connecting to the DB using your module but on the other side I dont want to offer everyone the login/password to the DB..
The data stored in the DB has nothing really critical and is temporary so securing just the login/password would be enough in my case.

I am not really familiar with Buffer function, but if someone retrieves such piece of code you provided `Buffer.from('8bb6118f8fd6935ad0876a3be34a717d32708ffd', 'hex')` and able to execute it, it will get the password too right?

Thank you
Fabrice

**Comment by sidorares** [comment]
It's hash of a password, you can connect with mysql using hash only. The problem is anyone who knows it can connect, the only benefit is that you don't show the password ( that can be used elsewhere ), but you don't restrict who can assess if you make this hash public

**Comment by tiofabby** [comment]
Yes, so any malicious person looking at the js client code in navigator could retrieve the hash connect to the DB which is what I would like to avoid.
Thanks a lot for your feedback!!
Regards
Fabrice
