### ISSUE TITLE
Connection execute and query work differently, the same request with execute reports unknown column, and query works fine.

### ISSUE THREAD

**Issue by skorolev-tjc** [sidorares/node-mysql2#1178]
connection execute and query work differently, the same request with execute reports unknown column, and query works fine.
I have the following SQL select request:
```SQL
SELECT part_1.* FROM 
`SessionRunFileList` as part_1 
WHERE 1 = 1 and part_1.`SessionUUID` = ? 
AND part_1.`RunId` = ?
ORDER BY part_1.`ErrorCount` DESC 
```
The mentioned table does have the column `ErrorCount` and at the moment I can't get rid of the alias.
When I execute it with **connection.execute** I receive error _**Unknown column 'part_1.ErrorCount' in 'order clause**_, at the same time the same request works fine with connection.query and also within MySQL Workbench or CLI client.

**Comment by sidorares** [comment]
interesting, syntax looks ok to me. Can you try manually preparing first and check if it returns any errors? e.i `connection.prepare(sql, (err, stmt) => console.log(err, stmt))`

Execute and query are different and may behave differently, but in this particular example I'd expect them to have same results.

Can you also try to simplify it a bit? `SELECT * FROM SessionRunFileList WHERE SessionUUID=? AND RunId=? ORDER BY ErrorCount DESC`

**Comment by sidorares** [comment]
Also try to prepare/execute manually in CLI client - https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html#idm45552353860320

**Comment by skorolev-tjc** [comment]
Tried with CLI and it appears it's MySQL itself not mysql2. Tried the following commands:
```SQL
prepare stmt from 'SELECT part_1.* FROM  `SessionRunFileList` as part_1  WHERE 1 = 1 and part_1.`SessionUUID` = ?  AND part_1.`RunId` = ? ORDER BY part_1.`ErrorCount` DESC';
set @UUID = 0xC2B73AA2BDE611EAB5571736CB554B78
set @run = 137
execute stmt using @UUID, @run;
```
Result: _ERROR 1054 (42S22): Unknown column 'part_1.ErrorCount' in 'order clause'_

However after removing alias **part_1** it works fine.

Also, direct SELECT from CLI without PREPARE works fine.

**Comment by skorolev-tjc** [comment]
Closing as this is not relevant to node-mysql2
