### ISSUE TITLE
[Question] How to get insertId value from a Promised query

### ISSUE THREAD

**Issue by albertms10** [sidorares/node-mysql2#1183]
Is there a way I can get `results.insertId` property using the Promised version of `pool.query`—as it returns a `rows` and `fields` tuple instead of `err` and `results`—?:

```js
// Using plain mysql

import * as mysql from "mysql2";

const pool = mysql.createPool(/* config */);

pool.query("INSERT INTO ...", (err, results) => {
  console.log(results.insertId);
});
```

```js
// Using Promised mysql

import * as mysql from "mysql2/promise";

const pool = mysql.createPool(/* config */);

pool.query("INSERT INTO ...")
  .then(([rows, fields]) => {
    console.log(/* Where can I get `resultId`? */)
  });
```

**Comment by sidorares** [comment]
Hi @albertms10 , promise pool.query resolves with same values as a callback - see https://github.com/sidorares/node-mysql2/blob/7ee4a7bbac0ca330728e371a53879fd3df78855f/promise.js#L334 and https://github.com/sidorares/node-mysql2/blob/7ee4a7bbac0ca330728e371a53879fd3df78855f/promise.js#L16 

in case of insert "columns" argument is undefined and "rows" is instead "resultset OK packet" - https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html

in your example:

```js
import * as mysql from "mysql2/promise";

const pool = mysql.createPool(/* config */);

pool.query("INSERT INTO ...")
  .then(([result]) => {
    // 
  });
```

other libraries do this slightly differently, for example mariadb driver returns array with extra `meta` field.
