### ISSUE TITLE
Property `escape` does not exist on type `Pool`

### ISSUE THREAD

**Issue by albertms10** [sidorares/node-mysql2#1184]
When accessing the `escape` method from a `Pool` object, TypeScript warns that it does not exist on its type. By the way, if you use the `Pool`’s `connection`, it works as expected.

<img width="523" alt="Captura de Pantalla 2020-08-01 a les 22 03 03" src="https://user-images.githubusercontent.com/26429103/89109615-1fd26180-d443-11ea-8199-a6b598e41d32.png">

From the [`mysql`](https://github.com/mysqljs/mysql/blob/master/Readme.md#escaping-query-values) Readme file:
> […] You can do so using the `mysql.escape()`, `connection.escape()` or `pool.escape()` methods.

This Pull request (#531) may be related.

**Comment by albertms10** [comment]
> I'm trying to solve some type issues too, maybe this can help: in my class it seems to find the escape method. Maybe it depends from where you imported the Pool and other types? I'm using @types/mysql2 but it looks like I'm importing Pool from mysql2/promise in order to use the promise method...
> 
> ![image](https://user-images.githubusercontent.com/22741818/89428804-1431b400-d73d-11ea-8851-fbb416908d09.png)

Taking a look at the screenshot, it looks like VSCode is suggesting you `Connection.escape`, not `Pool.escape`. Using TypeScript will not allow this, anyway…

**Comment by manueledones** [comment]
hmmm, maybe because Pool extends Connection

![image](https://user-images.githubusercontent.com/22741818/89467927-c8036580-d776-11ea-94a2-5f35ab1dac6e.png)

**Comment by ashkan117** [comment]
Any updates on this? Had a similar issue where I could not call pool.releaseConnection(conn) when I type pool as **Pool**. Changing the type to **any** seemingly fixes things for now.

**Comment by wellwelwel** [comment]
This has been fixed in #1610.

https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/typings/mysql/index.d.ts#L56
