### ISSUE TITLE
iconv-lite < 0.6.0 breaks for Electron-based apps

### ISSUE THREAD

**Issue by welljsjs** [sidorares/node-mysql2#1187]
This is a bug that was fixed in iconv-lite >= 0.6.0: https://github.com/ashtuchkin/iconv-lite/issues/204#issuecomment-640472025 that results in failing imports for Electron-based applications using Webpack.

Please upgrade iconv-lite to 0.6.x.

**Comment by dougwilson** [comment]
I believe you mean >= 0.6.0 correct?

**Comment by welljsjs** [comment]
Yes, sorry, that's correct
