### ISSUE TITLE
[Question] too many connections

### ISSUE THREAD

**Issue by wengair** [sidorares/node-mysql2#1193]
I'm using mysql2 with Next.js endpoint.
My SQL server is built in a docker and the version is 5.
I use `show status like '%onn%';` to check my connection and found out that my `Threads_connected` can only go up.

Here's how I use the pool:
I have a pool.js, which defines and exports the module `Pool` with 2 functions `get (createPool)` and `release (pool.end)`.
I only pass host, db name, user, and password to createPool.
I have a `endpointLIbrary.js` that define my `Query` function, which looks like this:
```
export const pool = Pool.get()

export const Query = async (queryString, queryParams) => {
  const promisePool = pool.promise()
  const [result] = await promisePool.execute(queryString, queryParams)
  return result
}
```
Then I import and access `Query` in my Next.js's API routes, so I basically use this function in many different files.
E.g. the endpoint `/projects` and `/projects:id` are handled by different .js files and there's no central file connects each endpoint.
Whenever I query my DB using `Query`, the `Threads_connected` add 1.
The number of `Threads_connected` won't change if I query in a short time, but it'll still add 1 after around 3~5 minutes.

I'm not sure where I did wrong, any suggestion or thought or related article would be appreciated!

**Comment by sidorares** [comment]
how is your `Pool.get()` implemented? Are you reusing same pool or you create new one for `Pool.get()` call?

**Comment by sidorares** [comment]
> Is there any way that I can check if I'm using the same pool?

you could check connection ids of connections in the pool.

`console.log(pool._allConnections.toArray().map( conn => conn.threadId ))`

**Comment by sidorares** [comment]
Also try to log free and queued connections https://github.com/sidorares/node-mysql2/blob/96fe54c73dd5d99d308ca7c2d2e1dcf3ddb60d24/lib/pool.js#L26-L28

**Comment by wengair** [comment]
When I first load the page, I got the following result:
```
_allConnections
[ 1807, 1808, 1809 ]
_freeConnections
[ 1809, 1807 ]
_connectionQueue
[]
```
When I refresh the page and query again, my connection's id increased:
```
_allConnections
[ 1811, 1812, 1813 ]
_freeConnections
[ 1811, 1812 ]
_connectionQueue
[]
```

**Comment by wengair** [comment]
I'm not sure whether this is an expected result.
I remember that the pool will release the connection after the query ends.
Does this result mean the connections are being released correctly and no connections stuck in the queue?

**Comment by sidorares** [comment]
do you call `Pool.release()` ( your wrapper, from https://github.com/sidorares/node-mysql2/issues/1193#issuecomment-683551994 ) anywhere in your code? From what you posted looks like it's completely new set of connections, not sure why

**Comment by wengair** [comment]
> do you call Pool.release() ( your wrapper, from #1193 (comment) ) anywhere in your code?

No, the only place that I call `Pool.release()` is when the transaction fails.
> From what you posted looks like it's completely new set of connections, not sure why

Could this situation caused by the design of Next.js API routes? 
It doesn't have a `server.js` file, every endpoint is accessed independently.
So even I only call it once in one library file, it still creates a new pool each time?

If this sounds reasonable to you, I guess I have to `Pool.get()` at the beginning of every endpoint file and `Pool.release()` after the query is finished? (If that endpoint only does a single query, maybe I can just get a connection?)

**Comment by sidorares** [comment]
oh, that's totally possible ( and there is no way around it ). Each api call can happen from separate physical server 

you can probably just create and close single individual connection before / after query, no need to have pool for that

**Comment by wengair** [comment]
> are you using vercel for hosting?

Probably not. I think I'll host everything on only one server.

> oh, that's totally possible ( and there is no way around it ).

Aw, too bad... but at least the problem got solved.
Thank you for your time and prompt reply!

**Comment by sidorares** [comment]
If you host everything on one server it should be possible to reuse same set of connections, my "not possible" was in relation to serverless-like architecture. Next itself should not prevent from doing that

**Comment by wengair** [comment]
> If you host everything on one server it should be possible to reuse same set of connection

I see. 
I think I'll just put it there and try to check the connection again when everything goes to server (should be a while later). 
Thank you!

**Comment by wengair** [comment]
I think the problem is Next.js complies the page each time when I visit the endpoint in the develope mode.
That's why I keep creating new pools and hit the limit.
I don't have this problem after I build and run the production mode.
Thank you!

**Comment by Kennytian** [comment]
`SET GLOBAL wait_timeout = 60; `

run this command in mysql client command terminal, the timeout unit is seconds
