### ISSUE TITLE
What does 2181036031 value in capabilityFlags mean?

### ISSUE THREAD

**Issue by jannikkeye** [sidorares/node-mysql2#1197]
Using `0xffffff ^ ClientFlags.COMPRESS` we cannot connect to the mysql2 server using SSL mode `Preferred` but using `2181036031` as in example [server](https://github.com/sidorares/node-mysql2/blob/master/examples/server.js) it works.

The proxy example does work https://github.com/sidorares/node-mysql2/blob/master/examples/mysqlproxy.js.

The only difference is the capability flags. Why does `0xffffff ^ ClientFlags.COMPRESS` prevent us from connecting with SSL mode `Preferred`

**Comment by sidorares** [comment]
hi @jannikkeye did you solve your issue?

2181036031 is the combination of the following flags:
```
LONG_PASSWORD
FOUND_ROWS
LONG_FLAG
CONNECT_WITH_DB
NO_SCHEMA
COMPRESS
ODBC
LOCAL_FILES
IGNORE_SPACE
PROTOCOL_41
INTERACTIVE
IGNORE_SIGPIPE
TRANSACTIONS
RESERVED
SECURE_CONNECTION
MULTI_STATEMENTS
MULTI_RESULTS
PS_MULTI_RESULTS
PLUGIN_AUTH
CONNECT_ATTRS
PLUGIN_AUTH_LENENC_CLIENT_DATA
CAN_HANDLE_EXPIRED_PASSWORDS
SESSION_TRACK
DEPRECATE_EOF
REMEMBER_OPTIONS
```

**Comment by jannikkeye** [comment]
Yes, I needed the SSL flag. Thanks for clarifying what the value actually means :)
