### ISSUE TITLE
MySQL JSON field requires JSON string rather than JavaScript object

### ISSUE THREAD

**Issue by chrisveness** [sidorares/node-mysql2#1220]
It would be nice if a JavaScript object could be passed as a parameter to be stored in a JSON field.

Given a table

    CREATE TABLE `tbl` (
      `id` integer,
      `fld` json
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8

If I do

    await connection.query('UPDATE tbl SET ? WHERE id = ?', [ { fld: { key: 'val' } }, 1001 ]);

I get an error

    Error: Invalid JSON text: "Invalid value." at position 1 in value for column 'tbl.fld'.

If I do

    await connection.query('UPDATE tbl SET ? WHERE id = ?', [ { fld: JSON.stringify({ key: 'val' }) }, 1001 ]);

then it's fine.

It's not a big deal to do the extra `JSON.stringify`, but it would be nice if an object could be passed.

This may be related to #1173, I'm not sure.

I'm using mysql2@2.2.5 against MySQL v8.0.15.

**Comment by chrisveness** [comment]
Note: if I use `connection.execute()` instead, I get an error "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? WHERE id = ?' at line 1"

**Comment by sidorares** [comment]
`.query()` parameters interpolation is completely client side, don't see how we can detect that whole object should be serialized as JSON string. 

for `connection.execute()` we do have parameter types returned from server from "prepare" step, but there are restrictions where placeholders can be used enforced by mysql sql parser

**Comment by chrisveness** [comment]
Ok, I thought that might be straightforward, but things are seldom as straightforward as we might hope!

Thanks
