### ISSUE TITLE
Promise: launch rejection problem

### ISSUE THREAD

**Issue by ascognamiglio** [sidorares/node-mysql2#1233]
Hi all,
we're developing a way to manage error in SQL when pool.query is launched inside a async promise. 
Using try catch, when there's some syntax problem or connection problem or missing table/fields, no reject are launched.
The only way to trigger a catch that we've found is to insert a makeDoneCb another time in a try catch.

	try{
        const done = makeDoneCb(resolve, reject, localErr);
        if (args) {
          corePool.query(sql, args, done);
        } else {
          corePool.query(sql, done);
        }
      }catch(err){
        reject('errore sul db');
      }

Is it correct? There's another easiest way? Are we doing some error?

Thanks from now to all.

**Comment by sidorares** [comment]
can you show how `.query()` is called?

```js
async function dbConsumer(pool) {
    try {
       await pool.query('select 1+1');
    } catch {
      // if you have error from db in theory it should be handled here, without extra try/catch in asyncPool.query*(
    }
}
```

can you prepare some simple example I can reproduce?

**Comment by ascognamiglio** [comment]
Hi sidorares and thanks for the quick answer.
I've rechecked al the code, and you're right. Reject is launched anyway without extra try/check. 
Was a problem of catching error on our functions. 
Regards.
