### ISSUE TITLE
Mysql server 8.0.22 + mysql2 = bug of matching ascii and unicode strings

### ISSUE THREAD

**Issue by Perlover** [sidorares/node-mysql2#1237]
Details:

In my project i found very strange bug after upgrade mysql-server 8.0.21 -> 8.0.22 package (Ubuntu 18.04)
My mysql statements throwed SQL errors as "Illegal mix of collations..."
I researched all docs of Mysql. There is Rerertoire mechanism. This bug manifests itself as if this mechanism does not work in mysql-server 8.0.22. But i cannot reproduce it by hand through mysql CLI command. This gave me the idea that the problem lies somewhere either in your module, or not in compatibility due to a change in mysql-server 8.0.22. I wrote a test for this problem and i was able to reproduce the problem. What is most interesting, it manifests itself only in `execute` (not `query`) method and when the table or/and SQL query has a second field. So i think it's prepared statement related problem.

I write test for bug described in pull request:

https://github.com/sidorares/node-mysql2/pull/1235

I described this bug at Oracle's bug report system too:

https://bugs.mysql.com/bug.php?id=101346

**Comment by jlottesnrgxp** [comment]
Also currently experiencing this on my dev box.

**Comment by testn** [comment]
@Perlover this is the server problem right? If so, can you close this?
