### ISSUE TITLE
COALESCE(SUM(field), 0) returning string "0", expecting number

### ISSUE THREAD

**Issue by marchand-software** [sidorares/node-mysql2#1238]
Using an empty table and finding the sum on an INT field then coalescing the results to 0 results in "0" as a string.

SUM(field) results in `null`
COALESCE(NULL, NULL, 0) results in` 0`
COALESCE(SUM(field), 0) results in `"0"`

[console.log](https://i.imgur.com/nqGWaqe.png) image

Using TypeScript & Express.js.

**Comment by sidorares** [comment]
can you show what's returned in fields for this query ( second argument to callback after result, or second element in array you get from promise version )

the driver converts to "nearest" JS type based on what mysql reports as field type for the result ( data is sent back as text anyway even in case of number )

**Comment by sidorares** [comment]
also is that using prepared statement? ( '.query()` or `.execute()` )?

**Comment by marchand-software** [comment]
This is using `.query()`.

`{
   "_buf":{
      "type":"Buffer",
      "data":[
         1, 0, 0, 1, 1, 43, 0, 0, 2, 3, 100, 101, 102, 0, 0, 0, 21, 67, 79, 65, 76, 69, 83, 67, 69, 40, 83, 85, 77, 40, 113, 116, 121, 41, 44, 32, 48, 41, 0, 12, 63, 0, 33, 0, 0, 0, 246, 128, 0, 0, 0, 0, 5, 0, 0, 3, 254, 0, 0, 34, 0, 2, 0, 0, 4, 1, 48, 5, 0, 0, 5, 254, 0, 0, 34, 0
      ]
   },
   "_clientEncoding":"utf8",
   "_catalogLength":3,
   "_catalogStart":10,
   "_schemaLength":0,
   "_schemaStart":14,
   "_tableLength":0,
   "_tableStart":15,
   "_orgTableLength":0,
   "_orgTableStart":16,
   "_orgNameLength":0,
   "_orgNameStart":39,
   "characterSet":63,
   "encoding":"binary",
   "name":"COALESCE(SUM(qty), 0)",
   "columnLength":33,
   "columnType":246,
   "flags":128,
   "decimals":0
}`

is the output of the second argument in the promise verison.

**Comment by sidorares** [comment]
Mysql server returns type 246 ( aka DECIMAL 0xf6 - see https://github.com/sidorares/node-mysql2/blob/442d3042245c761eaeafe36b0e35d45cb3f87025/lib/constants/types.js#L23 ) 

To preserve accuracy while converting to JS number for DECIMAL types result returned the same way it was sent from server, as string

The reasoning is that you use "normal" numbers ( SORT, LONG, FLOAT, DOUBLE ) for numeric values and DECIMAL where it's potentially important to have exact precision ( accounting / finances for example ), it's up to the client to decide how to consume that

You can change this behaviour with custom `typeCast` - see docs at https://github.com/mysqljs/mysql#custom-type-casting
