### ISSUE TITLE
Manual SQL-string cleaning up before query execution

### ISSUE THREAD

**Issue by pubmikeb** [sidorares/node-mysql2#1243]
Given the SQL-query:

```sql
# noinspection SqlResolve, SqlMissingColumnAliases
		UPDATE tblStudent
		SET
			isDeleted = 1,
			lastUpdatedBy = 2,
			lastUpdatedOn = NOW()
		WHERE
			recordID = 53;
```
I send this query to `await pool.query(…)` as a string, which contains some non-SQL-related special characters, e.g. `\n`, `\t`, and even IDE-specific annotation (`# noinspection SqlResolve, SqlMissingColumnAliases`):

![06_214037](https://user-images.githubusercontent.com/17231333/98412747-c6e51b80-2078-11eb-979a-8808ff834e13.png)

The query is working fine.

Questions:

1. Should I manually «clean-up» the SQL-query string to omit non-SQL-related special characters prior sending it to the SQL-engine?
2. Can manual SQL-string cleaning-up improve the query performance or there shouldn't be a huge boost?

Thanks.

**Comment by sidorares** [comment]
I believe the answer is "no" to both. If it's in hot path - try to benchmark before after, but I don't expect much difference. The whole query is sent over network to the server so it might be slight improvements in time.
