### ISSUE TITLE
Support nonprepared queries

### ISSUE THREAD

**Issue by Mygod** [sidorares/node-mysql2#1257]
Currently this library forces *every single* query to be a prepared statement, and caches them in an LRU, and expect users to just follow the best practice and reuse the query. This is not a reasonable thing to do and I have two reasons for it.

1. Currently this library is used by [sequelize](https://github.com/sequelize/sequelize), one of the most popular ORM libraries for node.js. sequelize automatically builds SQL queries based on what columns were changed, and therefore in the worst case, it could create an exponential number of queries to mysql2. To make matters worse, sequelize does not *always* follow the best practice of using bindParams everywhere. Related issue: https://github.com/sequelize/sequelize/issues/10832
2. This is a more general phenomenon. By the way this library is implemented, a big overhead is enforced on every query that is dynamically generated. (For example, if a user wishes to create a complicated filter, and the application translates it to a complicated SQL query.)

Conclusion: please do not enforce prepared statements on *every single* query, maybe only give it as an alternative, e.g. `connection.executePrepared`.

**Comment by sidorares** [comment]
you can manually prepare and execute: https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md#manual-prepare--execute

what would be the alternative of "not preparing"? Right now you can do non-ps via `.query()`, "automatic ps" with `.execute()` and "manual ps" with `connection.prepare(sql)` + `ps.execute(parameters)`

**Comment by Mygod** [comment]
Ah I see. `query` is the thing I am looking for. Thank you.

**Comment by sidorares** [comment]
yeah, it's up to higher level library like sequelize to decide which api to use
