### ISSUE TITLE
Client-side authentication plugin errors not closing the connection

### ISSUE THREAD

**Issue by ruiquelhas** [sidorares/node-mysql2#1263]
I was in the process of writing an authentication plugin to be used with the framework provided by mysql2, and I've realized that when a client-side plugin throws an error, the server connection is not closed.

```js
const mysql = require('mysql2')

const connection = mysql.createConnection({
  authPlugins: {
    caching_sha2_password () {
      throw new Error('boom')
    }
  },
  user: 'root' // with mysqld --initialize-insecure
})

connection.connect(err => {
  if (err) {
    console.error(err)
    return
  }

  console.log('done')
  connection.end()
})
```

Is this by design and are the plugins expected to close the connection themselves? In such a case, the only way the application can do it is by calling `process.exit()` or similar, otherwise if it calls `connection.end()` or `connection.destroy()` it will bump into an `Unexpected packet while no commands in the queue` error, which is somewhat noisy.

As far as I can tell, everytime the plugin "throws", you end up reaching the `handhakeResult` handler in `ClientHandshake` command.

https://github.com/sidorares/node-mysql2/blob/master/lib/commands/client_handshake.js#L157

The handler happens to emit an `error` event in the `connection` instance, for which, the event handler will only execute the callback with the error argument. However, the connection is already open by this point, and it does not close it.

https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L744

In the end, the fact that the client-side authentication plugin throws an error means that there was indeed an authentication error and there isn't really any way to recover from it unless creating a connection with different options. This should probably be no different than the case where the authentication error happens in the server and the server itself ends up closing the connection, allowing the client to also release resources. But we can disagree about this.

So, I won't claim this is a bug or a limitation, but rather an oversight or a design decision, and, if that is the case, is this something that can change?

**Comment by ruiquelhas** [comment]
@sidorares any thoughts about this?

**Comment by sidorares** [comment]
> So, I won't claim this is a bug or a limitation, but rather an oversight or a design decision, and, if that is the case, is this something that can change?

good observation, I think it should result in fatal 'error' event on connection, so that consumer ( or pool ) can throw it away and decide what to do ( report error / retry connection etc )

**Comment by ruiquelhas** [comment]
Yes, I think that is good idea. I'm thinking about submitting that PR, but I'm still waiting for an internal approval to do so. In the meantime, if you think this is something you can do yourself, that's even better.

Thanks

**Comment by oleh-poberezhets** [comment]
I have the same bug.
But I see additional information:
```
Warning: got packets out of order. Expected 7 but received 1
Warning: got packets out of order. Expected 8 but received 0
Error: Unexpected packet while no commands in the queue
    at PoolConnection.protocolError (/opt/vauth/node_modules/mysql2/lib/connection.js:371:17)
    at PoolConnection.handlePacket (/opt/vauth/node_modules/mysql2/lib/connection.js:418:12)
    at PacketParser.onPacket (/opt/vauth/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/opt/vauth/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/opt/vauth/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
```

Module version - **2.2.5**
