### ISSUE TITLE
Unhandled Promise rejections on asynchronous authentication plugins

### ISSUE THREAD

**Issue by ruiquelhas** [sidorares/node-mysql2#1264]
I was in the process of writing an authentication plugin to be used with the framework provided by mysql2, and I've realized that when an asynchronous client-side plugin throws an error, it isn't reported to the user.

```js
const mysql = require('mysql2')

const connection = mysql.createConnection({
  authPlugins: {
    caching_sha2_password () {
      return () => Promise.reject(new Error('boom'))
    }
  },
  user: 'root' // with mysqld --initialize-insecure
})

connection.connect(err => {
  if (err) {
    console.error(err)
    return
  }

  console.log('done')
  connection.end()
})
```

I'm assuming asynchronous plugins are, in fact, meant to be supported because, as far as I can tell, everytime the plugin returns a `Promise`, you end up reaching either the [`authSwitchRequest`](https://github.com/sidorares/node-mysql2/blob/master/lib/commands/auth_switch.js#L20) or the [`authSwitchMoreData`](https://github.com/sidorares/node-mysql2/blob/master/lib/commands/auth_switch.js#L60) handlers (depending on the authentication stage you are in) and both execute the following:

```js
Promise.resolve(connection._authPlugin(pluginData)).then(data => {
  if (data) {
    connection.writePacket(new Packets.AuthSwitchResponse(data).toPacket());
  }
});
```

However, there is no `Promise` rejection handling, which, in this case, means there is no feedback from the client until the server closes the connection due to inactivity.

Is this intended or is this an oversight? I guess this can be easily improved by introducing something like:

```js
Promise.resolve(connection._authPlugin(pluginData)).then(data => {
  if (data) {
    connection.writePacket(new Packets.AuthSwitchResponse(data).toPacket());
  }
}).catch(err => {
  connection.emit('error', err)
});
```

In the end, the application would, at least, have some feedback, although the driver would still hang until the server closes the connection. This is also something I think can be improved (see #1263).

**Comment by ruiquelhas** [comment]
@sidorares any thoughts about this or #1263?

**Comment by sidorares** [comment]
@ruiquelhas not intended and an oversight, happy to discuss solution, suggested `.catch(err => connection.emit('error', err));` might be good enough

**Comment by sidorares** [comment]
@ruiquelhas not intended and an oversight, happy to discuss solution, suggested `.catch(err => connection.emit('error', err));` might be good enough

**Comment by ruiquelhas** [comment]
Right, I don't see much else that can be done, in particular, if we do something about #1263 as well. Again, I'm waiting for an internal approval to submit a PR but I definitely won't mind if you do it yourself :)

Thanks
