### ISSUE TITLE
Can't create more than max_prepared_stmt_count statements (current value: 16382)

### ISSUE THREAD

**Issue by HsinHeng** [sidorares/node-mysql2#1266]
Package Version:

mysql2: 1.6.5
sequlize: 5.13.1

In Production phase, I encouter the prepare_stats_count exceeed limitation.
I temporarily in crease the value max_prepared_stmt_count for our RDS.

I think this issue is critical,
could anybody tell me have solution to resolve it?
can I close the prepare stats, or close prepare stats after execution?

**Comment by vlasky** [comment]
@HsinHeng are you parameterising your statements correctly? That is, are you using question mark placeholders wherever possible?

 If you are not, then you will keep creating new prepared statement handles and run into this issue repeatedly.

**Comment by sidorares** [comment]
maybe we should add a warning similar to how EventEmitter [tries to warn you about potential leak](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n) ( not sure what's reasonable limit should be and what's good heuristic to notice errors like `conn.execute('select items from xyz where item.id = ' + id)` )

**Comment by vlasky** [comment]
This is an extract from a guide I wrote for the developers working for us in 2016:

The node-mysql2 library uses the binary protocol provided by MySQL for passing arguments to prepared statements handles, which is more efficient than the conventional text-based protocol.

However, this mechanism is far more sensitive to mistakes in the way that queries and data are prepared. In the process of debugging and testing the DC code, I found a number of such mistakes which caused the prepared queries to malfunction.

I wish to draw your attention to these examples to help everyone avoid making them in the future:

1\. When performing a parameterised query, ensure that the second argument is ALWAYS an array - even for a single parameter.

Incorrect:

`querySyncBusinessLiveDb("SELECT driverid FROM drivers WHERE driverid = ?", driverIdVal);`

Correct:

`querySyncBusinessLiveDb("SELECT drierid FROM drivers WHERE driverid = ?", [driverIdVal]);`


2\. When using a MySQL function or operator that can take a varying number of arguments, you need to have a ? placeholder for EACH argument. That is, the number of question mark placeholders that you depends on the number of elements in the parameter array passed as the second argument.

`driverIdValues = [0,1,2,3];`

Incorrect:

`querySyncBusinessLiveDb("SELECT * from drivers where driverid IN (?)", [driverIdValues]`

Correct:

```
//The line below is an efficient way of creating the required comma-separated
//string with the correct number of question marks "?,?,?,?"

driverIdValsPlaceHolders = Array(driverIdValues.length).fill("?").join();

querySyncBusinessLiveDb("SELECT * from drivers where driverid IN (" + driverIdValsPlaceholders +")", driverIdValues);
```



3\. MySQL fields of type TINYINT(1) do not store boolean literals

TINYINT(1) is often used to represent boolean values, but it does not store the boolean literals false or true - it stores integers 0 and 1.

You must ensure that you properly convert JS boolean variables into integers.

Incorrect:

```
on_shift = true;

querySyncBusinessLiveDb("UPDATE drivers SET on_shift = ? WHERE driver_id=1", [on_shift]);
```

Also Incorrect:

```
on_shift = parseInt(true);

querySyncBusinessLiveDb("UPDATE drivers SET on_shift = ? WHERE driver_id=1", [on_shift]);
```

Explanation: parseInt() does not convert a boolean value into 0 or 1 - it converts to NaN (not a number). This is not the outcome that you want.

Correct:

The most compact way of converting a boolean value to an integer is by using a ternary expression like this

`on_shift = on_shift_bool ? 1 : 0;`


4\. Do not quote numerical values unless they are intended to be stored in a varchar/text MySQL datatype.

Incorrect:

`SELECT FROM drivers WHERE driver_id = '1';`

Correct:

`SELECT FROM drivers WHERE driver_id = 1;`

**Comment by sidorares** [comment]
thanks for sharing this @vlasky !

**Comment by HsinHeng** [comment]
> @HsinHeng are you parameterising your statements correctly? That is, are you using question mark placeholders wherever possible?
> 
> If you are not, then you will keep creating new prepared statement handles and run into this issue repeatedly.

@sidorares
I use the sequelize ORM to programing not use raw SQL interface, parameterising was automatic in sequelize layer/mysql2 layer.

I reference this closed issue https://github.com/sidorares/node-mysql2/issues/702.

Therefore, 
1. I add "maxPreparedStatements" parameter  to force close prepare statement for each connection session if exceed maxPreparedStatements.
2. And adjust max_prepared_stmt_count > connections * maxPreparedStatements.

I found that It start to close prepare statement in our environments.

is it a good solution to resolve this problem?

**Comment by sidorares** [comment]
lowering `maxPreparedStatements` would solve the error but it'll make communication quite inefficient compared even to a non-ps "query()": 1) prepare 2) execute 3) close each time.

**Comment by HsinHeng** [comment]
> lowering `maxPreparedStatements` would solve the error but it'll make communication quite inefficient compared even to a non-ps "query()": 1) prepare 2) execute 3) close each time.

OK, thanks for your reply!
