### ISSUE TITLE
replication protocol：first event is ROTATE_EVENT not FORMAT_DESCRIPTION_EVENT 

### ISSUE THREAD

**Issue by RifeWang** [sidorares/node-mysql2#1269]
As the mysql document said: the first event of binlog file is FORMAT_DESCRIPTION_EVENT, but I get ROTATE_EVENT after sending COM_BINLOG_DUMP packet , and the tcp connection was closed by mysql server , why ?

mysql version: 5.7.18-log.

**Comment by sidorares** [comment]
@RifeWang have you found an answer?

**Comment by RifeWang** [comment]
I find an answer about rotate event: https://softwareengineering.stackexchange.com/questions/326225/why-does-mysql-slave-receive-two-rotate-events .

But the connection was closed by mysql server for 5.7.18-log version , I have no idea, I change another version and it works well.
