### ISSUE TITLE
insertId for bigint incorrect 

### ISSUE THREAD

**Issue by weijarz** [sidorares/node-mysql2#1275]
```js
const mysql = require('mysql2/promise')

const bigId = BigInt('18446744073709551615') // 2**64 - 1
const bigId2 = bigId - 1000n

async function main() {
  conn = await mysql.createConnection({
    user: 'root',
    password: '',
    supportBigNumbers: true,
    bigNumberStrings: true
  })
  await conn.query('drop database if exists test_mysql')
  await conn.query('create database test_mysql')
  await conn.changeUser({ database: 'test_mysql' })

  await conn.query('create table ta (id bigint unsigned auto_increment primary key, name varchar(10))')
  await conn.query('insert into ta (id, name) values (?, ?)', [bigId2, 'a'])
  const result = await conn.query('insert into ta (name) values (?)', ['b'])
  console.log('Id from insertId', result[0].insertId)
  const row = await conn.query('select max(id) from ta')
  console.log('Id from query', row[0][0])

  await conn.end()
}

main().catch(e => {
  console.error(e)
})
```

Outputs:
```
Id from insertId -1000
Id from query TextRow { 'max(id)': '18446744073709550616' }
```

How to get the right insertId?

**Comment by sidorares** [comment]
did you find explanation @weijarz?
I havent tried your repro but my guess is what you see is expected mysql server behaviour

**Comment by weijarz** [comment]
@sidorares MySQL can actually store numbers larger than Number.MAX_SAFE_INTEGER into bigint column, but mysql2.ResultSetHeader.insertId uses a number (not bigint), so the id is truncated.

**Comment by sidorares** [comment]
can you trace it to these lines: https://github.com/sidorares/node-mysql2/blob/a640d471f043eb078c09ab0d6016030c315bd879/lib/packets/packet.js#L215-L227

since you pass `bigNumberStrings: true` I'd expect it to return stringified signed 64 bit integer ( yes, if converted to JS number might be truncated but in this case I don't expect truncation )

**Comment by weijarz** [comment]
```js
      const resNumber = res.toNumber();
      const resString = res.toString();
      console.log('!!', bigNumberStrings, res, word0, word1, resNumber, resString)
      res = resNumber.toString() === resString ? resNumber : resString;
      return bigNumberStrings ? resString : res;
 ```
Outpus:
```
!! true Long { low: -1001, high: -1, unsigned: false } 4294966295 4294967295 -1001 -1001
!! true Long { low: -1000, high: -1, unsigned: false } 4294966296 4294967295 -1000 -1000
Id from insertId -1000
Id from query TextRow { 'max(id)': '18446744073709550616' }
```

**Comment by sidorares** [comment]
@weijarz mysql stores insertId as unsigned 64 bit int, so max value you can possibly store is 2^63-1 ( 9,223,372,036,854,775,807 ). If you use any value equal or less than that in your example as `bigId` the result seems to be correct

**Comment by sidorares** [comment]
https://dev.mysql.com/doc/refman/8.0/en/integer-types.html

**Comment by itsjustbrian** [comment]
@sidorares Hi! I'm unclear on the solution or if there even is a solution here.
I have a table like:

```
CREATE TABLE `example` (
	`id` bigint NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE InnoDB,
  CHARSET utf8mb4,
  COLLATE utf8mb4_0900_ai_ci;
  ```

And a row in that table:
`id`
`1595907282730090505`

Querying for this ID like:
`pool.query("SELECT * FROM example");`

Returns:
`[ { id: 1595907282730090500 } ]`

So internally the library is storing this ID in a regular JS number. Is there no way to return these as `BigInt`s?

**Comment by Starman3787** [comment]
> @sidorares Hi! I'm unclear on the solution or if there even is a solution here. I have a table like:
> 
> ```
> CREATE TABLE `example` (
> 	`id` bigint NOT NULL,
> 	PRIMARY KEY (`id`)
> ) ENGINE InnoDB,
>   CHARSET utf8mb4,
>   COLLATE utf8mb4_0900_ai_ci;
> ```
> 
> And a row in that table: `id` `1595907282730090505`
> 
> Querying for this ID like: `pool.query("SELECT * FROM example");`
> 
> Returns: `[ { id: 1595907282730090500 } ]`
> 
> So internally the library is storing this ID in a regular JS number. Is there no way to return these as `BigInt`s or even just strings?

did you ever find a solution to this? i'm facing the same problem

**Comment by Starman3787** [comment]
> @sidorares Hi! I'm unclear on the solution or if there even is a solution here. I have a table like:
> 
> ```
> CREATE TABLE `example` (
> 	`id` bigint NOT NULL,
> 	PRIMARY KEY (`id`)
> ) ENGINE InnoDB,
>   CHARSET utf8mb4,
>   COLLATE utf8mb4_0900_ai_ci;
> ```
> 
> And a row in that table: `id` `1595907282730090505`
> 
> Querying for this ID like: `pool.query("SELECT * FROM example");`
> 
> Returns: `[ { id: 1595907282730090500 } ]`
> 
> So internally the library is storing this ID in a regular JS number. Is there no way to return these as `BigInt`s or even just strings?
@itsjustbrian 

did you ever find a solution to this? i'm facing the same problem
