### ISSUE TITLE
Malformed FieldPacket

### ISSUE THREAD

**Issue by mgummelt** [sidorares/node-mysql2#1276]
When fetching `FieldPacket`s from a query, I'm observing that `packet.type` is undefined, in violation of its type: https://github.com/sidorares/node-mysql2/blob/master/typings/mysql/lib/protocol/packets/FieldPacket.d.ts#L18

Example code:

```
$ const [res, fields] = await conn.execute<RowDataPacket[]>(sql);
$ fields[0].type
undefined
$ console.log(fields[0])
{ catalog: 'def',
    schema: 'companies',
    name: 'created_at',
    orgName: 'created_at',
    table: 'companies',
    orgTable: 'companies',
    characterSet: 63,
    columnLength: 19,
    columnType: 12,
    flags: 128,
    decimals: 0 }
```

In fact, `FieldPacket` seems to have a significantly different structure than its type indicates.

**Comment by luckyyyyy** [comment]
same issue here

@sidorares

**Comment by sidorares** [comment]
yeah, types are ported from mysqljs/mysql and looks like there are few differences to mysql2 `Field` shape. Probably the easiest way to make them somewhat compatible is to add aliases, for example type -> columnType
