### ISSUE TITLE
[Question] Can one connection/connectionPool automatically run multiple queries at the same time?

### ISSUE THREAD

**Issue by Kycermann** [sidorares/node-mysql2#1289]
```
const connectionPool = mysql
  .createPool({
    host: process.env.MYSQL_HOST,
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASS,
    database: process.env.MYSQL_DB,
  })
  .promise();
```

Is the following explicitly supported?

```
connectionPool.execute("Query A ?", [123]).then( ... promise handler ...  )
connectionPool.execute("Query B ?", [456]).then( ... promise handler ...  )

async function test() {
    await connectionPool.execute( ... );
    await connectionPool.execute( ... );
}

// Called twice in parallel
test();
test();
```

Is this suppoorted if `connectionPool` is actually a single connection?

**Comment by sidorares** [comment]
At the protocol level one connection is only allowed to execute one query at a time. Maybe at sql level the coul be potentially a way to start background job with a query, detach from it and later get result with another query but one connection = one query at a time

> Is this suppoorted if connectionPool is actually a single connection?

If connection limit set to 1 in the pool doing something like `await Promise.all(connectionPool.execute('select sleep(1)'), connectionPool.execute('select sleep(1)'))` would execute queries in sequence. If connection limit is more than 1 both queries might run in parallel

**Comment by sidorares** [comment]
`await Promise.all(connection.execute('select sleep(1)'), connection.execute('select sleep(1)'))` is also allowed when `connection` is a single connection and not a pool object. In that case it is guaranteed that second query is executed after first one
