### ISSUE TITLE
Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by greedThread** [sidorares/node-mysql2#1302]
Hi.

When the current connection pool is being used and the server is idle for a long time, the error "Error: This socket has been ended by the other party" occurs.

As expected, it seems to be caused by a network error when the windows10 is in sleep state.

Is there a solution to this phenomenon?

I'm sorry for my inexperienced English.

**Comment by greedThread** [comment]
Error: This socket has been ended by the other party

On 'commit' or'rollback' after error Another error has occurred.

Error: Can't add new command when connection is in closed state
    at PoolConnection._addCommandClosedState (\node_modules\mysql2\lib\connection.js:137:17)
    at PoolConnection.query (\node_modules\mysql2\lib\connection.js:510:17)
    at PoolConnection.rollback (\node_modules\mysql2\lib\connection.js:667:17)

**Comment by sidorares** [comment]
@greedThread try `enableKeepAlive: true` config option

See https://github.com/sidorares/node-mysql2/issues/683#issuecomment-565082130 and https://github.com/sidorares/node-mysql2/pull/1081

**Comment by sidorares** [comment]
we should probably make it default option. Currently when remote side closes the socket the client might not see it, see [net.setKeepAlive](https://nodejs.org/api/net.html#net_socket_setkeepalive_enable_initialdelay)

**Comment by greedThread** [comment]
The quick answer was helpful. Thank you.

**Comment by greedThread** [comment]
enableKeepAlive: true config option

I would be happy if you add it to ReadMe.
