### ISSUE TITLE
add "shutdown" command

### ISSUE THREAD

**Issue by sidorares** [sidorares/node-mysql2#134]
http://dev.mysql.com/doc/internals/en/com-shutdown.html

**Comment by sushantdhiman** [comment]
>COM_SHUTDOWN is deprecated as of MySQL 5.7.9 and removed in MySQL 8.0. Instead, use mysql_query() to execute a SHUTDOWN statement.

May be we should close it as `COM_SHUTDOWN` is deprecated in `5.7` ? @sidorares

**Comment by sidorares** [comment]
agree. In general, I'd prefer not to implement specific protocol commands if there is equivalent in sql
