### ISSUE TITLE
Does .execute() support parameterized IN clause? 

### ISSUE THREAD

**Issue by anders8** [sidorares/node-mysql2#1347]
Using parameters and the IN clause is most often addressed in one of two ways:

- telling people to use .query(), and reminding everyone to put their list in an array
- use text substitution on the query string itself

I'm familiar with these two, yes, they both do successfully run, and to shorten the conversation, I'll include them below:

```
    const db =  databaseConnectionPoolPromise
    let strQuery:string=`
        SELECT Id
        FROM item
        WHERE Id IN (?)`
    const [rows,fields] = await db.query(strQuery,[[85526,85527]])

```
```
    const db =  databaseConnectionPoolPromise
    let strMyData:string='85526,85527'
    let strQuery:string=`
        SELECT Id
        FROM item
        WHERE Id IN (${strMyData})`
    const [rows,fields] = await db.query(strQuery,[])

```
(On the second one, either .query() or .execute() will work, since there's no substitution anyway.)

So with those two things out of the way... how do you use the IN clause with **.execute()**? I came across the following:

> With .execute() prepared statement parameters are sent from the client as a serialized string and handled by the server. Since [the data] is an object, that's not going to work.

Is the result that using the IN clause with proper parameterized queries will **never** work? Because the result of:

```
    const db =  databaseConnectionPoolPromise
    let strQuery:string=`
        SELECT Id
        FROM item
        WHERE Id IN (?)`
    const [rows,fields] = await db.execute(strQuery,[[85526,85527]])
```

is:

```
  <rejected> Error: Incorrect arguments to mysqld_stmt_execute
      at PromisePool.execute (......) {
    code: 'ER_WRONG_ARGUMENTS',
    errno: 1210,
    sqlState: 'HY000',
    sqlMessage: 'Incorrect arguments to mysqld_stmt_execute'

```

**Comment by vlasky** [comment]
You need to implement code to dynamically add the correct number of question mark placeholders in your SQL statement.

I have written in depth about this here:

https://github.com/sidorares/node-mysql2/issues/1266#issuecomment-750585920

**Comment by sheepymeh** [comment]
@vlasky Given that there is varying number of arguments, would I run the risk of reaching `maxPreparedStatements`, since each new number of arguments requires creating a prepared statement? Thank you!

**Comment by sidorares** [comment]
>  Given that there is varying number of arguments, would I run the risk of reaching maxPreparedStatements, since each new number of arguments requires creating a prepared statement? 

@sheepymeh correct, you need to be ready to mitigate that. Another solution is to mix client-side query building / parameter escaping with real prepared statements, similar to what @anders8 mentions in the original example where instead of simple `.join(',')` `mysql.escape()` is used instead. Keep in ming that this is still client side interpolation and extra caution is advised to prevent SQL injection, at the very minimum validation of input parameters type

```js
const inParameters = mysql.format('?', [[1, '\' --', 3]]);
const let strQuery =`
        SELECT Id
        FROM item
        WHERE Id IN (${inParameters})`
```

**Comment by Avsy** [comment]
> Using parameters and the IN clause is most often addressed in one of two ways:
> 
> * telling people to use .query(), and reminding everyone to put their list in an array
> * use text substitution on the query string itself
> 
> I'm familiar with these two, yes, they both do successfully run, and to shorten the conversation, I'll include them below:
> 
> ```
>     const db =  databaseConnectionPoolPromise
>     let strQuery:string=`
>         SELECT Id
>         FROM item
>         WHERE Id IN (?)`
>     const [rows,fields] = await db.query(strQuery,[[85526,85527]])
> ```
> 
> ```
>     const db =  databaseConnectionPoolPromise
>     let strMyData:string='85526,85527'
>     let strQuery:string=`
>         SELECT Id
>         FROM item
>         WHERE Id IN (${strMyData})`
>     const [rows,fields] = await db.query(strQuery,[])
> ```
> 
> (On the second one, either .query() or .execute() will work, since there's no substitution anyway.)
> 
> So with those two things out of the way... how do you use the IN clause with **.execute()**? I came across the following:
> 
> > With .execute() prepared statement parameters are sent from the client as a serialized string and handled by the server. Since [the data] is an object, that's not going to work.
> 
> Is the result that using the IN clause with proper parameterized queries will **never** work? Because the result of:
> 
> ```
>     const db =  databaseConnectionPoolPromise
>     let strQuery:string=`
>         SELECT Id
>         FROM item
>         WHERE Id IN (?)`
>     const [rows,fields] = await db.execute(strQuery,[[85526,85527]])
> ```
> 
> is:
> 
> ```
>   <rejected> Error: Incorrect arguments to mysqld_stmt_execute
>       at PromisePool.execute (......) {
>     code: 'ER_WRONG_ARGUMENTS',
>     errno: 1210,
>     sqlState: 'HY000',
>     sqlMessage: 'Incorrect arguments to mysqld_stmt_execute'
> ```
