### ISSUE TITLE
Convert Field columnType to human readable format

### ISSUE THREAD

**Issue by UserSina** [sidorares/node-mysql2#1353]
I have a simple use case where I want to display the types of the fields:

```JAVASCRIPT
let [rows, fields] = await conn.execute("SELECT * FROM users");
var typesArray = fields.map((field) => {
    return field['columnType'];
  });
```
However the output is:
```
[3, 252, 252]
```

I want to ultimately get `['int', 'string', 'string']`  or something similar.

**Comment by sidorares** [comment]
there is no built in helper to do that. you can get name -> code mapping from `require('mysql2').Types`, but you'd have to build inverse of that map to get what you want

something along the lines:

```js
const _ = require('lodash');
const { Types } = require('mysql2');

const typeName = _.invert(Types); // https://lodash.com/docs/4.17.15#invert
const [rows, fields] = await conn.execute("SELECT * FROM users");
const typesArray = fields.map((field) => {
  return typeName[field.columnType];
});
```

**Comment by UserSina** [comment]
Sounds easy enough, thanks!
