### ISSUE TITLE
Password, in URL connection string, that contain a colon are not supported

### ISSUE THREAD

**Issue by dave-continuum-media** [sidorares/node-mysql2#1357]
The connection code that parses `mysql://` strings does not handle passwords containing a colon `:`.

https://github.com/sidorares/node-mysql2/blob/9d22796c71bd0b4bb17f587cfdbd6f0bd25e7768/lib/connection_config.js#L244

* The URL is correctly parsed and any URI encoding is decoded correctly.
* The `auth` part of the URL is split on the `:` character, giving more than 2 parts if the password contains such a character.
* It should treat the first `:` as the only delimiter.

**Comment by sidorares** [comment]
yes I can confirm the issue, should be an easy fix
