### ISSUE TITLE
[bug] use conn.execute, datetime fields '0' milliseconds lost

### ISSUE THREAD

**Issue by luckyyyyy** [sidorares/node-mysql2#1361]
dateStrings: true

![image](https://user-images.githubusercontent.com/9210430/126482730-3c30de52-8afd-4139-8477-a1fc9ae3b274.png)

![image](https://user-images.githubusercontent.com/9210430/126482802-f83b94ee-a13f-49da-ac52-b9c8577ce5ea.png)

**Comment by sidorares** [comment]
can you show your schema ( and what's returned in fields result? )

**Comment by luckyyyyy** [comment]
> can you show your schema ( and what's returned in fields result? )

## 'dt' is datetime(1)
![image](https://user-images.githubusercontent.com/9210430/126624030-8cf67974-4bd7-4f19-897c-73693df82d65.png)



## mysql client select 
![image](https://user-images.githubusercontent.com/9210430/126624106-04f2d8a0-649a-4833-9122-c2b84a4a8d67.png)


## mysql2 select 

![image](https://user-images.githubusercontent.com/9210430/126482802-f83b94ee-a13f-49da-ac52-b9c8577ce5ea.png)

**Comment by sidorares** [comment]
for mysql2 select - can you show whats returned from in the second argument, e.i

```
conn.query('select * from hello2', (err, roes, fields) => {
  console.log(fields) // <-- that one
})
```

**Comment by luckyyyyy** [comment]
> for mysql2 select - can you show whats returned from in the second argument, e.i
> 
> ```js
> conn.query('select * from hello2', (err, rows, fields) => {
>   console.log(fields) // <-- that one
> })
> ```

![image](https://user-images.githubusercontent.com/9210430/126641518-31cd96dc-695b-49b1-8863-0d24639eab66.png)

**Comment by luckyyyyy** [comment]
I have located the problem
## use execute

![image](https://user-images.githubusercontent.com/9210430/126642209-e252a8c2-cb22-4886-b307-bb6a6ad51fd7.png)


## use query 

![image](https://user-images.githubusercontent.com/9210430/126642320-43a71ca5-a703-4e59-af72-b85be63e27da.png)

**Comment by sidorares** [comment]
maybe we should document that but what happens is with `.query()` date is sent back as string ( `"... 04.27.41.0"` in your example ) and depending on `dateStrings` flag it is returned as Date object or same string that we received from the server.

`.execute()` response is encoded in completely different way, we receive `DATETIME` ( [columnType: 12](https://github.com/sidorares/node-mysql2/blob/d74558b605162156b813248a024f7559785de6fb/lib/constants/types.js#L17) ) and decode it like this: https://dev.mysql.com/doc/internals/en/binary-protocol-value.html#packet-ProtocolBinary::MYSQL_TYPE_TIME

> to save space the packet can be compressed:
> 
> if days, hours, minutes, seconds and micro_seconds are all 0, length is 0 and no other field is sent
> 
> if micro_seconds is 0, length is 8 and micro_seconds is not sent
> 
> otherwise length is 12
> 
> Fields
> length (1) -- number of bytes following (valid values: 0, 8, 12)
> 
> is_negative (1) -- (1 if minus, 0 for plus)
> 
> days (4) -- days
> 
> hours (1) -- hours
> 
> minutes (1) -- minutes
> 
> seconds (1) -- seconds
> 
> micro_seconds (4) -- micro-seconds

**Comment by sidorares** [comment]
Closing for now as it's expected behaviour.

when `dateStrings` is set to true
- `.query()` result is exactly the string server sends to us
-  `.execute()` result is decoded from binary date representation and converted to a string

**Comment by luckyyyyy** [comment]
> maybe we should document that but what happens is with `.query()` date is sent back as string ( `"... 04.27.41.0"` in your example ) and depending on `dateStrings` flag it is returned as Date object or same string that we received from the server.
> 
> `.execute()` response is encoded in completely different way, we receive `DATETIME` ( [columnType: 12](https://github.com/sidorares/node-mysql2/blob/d74558b605162156b813248a024f7559785de6fb/lib/constants/types.js#L17) ) and decode it like this: https://dev.mysql.com/doc/internals/en/binary-protocol-value.html#packet-ProtocolBinary::MYSQL_TYPE_TIME
> 
> > to save space the packet can be compressed:
> > if days, hours, minutes, seconds and micro_seconds are all 0, length is 0 and no other field is sent
> > if micro_seconds is 0, length is 8 and micro_seconds is not sent
> > otherwise length is 12
> > Fields
> > length (1) -- number of bytes following (valid values: 0, 8, 12)
> > is_negative (1) -- (1 if minus, 0 for plus)
> > days (4) -- days
> > hours (1) -- hours
> > minutes (1) -- minutes
> > seconds (1) -- seconds
> > micro_seconds (4) -- micro-seconds

I got it. Thanks for your reminding.
