### ISSUE TITLE
TIME column returned in wrong format

### ISSUE THREAD

**Issue by martenjacobs** [sidorares/node-mysql2#1365]
As per the [mysql specification](https://dev.mysql.com/doc/refman/5.6/en/time.html), a TIME column is in `hh:mm:ss` format. However, when querying, what I see is that the actual format returned by node-mysql2 is `h:mm:ss` for amounts less than 10 hours. This makes it more difficult to parse (luxon's Duration.fromISOTime requires the leading zero, for example). 
I'd expect that either the documentation would clearly describe the return type and format for each column type, or that the library would follow the mysql spec, but in the case of the TIME column type, it appears that neither is the case.

**Comment by sidorares** [comment]
looks like we need to add `leftPad(2, H)` here: https://github.com/sidorares/node-mysql2/blob/4e22e33495287c4c46336154ccfba01d3b23e9df/lib/packets/packet.js#L373

@martenjacobs would you like to contribute code change and a unit test to fix this?

**Comment by martenjacobs** [comment]
@sidorares done, see #1366
