### ISSUE TITLE
RangeError when using mysql2 with sequelize

### ISSUE THREAD

**Issue by Mohammad-Safayet** [sidorares/node-mysql2#1370]
Hi, I'm using sequelize with mysql2 in a node express app. And also using the cli of sequelize. But when I use the command `npx sequelize db:create`, it gives me this error.
     
>     Sequelize CLI [Node: 14.17.4, CLI: 6.2.0, ORM: 6.6.2]
>     
>     Loaded configuration file "src/config.js".
>     Using environment "development".
>     internal/buffer.js:83
>       throw new ERR_OUT_OF_RANGE(type || 'offset',
>       ^
>     
>     RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 9
>         at boundsError (internal/buffer.js:83:9)
>         at Buffer.readUInt32LE (internal/buffer.js:217:5)
>         at Packet.readInt32 (/root/sequelize-test/node_modules/mysql2/lib/packets/packet.js:103:24)
>         at Function.fromPacket (/root/sequelize-test/node_modules/mysql2/lib/packets/handshake.js:63:32)
>         at ClientHandshake.handshakeInit (/root/sequelize-test/node_modules/mysql2/lib/commands/client_handshake.js:93:40)
>         at ClientHandshake.execute (/root/sequelize-test/node_modules/mysql2/lib/commands/command.js:39:22)
>         at Connection.handlePacket (/root/sequelize-test/node_modules/mysql2/lib/connection.js:425:32)
>         at PacketParser.onPacket (/root/sequelize-test/node_modules/mysql2/lib/connection.js:75:12)
>         at PacketParser.executeStart (/root/sequelize-test/node_modules/mysql2/lib/packet_parser.js:75:16)
>         at Socket.<anonymous> (/root/sequelize-test/node_modules/mysql2/lib/connection.js:82:25)
>         at Socket.emit (events.js:400:28)
>         at addChunk (internal/streams/readable.js:290:12)
>         at readableAddChunk (internal/streams/readable.js:265:9)
>         at Socket.Readable.push (internal/streams/readable.js:204:10)
>         at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
>       code: 'ERR_OUT_OF_RANGE'
>     }
> 

my sequelize config:
```js
module.exports = {
  development: {
    username: 'root',
    password: 'root123456',
    database: 'test_run',
    host: 'localhost',
    port: 33060,
    dialect: 'mysql',
    timezone: '+06:00',
    // dialectOptions: {
      //   bigNumberStrings: true,
      // },
    },
};
```

my system is ubuntu and mysql version is `8.0.26-0ubuntu0.20.04.2`.

**Comment by sidorares** [comment]
from initial guess - the packet server sends is not a full "hello", maybe its an error packet? ( too many connections or something like that )

I really need to find a way to reproduce this to be able to debug. Can you make repo with single command to reproduce or even better docker image I can use?

**Comment by roziscoding** [comment]
Hello. I'm seeing this same error with [this code](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBCAngZwI4BsBMcBmUIhwDkSaWA9GPiMMgKZEDcAsAFBvAB2MdUOAhgGM6cAJIBVelDh0AHj04ATZAhQZMAOgBKEAO4ARfjH4AFIQGs68AN5s4cTvxB0AXHGQwoXAOYtW9uhB+YHQ3Dy9OXzs4MH5kZF1oRTDPHz8AXzY2QQhODxiICHQ4AF5VMk1BKDojOhNC9AAKW384AAsIDzcidAhBfnQOjyIAGmjIWDcAZimABgA2WbHWgFcpbvwIGFHxuISk7tj4xKhFHdbFI34AIzjXYh5h5ftdYJgAMWgAYVzOOkEYMBcsg3J4VnRnnAcpw-gCgZwADKgYAwNwARiW0VQ4PBSJoqLgszY6QAlH42I04ohOII4I0SaUAHxwFr2aH5ADa+F0yAAuqU4PxXiiCkUNHJ-iseAAeCRSDm8xmNIgAZQAogi1V8ACpwABUcHeWgA8gBZOBrXjIIhk6Lsop0DS9byNbnIDmzXm21ik+l+IA)

I setup mysql using Docker with the following command:
```shell
docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=password -p "3306:3306" -p "33060:33060" mysql`
```

And then following query:

```sql
CREATE DATABASE `test`;
CREATE TABLE USERS (
	id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30),
    email VARCHAR(50) UNIQUE,
    password VARCHAR(30)
);
```

`SELECT @@VERSION` gives me version `'8.0.26'`

I'm running my app with `ts-node-dev` on node version `v16.2.0` inside WSL with `Ubuntu 20.04.2`

Please let me know if this is useful or if I can be of any assistance in solving this.

Thanks!

**Comment by roziscoding** [comment]
Update: Changing `port` to 3306 worked.

**Comment by testn** [comment]
@roziscoding  Can you close it?

**Comment by roziscoding** [comment]
> @roziscoding  Can you close it?

I'm sorry, I can't, I'm not the issue author. I guess. @Mohammad-Safayet needs to do it.

**Comment by rognales** [comment]
> Update: Changing `port` to 3306 worked.

Any idea why this works?
