### ISSUE TITLE
Option bigNumberStrings=true not returning big numbers as string on insert

### ISSUE THREAD

**Issue by gabrielmmontenegro** [sidorares/node-mysql2#1375]
Hi maintainers,

I am using mysql2 with sequelize, and this seems to be a mysql2 issue, once sequelize doesn't handle dialect options in their source code but forward it to database library instead.

## Issue Description

Model create() doesn't return the id as string when using mysql dialect options below:

```js
dialectOptions: {
  supportBigNumbers: true,
  bigNumberStrings: true,
}
```

### What are you doing?

Insert query with Model.create()

```js
const session = await Session.create({
  user_id: userId,
  user_agent_id: userAgentId,
  user_client_id: userClientId,
  is_active: false,
});

console.log(session.dataValues);
```

### What do you expect to happen?

The return having the id as string as specified on dialect options.

### What is actually happening?

The output has id as number. It can be very problematic if id overpass Number.MAX_SAFE_INTEGER.

```js
{
  id: 23,
  user_id: 1,
  user_agent_id: 2,
  user_client_id: 1,
  is_active: false,
  updatedAt: 2021-03-10T17:25:45.906Z,
  createdAt: 2021-03-10T17:25:45.906Z
}
```

On the other hand, the output of a query has id as string, as expected.

Code
```js
const session = await Session.findOne({
  attributes: ['id', 'user_id'],
  where: {
    id: accessToken.payload.sid,
    user_id: accessToken.payload.sub,
    is_active: true,
  },
});

console.log(session.dataValues);
```

Ouput
```js
{ 
  id: '23',
  user_id: 1 
}
```

### Environment

- Mysql2 version: 2.3.0 (latest)
- Sequelize version: 6.6.5 (latest)
- Node.js version: 16.2.0
- Operating System: Elementary OS 6 (Ubuntu 20.04)

**Comment by sidorares** [comment]
@gabrielmmontenegro I'm a bit confused - per your example`.findOne()` returns id as string. Under which scenario is it returned as number?

**Comment by gabrielmmontenegro** [comment]
@sidorares on Model.create() - INSERT statement, as shown before.

Code
```js
const session = await Session.create({
  user_id: userId,
  user_agent_id: userAgentId,
  user_client_id: userClientId,
  is_active: false,
});

console.log(session.dataValues);
```

Output
```js
{
  id: 23,
  user_id: 1,
  user_agent_id: 2,
  user_client_id: 1,
  is_active: false,
  updatedAt: 2021-03-10T17:25:45.906Z,
  createdAt: 2021-03-10T17:25:45.906Z
}
```

**Comment by dougwilson** [comment]
If it helps, I believe this is the same report as #636

**Comment by gabrielmmontenegro** [comment]
@dougwilson many thanks. I failed trying to find it before creating a new issue. But yes, is the same report.

@sidorares closing this, but reinforcing as others it would be appreciated to have a consistent id return type, for any type of SQL statement, based on dialect options (```bigNumberStrings``` and ```supportBigNumbers```).
