### ISSUE TITLE
ColumnDefinition 'db' broken, 'schema' missing from TS defs

### ISSUE THREAD

**Issue by LeviticusMB** [sidorares/node-mysql2#1380]
Noticed that `ColumnDefinition.db` contains some kind of binary string that *begins* with the schema name while `ColumnDefinition.schema` only returns the schema name as one would expect.

However, there is no `schema` member in the `FieldPacket` interface.

**Comment by sidorares** [comment]
I believe it's a small internal optimisation - some fields that might be accessed less likely as others are deserialized to strings lazily - we just store offset/length and have a getter access function that converts it to a string when actually required

**Comment by sidorares** [comment]
https://github.com/sidorares/node-mysql2/blob/5cb5d5c420b240204141310880aaf9519959385f/lib/packets/column_definition.js#L110-L127

**Comment by LeviticusMB** [comment]
Yes I get that but look at the code for `get db()`. According to the comment it should just be an alias for `schema` but the code differs (no `StringParser.decode()` call). And in my case, `.schema` returns `leviticus` while `.db` returns ...

`leviticus\x03foo\x02kv\x06nyckel\x03key\f?\x00\x14\x00\x00\x00\b'B\x00\x00\x00/\x00\x00\x07\x03def\tleviticus\x03foo\x02kv\x06värde\x05value\f?\x00������\x00\x00\x00\x00\x05\x00\x00\b�\x00\x00\x03\x003\x00\x00\t\x011\x04text\x02{}\x132021-09-07 09:05:44\x019\x12["Martin", "Nina"]\x05\x00\x00\n�\x00\x00\x03\x00`.

**Comment by sidorares** [comment]
oh, good catch. We to make `.db()` an actual alias instead of duplicating implementation, something like `get db() { return this.schema; }`

**Comment by testn** [comment]
@sidorares  let's close this.
