### ISSUE TITLE
decodeURIComponent after parsing URL for initial connection

### ISSUE THREAD

**Issue by kwanhs** [sidorares/node-mysql2#1384]
It appears the URL package is not decoding some special characters correctly. In my case, it was `@` sign used in the password.
Regardless of whether `@` or `%40` (its encoded counterpart) is used, the attributes obtained from parsed URL is still `%40`.

**Comment by sidorares** [comment]
which version are you using? I'd expect this issue would be fixed by https://github.com/sidorares/node-mysql2/pull/1360 can you double check the version you have is v2.3.0?

**Comment by kwanhs** [comment]
Thanks for your quick response! From my package.json: `"mysql2": "^2.3.0",`

**Comment by sidorares** [comment]
can you clarify `the attributes obtained from parsed URL is still %40` part? Are you able to connect using url where password is urlencoded?

**Comment by kwanhs** [comment]
It was the `password` that remained url-encoded

**Comment by sidorares** [comment]
@acdibble should [this line](https://github.com/sidorares/node-mysql2/pull/1360/files#diff-1978d11697f58179bc32b66c6ac7f21cbdfd6649a8f013248a1f9feee25858feR241) be `password: unescape(parsedUrl.password)` or something similar?

**Comment by acdibble** [comment]
We might have to pass both username and password to `decodeURIComponent`. However, if a password or username contains `%` and it is not properly escaped before building the URL, `decodeURIComponent` will throw an error, e.g.:

```javascript
> password = 'pass!@$%^&*+()\\word:'
'pass!@$%^&*+()\\word:'
> conn = new URL(`test://user:${password}@www.example.com/path`)
URL {
  href: 'test://user:pass!%40$%%5E&*+()%5Cword%3A@www.example.com/path',
  origin: 'null',
  protocol: 'test:',
  username: 'user',
  password: 'pass!%40$%%5E&*+()%5Cword%3A',
  host: 'www.example.com',
  hostname: 'www.example.com',
  port: '',
  pathname: '/path',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
> decodeURIComponent(conn.password)
Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
> conn = new URL(`test://user:${encodeURIComponent(password)}@www.example.com/path`)
URL {
  href: 'test://user:pass!%40%24%25%5E%26*%2B()%5Cword%3A@www.example.com/path',
  origin: 'null',
  protocol: 'test:',
  username: 'user',
  password: 'pass!%40%24%25%5E%26*%2B()%5Cword%3A',
  host: 'www.example.com',
  hostname: 'www.example.com',
  port: '',
  pathname: '/path',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
> decodeURIComponent(conn.password)
'pass!@$%^&*+()\\word:'
```

So possible errors would have to be handled here and properly reported to the users, or we could try/catch and use `unescape` or fallback to the raw password.

I can open a PR to fix it when we determine which solution we want to use.

**Comment by sidorares** [comment]
can we just use `unescape` straight away instead of having initial try using  `decodeURIComponent`?

**Comment by sidorares** [comment]
(it's not just `%`,  I think `&` in the password also triggers `URI malformed ...` error )
