### ISSUE TITLE
Entering values as null but still getting error: TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null

### ISSUE THREAD

**Issue by stephepush** [sidorares/node-mysql2#1385]
I'm trying to pass data from my app to mariadb via mysql2. The model method collects the data from the template via req.body.* and then the data presumably gets stored into a new instance of the class Car and that instance is console.logged and is supposed to be passed to the model/class method. When I try and submit the form data, I get the following error:

`TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null`

Here's what's being console.logged (the unneeded properties are 'javascript nulls'):

```
Car {
  id: null,
  model_year: '2008',
  make: 'Chevrolet',
  model: 'Corvette',
  miles: '56000',
  color: 'red',
  transmission: 'automatic',
  layout: 'FR',
  engine_config: 'V8',
  car_photo_url: null,
  car_price: null
}
```

Here's the controller method code:

```js
exports.postAddVehicle = (req, res, next) => {
    //const id = null;
    const model_year = req.body.model_year;
    const make = req.body.make;
    const model = req.body.model;
    const miles = req.body.miles;
    const color = req.body.color;
    const transmission = req.body.transmission;
    const layout = req.body.layout;
    const engine_type = req.body.engine_config;
    // const car_photo_url = null;
    // const car_price = null;
    const car = new Car(
        null, model_year, make, model, 
        miles, color, transmission, layout, engine_type,
        null, null);
        console.log(car);
    car
        .save()
        .then(() => {
            res.redirect('/');
        })
        .catch(err => console.log(err))
}
```

So there are properties of the class that I don't want to enter the data for right now so I set those properties to null but apparently mysql2 doesn't see those properties as javascript nulls?

**Comment by sidorares** [comment]
can you `console.log({ model_year, make, model, miles, color, transmission, layout, engine_type })` just before `new Car()` so that make sure we don't miss some simple typo

**Comment by stephepush** [comment]
The first object is what I got after console.logging all of that stuff before `const car = new Car`:

```
{
  model_year: '2008',
  make: 'Chevrolet',
  model: 'Corvette',
  miles: '45286',
  color: 'red',
  transmission: 'automatic',
  layout: 'FR',
  engine_type: 'V8'
}
Car {
  id: null,
  model_year: '2008',
  make: 'Chevrolet',
  model: 'Corvette',
  miles: '45286',
  color: 'red',
  transmission: 'automatic',
  layout: 'FR',
  engine_config: 'V8',
  car_photo_url: null,
  car_price: null
}
```

**Comment by sidorares** [comment]
which ORM are you using? Somewhere on the way some fields are list and passed as `undefined` parameters ( maybe your model expects some additional fields to what you have logged, maybe something else )

**Comment by sidorares** [comment]
if you can add console.log in mysql2 dependency in your node_modules just before line indicated in `TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null` stack you should be able to see what is actually passed and what missing ( and maybe print query your ORM has generated )

**Comment by stephepush** [comment]
> which ORM are you using? Somewhere on the way some fields are list and passed as `undefined` parameters ( maybe your model expects some additional fields to what you have logged, maybe something else )

I'm not using an orm... I just wanted to do the sql on my own...



> if you can add console.log in mysql2 dependency in your node_modules just before line indicated in `TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null` stack you should be able to see what is actually passed and what missing ( and maybe print query your ORM has generated )

I'll try this.

**Comment by dougwilson** [comment]
The reason for the ORM question is because the code posted above does not show how mysql2 is called at all; it would seem to reason that even though when you log out the car object, whatever the `save` method is doing (which wasn't posted) is passing in ab object where some of the keys have the value as `undefined`.

**Comment by stephepush** [comment]
> The reason for the ORM question is because the code posted above does not show how mysql2 is called at all; it would seem to reason that even though when you log out the car object, whatever the `save` method is doing (which wasn't posted) is passing in ab object where some of the keys have the value as `undefined`.


Ah okay,

This is the save method from the Car model. I console.log "hi" to see if the controller method calls it, and the console logs hi, I just haven't copied that:
```
        save() {
            console.log("hi")
            
            return db.execute(
                'INSERT INTO cars (model_year, make, model, color, miles, transmission, layout, engine_type) VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
                [
                    this.model_year, 
                    this.make, 
                    this.model, 
                    this.color,
                    this.miles,
                    this.transmission,
                    this.layout,
                    this.engine_type
                ]
            )
        }
        ```

**Comment by dougwilson** [comment]
Thanks. The issue is `this.engine_type` is `undefined` for the car you posted above:
```
Car {
  id: null,
  model_year: '2008',
  make: 'Chevrolet',
  model: 'Corvette',
  miles: '45286',
  color: 'red',
  transmission: 'automatic',
  layout: 'FR',
  engine_config: 'V8',
  car_photo_url: null,
  car_price: null
}
```

**Comment by stephepush** [comment]
> if you can add console.log in mysql2 dependency in your node_modules just before line indicated in `TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null` stack you should be able to see what is actually passed and what missing ( and maybe print query your ORM has generated )

Dunno if all of this verbosity will help, but here's what I got after console.logging `console.log({ model_year, make, model, miles, color, transmission, layout, engine_type })` on line 628 of ...mysql/lib/connection.js

```
/home/stephen/Documents/carDealership/node_modules/mysql2/lib/pool.js:177
        throw e;
        ^

ReferenceError: model_year is not defined
    at /home/stephen/Documents/carDealership/node_modules/mysql2/lib/connection.js:628:25
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (/home/stephen/Documents/carDealership/node_modules/mysql2/lib/connection.js:620:22)
    at /home/stephen/Documents/carDealership/node_modules/mysql2/lib/pool.js:172:14
    at /home/stephen/Documents/carDealership/node_modules/mysql2/lib/pool.js:64:16
    at PoolConnection.<anonymous> (/home/stephen/Documents/carDealership/node_modules/mysql2/lib/connection.js:778:13)
    at Object.onceWrapper (events.js:483:26)
    at PoolConnection.emit (events.js:376:20)
    at ClientHandshake.<anonymous> (/home/stephen/Documents/carDealership/node_modules/mysql2/lib/connection.js:121:14)
    at ClientHandshake.emit (events.js:376:20)
```

**Comment by sidorares** [comment]
as @dougwilson posted - the issue is that you set `engine_config` in your Car object but later use `engine_type` which is undefined

**Comment by stephepush** [comment]
@dougwilson @sidorares: Thank you very much for your time and help!

**Comment by stephepush** [comment]
> The reason for the ORM question is because the code posted above does not show how mysql2 is called at all; it would seem to reason that even though when you log out the car object, whatever the `save` method is doing (which wasn't posted) is passing in ab object where some of the keys have the value as `undefined`.

No problem with you asking about ORM use, I guess I didn't realize people used orms along with a connectors like MySQL2. Wasn't offended or anything was just kinda a question I wasn't expecting.

**Comment by sidorares** [comment]
all good @stephepush 
a lot of users do not interact with mysql2 or mysqljs/mysql driver directly but have some higher level abstraction as on layer on top - sql builders or ORMs ( knex / sequilize / prisma etc ). In this it's very helpful to see what is end result of building a query and preparing parameters that is eventually passed to db driver
