### ISSUE TITLE
Query with a timeout triggers callback twice on error

### ISSUE THREAD

**Issue by tsachis** [sidorares/node-mysql2#1387]
Starting from v2.3.0, when specifying a query timeout and calling a query that results in an error, the query callback is called twice - once with the actual error, and a second time with a `PROTOCOL_SEQUENCE_TIMEOUT` after the timeout expires.

The reason is probably not clearing the timeout handle after a query error occurs.

Example:
```js
conn.query({
  sql: 'select 1 from non_existing_table',
  timeout: 5000
}, (err) => console.log(err.code));
```
Output:
```
ER_NO_SUCH_TABLE
PROTOCOL_CONNECTION_LOST  (after 5 seconds)
```

**Comment by sidorares** [comment]
@yuxizhe maybe you can investigate that?

**Comment by yuxizhe** [comment]
@sidorares I will fix this.
