### ISSUE TITLE
When Recieving Key-Value pair, Where the Value is Array. Use IN Instead of =

### ISSUE THREAD

**Issue by DanielBailey-web** [sidorares/node-mysql2#1388]
Feature Request:
It would be nice if this same query could be mapped to either `=` or `IN` depending on the type of input (array vs string/number)

```sql
SELECT * FROM users WHERE ?;
```
```ts
const userIds = [1, 2, 3, 4]; // or const userIds = 1; 
const users = (await con.query(sql, [{userId: userIds}]))[0]
```
This currently maps to the following string
```sql
SELECT * FROM users WHERE `userId` = 1, 2, 3, 4;
```
Which works fine for the single value example. But it would be nice if the value was an array it could map to:
```sql
 SELECT * FROM users WHERE `userId` in (1, 2, 3, 4);
```
This seems like it wouldn't be *too* hard, but I am unaware of any security vulnerabilities such a change could make.

I just want to cut down on the amount of functions I need to have to call specific tables. 

For the first query I could obviously call it with a different key and it would still work such as 
```ts
const emails = "email@example.com";
const users = (await con.query(sql, [{email: emails}]))[0]
```
But to my knowledge you cannot currently dynamically change the search param when using `IN`.

**Comment by sidorares** [comment]
can we move this discussion to https://github.com/mysqljs/sqlstring/issues ?

sqlstring is the plain text sql builder / interpolation library used by both this driver and mysqljs/mysql

**Comment by dougwilson** [comment]
You can use in with single values. Need to have one query for = and one for in; just have one with in and it will work for both use cases.

**Comment by DanielBailey-web** [comment]
@sidorares I didn't know that was the correct place, my bad. I'll move it there.

@dougwilson that prevents you from dynamically changing the column you want to search from. So that does not actually work...

**Comment by dougwilson** [comment]
Oh, I see you are talking about the object value subsitution. That is only for use with SET, not WHERE.

**Comment by DanielBailey-web** [comment]
I use it all the time in WHERE... So like it definitely works...

**Comment by DanielBailey-web** [comment]
In case anyone finds this and wants the issue in the correct repo: https://github.com/mysqljs/sqlstring/issues/66

**Comment by dougwilson** [comment]
> Is there a problem with doing that? (like a security problem)

It would seem to work if you provide only a single key, but as soon as you provide more than one it would not work. Changing likely has implications for the current use cases in SET, though.

**Comment by DanielBailey-web** [comment]
Yeah, when I need to use more then one I do something like
```sql
SELECT * from users WHERE ? OR ?;
```
And then 
```ts
const users = (await con.query(sql, [{userId: userIds}, {email: emails}]))[0]
```
So that they fill in separately. 
And then obviously you can build more complicated ones than that using AND/OR along with joins.

But I don't get why its not feasible, could just do something like this to get the question marks after the WHERE statement and treat them differently. 
```ts
const sql = "SELECT * from users WHERE ? OR ?;"
let newSql = sql;
// OR something like this
for (let i = 0; i < sql.match(/(?!WHERE)(?=[\s\S]*)\?/gi).length || 0; i++)
  newSql = newSql.replace(/(?!WHERE)(?=[\s\S]*)\?/i, object_value_subsitution_array[i])
```
I mean it definitely seems feasible imo. But I am not as familiar with the library as you are.

**Comment by dougwilson** [comment]
The SqlString library does not require a complete query to escape. It provides two main functions: escape and escapeId. The format function just takes a string and for each ? it calles the escape function and for each ?? It calls the escapeId function.

It is designed to be completly composible and not be based off context. What you are proposing is not bad, but it is not the design of the sqlstring module. You can always use one of the full-featured SQL builder modules out there, or even create a new module designed the way you like.

The sqlstring module is purposely not meant to repleace a full featured SQL builder module, because those already exist.
