### ISSUE TITLE
Possible means for keeping connection socket ref()'d only when executing queries?

### ISSUE THREAD

**Issue by mscdex** [sidorares/node-mysql2#1392]
My use case is that I have a utility function needs to perform some database queries but I also don't want it to keep the event loop alive unnecessarily.

I'm aware of `conn.stream.ref()`/`conn.stream.unref()`, however because the connection maintains a command queue, I have no way of knowing whether it's safe to `unref()` or not inside a query's callback for example.

So my question is, is there a way of achieving this with the public API and if not, is it possible something could be added to facilitate this in one way or another?

**Comment by sidorares** [comment]
This is probably very uncommon scenario, I think the best solution would be some generic system of hooks / events ( 
beforeConnect, afterConnect, beforeQuery, afterQuery ). Haven't put much thought in this yet but definitely open to some some possible addition to help with this

**Comment by mscdex** [comment]
I ended up solving this by simply using a queued query counter.
