### ISSUE TITLE
Where is affectedRows property?

### ISSUE THREAD

**Issue by vickyRathee** [sidorares/node-mysql2#1393]
I can't find `affectedRows` property in rows, fields on `query()` as well on `execute()` response. So where exactly it is?

![image](https://user-images.githubusercontent.com/6106479/133887632-7fe8e0d4-d8fa-41c1-a8fb-ede99a55dff1.png)

Not in response
```
const response = await db.query('Update Users set name = ? Where user_id = ?', ['vikash', 1]);
return response.affectedRows > 0;
```

Not in rows as well
```
const [rows, fields] = await db.execute('Update Users set name = ? Where user_id = ?', ['vikash', 1]);
return rows.affectedRows > 0;
```

**Comment by haroldiedema** [comment]
I just migrated my project from `mysql` to `mysql2` and found that if you use the type `ResultSetHeader`, you'll find `affectedRows` there.

**Comment by sidorares** [comment]
@vickyrathee I believe what @haroldiedema is correct. I haven't worked much on typings but can comment from the protocol point of view ( which is mostly reflected by API ). The INSERT/UPDATE/DELETE statement will return "ok packet" that includes affectedRows / sql state and other fields. For SELECT statement the response is "array of fields" followed by "array of rows" ( which api represents as `[rows, fields]` async response / `error, rows, fields` callback ( and it gets even  more complicated for multi result statements )

https://dev.mysql.com/doc/internals/en/com-query-response.html

![image](https://user-images.githubusercontent.com/173025/135556201-d3871957-17d9-4ea0-857f-3970a613b3ed.png)

**Comment by haroldiedema** [comment]
That makes perfect sense, @sidorares  👍 

@vickyrathee I would suggest implementing your own query/insert/update/delete methods in an abstraction part of your application that uses the correct return types. That way you don't always explicitly have to type them. It all boils down to what kind of query write that determines the actual return type.

**Comment by wellwelwel** [comment]
@haroldiedema, thanks for the suggestion.

You can follow this example from documentation about this topic:
[documentation/en/TypeScript-Examples.md#resultsetheader](https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/documentation/en/TypeScript-Examples.md#resultsetheader) 

Also a practical example here:
https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/examples/typescript/row-data-packet.ts#L35-L41

---

For other types, you follow the documentation:
[documentation/en/TypeScript-Examples.md](https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/documentation/en/TypeScript-Examples.md) 

---

@vickyRathee, I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️
