### ISSUE TITLE
MySQL json column doesn't parse

### ISSUE THREAD

**Issue by deepakaggarwal7** [sidorares/node-mysql2#1395]
I'm using knex with mysql2 driver to fetch the first row of a table which has two columns:
1. id: int
2. profile: json

```
const data:User = await knex<User>("user").first() || <User>{}
typeof(data.profile) === 'string' //true
```

I can do Json.parse but that causes different problems. Like, I'm using typescript and get an error in json.parse that it cannot accept object.

```
interface User{
id:number,
profile:{name:string}
}
```

json.parse(data.profile)// Error. Json.parse accepts only string and not {name:string}. If mysql2 automatically parses results of json, explicit parsing and related errors can be avoided.

**Comment by sidorares** [comment]
what's the type of that field in mysql table?

the driver automatically parses json if the type is json - https://github.com/sidorares/node-mysql2/blob/247ce10a364f0dc42c0720ca42925890d5db07f0/lib/parsers/binary_parser.js#L59 and https://github.com/sidorares/node-mysql2/blob/247ce10a364f0dc42c0720ca42925890d5db07f0/lib/parsers/text_parser.js#L63

**Comment by deepakaggarwal7** [comment]
> what's the type of that field in mysql table?
> 
> the driver automatically parses json if the type is json -
> 
> https://github.com/sidorares/node-mysql2/blob/247ce10a364f0dc42c0720ca42925890d5db07f0/lib/parsers/binary_parser.js#L59
> 
> and
> https://github.com/sidorares/node-mysql2/blob/247ce10a364f0dc42c0720ca42925890d5db07f0/lib/parsers/text_parser.js#L63

Sorry. My bad. For some reason knex migration set the column as varchar.
