### ISSUE TITLE
mysql@2.3.2 breaks typeCast property in Knex

### ISSUE THREAD

**Issue by AssetKid** [sidorares/node-mysql2#1442]
I have been using the `typeCast` property in Knex to convert `TINY` fields to boolean using this code

https://github.com/knex/knex/issues/1240#issuecomment-195534490

This has been working well for years but after upgrading to version `v2.3.1`, `typeCast` no longer works. Upgrading to `v2.3.2` did not fix it either.

I am not 100% certain if the issue is caused by `mysql2` or if it is Knex's implementation of the feature.

**Comment by testn** [comment]
TINY has the length of 4 instead of 1 so it should not work.

**Comment by AssetKid** [comment]
@testn The code above works on `TINYINT(1)` but not on `TINYINT(2)` or more.

The code checks the length of the field.

**Comment by testn** [comment]
that's right. you should just remove the length check

**Comment by sidorares** [comment]
@AssetKid  I just tried with length check removed and it works as expected
