### ISSUE TITLE
Versioning Problem (2.3.3-rc.0)

### ISSUE THREAD

**Issue by jansepke** [sidorares/node-mysql2#1449]
Could you exmplain what exactly is the reason you released a ReleaseCandidate Version (2.3.3-rc.0) as the latest release on npm? Now `npm outdated` reports a breaking new release and `npm update` will not update `mysql2` automatically.

Could you either release a 2.3.3 version or release the version 2.3.3-rc.0 as a prerelease.

Thanks for your great work on this package.

**Comment by sidorares** [comment]
`v2.3.3-rc.0` meant to be a prerelease, looks like I forgot to tag it as such. 
Context why RC: https://github.com/sidorares/node-mysql2/issues/1432#issuecomment-961335563

I published `v2.3.3` today ( no changes compared to `v2.3.3-rc.0` other than line in the changelog )
