### ISSUE TITLE
Problem with parameterised update query

### ISSUE THREAD

**Issue by chrisveness** [sidorares/node-mysql2#145]
Could you advise why this 'update' query fails?

My code is

    var koa   = require('koa');
    var mysql = require('mysql-co');
    
    var app = koa();
    var db;
    
    // set up mysql connection
    app.use(function* mysqlConnection(next) {
        var config = { host: 'localhost', port: '3306', database: 'db', user: 'usr', password: 'pw' };
        db = mysql.createConnection(config);
    
        yield next;
    
        db.end();
    });
    
    // test insert/update
    app.use(function* test() {
        var valuesI = { Firstname: 'My', Lastname: 'Name' };
        var resultI = yield db.query('Insert Into Member Set ?', valuesI);
    
        var id = resultI.insertId;
        var valuesU = { Firstname: 'Updated', Lastname: 'Name' };
        var resultU = yield db.query('Update Member Set ? Where MemberId = ?', valuesU, id);
    });
    
    app.listen(3000);

And I get this error:

    /.../node_modules/mysql-co/node_modules/mysql2/lib/commands/command.js:27
          this.onResult(err);
               ^
    TypeError: number is not a function
        at Query.Command.execute (/.../node_modules/mysql-co/node_modules/mysql2/lib/commands/command.js:27:12)
        at Connection.handlePacket (/.../node_modules/mysql-co/node_modules/mysql2/lib/connection.js:308:28)
        at PacketParser.onPacket (/.../node_modules/mysql-co/node_modules/mysql2/lib/connection.js:83:65)
        at PacketParser.executeStart (/.../node_modules/mysql-co/node_modules/mysql2/lib/packet_parser.js:39:12)
        at Socket.<anonymous> (/.../node_modules/mysql-co/node_modules/mysql2/lib/connection.js:95:31)
        at Socket.emit (events.js:107:17)
        at readableAddChunk (_stream_readable.js:162:16)
        at Socket.Readable.push (_stream_readable.js:125:10)
        at TCP.onread (net.js:514:20)

I'm using koa 0.14.0, mysql-co 0.0.2 (mysql2 0.15.0). MemberId is an auto-increment field. The 'insert' works fine.

I guess I'm doing something dumb, but I can't see what!

Thanks.

**Comment by adrianblynch** [comment]
Should this:

```
var resultU = yield db.query('Update Member Set ? Where MemberId = ?', valuesU, id);
```

Be this:

```
var resultU = yield db.query('Update Member Set ? Where MemberId = ?', [valuesU, id]);
```

**Comment by sidorares** [comment]
you need to pass all parameters as single array:

```js
var resultU = yield db.query('Update Member Set ? Where MemberId = ?', [valuesU, id]);
```

what happens is that query thinks valuesU is parameters and id a callback, and id(err) is called ( where err is "sql error" because one `?` is not substituted

**Comment by sidorares** [comment]
@adrianblynch you are 10 seconds quicker :)

**Comment by chrisveness** [comment]
Thank you! Fantastic response! You are quite right – I thought it would be simple, now I know what to look for I can see where I missed in in the readme.
