### ISSUE TITLE
Named placeholders

### ISSUE THREAD

**Issue by chrisveness** [sidorares/node-mysql2#146]
Am I correct in thinking that if `namedPlaceholders` is set true, then it's no longer possible to use positional placeholders?

If I am, would it be possible to make the use of named placeholders dependant on the type of the argument passed to `connection.query`? – if an object is passed, then use named placeholders, if an array is passed, then use standard positional placeholders.

If I'm not, I've got something else wrong!

**Comment by sidorares** [comment]
You can set it per query as well as in global config:

```js
connection.query({ sql: "select 1+:bar", namedPlaceholders: true }, { bar: 1 }, cb);
connection.query({ sql: "select 1+?" }, [ 1 ], cb);
```
Though I like your idea about assuming named based on object vs array in parameters

@dougwilson what do you think about "implicit named if object passed as parameters" ?

**Comment by chrisveness** [comment]
Thanks – I'll run with the per-query config for now, and hope to see auto-config in the future...

**Comment by dougwilson** [comment]
> what do you think about "implicit named if object passed as parameters" ?

As for the `mysql` module, I can tell you it's not backwards-compatible, since there is logic that will wrap non-array values into an array (such that `{}` becomes `[{}]`) and then if they were doing that with `SET ?`, it'd be weird. I like the named argument the best.

**Comment by sidorares** [comment]
does it always wrap? What about non-objects? `"select 1+?", 1, callback`?

**Comment by sidorares** [comment]
@chrisveness probably going to be explicit as otherwise not compatible with node-mysql. Depending which way is used more often you can set flag at connection time and override at query time

**Comment by dougwilson** [comment]
Yes; the code is this

    [].concat(values);

So your example would result in

    [].concat(1);

**Comment by sidorares** [comment]
Thanks @dougwilson 

@chrisveness - since node-mysql2 is using the same SqlString code that applies here as well:

https://github.com/sidorares/node-mysql2/blob/master/lib/sql_string.js#L68

**Comment by chrisveness** [comment]
Thanks @sidorares, I'll override on a per-query basis as needed, as you suggest.
