### ISSUE TITLE
How to inster into two tables?

### ISSUE THREAD

**Issue by qingfengll** [sidorares/node-mysql2#1460]
```js

const sql = `
                    INSERT INTO tb_config(name, description) VALUES(?,?);
                    INSERT INTO tb_config_relation(config_id, type_name) VALUES(LAST_INSERT_ID(), ?);`;
        connection.query(sql, function(err, results, fields) {
            console.log(err);
        })
```

Why do I get an error when I insert the table directly like this

**Comment by sidorares** [comment]
you need to enable multiple statements  in the connection config: `multipleStatements: true`
This option is disabled by default as a security measure against sql injection. See more info here: https://github.com/mysqljs/mysql#multiple-statement-queries
