### ISSUE TITLE
TypeScript: Property `promise` does not exist on type `Pool`

### ISSUE THREAD

**Issue by sungvzer** [sidorares/node-mysql2#1464]
I'm switching from a single connection to a connection pool. All my code-base uses promise-wrapped functions, so I need to return a promise-wrapped pool.

To do so I'm following the documentation, specifically this snippet of code, found [here](https://www.npmjs.com/package/mysql2#using-promise-wrapper):
```javascript
const mysql = require('mysql2');
// create the pool
const pool = mysql.createPool({host:'localhost', user: 'root', database: 'test'});
// now get a Promise wrapped instance of that pool
const promisePool = pool.promise();
```

Thing is, `tsc` complains about the `promise` function not existing on the pool.
This is the relevant code, before and after: 

- Before:
```javascript
import * as mysql2 from 'mysql2/promise';

export const getDatabaseConnection = async () => {
    return await mysql2.createConnection({
        host: process.env.MYSQL_HOST,
        password: process.env.MYSQL_PASSWORD_DEV,
        port: parseInt(process.env.MYSQL_PORT),
        database: "aurora",
        user: /*user*/,
        timezone: '+00:00'
    });
};
```

- After:
```javascript
import * as mysql2 from 'mysql2/promise';

const pool = mysql2.createPool({
    host: process.env.MYSQL_HOST,
    password: process.env.MYSQL_PASSWORD_DEV,
    port: parseInt(process.env.MYSQL_PORT),
    database: "aurora",
    user: /*user*/,
    timezone: '+00:00',
});

export const getDatabaseConnection = () => {
    return pool.promise(); // <-- Error here
};
```

**Comment by sungvzer** [comment]
Found the problem.
Importing with this syntax
```typescript
import * as mysql2 from 'mysql2/promise';
```
does not expose the promise function within Pool.

Changing to
```typescript
import mysql2 from 'mysql2';
```
fixes it.

**Comment by testn** [comment]
@sungvzer  can you close this then?

**Comment by sungvzer** [comment]
I could have sworn I'd already closed it as resolved.

**Comment by PeytonHanel** [comment]
I'm having this same problem, but instead of calling `promise()` on `pool`, I'm calling it directly on the connection. The docs [here](https://www.npmjs.com/package/mysql2#using-promise-wrapper) say this is allowed and the code works, but typescript shows an error in VS code.

**Comment by sidorares** [comment]
@PeytonHanel yes, this is supported by the main code but looks like typings are missing or wrong here
