### ISSUE TITLE
PoolPromise timing out when trying to connect to the MySQL server when hosted on AWS Elastic Beanstalk ( Error: connect ETIMEDOUT at PoolConnection._handleTimeoutError )

### ISSUE THREAD

**Issue by ryanbishop12** [sidorares/node-mysql2#1466]
```
const pool = mysql.createPool({
    host: '0.0.0.0.',
    user: 'root',
    database: 'db',
    password: 'pass',
    namedPlaceholders: true,
});
const poolPromise = pool.promise();
```

```
const VALIDATE_USER_COLUMNS = ['u_name',  'u_id', 'is_active', 'c_id', 'roles', 'message'];

async function callValidateUser(username) {
    //const results = 
    const [[rows, headers], fields] = await poolPromise.query(
        {
            sql: "call VALIDATE_USER(:username)",
            namedPlaceholders: true,
        },
        {
            username
        }
    );
    if (rows && rows.length === 1) {
        return rows[0];
    }
    return null;
}
```

> Dec  1 15:19:35 ip-172-31-29-26 web: (node:19444) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT
> Dec  1 15:19:35 ip-172-31-29-26 web: at PromisePool.query (/var/app/current/lib/Auth/node_modules/mysql2/promise.js:341:22)
> Dec  1 15:19:35 ip-172-31-29-26 web: at callValidateUser (/var/app/current/lib/Auth/DBUtils.js:60:57)
> Dec  1 15:19:35 ip-172-31-29-26 web: at Object.authenticateAdminUserFromUsernamePassword (/var/app/current/lib/Auth/DBUtils.js:87:31)
> Dec  1 15:19:35 ip-172-31-29-26 web: at /var/app/current/lib/Auth/Auth.js:32:36
> Dec  1 15:19:35 ip-172-31-29-26 web: at Layer.handle [as handle_request] (/var/app/current/lib/Auth/node_modules/express/lib/router/layer.js:95:5)
> Dec  1 15:19:35 ip-172-31-29-26 web: at next (/var/app/current/lib/Auth/node_modules/express/lib/router/route.js:137:13)
> Dec  1 15:19:35 ip-172-31-29-26 web: at Route.dispatch (/var/app/current/lib/Auth/node_modules/express/lib/router/route.js:112:3)
> Dec  1 15:19:35 ip-172-31-29-26 web: at Layer.handle [as handle_request] (/var/app/current/lib/Auth/node_modules/express/lib/router/layer.js:95:5)
> Dec  1 15:19:35 ip-172-31-29-26 web: at /var/app/current/lib/Auth/node_modules/express/lib/router/index.js:281:22
> Dec  1 15:19:35 ip-172-31-29-26 web: at Function.process_params (/var/app/current/lib/Auth/node_modules/express/lib/router/index.js:335:12)
> Dec  1 15:19:35 ip-172-31-29-26 web: (node:19444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
> Dec  1 15:19:57 ip-172-31-29-26 web: Error: connect ETIMEDOUT
> Dec  1 15:19:57 ip-172-31-29-26 web: at PoolConnection._handleTimeoutError (/var/app/current/lib/etruckbiz/node_modules/mysql2/lib/connection.js:189:17)
> Dec  1 15:19:57 ip-172-31-29-26 web: at listOnTimeout (internal/timers.js:549:17)
> Dec  1 15:19:57 ip-172-31-29-26 web: at processTimers (internal/timers.js:492:7) {
> Dec  1 15:19:57 ip-172-31-29-26 web: errorno: 'ETIMEDOUT',
> Dec  1 15:19:57 ip-172-31-29-26 web: code: 'ETIMEDOUT',
> Dec  1 15:19:57 ip-172-31-29-26 web: syscall: 'connect',
> Dec  1 15:19:57 ip-172-31-29-26 web: fatal: true
> Dec  1 15:19:57 ip-172-31-29-26 web: }

**Comment by sidorares** [comment]
is that specific to promise wrapper? e.i if you change your code to use callback api - do you see the same error?

**Comment by ryanbishop12** [comment]
Was a problem with whitelisting, it appears that the server the request is coming from was not whitelisted
