### ISSUE TITLE
Broken pool connections not flushed

### ISSUE THREAD

**Issue by parkr** [sidorares/node-mysql2#147]
We've hit a funny error. If there are >= 200 concurrent connections coming into express and we ask MySQL for something very small (but something nonetheless) in quick succession, we get error `{}`. Totally weird. We can only reproduce it with > 150 concurrent requests using `ab`, but we can repro it nonetheless. It looks like if a connection can't reach MySQL consistently, it's not thrown away. So we have requests which hit a funky / borked connection in the pool and error out as a result.

**Comment by sidorares** [comment]
Can you reduce it to something I would be able to reproduce locally? Also, does it happen when you use node-mysql? If not, this could be a pool bug that is already fixed in node-mysql ( pool code is the same, but one here is older )
