### ISSUE TITLE
Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'RowDataPacket[] | RowDataPacket[][] | OkPacket | OkPacket[] | ResultSetHeader'.   Property '0' does not exist on type 'RowDataPacket[] | RowDataPacket[][] | OkPacket | OkPacket[] | ResultSetHeader'.  When trying to access any index of the result parameter in the callback

### ISSUE THREAD

**Issue by destroyer22719** [sidorares/node-mysql2#1485]
Hi there so I have this code
```ts
    static async getById(id: string): Promise<Business> {
        return new Promise((resolve, reject) => {
            connection.execute(
                "SELECT * FROM business WHERE ID = ?;",
                [id],
                (err, result) => {
                    if (err) reject(err);
                    const { id, name, email, password }: {id: string, name: string, email: string, password: string} = result[0]; //it complains here
                    resolve({
                        id,
                        name,
                        email,
                        password,
                    });
                }
            );
        });
    }
```
And I have typescript giving me this error:
```js
Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'RowDataPacket[] | RowDataPacket[][] | OkPacket | OkPacket[] | ResultSetHeader'.
  Property '0' does not exist on type 'RowDataPacket[] | RowDataPacket[][] | OkPacket | OkPacket[] | ResultSetHeader'.ts(7053)
```
And I'm really not sure what to be doing here because I can't change return type of `result`

**Comment by sasial-dev** [comment]
+1, also an issue here
got around it by typecasting, but I don't know the library/mysql well so it's not ideal.
```ts
			const [matches] = await db.Connection.query(
				"SELECT `Discord UID` FROM `Information` WHERE `Staff Code` = ? OR `Discord UID` = ? OR `Roblox UID` = ? OR `Email`= ?",
				[`${staffInfo.department}-${staffInfo.staffid}`, staffInfo.user.id, userId, staffInfo.email],
			);
			console.log((matches as RowDataPacket[])[0]);
```
this is with "mysql2/promise"

**Comment by sidorares** [comment]
@astiob I'm not an expert in TS but your comment looks right from the protocol point of view: result of query / execute can be  

1) array of rows ( single select statement )  
2) `OkPacket | ResultSetHeader` ( single insert / delete / update / set variable statement ) ( I'm actually quite confused, they look nearly identical. Need to investigate why we need two )
3) array of (1|2) in case of multiple statements

**Comment by sidorares** [comment]
^ not just multiple statements in a single query `"select 1; select 2"`, a prepared statement can also return multiple tables - see https://github.com/sidorares/node-mysql2/blob/dbb344e89a1cc8bb457b24e67b07cdb3013fe844/test/integration/connection/test-binary-multiple-results.js#L77-L100

**Comment by 1stdeddy2nd** [comment]
Add this if else condition to handle the typescript

```
if(Array.isArray(result)){
  //your thing
} else {
  //res send status 500
}
```

**Comment by GIORGIPUNK123** [comment]
And it's still open

**Comment by wellwelwel** [comment]
Hi @destroyer22719, you can do it by:
- Extending `mysql.RowDataPacket`
- Using `as` from **TypeScript**

---

### For example:

#### Extending `mysql.RowDataPacket`
```ts
import mysql from 'mysql2';

interface Bussiness extends mysql.RowDataPacket {
   id: number;
   name: string;
   email: string;
   password: string;
}

const query = 'SELECT * FROM business WHERE ID = ?;';
const params = [1];

mysql.createPool({}).getConnection((_err, connection) => {
   connection.execute<Bussiness[]>(query, params, (_err, result) => {
      const { id, name, email, password } = result[0];

      return {
         id,
         name,
         email,
         password,
      };
   });
});
```

#### Using `as` from TypeScript
```ts
import mysql from 'mysql2';

interface Bussiness {
   id: number;
   name: string;
   email: string;
   password: string;
}

const query = 'SELECT * FROM business WHERE ID = ?;';
const params = [1];

mysql.createPool({}).getConnection((_err, connection) => {
   connection.execute(query, params, (_err, result) => {
      const bussiness = result as Bussiness[];
      const { id, name, email, password } = bussiness[0];

      return {
         id,
         name,
         email,
         password,
      };
   });
});
```

**Comment by wellwelwel** [comment]
> @astiob I'm not an expert in TS but your comment looks right from the protocol point of view: result of query / execute can be
> 
> 1. array of rows ( single select statement )
> 2. `OkPacket | ResultSetHeader` ( single insert / delete / update / set variable statement ) ( I'm actually quite confused, they look nearly identical. Need to investigate why we need two )
> 3. array of (1|2) in case of multiple statements

@sidorares, after reviewing all **TypeScript** Issues, I noticed that there are many questions, mostly about the use of types in `execute` and `query`.

I think it's good to have an "**TypeScript Examples**" documentation like in [documentation/en/Extras.md](https://github.com/sidorares/node-mysql2/blob/2d91b01fa0e9843b4f528af3ddc496b26ee40f32/documentation/en/Extras.md).

**Comment by sidorares** [comment]
Yes, definitely. Even just copying your previous comment to "TypeScript Examples" section would be of great value

**Comment by wellwelwel** [comment]
You can follow this example to see how to extend the `RowDataPacket`:

- [Extending and using **Interfaces** with `RowDataPacket`](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/row-data-packet.ts)

Also:
- [Extending and using **Interfaces** with `RowDataPacket` and `rowAsArray`](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/row-data-packet-row-as-array.ts)
- [Extending and using **Interfaces** with `RowDataPacket` and `multipleStatements`](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/row-data-packet-multi-statements.ts)
- [Extending and using **Interfaces** with `RowDataPacket`, `rowAsArray` and `multipleStatements`](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/row-data-packet-row-as-array-multi-statements.ts)

And finally, you can follow the documentation: [documentation/en/TypeScript-Examples.md#type-specification](https://github.com/sidorares/node-mysql2/blob/master/documentation/en/TypeScript-Examples.md#type-specification)

---

I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️
