### ISSUE TITLE
JSON_ARRAYAGG() does not exist

### ISSUE THREAD

**Issue by hengtop** [sidorares/node-mysql2#1488]
hello,I ran into a compatibility issue。

I used an aggregate function in my query ----- JSON_ARRAYAGG()

```sql
const statement = `select users.id, users.name, users.realname, users.cellphone, users.email, users.birthday, users.enable, users.avatar_url,
      if(count(r.id), JSON_ARRAYAGG(JSON_OBJECT('id', r.id,'name', r.name, 'describe', r.describe, 'createAt', r.createAt , 'updateAt', r.updateAt)), null) roles
      from users 
      left join users_roles ur on users.id=ur.user_id
      left join roles r on ur.role_id= r.id
      where users.id = ? GROUP BY users.id;`;
      const result = await connection.execute(statement, [id]);
```
![image](https://user-images.githubusercontent.com/62384610/148896289-d4045092-e736-490b-bdd0-56b756a7761d.png)

This statement can be executed in the mysql(8.0.25) 。
However, mariaDB(10.3.22) indicates that the function cannot be found. 
In addition, I can run the statement directly on mariaDB。

I am not sure if there is a problem with the library or the inconsistent version of the database

Thank you very much

**Comment by sidorares** [comment]
hi @hengtop - have you found an answer to your question? If yes can you post it here as well?

**Comment by hengtop** [comment]
> hello,I ran into a compatibility issue。
> 
> I used an aggregate function in my query ----- JSON_ARRAYAGG()
> 
> ```sql
> const statement = `select users.id, users.name, users.realname, users.cellphone, users.email, users.birthday, users.enable, users.avatar_url,
>       if(count(r.id), JSON_ARRAYAGG(JSON_OBJECT('id', r.id,'name', r.name, 'describe', r.describe, 'createAt', r.createAt , 'updateAt', r.updateAt)), null) roles
>       from users 
>       left join users_roles ur on users.id=ur.user_id
>       left join roles r on ur.role_id= r.id
>       where users.id = ? GROUP BY users.id;`;
>       const result = await connection.execute(statement, [id]);
> ```
> 
> ![image](https://user-images.githubusercontent.com/62384610/148896289-d4045092-e736-490b-bdd0-56b756a7761d.png)
> 
> This statement can be executed in the mysql(8.0.25) 。 However, mariaDB(10.3.22) indicates that the function cannot be found. In addition, I can run the statement directly on mariaDB。
> 
> I am not sure if there is a problem with the library or the inconsistent version of the database
> 
> Thank you very much


This is really a problem with my database version：
![image](https://user-images.githubusercontent.com/62384610/162344946-0c99c09c-0e75-4d98-92c3-702622721e03.png)
 [reason](https://mariadb.com/kb/en/json_arrayagg/)
