### ISSUE TITLE
Pooling: Selecting a table returns old value intermittently after update/delete/insert on the same table

### ISSUE THREAD

**Issue by tralmarcfredcamasis** [sidorares/node-mysql2#1489]
This is my pool config:

mysql.createPool({
            host: 'myhost',
            user: 'myuser',
            password: 'mypw',
            database: 'mydb',
            port: 'myport',
            connectionLimit: 10,
            waitForConnections: true,
            queueLimit: 0,
            multipleStatements: true
        });
        
I checked my code and i commit/rollback my transactions then release them afterwards. The data on db itself is updated but selecting by pool.query sometimes returns the old data.

**Comment by Cluster-Taek** [comment]
@tralmarcfredcamasis Hi. Did you solve this problem? If you solved can you tell us how you solved this issue ? It might help others (like me for instance ;-)) Thank you.
