### ISSUE TITLE
charset works only the one connection  connectionLimit:1

### ISSUE THREAD

**Issue by beforeti** [sidorares/node-mysql2#1495]
const pool = MYSQL.createPool(
        {
        
         charset: "utf8mb4",
         waitForConnections: true,
         connectionLimit: 50
      
      });

**Comment by sidorares** [comment]
hi @beforeti ! what are the symptoms of "not working" charset?

**Comment by sidorares** [comment]
I'm closing for now because of lack of information but if anyone has anything related ( pooled connection not getting charset setting from config? ) happy to repopen
