### ISSUE TITLE
Send multiple result tables for a single query?

### ISSUE THREAD

**Issue by andrisi** [sidorares/node-mysql2#1496]
MySQL allows you to send multiple queries separated with semicolons, and the server component handles this by issuing multiple "query" events. I'd like to send multiple resultsets for a single query (so not ones separated by ;) for an SQL languages extension I'm testing. Is this a limitation of the mysql2 package or the MySQL protocol that using multiple writeColumns/writeTextRow calls does not send over multiple resultsets?

**Comment by sidorares** [comment]
It should be able to handle multiple result sets, they are returned in a same way you's have result from multiple statements. What have you tried and what's expected / observed result?

You can see tests for multiple result sets in text protocol and binary protocol ( non-prepared & prepared ) here 

https://github.com/sidorares/node-mysql2/blob/6fae0c20e7459b2dee6439a2cd2beab0c45ab08d/test/integration/connection/test-multiple-results.js

https://github.com/sidorares/node-mysql2/blob/6fae0c20e7459b2dee6439a2cd2beab0c45ab08d/test/integration/connection/test-binary-multiple-results.js

**Comment by sidorares** [comment]
maybe need clarification is your question about the client or server side of the protocol? Do you want to make a server that generates multiple results?

**Comment by andrisi** [comment]
I meant the server side. I want to send multiple resultsets for a single query. For now it seems to say no query in buffer on the client if I try to do so with calling eof and then sending new columns and records. Let me experiment further and then get back to you.

**Comment by andrisi** [comment]
FYI, my original idea from a few years ago: https://dev.mysql.com/worklog/task/?id=358

**Comment by sidorares** [comment]
try to do client multi-statement "select * from a; select * from b" with debug enabled and then replicate same sequence of packets on your server. 

Client code handling myltiple results: https://github.com/sidorares/node-mysql2/blob/6fae0c20e7459b2dee6439a2cd2beab0c45ab08d/lib/commands/query.js#L233

Also in the docs https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-ProtocolText::Resultset

>  If the SERVER_MORE_RESULTS_EXISTS flag is set in the last EOF_Packet or (if the CLIENT_DEPRECATE_EOF capability flag is set) OK_Packet, another ProtocolText::Resultset will follow (see Multi-resultset).

![image](https://user-images.githubusercontent.com/173025/150706068-5d98db78-0f9a-486b-b9f8-7a3c1e242cbf.png)

**Comment by sidorares** [comment]
I wonder how a standard cli presents response with more than one table in it ( this is currently possible, just not with a single select - you need to create a stored procedure that selects 2 or more tables and call it )

**Comment by andrisi** [comment]
SERVER_MORE_RESULTS_EXISTS worked, I'll report more soon.

**Comment by andrisi** [comment]
This is how multiple resultsets look like in the cli, now for a single query too from a mysql2 server script.

![image](https://user-images.githubusercontent.com/1255809/151010606-822dddf2-adaa-44ea-94b0-1d61df6eb12d.png)

**Comment by andrisi** [comment]
Can I import this SERVER_MORE_RESULTS_EXISTS from the mysql2 package? It doesn't seem to get exported.

**Comment by sidorares** [comment]
right now the only way is to `require('mysql2/lib/constants/server_status')`

I think to avoid deep require we need to add all constants to the top level export ( possibly via lazy load getter ). Would you like to work on that @andrisi ?

**Comment by andrisi** [comment]
Not much experience in package creation, but will have a go at later.
