### ISSUE TITLE
node-mysql Potential incompatibility - Escaping values with object placeholders

### ISSUE THREAD

**Issue by sleepdotexe** [sidorares/node-mysql2#1502]
### Context
From the [mysqljs docs](https://www.npmjs.com/package/mysql#escaping-query-values):
> Alternatively, you can use ? characters as placeholders for values you would like to have escaped like this:
```js
connection.query('SELECT * FROM users WHERE id = ?', [userId], function (error, results, fields) {
  if (error) throw error;
  // ...
});
```
> This escaping allows you to do neat things like this:
```js
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'
```

By the looks of things, this syntax allows you to use object structure as a form of named placeholder in your query and leverage the value escaping helper.

### The issue
When trying to follow a similar syntax in my own code using mysql2, I am receiving the following error/stack trace:
```
TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at ...\node_modules\mysql2\lib\connection.js:628:17
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (...\node_modules\mysql2\lib\connection.js:620:22)
    at ...\node_modules\mysql2\lib\pool.js:172:14
    at ...\node_modules\mysql2\lib\pool.js:45:37
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```
This occurs even though I am logging my data and none of the properties are either null or undefined.
Strangely, the stack trace [does not seem to lead to the most relevant location in the source code](https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L628-L630)? Not sure exactly how that is working however.
I am using nodejs 16.8.0 and mysql2@2.3.3.

### Code sample:
```js
const mysql = require('mysql2/promise');

const con = mysql.createPool({
        //... database setup
	namedPlaceholders: true
});

const sql = `INSERT INTO users SET ?`;
const now = convertToSQLDateTime(new Date());	
const data = {
	email: user.email,
	display_name: user.display_name,
	country: user.country,
	join_date: now,
	most_recent_activity: now
}

console.log(data);
return con.execute(sql, data);
```
An example of what the `console.log(data);` line is returning:
```js
{
  email: 'testuser@mail.com',
  display_name: 'test.user',
  country: 'AU',
  join_date: '2022-02-05 05:44:04',
  most_recent_activity: '2022-02-05 05:44:04'
}
```

I am quite new to mysql & mysql2 so please feel free to offer a suggestion or correct me if I have made an error.

**Comment by sleepdotexe** [comment]
One other note, using `con.query` instead of `con.execute` produces the following:

```
...\node_modules\mysql2\promise.js:341
    const localErr = new Error();
                     ^

Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1
    at PromisePool.query (...\node_modules\mysql2\promise.js:341:22)
    at Object.addNewUser (...\services\db.js:30:14)
    at Request._callback (...\routes\login_callback.js:68:10)
    at Request.self.callback (...\node_modules\request\request.js:185:22)
    at Request.emit (node:events:394:28)
    at Request.<anonymous> (...\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:394:28)
    at IncomingMessage.<anonymous> (...\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:513:28)
    at IncomingMessage.emit (node:events:406:35) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sql: 'INSERT INTO users SET NULL',
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL' at line 1"
}
```

It looks as though the `data` object might not be getting parsed properly and is instead returned as `NULL`?

**Comment by sidorares** [comment]
in case of `.execute()` all parameters must be in an array and are mapped to a simple mysql type. What happens in your case since statements need one variable it's read as `data[0]` which is undefined - hence the error

**Comment by sidorares** [comment]
to fix - you need to expand `SET ?` manually into as many simple inputs as you have, e.i ``const sql = `INSERT INTO users SET (email=?,  display_name=?, country=?, join_date=?, most_recent_activity: ?)`; `` and pass array with 5 values in the execute call

**Comment by sleepdotexe** [comment]
Hi, thanks for your responses. I ended up adopting a similar workaround (just instead using `INSERT INTO users (...) VALUES (...)` and passing an array) in the meantime. May also consider writing my own helper function to parse an object into a readable array/SQL string.

**Comment by sleepdotexe** [comment]
### UPDATE:

The syntax I was originally using was in fact correct, however I made a small error which was preventing it form working.

1. As discussed in the comment above, `.query()` must be used instead of `.execute()` for the substitution to occur client-side
2. For the line `return con.execute(sql, data);`, the `data` object must be wrapped in an array. Missed this earlier.

### Corrected line:
```js
return con.query(sql, [data]);
```

### Working code:
```js
const sql = `INSERT INTO users SET ?`;
const now = convertToSQLDateTime(new Date());

const data = {
	email: user.email,
	display_name: user.display_name,
	country: user.country,
	join_date: now,
	most_recent_activity: now
}

return con.query(sql, [data]);
```


A bit of a dumb error on my part originally for missing that, considering how the placeholders work. Hopefully this can be of assitance to anyone who encounters a similar issue.
