### ISSUE TITLE
Add windows CI

### ISSUE THREAD

**Issue by sidorares** [sidorares/node-mysql2#151]
use appveyor config from https://github.com/felixge/node-mysql/pull/997

**Comment by dougwilson** [comment]
Here is the final configuration I ended up with: https://github.com/felixge/node-mysql/commit/74afe14e0d310c59ccc4bb08df77212979ac165c

**Comment by sidorares** [comment]
thanks @dougwilson !

**Comment by sidorares** [comment]
#152
