### ISSUE TITLE
批量插入数据时，只返回了一个insertId，期望插入n条数据就返回n个insertId

### ISSUE THREAD

**Issue by tanjwGit** [sidorares/node-mysql2#1510]
# 中文：
你好，
    批量插入后如何获取插入的所有insertId? 现在我只得到了一个insertId？

如果使用 insertId ～ insertId + affectedRows 之间的数字作为所有的insertId 会不会不准确呢？

# English:
Hello,
     How to get all insertIds inserted after bulk insert? Now I get only one insertId?

Would it be inaccurate if the number between insertId ~ insertId + affectedRows is used as all insertIds?

**Comment by testn** [comment]
You can't get all the insert ids.

**Comment by sidorares** [comment]
I think stored procedure is the only real option, at a protocol level there is no support for this feature as per linked discussion
