### ISSUE TITLE
stream() methods only argument is optional

### ISSUE THREAD

**Issue by pihentagy** [sidorares/node-mysql2#1520]
options argument should be optional
https://github.com/sidorares/node-mysql2/blob/943b8b2d1423d8f0d010d09f3ab9d1a0aceff676/typings/mysql/lib/protocol/sequences/Query.d.ts#L139

**Comment by MasterOdin** [comment]
#1340 would fix this

**Comment by sidorares** [comment]
merged, will try to cut a release soon
