### ISSUE TITLE
WHERE..IN with Named Placeholder

### ISSUE THREAD

**Issue by mrsekut** [sidorares/node-mysql2#1524]
Is it possible to use WHERE..IN in SQL when using [Named Placeholders](https://github.com/sidorares/node-mysql2/blob/943b8b2d1423d8f0d010d09f3ab9d1a0aceff676/documentation/Extras.md#named-placeholders)?

When I wrote the following,
```ts
const sql = `
  SELECT *
  FROM users
  WHERE user_id IN (:userIds)`;
```

pattern1 The result is incorrect. Same as an empty array.
```ts
const res= await connection.get(sql, {
  userIds: userIds, // == []
});
```

pattern2: The result is incorrect. Same as an empty array.
```ts
const res= await connection.get(sql, {
  userIds: [userIds], // == []
});
```

pattern3: The result is incorrect. Only the first item is retrieved.
For example, when `userIds = [1,2,3]`, only `userId = 1` is acquired.
```ts
const res= await connection.get(sql, {
  userIds: userId.join(","), // only first item
});
```

pattern4: It works, but it's not good because it's not escaped.
```ts
const sql = `
  SELECT *
  FROM users
  WHERE user_id IN (${userIds.join(',')})`;
```

Is this writing supported?
If not, I think it's better to add it to the document.

**Comment by flipperlite** [comment]
I haven't seen support for arrays in the SQL template string formatter but I could be wrong. If it's not supported, I agree that the documentation should reflect that fact.  I know it supports strings, numbers, objects. Without support for arrays and more importantly, array item data types, I'd use pattern4 and simply validate your array values as integers. Integers do not need to be escaped in the SQL statement.

```javascript
const sql = `
  SELECT *
  FROM users
  WHERE user_id IN (${userIds.filter(e => Number.isInteger(e)).join(',')})`;
```

The following would be a valid SQL statement without any need for double quotes around your user_id values:

```javascript
const sql = `
  SELECT *
  FROM users
  WHERE user_id IN (1, 2, 3, 4)`;
```

Here's the documentation for the [Number.isInteger function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger).

**Comment by flipperlite** [comment]
I was wrong (although I haven't tested it myself). Follow [this link](https://github.com/sidorares/node-mysql2/issues/1347) on how to pass an array to an index placeholder.

**Comment by sidorares** [comment]
yes, mostly answered in https://github.com/sidorares/node-mysql2/issues/1347 and linked issues

@mrsekut

assuming `connection.get` in your code performs `.query()` pattern 1 works for me, example:

```js
import mysql from "mysql2/promise"

const conn = await mysql.createConnection({ 
    host: "localhost",
    port: 3306,
    user: 'root',
    database: 'mysql',
    password: 'password',
    namedPlaceholders: true
});

const sql = await conn.format("SELECT * from user WHERE User IN (:user_names)", {user_names: ["mysql_sys", "root"]});
console.log(sql);
const [rows] = await conn.query("SELECT * from user WHERE User IN (:user_names)", {user_names: ["mysql_sys", "root"]});
console.log(rows);
await conn.close()
```

prepared statements need exactly the same number of placeholders as number of parameters, you'd need to choose between dynamic placeholders or client side dynamic interpolation for IN parameters only
