### ISSUE TITLE
Add links for MySQL connection study in contribution guide

### ISSUE THREAD

**Issue by diegogit03** [sidorares/node-mysql2#1532]
Please, you can add links for study MySQL connection in contribution guide, for new contributors

**Comment by diegogit03** [comment]
I found this official article: https://dev.mysql.com/doc/internals/en/overview.html

**Comment by sidorares** [comment]
the "wire protocol documentation" is linked in "Other Resources" section here https://github.com/sidorares/node-mysql2/tree/master/documentation
