### ISSUE TITLE
error TS2339: Property 'affectedRows' does not exist on type 'RowDataPacket[] | RowDataPacket[][]...

### ISSUE THREAD

**Issue by kricha** [sidorares/node-mysql2#1556]
Hello, i've some code, and have problems with it. I need to use `// @ts-ignore` to handle compiler problems:

```ts
import mysql, {Connection} from 'mysql2/promise';

const conn: Connection = await mysql.createConnection({
    database: 'bot',
    namedPlaceholders: true,
    host: 'db',
    user: 'root'
});

conn.execute('UPDATE test set inc=inc+1 where active=1;')
    .then(([result]) => {
        if (result && result.hasOwnProperty('affectedRows')) {
            console.log(result.affectedRows)
        }
    })
;
```

here i've got error:
```
error TS2339: Property 'affectedRows' does not exist on type 'RowDataPacket[] | RowDataPacket[][] | OkPacket | OkPacket[] | ResultSetHeader'.
Property 'affectedRows' does not exist on type 'RowDataPacket[]'.
```

Also, my IDLE says:
<img width="548" alt="image" src="https://user-images.githubusercontent.com/4619899/162780715-46c80000-df7a-4459-ab1a-f8a0fd55411c.png">

i don't know why execute method returns me mysql.Query instead of promise...

**Comment by sidorares** [comment]
Hm, I can see `affectedRows` in the definition - https://github.com/sidorares/node-mysql2/blob/dbb344e89a1cc8bb457b24e67b07cdb3013fe844/typings/mysql/lib/protocol/packets/OkPacket.d.ts#L7

**Comment by yuxizhe** [comment]
@kricha You can use the 'in' operator to check 

```ts
conn.execute('UPDATE test set inc=inc+1 where active=1;')
    .then(([result]) => {
        // You can use the 'in' operator to check
        if ("affectedRows" in result) {
            console.log(result.affectedRows)
        }
    })
;
```

> https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types

**Comment by wellwelwel** [comment]
Hi @kricha, complementing @yuxizhe's answer, you can also specify the expected type of the `execute`.

For example:
```ts
import mysql, { Connection } from 'mysql2/promise';

const conn: Connection = await mysql.createConnection({});

/** Note the `execute<mysql.ResultSetHeader>` */
const [result] = await conn.execute<mysql.ResultSetHeader>('UPDATE...');

console.log(result.affectedRows);
```

**Comment by wellwelwel** [comment]
You can follow this example from documentation:
[documentation/en/TypeScript-Examples.md#resultsetheader](https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/documentation/en/TypeScript-Examples.md#resultsetheader) 

Also a practical example here:
https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/examples/typescript/row-data-packet.ts#L35-L41

---

@kricha, I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️
