### ISSUE TITLE
Decimal being returned as string instead of number

### ISSUE THREAD

**Issue by owen95t** [sidorares/node-mysql2#1561]
Hey guys

I am facing an issue here where my decimal columns are being returned as string. I am using mysql2 with knex/objection. 

I've read that objection doesnt modify and datatypes and knex uses the db lib to retrieve data only, which means that this library is the only thing left causing this issue.

I am unable to fix this, even after enabling **supportBigNumbers** and disabling **bigNumberStrings**. My decimals are nothing wild, only 2 decimal points and 8 total digits. (which means numbers up to 999999.99 is supported, well within the limits of JS's Number type)

Is there anything else I can try?

Thank you very much

**Comment by sidorares** [comment]
can you post your table schema and the query?

**Comment by sidorares** [comment]
`DECIMAL` is intentionally always returned as string to prevent data loss, can you check that first?

**Comment by sidorares** [comment]
I'll close the issue for now, from the title it looks like the column type is `DECIMAL`.
Your options right now: cast results to another type in the sql query ( float and double are parsed into js numbers ) or use `typeCast` ( https://github.com/mysqljs/mysql#custom-type-casting ) - see example and other comments in https://github.com/sidorares/node-mysql2/issues/795#issuecomment-396769077

**Comment by owen95t** [comment]
@sidorares Thanks!

Sorry i didnt see #795 earlier! I'll try it out

Thanks!
