### ISSUE TITLE
Missing prepare/unprepare

### ISSUE THREAD

**Issue by zordtk** [sidorares/node-mysql2#1564]
Looked at the documentation at https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md when I try to run a prepared statement

```js
connection.execute('statement', (error, results) => {

});

connection.unprepare('statement');
```

I get the following error

`
 error TS2339: Property 'unprepare' does not exist on type 'Connection'.
`

The prepare method also doesn't exist

**Comment by sidorares** [comment]
thanks for the report @zordtk 
I don't contribute to typings myself but happy to review a PR - do you feel you can add the missing method to the interface?
