### ISSUE TITLE
Can't insert multiple rows with query

### ISSUE THREAD

**Issue by EmberRandall** [sidorares/node-mysql2#1567]
I've looked through https://github.com/sidorares/node-mysql2/issues/1244 and the issues linked there, but I'm still not able to figure out how to insert multiple rows with either `query` or `execute`.  Can you help?

Current code:
```
const args = [
    [2, 3],
    [3, 4],
  ]
  const test = await pool.query(`INSERT INTO ${tableName}` + '(ZipCode, `Beg+4`) VALUES ?', args)
```

When I run this, it says "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2, 3' at line 1".  I can insert a single row like

```
const args = [2, 3]
const test = await pool.query(`INSERT INTO ${tableName}` + '(ZipCode, `Beg+4`) VALUES(?, ?)', args)
```

but multiple rows consistently fail no matter what variation of syntax I try.  If I understand the previous issues right, this should be possible -- what's the correct syntax?

**Comment by EmberRandall** [comment]
@flipperlite if I'm understanding https://github.com/sidorares/node-mysql2/issues/1244#issuecomment-1094547067 correctly, you shouldn't need to have a predetermined number of question marks, you should be able to do it with a single one. But I've tried a lot of variations of that example, and haven't been able to get it to work yet

**Comment by sidorares** [comment]
@EmberRandall you need to pass single parameter, an array of values in order for it to be interpreted as a list. So you put one element into your array of parameters, and _that_ element is array of tuples

```js
const { format } = require('sqlstring');
const tableName = "tableName";
const args = [[
    [2, 3],
    [3, 4],
  ]]
  const sql = format(`INSERT INTO ${tableName}` + '(ZipCode, `Beg+4`) VALUES ?', args)
```

returns ``'INSERT INTO tableName(ZipCode, `Beg+4`) VALUES (2, 3), (3, 4)'``.
