### ISSUE TITLE
Queries are slow

### ISSUE THREAD

**Issue by jonas-w** [sidorares/node-mysql2#1569]
I have a huge table above 250.000 lines. When executing a select statement in the mysql cli it returns in like 0.002 seconds an output. But if i use your library it's minimum 30 seconds...
I'm using mariadb and connect via the unix socket

**Comment by sidorares** [comment]
Hi @jonas-w have you found an answer to your question?

250000 rows is a fairly large response. Does it take 0.002 seconds for mysql cli to do everything from start to end ( from the time you press enter to last row printed on the screen? ) Can you show sample code you use to measure time?

**Comment by sidorares** [comment]
pool or not should not matter for single query time

**Comment by jonas-w** [comment]
Yeah no that's the point it wasn't only one query. It was async and many queries were sent and then via websockets i requested one and it took so long, because it waited for the others to finish!
