### ISSUE TITLE
CI: coverage-comment-action premissions problem

### ISSUE THREAD

**Issue by yuxizhe** [sidorares/node-mysql2#1585]
https://github.com/sidorares/node-mysql2/blob/ab3feb75bb4af1f6d288c0494a99aa2483ac24d5/.github/workflows/ci-linux.yml#L118-L122

there is a bug in coverage-comment-action
https://github.com/ewjoachim/coverage-comment-action/issues/26

external users creating PRs will trigger actions whose github token won't have the right to post comments.

so external users PRs always fail. 

eg: https://github.com/sidorares/node-mysql2/runs/6649645051?check_suite_focus=true

```
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/issues#create-an-issue-comment"}
Operating on refs/pull/1584/merge
Commenting on the coverage on PR 1584
Previous coverage results not found, cannot report on evolution.
```

**Comment by sidorares** [comment]
I'm thinking to completely disable this workflow unfortunately
Maybe I'll give https://github.com/ewjoachim/python-coverage-comment-action a try first

**Comment by sidorares** [comment]
added `continue-on-error: true` via #1697 , PRs from external users won't have a coverage message but at least should not see failure if everything else is ok
