### ISSUE TITLE
In queries don't work with execute

### ISSUE THREAD

**Issue by shawnam** [sidorares/node-mysql2#159]
I've been having trouble using in queries with execute. I'm hoping this will demonstrate the issue:

```
connection.query("create temporary table in_test (id int unsigned)");
connection.query("insert into in_test set id=1");
connection.query("insert into in_test set id=2");
connection.query("SELECT * FROM in_test WHERE id IN ?", [[[1, 2]]], function (err, rows, cols) {
        console.log(arguments);
});
connection.execute("SELECT * FROM in_test WHERE id IN ?", [[[1, 2]]], function (err, rows, cols) {
        console.log(arguments);
        connection.end();
});
```

And the output:
```
{ '0': null,
  '1': [ { id: 1 }, { id: 2 } ],
  '2': [ [object Object] ],
  '3': 1 }
{ '0': { [Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1] code: 'ER_PARSE_ERROR', sqlState: '#42000' } }
```

Is this behavior expected for some reason that I'm missing?

**Comment by sidorares** [comment]
I haven't tried using "in()" operator with binary protocol, I'll look into this

Simple rule is that you must provide same number of arguments as you have ? in the statement, and it's just flat array of simple types ( everything except Buffer converted to string during "execute command" )

You can try this code:

```js
connection.execute("SELECT * FROM in_test WHERE id IN (?,?)", [1, 2], function (err, rows, cols) {
        console.log(arguments);
        connection.end();
});
```

The order of execution is like this:
<-  prepare "SELECT * FROM in_test WHERE id IN (?,?)"
-> ok. Your statement is 1234
<- execute 1234. First parameter is "1", second parameter is "2"
-> fields, rows response

So in your case it's probably prepare("SELECT * FROM in_test WHERE id IN ?") and execute with "[[1, 2]]" parameter

**Comment by sidorares** [comment]
also you can do prepare/execute manually to check at which stage error happen:

```js
connection.prepare("SELECT ... ", function(err, stmt) {
   // check errors
   stmt.execute(parameters, function(err, rows, fields) {
      //
   });
});
```

or just post your log here with debug flag set to true when you connect: 
```js
    var connection = mysql.createConnection({ debug: true });
```

**Comment by shawnam** [comment]
The code I posted above with debugging enabled:
```
Add command: Connection
Add command: query
Add command: query
Add command: query
Add command: query
Add command: execute
0 undefined ==> Connection#handshakeInit(0,,83)
 raw: 0a352e352e33382d33352e322d6c6f6700608c0000224e4651433e4c4200fff72102000f8015000000000000000000004824764b523b6e3c7d253930006d7973716c5f6e61746976655f70617373776f726400
Server hello packet: capability flags:-2146437121=(long password, found rows, long flag, connect with db, no schema, compress, odbc, local files, ignore space, protocol 41, interactive, ignore sigpipe, transactions, reserved, secure connection, multi statements, multi results, ps multi results, plugin auth, remember options)
Sending handshake packet: flags:193487=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results)
0 35936 <== Connection#handshakeInit(1,,73)
0 35936 ==> Connection#handshakeResult(2,maybeOK,7)
 raw: 00000002000000
        Sending query command: create temporary table in_test (id int unsigned)
0 35936 <== query#start(0,,53)
0 35936 ==> query#resultsetHeader(1,maybeOK,7)
 raw: 00000002000000
        Resultset header received, expecting 0 column definition packets
        Sending query command: insert into in_test set id=1
0 35936 <== query#start(0,,33)
0 35936 ==> query#resultsetHeader(1,maybeOK,7)
 raw: 00010002000000
        Resultset header received, expecting 0 column definition packets
        Sending query command: insert into in_test set id=2
0 35936 <== query#start(0,,33)
0 35936 ==> query#resultsetHeader(1,maybeOK,7)
 raw: 00010002000000
        Resultset header received, expecting 0 column definition packets
        Sending query command: SELECT * FROM in_test WHERE id IN (1, 2)
0 35936 <== query#start(0,,45)
0 35936 ==> query#resultsetHeader(1,,1)
 raw: 012f0000020364656607646f70706c657207696e5f7465737407696e5f746573740269640269640c3f000a00000003200000000005000003fe0000220002000004013102000005013205000006fe00002200
        Resultset header received, expecting 1 column definition packets
0 35936 ==> query#readField(2,,47)
 raw: 0364656607646f70706c657207696e5f7465737407696e5f746573740269640269640c3f000a00000003200000000005000003fe0000220002000004013102000005013205000006fe00002200
        Column definition:
          name: id
          type: 3
         flags: 32
        Compiled text protocol row parser:


(function() { return function TextRow(packet) {
  // "id": LONG
  this["id"] = packet.parseLengthCodedInt();
};})()


0 35936 ==> query#fieldsEOF(3,EOF,5)
 raw: fe0000220002000004013102000005013205000006fe00002200
0 35936 ==> query#row(4,,2)
 raw: 013102000005013205000006fe00002200
0 35936 ==> query#row(5,,2)
 raw: 013205000006fe00002200
0 35936 ==> query#row(6,EOF,5)
 raw: fe00002200
0 35936 <== execute#start(0,,40)
{ '0': null,
  '1': [ { id: 1 }, { id: 2 } ],
  '2':
   [ { catalog: 'def',
       schema: 'doppler',
       table: 'in_test',
       orgTable: 'in_test',
       name: 'id',
       orgName: 'id',
       characterSet: 63,
       columnLength: 10,
       columnType: 3,
       flags: 32,
       decimals: 0 } ] }
0 35936 ==> execute#prepareHeader(1,Error,156)
 raw: ff2804233432303030596f75206861766520616e206572726f7220696e20796f75722053514c2073796e7461783b20636865636b20746865206d616e75616c207468617420636f72726573706f6e647320746f20796f7572204d7953514c207365727665722076657273696f6e20666f72207468652072696768742073796e74617820746f20757365206e65617220273f27206174206c696e652031
{ '0': { [Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1] code: 'ER_PARSE_ERROR', sqlState: '#42000' } }
Add command:
```

```
connection.query("SELECT * FROM in_test WHERE id IN (?, ?)", [1, 2], function (err, rows, cols) {
        console.log(arguments);
});
```
Works, yes, though I use the other syntax because I don't always know precisely how many items I'll be including in my IN query. Is the syntax used with query expected to work with execute? Or it as designed that this works in query but not in execute?

**Comment by sidorares** [comment]
yes, query treats input sql more like a template and there are lots of automatic substitutions for arrays and objects. execute query is always sent as is to prepare command. If prepare does not support some syntax execute will fail.

For simple queries `execute` and `query` are interchangeable but for more complicated parameters substitutions there are differences

**Comment by sidorares** [comment]
actually, I would expect your example to work. This is similar sql in mysql command line client:

```
mysql> PREPARE stmt2 FROM 'SELECT * from test.insert_test WHERE id IN (?,?)';
Query OK, 0 rows affected (0.01 sec)
Statement prepared

mysql> set @a = 10;
Query OK, 0 rows affected (0.00 sec)

mysql> set @b = 11;
Query OK, 0 rows affected (0.00 sec)

mysql> EXECUTE stmt2 USING @a, @b;
+----+--------------+
| id | title        |
+----+--------------+
| 10 | test abc xyz |
| 11 | test abc xyz |
+----+--------------+
2 rows in set (0.01 sec)
```

**Comment by sidorares** [comment]
could you add something like `console.log('Preparing statement: ', + this.query)` after https://github.com/sidorares/node-mysql2/blob/master/lib/commands/prepare.js#L24 ? I'd like to see which query is actually failing in your case.

**Comment by shawnam** [comment]
I didn't intend to be confusing. The following works as expected:
```
connection.query("SELECT * FROM in_test WHERE id IN (?, ?)", [1, 2], function (err, rows, cols) {
        console.log(arguments);
});
```

Running this:
```
connection.query("create temporary table in_test (id int unsigned)");
connection.query("insert into in_test set id=1");
connection.query("insert into in_test set id=2");

connection.prepare('SELECT * FROM in_test WHERE id IN ?', function (err, statement) {
    console.log(arguments);
   connection.end();
});
``` 

and adding the debugging line to prepare.js results in:

```
Preparing statement: SELECT * FROM in_test WHERE id IN ?
{ '0': { [Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1] code: 'ER_PARSE_ERROR', sqlState: '#42000' } }
```

So from the sounds of it, I shouldn't expect execute to work for this query, and if I require this syntax, I should keep using conneciton.query. Is that right?

**Comment by sidorares** [comment]
Query syntax ( where ? is replaced with "1,2,3" client side before sending to server ):

```js
connection.query("SELECT * FROM in_test WHERE id IN (?)", [ [1,2,3] ], onresult);
```

Explanation: there is one placeholder in query and one `[1,2,3]` value in arguments array. SqlString expands array to `"1,2,3"` string and "SELECT * FROM in_test WHERE id IN (1,2,3)" sql is sent to server for execution

Prepared statements syntax:
```js
connection.execute("SELECT * FROM in_test WHERE id IN (?,?,?)", [ 1,2,3 ], onresult);
```
Explanation: first, `"SELECT * FROM in_test WHERE id IN (?,?,?)"` string is sent to server to prepare statement. After that, "execute" command with statement is and three values `[1,2,3]` is sent to server

Hope that helped :)

So your options for"select in":
- use text protocol (query), treat array as single value in placeholder and arguments list
- explicitly put all values with matching number of placeholders ( works for both query and execute )
- change your logic to use some kind of join to avoid variable number of values in the test

**Comment by angusmccloud** [comment]
> Query syntax ( where ? is replaced with "1,2,3" client side before sending to server ):
> 
> ```js
> connection.query("SELECT * FROM in_test WHERE id IN (?)", [ [1,2,3] ], onresult);
> ```
> 
> Explanation: there is one placeholder in query and one `[1,2,3]` value in arguments array. SqlString expands array to `"1,2,3"` string and "SELECT * FROM in_test WHERE id IN (1,2,3)" sql is sent to server for execution
> 
> Prepared statements syntax:
> 
> ```js
> connection.execute("SELECT * FROM in_test WHERE id IN (?,?,?)", [ 1,2,3 ], onresult);
> ```
> 
> Explanation: first, `"SELECT * FROM in_test WHERE id IN (?,?,?)"` string is sent to server to prepare statement. After that, "execute" command with statement is and three values `[1,2,3]` is sent to server
> 
> Hope that helped :)
> 
> So your options for"select in":
> 
> * use text protocol (query), treat array as single value in placeholder and arguments list
> * explicitly put all values with matching number of placeholders ( works for both query and execute )
> * change your logic to use some kind of join to avoid variable number of values in the test

Just want to say - thanks for this post! I had been turning my arrays into a string of "5, 6, 7" to insert into Queries and that sure wasn't working. This fixed it for me - pass the array of values you want that `?` to turn into
