### ISSUE TITLE
UNION SELECT of NULL and UNSIGNED TINYINT(1) returned as JS string on MariaDB 10.3+

### ISSUE THREAD

**Issue by Ashoat** [sidorares/node-mysql2#1591]
I have a `UNION SELECT` query that unions two values:

1. A column with type `UNSIGNED TINYINT(1)` in the primary `SELECT`
2. `NULL` in the `UNION SELECT`

I upgraded to MariaDB 10.3 and I'm now seeing this value being returned as a JS string (eg. `'1'` or `'3'`) instead of a JS number.

The issue doesn't seem to occur in MariaDB 10.2 or MySQL 5.7. I'm using the latest release of `mysql2` (2.3.3).

`DESCRIBE` queries on the table return exactly the same on MariaDB 10.3 vs. MariaDB 10.2, but I'm not sure if that's relevant.

I also observed that this issue does not occur if you use `BIGINT(20)` in place of `UNSIGNED TINYINT(1)`.

**Comment by Ashoat** [comment]
Not sure why this was happening, but found a [couple](https://stackoverflow.com/questions/71134698/mariadb-10-3-unions-casting-integers-to-strings-when-using-null-placeholder) of [StackOverflows](https://stackoverflow.com/questions/56824451/union-select-concat-works-differently-between-mariadb-mysql) reporting similar issues with different libraries, so I don't think this is `mysql2`'s fault.

Found that I could circumvent the issue by replacing `NULL` with `CAST(NULL AS UNSIGNED)`.

**Comment by sidorares** [comment]
do you think its specific to MariaDB 10.3+ only ?

**Comment by sidorares** [comment]
is you can provide minimum example to reproduce that would help a lot me to debug ( script that creates a temporary table, populates it and performs select )
