### ISSUE TITLE
Question, what happend with the connection when a query fails?

### ISSUE THREAD

**Issue by Luis-Enrique93** [sidorares/node-mysql2#1594]
i have two question, i am using serverless and rds, with a pool with 'mysql2/promise' and mysql.createPool(params) and conn.release() 

first: if i have an error before conn.release(), what would happend with that connection? would it get inmediatly close? 

second: how could i debug how many active connections do i have? i would like to optimize because it's serverless, i could have many requests in a litle time

**Comment by sidorares** [comment]
this depends on error type, if its "fatal" ( usually tcp connection closed or unknown error ) then its removed from the pool, if it's non fatal ( sql error etc )

There is no documented interface to query pool for the number of active connections but you might use `pool._allConnections.length - pool._freeConnections` - https://github.com/sidorares/node-mysql2/blob/d8de3cae7389f37207fc532bb4b563f162b241af/lib/pool.js#L26-L27
