### ISSUE TITLE
`execute` not working when `querry` is working

### ISSUE THREAD

**Issue by intern7777** [sidorares/node-mysql2#1598]
similar to https://github.com/sidorares/node-mysql2/issues/1456, which is in fact where i found the solution to use query. only my example is much more simple, so I may be missing something.

```js
async function updateUser(){
        var data = {"id": "1", "name" : "John Doe"};
	const mysql = require('mysql2/promise');
	const  con = await mysql.createConnection({ host: [host], user: [user], password: [password] , database: [database] });
	var sql = 'UPDATE users SET ? WHERE id = ?';
	var [rows, fields] = await con.execute(sql, [data, data.id]);
	await con.end();
	return rows;
}
``` 
returns

```
code: 'ER_PARSE_ERROR',
  errno: 1064,
  sql: 'UPDATE users SET ? WHERE id = ?',
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? WHERE id = ?' at line 1"
}
```

**Comment by sidorares** [comment]
SET name can't be prepared statement parameter, you need to set it client side

See https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html#prepared-statements-permitted for detailed documentation on allowed syntax

Possible solution:

```js
const sql = mysql.escape('UPDATE users SET ? WHERE id = ?', [data]);
const [rows, fields] = await con.execute(sql, [data.id]);
```

**Comment by intern7777** [comment]
@sidorares thank you for the reply. I see from https://github.com/sidorares/node-mysql2/issues/945 you wrote:

> .query() parameter escaping is very robust as well and there is no known sql injections vulnerabilities known right now ( here are some example where bugs in libmysql client-side escaping has bitten in the past: https://stackoverflow.com/questions/5741187/sql-injection-that-gets-around-mysql-real-escape-string/12118602#12118602 )

in your view has the situation changed in the past three years? Can I continue using `query` or is `execute` recommended?  

(closing as the main issue was resolved.)

**Comment by sidorares** [comment]
use `.execute()` for dynamic / user generated input and `.format()` or `.query()` where you build query from a static data ( table names, field names etc )
