### ISSUE TITLE
Add support for cursor 

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [sidorares/node-mysql2#1603]
> A cursor can be used to efficiently read through large result sets without loading the entire result-set into memory ahead of time. It's useful to simulate a 'streaming' style read of data, or exit early from a large result set. 
ref: https://node-postgres.com/api/cursor

we need a API like this:
```JavaScript 
const cursor = connection.query(new Cursor(sql, params))
cursor.read(100, (err, rows) => {
  cursor.close(() => {
    connection.release()
  })
})
```

**Comment by sidorares** [comment]
Afaik there is no support for cursors at the protocol level.

**Comment by sidorares** [comment]
If not already in the query via limit keyword I think the only option is to kill stream of result rows by thread Id ( from another connection ) or just close client side of tcp connection

**Comment by Lloyd-Pottiger** [comment]
I have two ideas to simulate cursor, but both of them has limitations.
1. use stream, but we can only get the result row by row.
    ```JavaScript
    var stream = require('stream');

    connection.query('select * from bigdata')
      .stream()
      .pipe(stream.Transform({
        objectMode: true,
        transform: function(data,encoding,callback) {
          // do something with data...
          callback()
        }
       })
      .on('finish',function() { console.log('done');})
    ```
2. Add `LIMIT` and `OFFSET` clause to the input `SELECT` sql, but it is kind of difficult to handle all sql statements.

**Comment by sidorares** [comment]
I prefer consumers to have explicit LIMIT / OFFSET

I'll close this issue for now, feel free to continue discussion but my preference is to only add this functionality once there is a protocol level support for it. More high level libraries ( query builders / orms ) might want to have something like you suggested but probably not belongs at a driver level
