### ISSUE TITLE
Unable to execute bulk insert query

### ISSUE THREAD

**Issue by soysandeep** [sidorares/node-mysql2#1607]
I was trying to bulk insert rows into a table and I'm getting an error. Isn't this how we are supposed to insert multiple rows with one query?

```
sql.execute(
  `INSERT INTO ${MENU_TABLE} VALUES ?`,
  values,
  () => { ... }
);
```

`values` here is an array of array, like - `[ ['1', 'foo' ,'bar' ], [ .. ], [ .. ] ]`

Result:

```
{
    "message": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1"
}
```

**Additional info**:

- mysql2 version `2.3.3`

**Comment by sidorares** [comment]
Not with execute - it does not work like "query builder" and requires exactly same number of ? placeholders as the number of parameters you pass. Either use .query or expand placeholder

**Comment by SilasGrygier** [comment]
Hi @sidorares, is the query() command still a prepared statement because the [docs](https://www.npmjs.com/package/mysql2) for mysql2 only mention the execute() command explicitly for prepared statements, thanks in advance!

**Comment by sidorares** [comment]
`query()` is not using prepared statements.

`.query()` steps: 

- perform client side parameters interpolation ( also available via `format()` and `escape()` functions, also available as a standalone package https://www.npmjs.com/package/sqlstring )
- send result of the above step as COM_QUERY mysql command
- serialise response rows

`execute()` steps:

- check if there is a previously prepared statement for the parametrized query you have
- if there is, perform COM_EXECUTE command with statement id and parameters
- if not, prepare first and save result, then execute
- no client side parameter interpolation step

**Comment by SilasGrygier** [comment]
Great thanks so much for the answer! Based on your response I've put together an insert query that uses a prepared statement:
```
let sql = 'insert into product (id,title, counter) values ?';
sql = mysql.format(sql, [product_array]);
let result = await conn.query(sql).catch(error => {
    conn.release();
    throw new Error('Error during SQL insertion', { cause: error });
});

```

**Comment by sidorares** [comment]
@SilasGrygier since you use .query() there is no prepared statement in your example. Also .query would call format automatically.

```js
const product_array = [ [ '1', 'dry-rain', 0], ['2', 'velvet-desk', 0 ], ['3', 'metal-chair', 0  ] ] 
try {
  let result = await conn.query('insert into product (id, title, counter) values ?', [product_array]);
  // ...
} catch(error) {
  // ...
}
```

Example which uses prepared statement is exactly as above but with .query replaced with .execute

```js
const product_array = [ [ '1', 'dry-rain', 0], ['2', 'velvet-desk', 0 ], ['3', 'metal-chair', 0  ] ] 
try {
  let result = await conn.execute('insert into product (id, title, counter) values ?', [product_array]);
  // ...
} catch(error) {
  // ...
}
```

**Comment by SilasGrygier** [comment]
Oh I I see, thanks @sidorares , I tried your code snippet but it needs a placeholder (in my case '?') for every single product_array element that I want to insert. So if I were to insert 3 elements the insert would look like this which I wasn't happy with:

```javascript
const product_array = [ [ '1', 'dry-rain', 0], ['2', 'velvet-desk', 0 ], ['3', 'metal-chair', 0  ] ] 
try {
  let result = await conn.execute('insert into product (id, title, counter) values ???', [product_array]);
  // ...
} catch(error) {
  // ...
}
```

Because in my case I have thousands of elements to insert so I thought it would be fishy if my sql insert query had 1000 placeholders which is why I was hoping that there was a way to use the **query()** function since it only needs 1 placeholder for the entire products array
