### ISSUE TITLE
Typed `execute` for `SELECT` stored procedures not accurate

### ISSUE THREAD

**Issue by hvolschenk** [sidorares/node-mysql2#1608]
I am using `execute` to execute stored procedures, but the return type is not accurate.

**Stored procedure**:

```sql
DELIMITER //
CREATE PROCEDURE `user_get_by_username`(
  IN in_username VARCHAR(25)
)
BEGIN
  SELECT `id`, `username` FROM `user` WHERE `username` = in_username;
END //
DELIMITER ;
```

**Code**

```ts
import { RowDataPacket } from 'mysql2';

import configuration from '../configuration';

export interface User extends RowDataPacket {
  id: number;
  username: string;
}

databaseConnection = mysql.createConnection({
  database: configuration.mySQL.database(),
  host: configuration.mySQL.host(),
  password: configuration.mySQL.password(),
  user: configuration.mySQL.username(),
});

const userGetByUsername = ({ username }: { username: string }) =>
  new Promise<User | null>((resolve, reject) => {
    databaseConnection.execute<User[][]>(
      { sql: 'CALL user_get_by_username(?)', values: [username] },
      (error, response) => {
        if (error) {
          reject(
            new Error(`Failed to get user '${username}': ${error.message}`)
          );
        } else {
          resolve(response[0].length > 0 ? response[0][0] : null);
        }
      }
    );
  });
```

The issue is that the callback does **not** receive `User[][]`, but instead it receives `[User[], ResultSetHeader]`,
and I cannot use the following as it does not work:

```ts
databaseConnection.execute<[User[], ResultSetHeader]>(
```

**Comment by sidorares** [comment]
@hvolschenk this is how stored procedure results are returned: an array of results from each select/update/insert/delete query followed by the final ResultSetHeader ( for the procedure call itself )

**Comment by hvolschenk** [comment]
I feel like you didn't read what I wrote above. That is exactly what I am saying.
It does return what you say it does, but the type/generic does not reflect that.

**Comment by wellwelwel** [comment]
@hvolschenk, sorry for the delay, I didn't see this Issue before.

From version `3.5.1` onwards, it's possible to use a dedicated type for **Procedure Calls**.

You can follow the `ProcedureCallPacket` documentation and practical examples on [documentation/en/TypeScript-Examples.md#procedurecallpacket](https://github.com/sidorares/node-mysql2/blob/master/documentation/en/TypeScript-Examples.md#procedurecallpacket).

---

About the `execute<[User[], ResultSetHeader]>`, you can use it as:

```ts
execute<ProcedureCallPacket<User[]>>
```
