### ISSUE TITLE
Bulk insert via db.query

### ISSUE THREAD

**Issue by pratikdhody** [sidorares/node-mysql2#1613]
Hi,

I have the following query

```
    var query = await db.query(
      "INSERT INTO wp_postmeta SET post_id=(?),meta_key=(?),meta_value=(?)",
      [values]
    );
```

with the following values data.

```
    let values = [
      [
        1,
        "text",
        "text is this",
      ],
    ];
```

but I keep getting Malformed communication packet error.
I have also tried the following but this doesn't work either

```
db.query(
      "INSERT INTO wp_postmeta SET post_id=?,meta_key=?,meta_value=?",
      [values]
    );
```

Please advise. I've searched the previous issues and I found some handy links unfortunately I was still unable to get it working.

Cheers

**Comment by sidorares** [comment]
I think the problem is with extra array around values, in that case the parameter is serialized as comma separated list

try

```js
 var query = await db.query(
      "INSERT INTO wp_postmeta SET post_id=(?),meta_key=(?),meta_value=(?)",
      [ 1, "text", "text is this" ]
    );
```

( or if you need to read it from values that would be `db.query(sql, values[0])` )

**Comment by pratikdhody** [comment]
Thanks for the quick reply. What would the format be though when trying to bulk insert multiple values?
e.g. the following throws _Incorrect arguments to mysqld_stmt_execute_

```
   var query = await db.query(
      "INSERT INTO wp_postmeta SET post_id=(?),meta_key=(?),meta_value=(?)",
      [
        [
         1,
          "text",
          "text is this",
        ],
        [
         2,
          "text",
          "text is the second text",
        ],
      ]
    );
```

**Comment by sidorares** [comment]
try this:

```js
var query = await db.query(
      "INSERT INTO wp_postmeta (post_id,meta_key,meta_value) VALUES ?",
      [[
        [
         1,
          "text",
          "text is this",
        ],
        [
         2,
          "text",
          "text is the second text",
        ],
     ]]
);
```

Quicker way to validate client side query generation ( possible in repl ) is to use `.format()`, you don't even need server connection

```js
mysql.format("INSERT INTO wp_postmeta (post_id,meta_key,meta_value) VALUES ?", [[[1, 2, 3, 4], [5, 6, 7, 8]]])
```

returns `'INSERT INTO wp_postmeta (post_id,meta_key,meta_value) VALUES (1, 2, 3), (5, 6, 7)'`

Why 2 nested arrays here: 1st level = list of arguments ( we have one ? placeholder, 1 argument in the list ). The only argument is an array itself - list of rows, each element is list of values in the row.

https://github.com/mysqljs/mysql#escaping-query-values
>  - Arrays are turned into list, e.g. ['a', 'b'] turns into 'a', 'b'
>  - Nested arrays are turned into grouped lists (for bulk inserts), e.g. [['a', 'b'], ['c', 'd']] turns into ('a', 'b'), ('c', 'd')

**Comment by pratikdhody** [comment]
Thanks @sidorares. That works but I had to wrap it like so:

```
await db.query(
      mysql.format(
        "INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES ?",
        [
          [
            [
              1,
              "text",
              "text is this",
            ],
            [
              2,
              "text",
              "text is this 2",
            ],
              3,
              "text",
              "text is this 3",
            ],
          ],
        ]
      )
    );
```

**Comment by sidorares** [comment]
db.query calls format internally, you should be able just do

```js
await db.query(
        "INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES ?",
        [
          [
            [
              1,
              "text",
              "text is this",
            ],
            [
              2,
              "text",
              "text is this 2",
            ],
              3,
              "text",
              "text is this 3",
            ],
          ],
        ]
    );
```
