### ISSUE TITLE
query inside forEach loop is running only a few times

### ISSUE THREAD

**Issue by Nithur-M** [sidorares/node-mysql2#1616]
I am inserting objects from an array of object as follows:
```
    var sql = 'INSERT INTO my_table SET ?';
    arr.forEach(item => {
      con.query(sql, item, function (err, result) { 
        if (err) throw err;
        console.log("1 record inserted");
      });
    })
```
The `arr` has around 80 items but the above code only be able to insert around 45 objects or so. Why does this happen? are there any other workarounds?

**Comment by sidorares** [comment]
is `con` a single connection or a pool connection?
how do you check how many are actually inserted? 

Note that in your forEach loop you start by queuing 80 insert commands on the client and they are then go one by one. If the connection is killed while commands are running you might not get all of them inserted

**Comment by Nithur-M** [comment]
It is a single connection.
I query the DB to see how many have been inserted.

**Comment by Nithur-M** [comment]
Using a pool connection solved the issue. Thanks for the quick response.

**Comment by sidorares** [comment]
would below example work for you?

```js

function insertArray(conn, items, cb) {
   if (arr.length < 1) {
       return cb(null, 'done!');
   }
   const [item, ...tail] = items;
   con.query('INSERT INTO my_table SET ?', [item], (err, result) => {
      if (err) {
         return cb(err);
      }
      console.log(`1 item inserted, ${tail.length} left`);
      insertArray(con, tail, cb);
   });
}

insertArray(con, arr, (err, result) => {
   console.log({ err, result });
});
```

**Comment by sidorares** [comment]
> Using a pool connection solved the issue. Thanks for the quick response.

curious what was the original issue ( my guess - killing connection too early )

**Comment by Nithur-M** [comment]
> curious what was the original issue ( my guess - killing connection too early )

yes, when I was using a single connection, all the insert attempts resulted in partial insertion like 40 items, 48 items, 55 items, etc.
So changed to pool connection as you pointed out, and the expected number of elements got inserted like a charm.

**Comment by sidorares** [comment]
It's actually opposite - single connection buffers query commands and they are inserted sequentially ( mysql protocol only allows one active command at a time in a given connection ), and in case of a pool you make inserts in parallel

**Comment by Nithur-M** [comment]
Ok, got it. Thanks for this nice info. I am actually inserting it into a database from a cron job. Would it be the reason for the connection being killed??
