### ISSUE TITLE
Heroku / ClearDB connections not closing

### ISSUE THREAD

**Issue by chrisveness** [sidorares/node-mysql2#162]
Using Heroku + ClearDB (1-dyno / ignite), it seems that `connection.end()` doesn't close the connection - `SHOW PROCESSLIST` shows connections building up with each page request in the same way as they do if I don't call `connection.end()` when using MySQL on localhost – after 10 pages refreshes, the app crashes.

Have you any idea what might cause this, or how to solve it?

Code to replicate it is as follows:

````sql
var koa   = require('koa');
var mysql = require('mysql-co');

var app = koa();

app.use(function* mysqlConnection(next) {

    var opt = { host: 'localhost', database: 'test', user: 'test', password: 'test' };
    var opt = { host: 'xxx.cleardb.com', database: 'heroku_xxx', user: 'xxx', password: 'xxx' };
    this.db = mysql.createConnection(opt);
    this.db.connect();

    yield next;

    this.db.end();
});

app.use(function* query(next) {
    var result = yield this.db.query('show processlist');
    console.log(result[0]);
});

app.listen(3000);
````

Using the cleardb opt processes build up in the same way as the localhost opt does with the call to ` this.db.end()` removed.

Behaviour is same on Node.js v0.12.0 and io.js v1.4.3.

**Comment by sidorares** [comment]
This might be because `end()` just closes tcp connection and does not send proper `CMD_QUIT` packet atm - see #135. Tcp fin might get lost somehow and server thinks that connection is still alive

**Comment by chrisveness** [comment]
Is that straightforward to sort? I don't think I'd be capable of offering a PR, but if there's any testing I could help with, I'd be glad to.

**Comment by sidorares** [comment]
@chrisveness could you try master? ( or wait couple of days, I'd like to finish something else before publishing v0.15.4 )

**Comment by chrisveness** [comment]
Andrey, that's fantastic!

I take it I've done the correct thing to test from master - since I don't require mysql2 directly, I've done this:

    $ rm -r node_modules/mysql-co/node_modules/mysql2/
    $ npm install git+https://git@github.com/sidorares/node-mysql2

Having done that, all my tests work perfectly.

I'll happily retest before you release v0.15.4.

**Comment by sidorares** [comment]
great, I'll try to publish today ( and bump in mysql-co as well )

**Comment by sidorares** [comment]
published as mysql2@0.15.4 and mysql-co@0.0.3

**Comment by chrisveness** [comment]
That works perfectly, thanks for the fast response.

**Comment by sidorares** [comment]
is there any specific reason why you are not using connections pool in the first place?

**Comment by chrisveness** [comment]
Good question! For what I’m doing, I wasn’t really sure of the benefits, and couldn’t get a quick trial working – but I’m new to Node, and still learning...

Digging deeper (using ApacheBench), I realise that concurrency soon hits a problem with simple connections, so I was going down the wrong path, after all.

Could you re-work my original mini Koa app above to use a connection pool, so I can see how it should be done?

Thanks!

**Comment by chrisveness** [comment]
FWIW, this is what I tried for connection pooling:

````javascript
var koa   = require('koa');
var mysql = require('mysql-co');

var app = koa();

var opt = { host: 'localhost', database: 'test', user: 'test', password: 'test' };
var pool = mysql.createPool(opt);

app.use(function* mysqlConnection(next) {
    this.db = yield pool.getConnection();
    yield next;
    this.db.release();
});

app.use(function* query(next) {
    var result = yield this.db.query('show processlist');
    console.log(result[0]);
});

app.listen(3000);
````

... which works for one call but hangs at the second `this.db.query()`...

What am I missing?

**Comment by sidorares** [comment]
there was a bug in mysql-co, see https://github.com/sidorares/mysql-co/commit/9f9b38b7810e1f3eda07bcb0c6378e66838e24af (change in mysql-co@0.0.4)

your code looks ok to me :)

**Comment by chrisveness** [comment]
Fantastic! Everything's working a treat now.
