### ISSUE TITLE
JSON type not recognized on AWS RDS 5.7.12

### ISSUE THREAD

**Issue by newza-fullmetal** [sidorares/node-mysql2#1630]
Hello 

I am currently trying to migrate from mysql to mysql2 on a nodejs project. 

I am facing an issue with the JSON columns. On my local environment (mysql 5.7.24), JSON columns are well recognized because I get back a JS Object on a SELECT query. 

But on my cloud environment on AWS it is still a String I have to parse. 
Could it be a problem of MySQL version, or something with AWS RDS. 

Thanks for your help

**Comment by sidorares** [comment]
can you post what is the fields array returned in the local/non local scenarios? ( e.i `const [rows, fields] = await conn.query(...)` or callback equivalent )

String vs JSON.parse return value is decided based on the column type: https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/parsers/text_parser.js#L59-L63
