### ISSUE TITLE
behavior of connection.end() on closed connection differs from mysqljs/mysql.

### ISSUE THREAD

**Issue by Andrew-Opplaud** [sidorares/node-mysql2#1638]
In mysqljs/mysql, calling:
```
connection.end();
connection.end( err => { if ( err ) console.info( err.message ); } );
```
results in:
```
Cannot enqueue Quit after invoking quit
```
In mysql2, the second call to `end()` doesn't invokes the callback.

After dropping in mysql2 to replace mysql, this was detected by a unit test expecting a call to `end()` on a closed connection to result in an error.

**Comment by sidorares** [comment]
do you have some time to debug this @Andrew-Opplaud ?
I'd expect end callback to be called with `Error('Cannot enqueue Quit after invoking quit')` argument passed to it

https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/connection.js#L865

https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/connection.js#L158

**Comment by sidorares** [comment]
do you want to try to debug this issue yourself @Andrew-Opplaud ?
I'd expect second line in your example to invoke callback as well

https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/connection.js#L865

https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/connection.js#L158

https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/commands/quit.js#L10

**Comment by sidorares** [comment]
Actually I think I know what problem is

`done` needs to be renamed to 'onResult`
https://github.com/sidorares/node-mysql2/blob/d065991c88c98aa028420147f7b005ebd76f5449/lib/commands/quit.js#L10
