### ISSUE TITLE
ES6 tagged template strings useful for prepared statements

### ISSUE THREAD

**Issue by krnlde** [sidorares/node-mysql2#165]
Hey Andrey,
I'm currently playing around with ES6 a lot and found the [template strings](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/template_strings#Tagged_template_strings) pretty useful for prepared statements. Here's the tag function:

```js
export function query(queryParts, ...params) {
  return new Promise(function (resolve, reject) {
    connection.query(queryParts.join('?'), params, function (error, rows) {
      if (error) return reject(error);
      resolve(rows);
    })
  });
}
```

and here's how you (can) use it:

```js
query`SELECT * FROM users WHERE users.username = ${"admin"}`
  .then((rows) => console.log(rows))
  .catch(console.error);
```

I just wanted to throw this one in, it's not an issue really.

Greetings

**Comment by krnlde** [comment]
Close because it's no issue.

**Comment by sidorares** [comment]
might be useful, but belongs to wrapper user code. Also this library still works with very old node versions ( possibly even 0.6 )

**Comment by krnlde** [comment]
Yes sure it is bleeding edge.
If your streaming API worked the same as in felixge/node-mysql the above code could be improved with lazy iteration via generators:

```js
export function query(queryParts, ...params) {
  const query = connection.query(queryParts.join('?'), params);

  return new Promise(function (resolve, reject) {
    const stream = query.stream();

    function* lazyIterator() {
      let chunk;
      while (null !== (chunk = stream.read())) {
        yield chunk;
      }
    }

    stream
      .on('error', reject)
      .on('readable', () => {
        resolve(lazyIterator(), query);
      });
  });
}
```

You could then do even cooler stuff:

```js
query`SELECT * FROM users`
  .then(function (stream) {
    let take = 5;
    for (let row of stream) {
      if (!take--) break;
      console.log(row);
    }
  })
  .catch(console.error);
```

Despite it makes no sense to first grab all users and then take only 5, because it's a lazy iterator that uses streaming, only 5 users will be transferred in the end.

Just some future stuff*, or my 2 cents.

*possible in iojs already, only without the "export" keyword and rest parameters

**Comment by sidorares** [comment]
Streaming api should be identical to node-mysql, If not it needs to be fixed. What incompatibilities you see?

**Comment by krnlde** [comment]
Yes it's not working at all. Did you try it? `query(/*...*/).stream` is undefined. Latest version.

**Comment by sidorares** [comment]
row streaming should be fixed in v0.15.5

**Comment by krnlde** [comment]
Nice, I'll try it in the evening :)

**Comment by krnlde** [comment]
Smooth. Works great.
