### ISSUE TITLE
How to correctly define the return type of a .query

### ISSUE THREAD

**Issue by kaykhan** [sidorares/node-mysql2#1657]
Im trying to set the return type of a .query and getting that to work with a test. I have a problem here 

**auth.repo.ts**

> Compilation error in /auth/auth.service.ts
> [ERROR] 11:11:16 ⨯ Unable to compile TypeScript:
> src/api/auth/auth.service.ts(119,55): error TS2344: Type 'IFindUserWithAuthResponse[]' does not satisfy the constraint 'RowDataPacket[] | RowDataPacket[][] | OkPacket | OkPacket[] | ResultSetHeader'.
>   Type 'IFindUserWithAuthResponse[]' is not assignable to type 'RowDataPacket[]'.
>     Type 'IFindUserWithAuthResponse' is not assignable to type 'RowDataPacket'.
>       Types of property 'constructor' are incompatible.
>         Type '{ name: "RowDataPacket"; } | undefined' is not assignable to type '{ name: "RowDataPacket"; }'.
>           Type 'undefined' is not assignable to type '{ name: "RowDataPacket"; }'.

```
interface IFindUserWithAuthResponse extends Partial<RowDataPacket> {
    id: string;
    authentication_id: string;
    dtype: string;
    session: string;
}

export const FindUserWithAuth = async (auth_id: string) => {
    const query = `        
        SELECT u.*, a.id as authentication_id, a.dtype, a.session
        FROM user u
        JOIN authentication a on u.id = a.user_id
        WHERE a.id = ?
        AND a.deleted_at IS NULL
    `;

    const q = MySQLPreparedStatement(query, [auth_id]);
    try {
        const [rows, field] = await MySQLMaster.query<IFindUserWithAuthResponse[]>(q);
        return [rows, null] as const;
    } catch (err) {
        Logger.error({ method: "FindUserWithAuth", error: err, stack_trace: err.stack });
        return [null, err] as const;
    }
};
```

**auth.test.ts**

> 1. Type '{ id: string; authentication_id: string; dtype: string; session: string; }' is not assignable to type 'IFindUserWithAuthResponse'.
>      The types of 'constructor.name' are incompatible between these types.
>        Type 'string' is not assignable to type '"RowDataPacket"'.

```
 const mockFindUserWithAuthData: Awaited<ReturnType<typeof FindUserWithAuth>> = [
            [
                {
                    id: "123",
                    authentication_id: "123",
                    dtype: "checkpoint_login",
                    session: "123",
                },
            ],
            null,
        ];

        const mockFindUserWithAuth = jest.mocked(FindUserWithAuth);

        mockFindUserWithAuth.mockResolvedValueOnce(mockFindUserWithAuthData);
```

**Comment by wellwelwel** [comment]
@kaykhan, it was a little difficult to fill the missing pieces of your code.

I tried to fill your example until it works.
> I know it has been a long time, but please feel free to ask and also complement any part of your example that I missed 🙋🏻‍♂️

---

#### I will explain the type changes directly on code (by commenting):

- `auth.repo.ts`
```ts
import mysql, { RowDataPacket } from 'mysql2/promise';
import jest from 'jest-mock';

const MySQLMaster = await mysql.createConnection({});

/** You need to define an usable Interface */
interface IFindUserWithAuthResponse {
   id: string;
   authentication_id: string;
   dtype: string;
   session: string;
}

/** Now you can extending the RowDataPacket */
interface IFindUserWithAuthResponseQueryable extends IFindUserWithAuthResponse, RowDataPacket {}

/** Creating a type for returned Users */
export type Users = readonly [IFindUserWithAuthResponse[], null];

/** Defining the expected type returned from `FindUserWithAuth` */
export const FindUserWithAuth = async (auth_id: string): Promise<Users> => {
   const query = `        
       SELECT u.*, a.id as authentication_id, a.dtype, a.session
       FROM user u
       JOIN authentication a on u.id = a.user_id
       WHERE a.id = ?
       AND a.deleted_at IS NULL
   `;

   /** Using the Interface that extends the RowDataPacket */
   const [rows] = await MySQLMaster.query<IFindUserWithAuthResponseQueryable[]>(query, [auth_id]);

   /** Just testing the types of `rows` */
   console.log(rows[0].authentication_id);

   return [rows, null] as const;
};
```

- `auth.test.ts`
```ts
import { Users, FindUserWithAuth } from './auth.repo.js';

/** Changing type for the expected `FindUserWithAuth` return */
const mockFindUserWithAuthData: Users = [
   [
      {
         id: '123',
         authentication_id: '123',
         dtype: 'checkpoint_login',
         session: '123',
      },
   ],
   null,
];

const mockFindUserWithAuth = jest.mocked(FindUserWithAuth);

mockFindUserWithAuth.mockResolvedValueOnce(mockFindUserWithAuthData);
```

**Comment by wellwelwel** [comment]
You can follow these examples to see how to extend the `RowDataPacket`:

- [Extending and using **Interfaces** with `RowDataPacket`](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/row-data-packet.ts)
- [Extending and using **Interfaces** with `RowDataPacket` and `rowAsArray`](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/row-data-packet-row-as-array.ts)
- [Extending and using **Interfaces** with `RowDataPacket` and `multipleStatements`](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/row-data-packet-multi-statements.ts)
- [Extending and using **Interfaces** with `RowDataPacket`, `rowAsArray` and `multipleStatements`](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/examples/typescript/row-data-packet-row-as-array-multi-statements.ts)

Also, you can follow the **Type Specification** in [documentation/en/TypeScript-Examples.md#type-specification](https://github.com/sidorares/node-mysql2/blob/master/documentation/en/TypeScript-Examples.md#type-specification)

---

I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️
