### ISSUE TITLE
Too Many Connections | nodejs + Apollo GrpahQL 

### ISSUE THREAD

**Issue by yodarango** [sidorares/node-mysql2#1658]
I have the following code in my connection file: 

```js
const mysql = require('mysql2');

// connection pool
const connection = mysql.createPool({
   connectionLimit: 150,
   host: process.env.MYSQL_VPS_IP,
   user: process.env.MYSQL_DB_USER,
   password: process.env.MYSQL_DB_PASSWORD,
   database: process.env.MYSQL_DATABASE,
   // acquireTimeout: 600000, //'waitForConnections' determines the pool's action when no connections are
   // free. If true, the request will queued and a connection will be presented
   // when ready. If false, the pool will call back with an error.
   connectTimeout: 300000, // 'connectTimeout' is the maximum number of milliseconds before a timeout occurs during the initial connection to the database.
   queueLimit: 0, // unlimited
   port: 3306,
   charset: 'utf8mb4',
});

module.exports = connection;
```

 2. then I pass the  connection in my context like this: 

```js
const connPromise = connection.promise();

   const apolloServer = new ApolloServer({
      schema,
      csrfPrevention: true, 
      context: async () => {
         return {
            db: connPromise,
         };
      },
   });
```

3. Then on my resolvers I access the pool promise as follows: 

```js
const resolver = async =(parent, args, ctx) =>
ctx.db.query(
         `
            SELECT ...
            FROM ...
            WHERE ....
            LIMIT ...
               `,
         [...args]
      );
```

But I am getting a "too many connections" error. What am I doing wrong?

thank you!

**Comment by sidorares** [comment]
the usual suspect for "too many connections" error is a pool connection that is never released, but you are using `poolConnection.query()` which internally does "get from the pool" + query + "return to the pool" so that should be ok.

Is there any possibility that you actually have a lot of connections? How many server instances do you have? If only one you should never see more that 150 open connections to the server, but if more than one that number is `* number of servers`

**Comment by yodarango** [comment]
Thank you for your response, @sidorares! 
I only have 1 instance. I checked the proceslist in my db for connections and I had a total of 149 asleep and one open, is that normal? I dont know if I ever seen so many. By the way, i want to say this is happening on my Staging server, so i am sure the only connection should be mine? 

Is there another way I can try with mysql2, even if it is not the automated pool function? 

Thank you again!

**Comment by sidorares** [comment]
> Is there another way I can try with mysql2, even if it is not the automated pool function?

try to replace `ctx.db.query` with manual get / query / release:

```js
const resolver = async =(parent, args, ctx) => {
   const connection = await ctx.db.getConnection();
   try {
       const result = await connection.query(
         `
            SELECT ...
            FROM ...
            WHERE ....
            LIMIT ...
               `,
         [...args]
      );
      connection.release();
   } catch(err) {
      connection.release();
   } 
}
```

and maybe add some logging to see if its actually released

**Comment by yodarango** [comment]
Thank you, this is what I was looking for!

**Comment by sidorares** [comment]
@yodarango did you find what was the root cause? In theory your code is identical to my example

**Comment by yodarango** [comment]
@sidorares I just had a chance to look at the problem again (it seems like the proposed solution above did not get rid of the problem.) What part of the log would let me know if the connection was actually released? 
Thank you again!

**Comment by sidorares** [comment]
> What part of the log would let me know if the connection was actually released?

logging just before `connection.release();`
