### ISSUE TITLE
Error: connect ETIMEDOUT - win32 | Node.js 16.17.1

### ISSUE THREAD

**Issue by mado-bohsali** [sidorares/node-mysql2#1676]
Error: connect ETIMEDOUT
    at Connection._handleTimeoutError (c:\Users\me216\Desktop\node_js_gain_mhi\node_modules\mysql2\lib\connection.js:189:17)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

`const pwd = process.platform === "win32" ? __dirname + '\\ca-certificate.crt' : __dirname + '/ca-certificate.crt';`

I have used the above ternary operator so that I make sure it differentiates between file systems

**Comment by barkermn01** [comment]
Just quickly why this?
```js
const pwd = process.platform === "win32" ? __dirname + '\\ca-certificate.crt' : __dirname + '/ca-certificate.crt';
```

You should use 
```
const path = require('path')
path.sep
```

But as for Timeout a lot of things can cause it, could I double check have you confirmed it's just a network problem by using a MySQL or MariaDB CLI client? or MySQL Workbench?

**Comment by mado-bohsali** [comment]
I confirm it's a firewall problem on my machine.

**Comment by sidorares** [comment]
> Just quickly why this?

you are right, happy to see a PR with this improvement :)
