### ISSUE TITLE
Include errno in error object

### ISSUE THREAD

**Issue by tgriesser** [sidorares/node-mysql2#168]
Just noticed that the `errno` isn't included on the error object as it is in [node-mysql](https://github.com/felixge/node-mysql/commit/8ee7d104247d0ee1cb5e16b2e744141fdd35a949#diff-4fbc1e330878693a9c58d3fafa3af6e4) 

Do you have any reservations on adding it?

**Comment by sidorares** [comment]
no, happy to add myself or accept pr
