### ISSUE TITLE
connection string parsing is invalid

### ISSUE THREAD

**Issue by rafipiccolo** [sidorares/node-mysql2#1704]
[  static parseUrl(url) {](https://github.com/sidorares/node-mysql2/blob/06a94feb4a2f3f5134178e58111c93ffa4eae0b5/lib/connection_config.js#L251)

To parse the connection string, we use "new Url(xxx)" but it looks like it urlencodes the parameters : Hence invalidating them when there are special chars.

imagine the password is xx^xx

the connection string can be :
mysql://root:xx^xx@xx.com/xx?charset=utf8mb4
or 
mysql://root:xx%5Exx@xx.com/xx?charset=utf8mb4
both usually work in other libs.

it's worth noting that "new Url()" returns in both cases "password: xx%5Exx"
then ofc the connection cant be established because the password is wrong.

Since we use new Url, we should pass the "password" through decodeURIComponent to get it correctly.

IMHO valid parser would be :
```
const options = {
      host: parsedUrl.hostname,
      port: parsedUrl.port,
      database: parsedUrl.pathname.slice(1),
      user: parsedUrl.username,
      password: decodeURIComponent(parsedUrl.password)
};
```

**Comment by sidorares** [comment]
see #1621 
feel free to reopen if you think this is a separate issue
