### ISSUE TITLE
move mocha and chai to devDependencies, update lru-cache in named-placeholders to allow deduplication

### ISSUE THREAD

**Issue by sidorares** [sidorares/node-mysql2#1711]

**Comment by falkenhawk** [comment]
I've also noticed it while testing `3.0.0-rc.1` :)
mysql2 brings in mocha with all its sub-dependencies. btw this was introduced in #1606

**Comment by MasterOdin** [comment]
The PR title isn't quite right I think, where it's `named-placeholders` that needs to be updated with regards to `lru-cache`, not `sqlstring`:

```
$ npm ls lru-cache
mysql2@3.0.0-rc.1 /Users/mpeveler/code/github/node-mysql2
├─┬ @typescript-eslint/eslint-plugin@5.48.0
│ └─┬ semver@7.3.8
│   └── lru-cache@6.0.0
├── lru-cache@7.14.1
└─┬ named-placeholders@1.1.2
  └── lru-cache@4.1.5
```

**Comment by sidorares** [comment]
@MasterOdin you are right, I meant "update lru-cache sub dependency in named-placeholders to be the same version as mysql2 uses (or a range that allows deduplication)"

**Comment by sidorares** [comment]
https://github.com/mysqljs/named-placeholders/pull/19 fixes lru-cache dedupe issue
