### ISSUE TITLE
Typing error in v3.0.0-rc1 Interface 'PoolConnection' cannot simultaneously extend types 'PoolConnection' and 'Connection'

### ISSUE THREAD

**Issue by abentpole** [sidorares/node-mysql2#1722]
Hello, I was giving v3.0.0-rc1 a spin and noticed the following issue:
```
node_modules/mysql2/index.d.ts:86:18 - error TS2320: Interface 'PoolConnection' cannot simultaneously extend types 'PoolConnection' and 'Connection'.
  Named property 'execute' of types 'PoolConnection' and 'Connection' are not identical.

86 export interface PoolConnection extends mysql.PoolConnection, Connection {
                    ~~~~~~~~~~~~~~
```

This was noticed with Typescript version 4.5.5, though I also just tested with 4.9.3 and confirmed it occurs there too.
**Edit:** A note that for this to come up when the library is in use; ensure `skipLibCheck` isn't `true`.

**Comment by sidorares** [comment]
could you post a snippet of typescript code to reproduce the error @abentpole ?

**Comment by abentpole** [comment]
@sidorares Just a matter of importing the promise version of the library in a Typescript project with `"skipLibCheck": false`.

So to replicate it:
1. `npm init`
2. `npm i mysql2@3.0.0-rc.1 typescript`
3. `npx tsc --init`
4. Open `tsconfig.json`, go to the bottom and set "skipLibCheck" to `false`
5. Make a file, `index.ts`, with the content `import * as mysql from 'mysql2/promise';`
6. `npx tsc` and observe the error

**Comment by CComparon** [comment]
Same problem happening to me. Both with `typescript": "4.7.4"` and `typescript": "4.9.4"`.

**Comment by HofmannZ** [comment]
Same issue with version `3.0.1`.

**Comment by rohan-qp** [comment]
Same issue with typescript version `4.9.4`. For now, the only way I found to get it running was by setting `skipLibCheck: true` in `tsconfig`.

**Comment by khanfx** [comment]
So for a concrete example -

When faced with this error:

```
node_modules/mysql2/index.d.ts:86:18 - error TS2320: Interface 'PoolConnection' cannot simultaneously extend types 'PoolConnection' and 'Connection'.
  Named property 'unprepare' of types 'PoolConnection' and 'Connection' are not identical.

86 export interface PoolConnection extends mysql.PoolConnection, Connection {
                    ~~~~~~~~~~~~~~
```

The items indicated are:

From `mysql2\index.d.ts`:

```ts
  unprepare(sql: string): mysql.PrepareStatementInfo;
```

From `mysql2\typings\mysql\lib\Connection.d.ts`:

```ts
    unprepare(sql: string): any;
```

Experimented a little but unsure how to progress.

This seems to be the item over in Typescript that would make this work as specced, but clearly not being built any time soon:

https://github.com/microsoft/TypeScript/issues/16936

**Comment by eschneor** [comment]
Get this issue, too, when trying to update from `"mysql2": "2.3.3"` to `"mysql2": "3.1.2"`, using `"typescript": "4.9.5"`.

Is there an ETA to get this in place? Thanks!

**Comment by oilop9000** [comment]
Same problem here!

**Comment by HofmannZ** [comment]
I don't think @sidorares is going to fix this. See #1792.

**Comment by sidorares** [comment]
I really want to fix, just don't have enough time. If anyone wants to help that would be great

**Comment by eschneor** [comment]
So, for now the solution is to stick with an old version? (before `v3.0.0`)

**Comment by sidorares** [comment]
> So, for now the solution is to stick with an old version? (before v3.0.0)

- stay on pre v3
- `"skipLibCheck": true,`
- have your own local types that fix the errors
- submit a PR to fix on mysql2 side, wait it to be reviewed / merged / released

**Comment by wellwelwel** [comment]
Once the [`PoolConnection.d.ts`](https://github.com/sidorares/node-mysql2/blob/master/typings/mysql/lib/PoolConnection.d.ts#L4) has already declared extending the `Connection`:

```ts
declare class PoolConnection extends Connection {
    connection: Connection;
    release(): void;
}
```

Then it doesn't need to re extends the Connection type in [`index.d.ts` `#86`](https://github.com/sidorares/node-mysql2/blob/master/index.d.ts#L86) like:
```ts
export interface PoolConnection extends mysql.PoolConnection, Connection {
  promise(promiseImpl?: PromiseConstructor): PromisePoolConnection;
}
```

So, just by removing the `Connection` from extends in [`index.d.ts`](https://github.com/sidorares/node-mysql2/blob/master/index.d.ts#L86), it will work:
```ts
export interface PoolConnection extends mysql.PoolConnection {
  promise(promiseImpl?: PromiseConstructor): PromisePoolConnection;
}
```

I cloned the `3.2.0` release and tested it in a real use, it works perfectly.

@sidorares, can I create a `PR` for a change that is too small?

**Comment by wellwelwel** [comment]
> > So, for now the solution is to stick with an old version? (before v3.0.0)
> 
> 
> 
> - stay on pre v3
> 
> - `"skipLibCheck": true,`
> 
> - have your own local types that fix the errors
> 
> - submit a PR to fix on mysql2 side, wait it to be reviewed / merged / released

@sidorares Did you give up on that? 😕

**Comment by sidorares** [comment]
@wellwelwel should be in npm as v3.2.1 in a minute

**Comment by sidorares** [comment]
@abentpole give v3.2.1 a try and if the issue is fixed we can close it

**Comment by HofmannZ** [comment]
Does not seem to fix it:

```
> tsc -p .

node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index.d.ts:10:18 - error TS2430: Interface 'import("/Users/zinohofmann/Projects/github.com/expatfile/firestore-service/node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index").Connection' incorrectly extends interface 'import("/Users/zinohofmann/Projects/github.com/expatfile/firestore-service/node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/typings/mysql/index").Connection'.
  The types returned by 'promise(...)' are incompatible between these types.
    Type 'Connection' is missing the following properties from type 'Promise<Connection>': then, catch, finally, [Symbol.toStringTag]

10 export interface Connection extends mysql.Connection {
                    ~~~~~~~~~~

node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index.d.ts:86:18 - error TS2430: Interface 'import("/Users/zinohofmann/Projects/github.com/expatfile/firestore-service/node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index").PoolConnection' incorrectly extends interface 'import("/Users/zinohofmann/Projects/github.com/expatfile/firestore-service/node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/typings/mysql/index").PoolConnection'.
  The types returned by 'promise(...)' are incompatible between these types.
    Type 'PoolConnection' is missing the following properties from type 'Promise<Connection>': then, catch, finally, [Symbol.toStringTag]

86 export interface PoolConnection extends mysql.PoolConnection {
                    ~~~~~~~~~~~~~~

node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index.d.ts:90:18 - error TS2430: Interface 'Pool' incorrectly extends interface 'Connection'.
  The types returned by 'promise(...)' are incompatible between these types.
    Type 'Pool' is missing the following properties from type 'Promise<Connection>': then, catch, finally, [Symbol.toStringTag]

90 export interface Pool extends mysql.Connection {
                    ~~~~


Found 3 errors in the same file, starting at: node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index.d.ts:10

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by wellwelwel** [comment]
> Does not seem to fix it:
> 
> 
> 
> ```
> 
> > tsc -p .
> 
> 
> 
> node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index.d.ts:10:18 - error TS2430: Interface 'import("/Users/zinohofmann/Projects/github.com/expatfile/firestore-service/node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index").Connection' incorrectly extends interface 'import("/Users/zinohofmann/Projects/github.com/expatfile/firestore-service/node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/typings/mysql/index").Connection'.
> 
>   The types returned by 'promise(...)' are incompatible between these types.
> 
>     Type 'Connection' is missing the following properties from type 'Promise<Connection>': then, catch, finally, [Symbol.toStringTag]
> 
> 
> 
> 10 export interface Connection extends mysql.Connection {
> 
>                     ~~~~~~~~~~
> 
> 
> 
> node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index.d.ts:86:18 - error TS2430: Interface 'import("/Users/zinohofmann/Projects/github.com/expatfile/firestore-service/node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index").PoolConnection' incorrectly extends interface 'import("/Users/zinohofmann/Projects/github.com/expatfile/firestore-service/node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/typings/mysql/index").PoolConnection'.
> 
>   The types returned by 'promise(...)' are incompatible between these types.
> 
>     Type 'PoolConnection' is missing the following properties from type 'Promise<Connection>': then, catch, finally, [Symbol.toStringTag]
> 
> 
> 
> 86 export interface PoolConnection extends mysql.PoolConnection {
> 
>                     ~~~~~~~~~~~~~~
> 
> 
> 
> node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index.d.ts:90:18 - error TS2430: Interface 'Pool' incorrectly extends interface 'Connection'.
> 
>   The types returned by 'promise(...)' are incompatible between these types.
> 
>     Type 'Pool' is missing the following properties from type 'Promise<Connection>': then, catch, finally, [Symbol.toStringTag]
> 
> 
> 
> 90 export interface Pool extends mysql.Connection {
> 
>                     ~~~~
> 
> 
> 
> 
> 
> Found 3 errors in the same file, starting at: node_modules/.pnpm/mysql2@3.2.1/node_modules/mysql2/index.d.ts:10
> 
> 
> 
>  ELIFECYCLE  Command failed with exit code 1.
> 
> ```

@HofmannZ Can you share your `tsconfig`?

**Comment by wellwelwel** [comment]
@HofmannZ, @sidorares  and @bluefeet 

I see it now, in this release (3.2.1), @sidorares merged two `PR`, in one (#1949), it changes the structure for `Connection` interface adding:

```ts
promise(): Promise<Connection>;
```

To test, try to delete thi line `294` in [Connection.d.ts](https://github.com/sidorares/node-mysql2/blob/master/typings/mysql/lib/Connection.d.ts#L294) and it will work perfectly.

Unfortunately, the change in this `PR` turn the `Conection` interface incompatible with 3 different types in lines `10`, `86` and `90` from [index.d.ts](https://github.com/sidorares/node-mysql2/blob/master/index.d.ts).

**Comment by wellwelwel** [comment]
@HofmannZ 

This error is not a part of this issue. I suggest you to look at the issue #1936.
Anyway, I submited a `PR` to fix this too in #1955.

**Comment by wellwelwel** [comment]
@HofmannZ, @abentpole, can you try now in `3.2.2` release?

**Comment by abentpole** [comment]
Sorry @sidorares, I missed your first ping. Gave this a test and can confirm it doesn't happen in `v3.3.1`.

Thanks!
