### ISSUE TITLE
Compress not working

### ISSUE THREAD

**Issue by asafyish** [sidorares/node-mysql2#173]
Hi,

Just noticed that compress is no longer available since commit https://github.com/sidorares/node-mysql2/commit/b715a5fd577bc4fba9dfffbe5846bc81e3d6fb7e. Is that on purpose ?
Even after locally patching the code to use compress, querying just hangs.

**Comment by sidorares** [comment]
No, not on purpose. I'm keen to support it but it seems to be very rarely used (and there is no tests currently unfortunately)

**Comment by asafyish** [comment]
Yeah I guess it's complicated to test compression...What can be tested ?

We are reading large chunks from the database, a few gigs each time, I think compression can be very useful for that use case, because most of the time is spent on waiting for the network.

**Comment by sidorares** [comment]
It could be tested end to end if ci server can be configured to support compression, also we could add compression support to a server side of protocol and test mocked server.

**Comment by mantisjazz** [comment]
+1 to get compression working

Or at least remove it as a feature from the README

**Comment by rickyk586** [comment]
+1 to get compression working

Or at least remove it from the README as a listed feature

**Comment by sidorares** [comment]
thanks, I'll try to restore it by next release. You can track progress in https://github.com/sidorares/node-mysql2/tree/compression-fixes branch

**Comment by sidorares** [comment]
hi @rickyk586  I have completely rewrote compressed protocol, all tests now run twice, secont time with compression enabled. Changes are in master and I'll publish soon with next release

**Comment by sidorares** [comment]
@asafyish 
> We are reading large chunks from the database, a few gigs each time, I think compression can be very useful for that use case, because most of the time is spent on waiting for the network.

might save time if network has low throughput. On local DB all my benchmarks show slow down when compression is enabled. Network latency does not matter, mysql protocol is sequential ( or half duplex ) - client has to wait response from each command before sending next one, and that is the same with and without compression
