### ISSUE TITLE
Use of namedPlaceholders config option causes dependency conflict in built Nuxt 3 app

### ISSUE THREAD

**Issue by dmeehan1968** [sidorares/node-mysql2#1731]
I've been using Nuxt 3 to implement a server api (REST) with mysql2 as the DB driver.  This was working fine when in development mode, but when the Nuxt app is built (`npx nuxt build`) and previewed (`npm nuxt preview`), the use of named placeholders in a query will cause an exception, reporting that LRUCache requires the use of `new`.

This stems from the `named-placeholders` dependency, which `require`s the LRUCache package, then treats the default export as a function when in later versions of LRUCache its a constructor.

Nuxt has a dependency on LRUCache 6, whereas named-placeholders has a dependency on 4.1.5.

It seems odd that the conflict only occurs in the built version, and was working ok in nuxt development mode (`npx nuxt dev`).

`named-placeholders` hasn't been updated in 4+ years and issues appear to go unacknowledged so maybe its been abandoned.

**Comment by sidorares** [comment]
> named-placeholders hasn't been updated in 4+ years and issues appear to go unacknowledged so maybe its been abandoned.

I'm original author, happy to give the package some refresh, but encourage you to contribute as well ( migrate CI to github actions, enable dependabot action, add release-please etc )

**Comment by sidorares** [comment]
@dmeehan1968 v3.0.0 is released and now uses lru-cache 7.14.1 in its direct dependency and via named-placeholders, see https://github.com/mysqljs/named-placeholders/pull/19
