### ISSUE TITLE
Can't create more than max_prepared_stmt_count statements

### ISSUE THREAD

**Issue by lyg4795** [sidorares/node-mysql2#1745]
when I execute sql by pool.execute(sql,[..]) many times, it will raise the error.
The sql like following:
```
    let ts = Math.floor(moment.now() / 1000)
    let sql = 'select * from ipinuse where ip=? and ts>?'
    let [rows, field] = await pooldev.execute(sql, [ip, ts - 3700])
```
If I dont want to change execute to query, how cant I fix this problem? is pool has the unprepare function?

**Comment by sidorares** [comment]
hm, this is quite strange, the most common cause for this is incorrect use of parameters ( interpolating client side and then passing result to execute ) but your code looks ok to me

One theory we could check:
statements are scoped (and reused) per connection
If it takes `.execute()` a lot of time to respond and you call your code frequently enough you'll end up creating new connections and new statements in that connection

What's `connectionLimit` in your pool config? Can you set it to 1 and see if the problem persists? Also what is your server `max_prepared_stmt_count` value?

**Comment by sidorares** [comment]
@lyg4795 closing this for now, I believe you issue is described by my last comment ( a spike in the number of open connections in the pool, each having its own prepare ).
