### ISSUE TITLE
Named placeholders for field & tables

### ISSUE THREAD

**Issue by akayami** [sidorares/node-mysql2#176]
Hi, 

I like a lot the feature of named placeholders but it I have not found a way to make it work with field names or table names. Would it be difficult to extend your syntax to support that ? 

I propose the following: 
```
conn.execute('SELECT * FROM ::table WHERE id=:id', {table: 'sometable', id: 1}, ...);
```
to be converted to:
```
conn.query('SELECT * FROM ?? WHERE id=?, ['sometable', 1],...);
```

**Comment by sidorares** [comment]
I adopted parser from https://github.com/mscdex/node-mariasql so at the moment syntax is the same as originally there. I don't mind extending it as per your suggestion, should be relatively easy
