### ISSUE TITLE
Property 'releaseConnection' does not exist on type 'Pool'.

### ISSUE THREAD

**Issue by amirhossein-karimi** [sidorares/node-mysql2#1761]
Hi,

I use the connection pool and according to the documentation, when I release it (connection), I face the following problem .
`Property 'releaseConnection' does not exist on type 'Pool'.`

notes : i used typescript

and this is my code
`pool.getConnection(function (err, conn) {
    // Do something with the connection
    conn.query("CREATE DATABASE IF NOT EXISTS zxc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;", (err, rows, fields) => {
        if (err) throw err;
    });
    pool.releaseConnection(conn);
})`

**Comment by jake-knerr** [comment]
I am having the same problem. I am using `conn.release()` instead.

**Comment by JiaJiaJiang** [comment]
The doc [here](https://github.com/sidorares/node-mysql2#using-connection-pools) is wrong, please fix it.
The correct one is `pool.release`, not `pool.releaseConnection`

**Comment by wellwelwel** [comment]
@JiaJiaJiang, the documentation is correct.

The `releaseConnection` is used as a method from the `pool`, like:

```js
pool.getConnection((err, conn) => {
  pool.releaseConnection(conn);
});
```

The `release` is used as a method of the connection from `pool`, like:
```js
pool.getConnection((err, conn) => {
  conn.release();
});
```

<hr />

In fact, the type `releaseConnection` is missing in `Pool`.

**Comment by wellwelwel** [comment]
@amirhossein-karimi and @jake-knerr, can you check this in `^3.3.4` version?

**Comment by wellwelwel** [comment]
After version `^3.3.4`, you can follow this example for `releaseConnection`:
https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/test/tsc-build/mysql/createPool/callbacks/releaseConnection.ts#L4-L8

And for `release`:
https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/test/tsc-build/mysql/createPool/callbacks/release.ts#L4-L7

---

I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️
