### ISSUE TITLE
support for on('enqueue')

### ISSUE THREAD

**Issue by cheshirecatalyst** [sidorares/node-mysql2#177]
Is there any plan to add this event emitted by node-mysql when the pool is exhausted and request queued?

**Comment by sidorares** [comment]
yes, I'm trying to reuse pool code from node-mysql, but at the moment it's manual update. I'll try to pull current version

**Comment by cheshirecatalyst** [comment]
Thanks.

**Comment by sbisbee** [comment]
Hi @sidorares - Any update on this? This incompatibility burned me during some testing recently, so I wouldn't mind helping getting it in.

Does it need to be a full code pull from upstream or could we just emit the event when there are no free connections, we're willing to wait for a connection, and we haven't gone passed the queue limit? I believe here: https://github.com/sidorares/node-mysql2/blob/master/lib/pool.js#L65

Cheers
