### ISSUE TITLE
issue with search using array in process

### ISSUE THREAD

**Issue by ssubham** [sidorares/node-mysql2#1776]
Hi,
I am trying to use sql command 
SELECT * FROM 'tablename' WHERE name in (?);
In the place of ? passing an array with more than one value.

For a single element it is working well. But, with more than one value, it is giving empty result.

Please let me know how to resolve it.
If you want an example then the example is as below:

const values = ['value1', 'value2', 'value3'];

const sql = `SELECT * FROM table WHERE column IN (?)`;

connection.query(sql, [values], (error, results) => {
  if (error) throw error;
  console.log(results);
});

Hope to get it helped

**Comment by sidorares** [comment]
I believe client side parameters interpolation does something like `'(' + param.join(',') + ')'` if parameter is an array, so you might need to change your query to `SELECT * FROM table WHERE column IN ?` to avoid extra brackets

Note (not your case but fyi) that its a common mistake to use query like this with .execute - unlike .query execute needs exactly 1:1 mapping from `?` placeholder to a parameter value

**Comment by sidorares** [comment]
https://github.com/mysqljs/sqlstring/blob/cd528556b4b6bcf300c3db515026935dedf7cfa1/lib/SqlString.js#L60-L74

**Comment by ssubham** [comment]
Hi Sidorares,
The query process what I have passed is well writen.
If I try with one value then it works well and returns related data. But, If I give more than one value. Then, it gives empty data.

Though, I tried with your suggestions. But, it did not worked.

When, you will try with same query and values in sql executions. It is working well.

**Comment by ssubham** [comment]
Hi, Any updates with this point?

**Comment by ssubham** [comment]
Hi,
const allergystr = [ 'Soy', 'Garlic'];
const str = '(' + allergystr.join(',') + ')'
    console.log('str ', str)
    const sql = `SELECT sub_categories FROM TableName WHERE name IN ?`;
    
  Checking for console.log -- str goes as like this 
SELECT sub_categories FROM allergy_preferences WHERE name IN ? **(Soy,Garlic)**
Means, array is not as going as individual element string.

And getting this error -- **TypeError: Bind parameters must be array if namedPlaceholders parameter is not enabled**

**Comment by sidorares** [comment]
Make sure you pass the list as its own separate parameter, example:

```js
const mysql = require('mysql2');
console.log('SELECT sub_categories FROM allergy_preferences WHERE name IN ?',  [ ["Soy","Garlic"] ]));
```

prints `SELECT sub_categories FROM allergy_preferences WHERE name IN 'Soy', 'Garlic'`

note that in the parameters array there is just one item, which in turn is an array with two elements

**Comment by ssubham** [comment]
This also does not working.

The actual flow works with single element.
example -- const allergystr = [ 'Soy']
const sql = `SELECT sub_categories FROM ${this.allergyTableName} WHERE name IN (?)`;
It gives back result what are required.
result - [
  BinaryRow {
    sub_categories: 'Soya Milk, Soybean, Tofu, Soy Vanilla Yoghurt, Firm Tofu, Silken Tofu, Soy Sauce, Tamari Sauce, Plant-Based Yoghurt (unspecified), Edamame, Tempeh, Textured Vegetable Protein (soya), Liquid Aminos'
  }
]






But, when I am giving more than one element it is giving empty result. while they have responding data.
example -- const allergystr = [ 'Soy', 'Garlic']
const sql = `SELECT sub_categories FROM ${this.allergyTableName} WHERE name IN (?)`;
result = []
The query for array process only work from the above statement not other. But, for a single element not multiple elements.
That is the issue.

**Comment by ssubham** [comment]
But now got it working any how making a query string with out passing values.
Example :-
const allergystr = [ 'Soy', 'Garlic'];
const querystr = '("' + allergystr.join('","') + '")' 
const sql = `SELECT sub_categories FROM ${this.allergyTableName} WHERE name IN ${querystr}`;
let data = await query(sql);

It worked for me.  👍 

But, issue is multple element to work from last message commenting. Please look for it.

**Comment by sidorares** [comment]
Can you show full example?
I expect below to work, the `mysql.format()` call with the query and parameters generates same sql as you do manually

```js
const allergystr = [ 'Soy', 'Garlic'];
let data  = await connection.query(`SELECT sub_categories FROM ${this.allergyTableName} WHERE name IN (?)`, [allergystr]);
```
