### ISSUE TITLE
The eslint-config-prettier package should be moved to devDependencies

### ISSUE THREAD

**Issue by joakimbeng** [sidorares/node-mysql2#1783]
Great that some packages have moved to devDependencies in the new v3.0 release but there is one more that should be moved. It's the `eslint-config-prettier` package.

Currently when installing `mysql2` it complains that `eslint` is missing because it's a peerDependency of `eslint-config-prettier`.

**Comment by sidorares** [comment]
@joakimbeng https://github.com/sidorares/node-mysql2/releases/tag/v3.0.1

First release pushed automatically to npm by release-please
