### ISSUE TITLE
Enable SSL by default?

### ISSUE THREAD

**Issue by sidorares** [sidorares/node-mysql2#1788]
RFC: I'm thinking to set SSL to `{ rejectUnauthorized: true }` by default if not set in the input `createConnection()` options.
If you do NOT want client to switch to ssl ( advertise ssl capability via client flags ), you'd need to use `ssl: null` ( or `false` ?)

**Comment by sidorares** [comment]
Note: AWS and GCP have own server certs an you's still need to configure that ( we have pre  bundled set of AWS certs and currently you manually download and configure client and server certs for GCP ). PlanetScale should just work with slightly shorter connection url ( I believe their cert is derived from well known chain but need to research more here )

**Comment by testn** [comment]
One of the problems I noticed with TLS is that the overhead of TLS handshake is huge. If you open/close connections very often, it can overwhelm both databases and clients easily.

**Comment by sidorares** [comment]
Good point. If you are in the private network not worth the overhead
