### ISSUE TITLE
mysql2 2.3 with MySQL 8.0 fails excute query with parameters in LIMIT, eg.: SELECT ... LIMIT ?, ?

### ISSUE THREAD

**Issue by cesco69** [sidorares/node-mysql2#1789]
mysql2 2.3 with MySQL 8.0 fails when excuting query with parameters in LIMIT, eg.:

```ts
const pool = mysql.createPool({
    host: '...',
    port: '...',
    user: '...',
    password: '...',
    database: '...',
    multipleStatements: true,
    timezone: 'Z'
}).promise();

await pool.execute(`SELECT 1 LIMIT ?, ?`, [0, 1000]);
```

Error:

```
Error: Incorrect arguments to mysqld_stmt_execute
    at PromisePool.execute (D:\backend\node_modules\.pnpm\mysql2@2.3.3\node_modules\mysql2\promise.js:359:22)
```

**Comment by sidorares** [comment]
I believe the cause is the same as discussed in https://github.com/sidorares/node-mysql2/issues/1239

As a workaround, try to send `LIMIT` parameters as a string, e.i

```js
await pool.execute(`SELECT 1 LIMIT ?, ?`, ['0', '1000']);
```

The problem is from the server expecting an int type parameter and client sending it as a float ( because its a JS number value )

**Comment by cesco69** [comment]
ok, works with string!
