### ISSUE TITLE
Named arguments not replaced in .format

### ISSUE THREAD

**Issue by abellina** [sidorares/node-mysql2#179]
I was trying to use named parameters (which is a great great feature by the way), but I really like to print my SQL when I have complicated queries. Would it be possible to have .format print the SQL with the replaced values, kind of what it does for the regular prepared statement '?' placeholders?

Thank you

Alessandro

**Comment by sidorares** [comment]
Hi! It's possible now:

```js
onnection.query([
  'CREATE TEMPORARY TABLE `test_table` (',
  '`id` int(11) unsigned NOT NULL AUTO_INCREMENT,',
  '`num1` int(15),',
  '`num2` int(15),',
  'PRIMARY KEY (`id`)',
  ') ENGINE=InnoDB DEFAULT CHARSET=utf8'
].join('\n'));

connection.query('insert into test_table(num1,num2) values(?, 3)', [1]);
connection.query('insert into test_table(num1,num2) values(3-?, -10)', [5]);
connection.query('insert into test_table(num1,num2) values(4+?, 4000000-?)', [-5, 8000000]);
connection.query('insert into test_table(num1,num2) values(?, ?)', [-5, 8000000]);
connection.config.namedPlaceholders = true;
var qCmd = connection.query('SELECT * from test_table where num1 < :numParam and num2 > :lParam', {lParam: 100, numParam: 2}, function(err, rows, fields) {
  console.log(cqCmd.sql); // here
});
console.log(cqCmd.sql); // or here
```

However I just notices `namedPlaceholders` are not enabled if you set parameter during `createConnection(params)`, I'll fix it in next release

**Comment by sidorares** [comment]
the code that does conversion is here: https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L359

**Comment by abellina** [comment]
Any way the .format function could be given this functionality? Else you need to execute the query before you get the formatted output... If you have a long running query, you may be waiting for a while.

**Comment by sidorares** [comment]
Yes, I think this might be useful
