### ISSUE TITLE
erros with tsc

### ISSUE THREAD

**Issue by guidev** [sidorares/node-mysql2#1792]
after upgrading from `2.3.3` to `3.0.1`, if I run `tsc` I get the following error:

```
node_modules/mysql2/index.d.ts:86:18 - error TS2320: Interface 'PoolConnection' cannot simultaneously extend types 'PoolConnection' and 'Connection'.
  Named property 'execute' of types 'PoolConnection' and 'Connection' are not identical.

86 export interface PoolConnection extends mysql.PoolConnection, Connection {
                    ~~~~~~~~~~~~~~

node_modules/mysql2/index.d.ts:86:18 - error TS2320: Interface 'PoolConnection' cannot simultaneously extend types 'PoolConnection' and 'Connection'.
  Named property 'unprepare' of types 'PoolConnection' and 'Connection' are not identical.

86 export interface PoolConnection extends mysql.PoolConnection, Connection {
                    ~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/mysql2/index.d.ts:86
```

**Comment by PortalTime** [comment]
Hi,

I ran into the same problöem and could resolve it by adding in my tsconfig the skipLibCheck:

`{
  "compilerOptions": {
    "module": "commonjs",
    ....
    **"skipLibCheck": true**
  }
}`

May it will help you as well :)

**Comment by sidorares** [comment]
@guidev @PortalTime if you know the fix properly please submit a PR, I don't maintain typings actively myself

**Comment by HofmannZ** [comment]
This is holding us back from upgrading to v3. Is there any LTS on v2?

**Comment by sidorares** [comment]
@HofmannZ currently I don't plan to support multiple major versions at the same time
