### ISSUE TITLE
Connection duration (lifetime)

### ISSUE THREAD

**Issue by komanton** [sidorares/node-mysql2#1797]
It would be really helpful to have such option for the connection pool. Because it should help to work with 'persistent' connections more carefully with keepAlive option enabled.

It already exists in other framework and it is one of suggestions from GCP to optimize performance ([link](https://cloud.google.com/sql/docs/mysql/manage-connections#duration)).

Python:
```
# 'pool_recycle' is the maximum number of seconds a connection can persist.
# Connections that live longer than the specified amount of time will be
# re-established
pool_recycle=1800,  # 30 minutes
```

Java:
```
// maxLifetime is the maximum possible lifetime of a connection in the pool. Connections that
// live longer than this many milliseconds will be closed and reestablished between uses. This
// value should be several minutes shorter than the database's timeout value to avoid unexpected
// terminations.
config.setMaxLifetime(1800000); // 30 minutes
```

C#:
```
// ConnectionLifeTime sets the lifetime of a pooled connection
// (in seconds) that a connection lives before it is destroyed
// and recreated. Connections that are returned to the pool are
// destroyed if it's been more than the number of seconds
// specified by ConnectionLifeTime since the connection was
// created. The default value is zero (0) which means the
// connection always returns to pool.
connectionString.ConnectionLifeTime = 1800; // 30 minutes
```

Go:
```
// Set Maximum time (in seconds) that a connection can remain open.
db.SetConnMaxLifetime(1800 * time.Second)
```

_NOTE: Maybe this option already exists but I can't find it in doc._

**Comment by sidorares** [comment]
Is this similar to what you want https://github.com/sidorares/node-mysql2/pull/1791 ? (in master but not released to npm yet)

**Comment by komanton** [comment]
@sidorares Yes. Thanks a lot!👍

**Comment by joaquinbentancor** [comment]
> Is this similar to what you want #1791 ? (in master but not released to npm yet)

Hi, this PR only works for managing lifetime in idle connections, but what happens with active connections? if the connection never reach a idle state (could be possible?) which is the defined default lifetime? can be also configured?
