### ISSUE TITLE
Support bun and deno

### ISSUE THREAD

**Issue by sidorares** [sidorares/node-mysql2#1801]
Bun 0.5 added support for `net` and `tls` modules
I did a quick tests and there are few issues connecting to the server when started from bun:

- call to `TLSSocket._start()` - this is undocumented method, need to figure out how to start secure connection after tls socket is constructed from unsecure stream
- `crypto.update('string')` calls - bun wants to see a `Buffer` here, probably worth to convert to a buffer explicitly

Haven't tried deno yet

**Comment by vlasky** [comment]
Bun.js's previously stated that ["Support for Node.js APIs continues to be a top priority for Bun"](https://bun.sh/blog/bun-v0.4.0#:~:text=Support%20for%20Node.js%20APIs%20continues%20to%20be%20a%20top%20priority%20for%20Bun), so perhaps it's preferable that this missing functionality is best incorporated into Bun.js?

**Comment by sidorares** [comment]
Yeah, I'll be reporting functionality that is broken when used in bun and not yet deprecated in node, and refactor undocumented or deprecated apis on the driver side

**Comment by sidorares** [comment]
I don't have time to focus on deno ( or even check what works and what not ), but bun can probably be considered "officially" supported: main functionality, tls, compression work out of the box and unit tests run for bun in CI ( small subset for now )

**Comment by suchislife801** [comment]
Just here to express my complete and total frustration with people who insist in supporting Node JS when Deno exists. God how I hate Node JS.... Is it even possible to dislike something this much?

Deno's driver is made by people who don't think strings are important in queries...
mysql2 port of Node JS is never updated...
mysql connector from Oracle is Node JS...
