### ISSUE TITLE
Typescript issue: `createPool` no longer accepts `decimalNumbers` flag as an option

### ISSUE THREAD

**Issue by DarkGL** [sidorares/node-mysql2#1803]
In version [v2.3.3](https://github.com/sidorares/node-mysql2/releases/tag/v2.3.3) compiled fine when passing decimalNumbers as one of the options, with version 3.x it no longer works.

**Comment by sidorares** [comment]
hm, I can see it in here https://github.com/sidorares/node-mysql2/blob/24126ab3e30e4295dd260f095e1cbfd9bfd4be88/index.d.ts#L172

But it seems like `createPool` looks for its types in typings/mysql/lib/Pool.d.ts -> https://github.com/sidorares/node-mysql2/blob/24126ab3e30e4295dd260f095e1cbfd9bfd4be88/typings/mysql/lib/Connection.d.ts#L13

**Comment by sidorares** [comment]
I can add it typings/mysql/lib/Connection.d.ts but need to review why we have this duplication

**Comment by DarkGL** [comment]
Bump :)

**Comment by sidorares** [comment]
@DarkGL should be published in a few minutes

**Comment by sidorares** [comment]
@DarkGL published as v3.2.3 - https://github.com/sidorares/node-mysql2/releases/tag/v3.2.3
