### ISSUE TITLE
improvement of mTLS connection

### ISSUE THREAD

**Issue by wenhujin** [sidorares/node-mysql2#1826]
when using pool.getConnection to create new connection, the connectionConfig including old certficate which may expired.
https://github.com/sidorares/node-mysql2/blob/70d86bb6ef1bab4e3fbc761458f3727f295ee808/lib/pool.js#L55

suggest pass cert file path as config and read cert file here, to make sure every new connection using newest certificate info.
https://github.com/sidorares/node-mysql2/blob/70d86bb6ef1bab4e3fbc761458f3727f295ee808/lib/connection.js#L344-L350

**Comment by sidorares** [comment]
I don't think pool should read from the file, this would make it less flexible (and have some unknown perf issues if each createConnection is associate with file operation)
If thats really a concern in your use case you can have a file watcher and update config values each time cert of the file system is updated

**Comment by wenhujin** [comment]
I agree about less flexible. but if don't handle new cert at driver side, clients always needs consider create new pool. I think This is more of a disadvantage than flexibility when using pool (may be it's only my case).

> and have some unknown perf issues if each createConnection is associate with file operation
it's only happen on create new connection, in case using pool I think there is no that much file operation.

**Comment by sidorares** [comment]
I'd rather have some system of hooks to allow any user code to run before connection is created ( I think we emit some events but probably not very easy to synchronise, e.i only create connection after some extra code finishes )

**Comment by wenhujin** [comment]
yeah, that is good idea.

**Comment by wenhujin** [comment]
Hi, sidorares 
I checked other drivers of some languages, and realized all of drivers pass tls config to driver as file path, and load them on create connection. how are you think about this? Don't you think most users are more likely to load the tls context as a file on the client side even though we provide a flexible way to pass the tls configuration? 

- java:
https://github.com/mysql/mysql-connector-j/blob/fa4912a849140828e48162a2c396c8df0091bed7/src/main/core-impl/java/com/mysql/cj/protocol/ExportControlled.java#L320

- python: 
https://github.com/mysql/mysql-connector-python/blob/735322dbe0b453b01d3e52392cf364717b78bdb8/lib/mysql/connector/network.py#L390-L392

- golang:
https://github.com/go-sql-driver/mysql/blob/fa1e4ed592daa59bcd70003263b5fc72e3de0137/utils.go#L32-L56

**Comment by sidorares** [comment]
> certs, err := tls.LoadX509KeyPair("/path/client-cert.pem", "/path/client-key.pem")

if I read golang comments correctly its up to a user to read certs content and pass that as tls config

**Comment by sidorares** [comment]
Closing this for now, it's already possible for a user to re-read cert each time connection is created, I'll leave this to the user as a relatively niche feature to live in the library
