### ISSUE TITLE
Inserting NULL

### ISSUE THREAD

**Issue by idmean** [sidorares/node-mysql2#184]
Is there a way to insert a NULL value using a prepared statement?

**Comment by adrianblynch** [comment]
Something other than:

`db.query("INSERT INTO table (x, y, z) VALUES (?, ?, ?)", ["x", "y", null], function(err, result) {})`

**Comment by idmean** [comment]
But `query` does not use a real prepared statement, does it?

**Comment by sidorares** [comment]
`db.execute("INSERT INTO table (x, y, z) VALUES (?, ?, ?)", ["x", "y", null], function(err, result) {})` should work
