### ISSUE TITLE
Timeouts are not supported

### ISSUE THREAD

**Issue by euglv** [sidorares/node-mysql2#185]
Incompatibility with **felixge** node-mysql, see documentation:
https://github.com/felixge/node-mysql#timeouts

**Comment by sidorares** [comment]
Thanks, I'll try to add soon

**Comment by euglv** [comment]
By the way, **felixge**`s node-mysql does not handle timeouts properly.

If I execute the following code 10 times:
```javascript
connection.query({sql: 'SELECT SLEEP(200)', timeout: 10}, function (err, rows) {
  if (err) {
    console.log(err);
  }
});
```
Then console shows 10 PROTOCOL_SEQUENCE_TIMEOUT errors, but running sql query  `show full processlist` shows that 10  `SELECT SLEEP(200)` queries are still running on mysql server.

Is there any possibility to implement query execution aborting on mysql server after timeout is reached?
I created such issue for felixge too.

**Comment by sidorares** [comment]
as @dougwilson already explained, timeouts are not part of the protocol but simple client side helpers - "I need this callback with data, but not later than X ms, if it takes more just call me with error and I'll figure out what to do after"

**Comment by sidorares** [comment]
> Is there any possibility to implement query execution aborting on mysql server after timeout is reached?
I created such issue for felixge too.

It would be probably out of scope of this driver. If you really want, you can create monitoring connection in your app and have it always kill processes when there is PROTOCOL_SEQUENCE_TIMEOUT - and expose this as wrapper with same api as connection.query() or pool.query()

**Comment by euglv** [comment]
Other software have ability to terminate query execution on mysql side, for example when pressing "stop" button. I belive, when connection to MySQL server is terminated (socket is closed) then mysql server should abort query.

May be connection remains open after timeout is reached in felixge`s implementation. (But documentation say that connection should be destroyed)

**Comment by euglv** [comment]
Yes, you are right. Closing socket to mysql doesn't terminates query. 
So I use such wrapper:

````javascript
var pool = mysql.createPoolCluster();
pool.add(config.db);
pool.query = function (sql, params, done)
{
	var connection;
	pool.getConnection(connected);
	function connected(err, conn) 
	{
		if (err)
		{
			if (done) done(err);
			return;
		}
		
		connection = conn;
		conn.query(sql, params, queryDone);
	}
	function queryDone(err, rows, fields)
	{
		if (err && err.code === 'PROTOCOL_SEQUENCE_TIMEOUT') 
			pool.query("kill :id", {id: connection.threadId});
			
		if (connection.release)
			connection.release()
		else
			connection.end();
		if (done) done(err, rows, fields);
	}
}

````

**Comment by sidorares** [comment]
dbForge is probably doing exactly what I described. There is definitely no timeout parameter at protocol level

**Comment by sidorares** [comment]
yes, your code looks ok to me ( you probably want to save original 'pool.query()` and use it when you do `pool.query("kill ...")` )

**Comment by linusnorton** [comment]
@sidorares are you still considering adding this feature? I am encountering an issue where a TRUNCATE is taking a long time and timing out and I would like to ask the library/client to wait longer. Is there any other way to achieve that?

**Comment by sidorares** [comment]
@linusnorton yes, I'm keen to add this feature

> I am encountering an issue where a TRUNCATE is taking a long time and timing out and I would like to ask the library/client to wait longer.

Do you want to see same behaviour as in mysqljs/mysql? E.i if execution time > timeout connection is killed and callback gets called with fatal error as parameter ( and removed from pool if pool is used ) "would like to ask the library/client to wait longer." feels like a different behaviour

**Comment by linusnorton** [comment]
I'm unsure of the exact implementation but as a naive end user I don't expect the execution time / connection time to be related. I assume that the connection timeout is for establishing the connection, or in the case of radio silence with mysql. 

I'm not sure if you can tell the difference between a slow executing query and radio silence? If not then it makes sense that connection timeout and execution time to be connected. 

I was intending to use the `{ sql: 'TRUNCATE test', timeout: 60000 }` syntax

**Comment by sidorares** [comment]
> I'm not sure if you can tell the difference between a slow executing query and radio silence? If not then it makes sense that connection timeout and execution time to be connected.

no, it's not possible. In fact, it's not possible to send any command to a connection until previous one is finished. This is why api is like this: you can set timeout, but semantics is "if reached, just throw away connection entirely". Did you mean "would like to ask the library/client _NOT_ to wait longer."?

**Comment by linusnorton** [comment]
Okay. I did mean I would like to ask it to wait longer but it sounds like my understanding of how things currently work was flawed and if I increase the connection timeout settings it may help with my issue.

**Comment by sidorares** [comment]
currently there is no timeout at all (and no default), so just waiting for command to finish should be enough for you

**Comment by linusnorton** [comment]
Strange, I will try to tweak the code to find out a bit more

**Comment by linusnorton** [comment]
It appears to be something to do with how I am using the promised version. Essentially, I am doing the SQL query, storing the promise, doing some slow blocking stuff (unzipping a file) and then awaiting the promise.

This is the error I receive:

```
{ Error: connect ETIMEDOUT
    at PromisePool.query (./node_modules/mysql2/promise.js:272:20)
    at MySQLSchema.dropSchema [clipped]
  message: 'connect ETIMEDOUT',
  code: 'ETIMEDOUT',
  errno: undefined,
  sqlState: undefined }
```

If I just do the query and await the promise then it is fine.
