### ISSUE TITLE
similar to TLS minVersion, allow configuration of maxVersion

### ISSUE THREAD

**Issue by johndevedu** [sidorares/node-mysql2#1870]
Node is defaulting to TLS1.3 which is incompatible with Amazon RDS Aurora which supports up to TLS1.2. As was done for https://github.com/sidorares/node-mysql2/issues/960 where minVersion was added, can we also add maxVersion?

I can submit PR if this sounds ok.

**Comment by sidorares** [comment]
sounds ok to me, PR welcome

**Comment by johndevedu** [comment]
Thank you for your work, and quick turnaround!
