### ISSUE TITLE
Return affected row from INSERT statement

### ISSUE THREAD

**Issue by Satalicious** [sidorares/node-mysql2#1900]
I got this function, where we insert a new message. Is there a way to get the id of the affected row from the INSERT stmt?

table scheme:
``` sql
CREATE TABLE IF NOT EXISTS messages (
  id INTEGER PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
  chat_id INTEGER NOT NULL,
....
```

``` typescript
export async function sendMessage(newMessage: Message) {
  // sends Message and sets has_read for each user in the chat
  const [rows, fields] = await con.execute(
    `INSERT INTO messages (user_id, chat_id, msg_type, msg) VALUES (${newMessage.user_id}, ${newMessage.chat_id}, ${newMessage.msg_type}, '${newMessage.msg}')`, (err, res, fields) => {
      
      if(err) {
        throw(err)
      }
    console.log(fields)
    console.log(rows, fields)
    console.log(res)
    }
  );
```

console.log of fields: ```undefined```

console.log of rows, field: ```undefined undefined```

console.log of res:
```
ResultSetHeader {
  fieldCount: 0,
  affectedRows: 1,
  insertId: 24,
  info: '',
  serverStatus: 2,
  warningStatus: 0
}
```

Now i'm pretty sure that ResultSetHeader.insertId is nothing that we can work with.
I can't use a SELECT statement passing the new Message because the id is the only thing that is unique.

**Comment by Satalicious** [comment]
i think i just found the solution in the mysql docu: 
https://github.com/mysqljs/mysql#getting-the-id-of-an-inserted-row

**Comment by sidorares** [comment]
@Satalicious unrelated to your question, but in your example you are creating new prepared statement each time `.execute()` is called ( also `newMessage.user_id`, and `newMessage.chat_id` are not sanitised, if comes from user input this is a security risk ). Better to use PS parameters in the query instead, and pass values as parameters array

Another problem: you are mixing promise and callback style api, don't pass a callback and use value of a resolved promise instead if its a promisified `.execute()` ( or the other way around - only use values in the callback and don't rely on the return value feom `.ecute()` if its a non-promise api )

**Comment by Satalicious** [comment]
> i think i just found the solution in the mysql docu: https://github.com/mysqljs/mysql#getting-the-id-of-an-inserted-row

**Comment by Satalicious** [comment]
> i think i just found the solution in the mysql docu: https://github.com/mysqljs/mysql#getting-the-id-of-an-inserted-row
