### ISSUE TITLE
insertId on duplicate key update

### ISSUE THREAD

**Issue by cheshirecatalyst** [sidorares/node-mysql2#193]
Is it possible to get this? currently it just returns 0 if the row was updated, and new id if inserted.

**Comment by sidorares** [comment]
the library just return whatever is returned by server. Could you give example query? Probably not possible

**Comment by sidorares** [comment]
No, there is no special result on update. Insert ID is returned in first [packet](https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html) if the number of columns in the resultset is 0.
![](https://dev.mysql.com/doc/internals/en/images/graphviz-3ab2ba81081a7f3cc556d11fd09f50341bba6f15.png)

- see https://dev.mysql.com/doc/internals/en/com-query-response.html

**Comment by cheshirecatalyst** [comment]
Thank you for the information and timely response
