### ISSUE TITLE
Typing for stored procedure results wrong

### ISSUE THREAD

**Issue by joshuajaharwood** [sidorares/node-mysql2#1934]
When executing a stored procedure, results are returned in the following shape:

`[[[RowDataPacket], ResultSetHeader], ColumnDefinition[]]`

This can't be typed by passing in a RowDataPacket overload to the..

```typescript
query<T extends RowDataPacket[][] | RowDataPacket[] | OkPacket | OkPacket[] | ResultSetHeader>(
    options: QueryOptions
  ): Promise<[T, FieldPacket[]]>;
```

...query method as T's bounds don't allow for the actual result format.

Here's an example of the returned result:

```json
[
  [
    [
      {
        "rowResult1": true
      },
      {
        "row2Result2": true
      }
    ],
    {
      "fieldCount": 0,
      "affectedRows": 0,
      "insertId": 0,
      "info": "",
      "serverStatus": 34,
      "warningStatus": 0
    }
  ],
  [
    [
      {
        "_buf": {
          "type": "Buffer",
          "data": ["data was removed"]
        },
        "_clientEncoding": "utf8",
        "_catalogLength": 3,
        "_catalogStart": 10,
        "_schemaLength": 0,
        "_schemaStart": 14,
        "_tableLength": 0,
        "_tableStart": 15,
        "_orgTableLength": 0,
        "_orgTableStart": 16,
        "_orgNameLength": 15,
        "_orgNameStart": 33,
        "characterSet": 63,
        "encoding": "binary",
        "name": "column_name",
        "columnLength": 10,
        "columnType": 10,
        "type": 10,
        "flags": 128,
        "decimals": 0
      },
      {"others":  "removed"}
    ],
    null
  ]
]
```

I'm using mysql2 v3.2.0.

**Comment by adammflax** [comment]
Hi Sidorares,
I'm struggiling to visualise all these situations if you give a couple of examples of output we can try and make a better type

**Comment by sidorares** [comment]
some examples are in the unit tests:

https://github.com/sidorares/node-mysql2/blob/ef7bac8a994b9bd8073b93212f303ad227ba4c61/test/integration/connection/test-binary-multiple-results.js#L27-L106

https://github.com/sidorares/node-mysql2/blob/ef7bac8a994b9bd8073b93212f303ad227ba4c61/test/integration/connection/test-multiple-results.js#L27-L105

**Comment by wellwelwel** [comment]
@joshuajaharwood, thanks for report it.

The type from the **Procedure** creating is a `ResultSetHeader`.
But when it's called, the type is `[/* every current type */, ResultSetHeader]`.

---

### Testing

I created an example to test it in some ways.

```sql
CREATE PROCEDURE myProcedure()
BEGIN
  -- some query (SELECT, UPDATE, etc.)
END
```

---

### Conslusion
> When calling to `myProcedure`:
- the `query` between `BEGIN` and `END` will define the returned type of the first result: `[0]`
- the second result always be a `ResultSetHeader`: `[1]`

I tried it for each current overload and none of them matched.

---

### Practical Testing
> This code can helps to create the missing `PROCEDURE CALL` TypeScript **overload**.

```ts
import mysql from 'mysql2/promise';

/** Creating a test type for Procedures */
type Procedure = [mysql.RowDataPacket[], mysql.ResultSetHeader];

const connection = await mysql.createConnection({});

/** It will return a `mysql.ResultSetHeader` ✅ */
await connection.query(`
   CREATE PROCEDURE myProcedure()
   BEGIN
      SELECT 1;
   END
`);

/**
 * It will return a non-matching type equal to `Procedure` type
 * [0] `Procedure` (doesn't exists) ❌
 * [1] `mysql.FieldPacket` ✅
 */
const result = (await connection.query('CALL myProcedure()'))[0] as Procedure;

/**
 * The `const procedure` should be any currently overload
 * `mysql.RowDataPacket[] | mysql.RowDataPacket[][] | mysql.OkPacket | mysql.OkPacket[] | mysql.ResultSetHeader`
 */
const procedure = result[0];
/**
 * The `const header` should be a `mysql.ResultSetHeader`
 */
const header = result[1];

/** It will return a `mysql.ResultSetHeader` ✅ */
await connection.query('DROP PROCEDURE IF EXISTS myProcedure');

await connection.end();

console.log('Procedure:', procedure);
console.log('Header:', header);
```

That returns:
```js
Procedure: [ { '1': 1 } ] 

Header: ResultSetHeader {
  fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  info: '',
  serverStatus: 2,
  warningStatus: 0
}
```

**Comment by wellwelwel** [comment]
After version `^3.4.4`, you can use the `ProcedureCallPacket` type.

You can follow this example:
https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/examples/typescript/procedure-call-packet.ts#L72-L88

And also, learn about it in [documentation/en/TypeScript-Examples.md#procedurecallpacket](https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/documentation/en/TypeScript-Examples.md#procedurecallpacket).

---

I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️
