### ISSUE TITLE
Attribute "promise" does not exist on type "Connection"

### ISSUE THREAD

**Issue by tomoat** [sidorares/node-mysql2#1936]
Attribute "promise" does not exist on type "Connection"

import mysql from 'mysql2'
import util from 'util'

const conn = mysql.createConnection({
  host: '127.0.0.1',
  user: 'root',
  password: '12345678',
  port: 3306,
  database: 'domain',
  rowsAsArray: true,
})

const db = conn.promise()  // This line reported an error
export { db }

**Comment by wellwelwel** [comment]
You need to import by `mysql2/promise`:

```ts
import { createConnection } from 'mysql2/promise';

const db = await createConnection({
   host: '127.0.0.1',
   user: 'root',
   password: '12345678',
   port: 3306,
   database: 'domain',
   rowsAsArray: true,
});

export { db };
```

**Comment by gtavos** [comment]
Even from `mysql2/promise` the` promise()` option is not available in Connection class.  Is it available in 3.2.0 or lower versions?

**Comment by bluefeet** [comment]
I've run into the same issue - while I could import `mysql2/promise` I would prefer to import `mysql2` and then use `conn.promise()` to upgrade it as needed. It would be nice if the typing for Connection included the promise function so that I don't have to create custom typings or explain to developers why it works and to ignore the type errors.

**Comment by bluefeet** [comment]
I figured out how to get `conn.promise()1 types working. Here's my `src/mysql2.d.ts`:

```
import * as mysql2 from 'mysql2';

declare module 'mysql2' {
  export interface Connection {
    promise: () => Promise<Connection>;
  }
}
```

I also have to use it in my `src/index.ts` to make it take affect:

```
import './mysql2.d.ts';
```

A similar edit to the typings for Connection would resolve this for everyone.

**Comment by sidorares** [comment]
Looks like #1949 should fix the issue

**Comment by newtoncodes** [comment]
Doesn't seem right.
Here is the code: https://github.com/sidorares/node-mysql2/blob/master/lib/connection.js#L155
It should not return a promise. All my implementations require createConnection and .promise() to directly return a connection instance. Seems like the code is right, but the typings are wrong in the new version as well.

**Comment by wellwelwel** [comment]
@tomoat and @gtavos:

In case `PR` #1955 is merged by @sidorares, I suggest you look at the two examples in the comment of this `PR`.

**Comment by wellwelwel** [comment]
@tomoat, @gtavos, can you try it now in `3.2.2` release?

**Comment by wellwelwel** [comment]
@tomoat, can you try it in version `^3.3.5`?

**Comment by wellwelwel** [comment]
After version `^3.3.5`, you can follow this example:
https://github.com/sidorares/node-mysql2/blob/00508c38a13f1394fb8a6cf3fd88df1353ba0e77/test/tsc-build/mysql/createConnection/promise/execute.ts#L5-L11

---

I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️
