### ISSUE TITLE
Module "mysql2" has no exported member "Types"

### ISSUE THREAD

**Issue by neeppy** [sidorares/node-mysql2#1938]
Hello,

Apparently, when using typescript, the `Types` export from `index.js` is not being resolved. I assume this is because it's missing from the `index.d.ts` file.

![image](https://user-images.githubusercontent.com/22986246/230616865-bdba3454-b176-4afb-9a86-9494548514f1.png)

However, logging out `Types` works as expected, even if it says that it's missing, so a simple `@ts-ignore` works as a workaround. Trying to import from the promise API, however, doesn't work, as expected, since the `Types` object is not exported.

Is there a reason why the column types couldn't be exported from `mysql2/promise` as well?

Thanks a lot!

**Comment by wellwelwel** [comment]
Hi @cptpaws, can you check it in `^3.4.1` version?

---

### Just a suggestion in case you use with **ES Module**

To import the Constants, I recommend you do it as follows:
```ts
import mysql from 'mysql2';
// or
import * as mysql from 'mysql2';

// then
mysql.Types;
```

---

By using by this way in an **ES Module**
```ts
import { Types } from 'mysql2';
```

It will print an error like:
```bash
import { Types } from 'mysql2';
         ^^^^^
SyntaxError: Named export 'Types' not found. The requested module 'mysql2' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mysql2';
const { Types } = pkg;
```

---

As before, it's just a suggestion 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
After version `^3.4.1`, you can use the `Types` constants.

#### Some examples:

- `import mysql from 'mysql2'`
https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/test/tsc-build/mysql/constants/Types.ts#L3-L5

- `import mysql from 'mysql2/promise'`
https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/test/tsc-build/promise/constants/Types.ts#L3-L5

---

I'm closing this **Issue**, but feel free to ask anything 🙋🏻‍♂️
