### ISSUE TITLE
Opened connections are not beeing closed. 

### ISSUE THREAD

**Issue by IBleSSeDI** [sidorares/node-mysql2#194]
We faced a problem - node started throwing the exception 

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: Too many connections
        at Packet.asError (/var/app/current/node_modules/mysql2/lib/packets/packet.js:493:13)
        at ClientHandshake.Command.execute     (/var/app/current/node_modules/mysql2/lib/commands/command.js:25:22)
        at Connection.handlePacket (/var/app/current/node_modules/mysql2/lib/connection.js:310:28)
        at PacketParser.onPacket (/var/app/current/node_modules/mysql2/lib/connection.js:83:65)
        at PacketParser.executeStart (/var/app/current/node_modules/mysql2/lib/packet_parser.js:39:12)
        at Socket.<anonymous> (/var/app/current/node_modules/mysql2/lib/connection.js:95:31)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:765:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)

Then we started the investigation - closed a website for everybody, restarted mysql, node (forever) and nginx. show full processlist showed no connection. We send a request to node.js server and got the response. show full processlist showed us 3 opened connections. One more call - 3 new connections. One more - 3 new connections. So, 3 calls opened 9 connections which were not closed. So, seams like 
1. node mysql driver creates a new connection for every new query
2. It doesn't close the connections

How to fix that? Thanks.

**Comment by sidorares** [comment]
The driver does not close connection automatically ( because it does not know when connection is not longer in use) you need to do this manually.

**Comment by IBleSSeDI** [comment]
Yes, you are right. We must use already opened connection instead of opening new ones. Thanks.

**Comment by IBleSSeDI** [comment]
Could you tell us, if there any way to get current connection? The problem is that we are always opening a new one. Is there any way we can get existing one and always use it? Thanks.

**Comment by sidorares** [comment]
There is built in pooling functionality:

```js

var pool = mysql.createPool(); // same parameters as to createConnection
pool.getConnection(function(err, conn) {
  conn.query("select 1+1", function(err, res) {
    // use result;
    conn.release(); // tell pool that you no longer need this connection
  }
});
```

or just store your single connection in some global store ( global variable, config or something ) and just always reuse it. There is no need to ensure that previous query finished - connection just anqueues all commands and executes them as soon as server is ready

**Comment by Nithur-M** [comment]
> just store your single connection in some global store ( global variable, config or something ) and just always reuse it. There is no need to ensure that previous query finished - connection just anqueues all commands and executes them as soon as server is ready

Can you provide an example for this? I am trying to query data from mysql for a NextJS app with getStaticProps. And it is throwing too many connection errors because there are around 130 pages and a connection is made for each page build (my guess).
