### ISSUE TITLE
websocket without json

### ISSUE THREAD

**Issue by GoNode5** [sidorares/node-mysql2#195]
I have an autocomplete function at first running via http/post, working ok. I replaced this with a websocket, beter/faster, But I still create from row/array to  json  at the  server as reply to the  client (Angular) where I do a JSON.parse back to array. Is there a way to go more native via websockets so can skip the json and use another protocol?

**Comment by sidorares** [comment]
Your question is not really related to this driver. This mysql client exposes result to you as plain javascript objects, it's up to you how to serialise them (and serialisation to/from JSON is very fast in V8). If size is a bottleneck you might consider [BSON](https://www.npmjs.com/package/bson), [protocol buffers](https://github.com/mafintosh/protocol-buffers) or [msgpack](https://github.com/pgriess/node-msgpack)

**Comment by GoNode5** [comment]
Thank you for answering. If I cache the plain objects, I go to 4ms , rows-jsons-json rows gives me 200-400ms...I was hoping to find something inbetween :-). Yes json is very fast, but  dont need the extra converserions.

**Comment by sidorares** [comment]
how big is your json? I'm pretty sure it's not the `JSON.strtingify` time, it's network IO. Can you measure each individually?

**Comment by GoNode5** [comment]
I log the websocket roundtrip. The onMessage gets random cache or direct. I'am trying to find out how much faster websocket is compared to the same request via http/get. But you could be right that the stringify/parse is not the problem. But on the end its all extra layers I dont need in the first place.
````
send: function(msg) {	  		         		
	msg.requestTime=performance.now();
	dataWs.send(JSON.stringify(msg));
}	

dataWd.onMessage(function(msg) {
		var b=performance.now()				
		var data=JSON.parse(msg.data)
			 if (data.requestTime){	
				 	$rootScope.webReqTime='Request: ' +(Math.round(b - data.requestTime,3)) + 'ms.'					
			 }
````

**Comment by sidorares** [comment]
feel free to post updates here (and reopen if you feel it's related to driver performance)
