### ISSUE TITLE
mix callbacks and await queries

### ISSUE THREAD

**Issue by syco** [sidorares/node-mysql2#1950]
Hi,
I moved to mysql2 from mysql to use the promise functionality, but I'm having an issue:

when I require `mysql2/promise` all queries with a callback hang instead of executing the callback,
await queries works fine, but I don't want to rewrite all queries already done and tested.

Is that a known behaviour? Should I be able to use both await and callbacks?

**Comment by sidorares** [comment]
> Is that a known behaviour? Should I be able to use both await and callbacks?

Yes, this is per design. No. promise versions of `.query()` / `execute()` etc don't take callback as a parameter and return a promise. If you pass a callback its probably just ignored. You should `await` / `.then` returned promise instead
