### ISSUE TITLE
beginTransaction / rollback is not working

### ISSUE THREAD

**Issue by ladmini** [sidorares/node-mysql2#1969]
Hi guys, thank you very much for bringing us such an amazing library! 
I encountered a problem while using it. **Data rollback seems to be not working**, perhaps my usage is incorrect. Could you please help me check what the problem is? Thank you!

Here is some code snippet:

**Environment**
```javascript
"mysql2": "3.2.0"
node V16.13.0
mysql  Ver 8.0.27 for Linux on x86_64
```

**db.pool.js code snippet**
```javascript
const mysql = require('mysql2/promise')

const dbPool = mysql.createPool({
  host: config.SERVER_DB_HOST,
  user: 'expireday',
  password : 'secret xxx',
  database: config.SERVER_DB_NAME,
  waitForConnections: true,
  connectionLimit: 100,
  queueLimit: 0
})
```
**user.controller.js  code snippet**
```javascript
  let conn = null
  try {
    conn = await dbPool.getConnection()
    const sql = 'My SQL statement as follows'
    logger.debug(sql)
    await conn.beginTransaction()
    const [rows, filed] = await conn.execute(sql)
    await conn.commit()
    throw('$$$ throw some error $$$')
  } catch (error) {
    if (conn) {
      logger.debug('will roll back db record')
      await conn.rollback()
      logger.debug('db record rollback finished')
    }
    logger.error('API /user/regist error: ' + error)
  } finally {
    if (conn) {
      logger.debug('will release poll connection')
      conn.release()
      logger.debug('poll connection release finished')
    }
  }
```

**My SQL statement is as follows**
```sql
INSERT INTO
  user (
    email,
    password,
    registTime,
    startTime,
    endTime,
    status,
    role,
    updateBy,
    updateTime
  )
VALUES
(
    'ladmini@126.com',
    'e10adc3949ba59abbe56e057f20f883e',
    unix_timestamp(),
    unix_timestamp(),
    unix_timestamp(date_add(now(), INTERVAL 1 YEAR)),
    3,
    0,
    0,
    unix_timestamp()
  )
```

**My logs are as follows**
```log
[2023-04-23T20:48:22.861] [DEBUG] default - INSERT INTO
  user (
    email,
    password,
    registTime,
    startTime,
    endTime,
    status,
    role,
    updateBy,
    updateTime
  )
VALUES
(
    'ladmini@126.com',
    'e10adc3949ba59abbe56e057f20f883e',
    unix_timestamp(),
    unix_timestamp(),
    unix_timestamp(date_add(now(), INTERVAL 1 YEAR)),
    3,
    0,
    0,
    unix_timestamp()
  )
[2023-04-23T20:48:22.982] [DEBUG] default - will roll back db record
[2023-04-23T20:48:23.011] [DEBUG] default - db record rollback finished
[2023-04-23T20:48:23.012] [ERROR] default - API /user/regist error: $$$ throw some error $$$
[2023-04-23T20:48:23.012] [DEBUG] default - will release poll connection
[2023-04-23T20:48:23.013] [DEBUG] default - poll connection release finished
```
**DB screenshot**
<img width="1111" alt="截屏2023-04-23 20 58 16" src="https://user-images.githubusercontent.com/5718706/233838381-6f88d946-fcae-47c2-a11b-4e999568dad0.png">

**According to the log the rollback above has already been executed, why did the database data not roll back？**

**Comment by wellwelwel** [comment]
@ladmini Sorry if I'm confusing, but in this part:

```js
    await conn.beginTransaction()
    const [rows, filed] = await conn.execute(sql)

    await conn.commit() // here
    throw('$$$ throw some error $$$') // and here
```

You committed the changes and then caused the error after it.

Shouldn't the `await conn.commit()` come as the last step of the `try`?

**Comment by elimelt** [comment]
Echoing what @wellwelwel said, I think the issue is that you already committed your transaction before throwing the error. 

In other words, you want to commit a transaction only after verifying the query/update was successful. With your current useage, the transaction is already committed by the time your error was thrown, meaning a rollback shouldn't change the state of your database.

**Comment by ladmini** [comment]
@wellwelwel @elimelt Thank you very much. I'll try.

**Comment by ladmini** [comment]
@wellwelwel @elimelt  I tried it and it's working now. It seems that putting  ```await conn.commit()``` in the last step of try is a good habit.
