### ISSUE TITLE
byte1 is not defined in Packet.prototype.readLengthCodedNumberExt

### ISSUE THREAD

**Issue by ChiperSoft** [sidorares/node-mysql2#197]
Something in our codebase is hitting this line: https://github.com/sidorares/node-mysql2/blob/master/lib/packets/packet.js#L138

`byte1` is defined in `readLengthCodedNumber `, not `readLengthCodedNumberExt `.  There is no scenario where this produces useful output.  Perhaps it should have been `word0`?

Additionally, is it possible for this throw to be captured in the query handling and passed on the callback instead of being left unhandled?  We have no idea what query is triggering the error.

**Comment by sidorares** [comment]
Yes, you are right  ( though it should probably report `tag`, not `word0` )

The two ( readLengthCodedNumberExt and readLengthCodedNumber ) exist together for performance reasons - in most cases length is < 251 ( most of the names and often data itself ) and there was a measurable speed improvement after split ( shorter readLengthCodedNumber is more likely to be inlined )

we could probably safely delete both lines, the only possible way to be there is wen tag is 0xff and that should be handled with check for `null`
