### ISSUE TITLE
.

### ISSUE THREAD

**Issue by fx1738** [sidorares/node-mysql2#1984]
using mysql2/promise, default idleTimeout (60sec)
screenshot shows it doesn't close the connections (3000+ sec,) until they hit the mysql server configured timeout...

I'll add repeatable tests asap.

![image](https://user-images.githubusercontent.com/20156850/234719380-05cf89cb-fe6d-4c0d-929f-cfe21ce1b9b0.jpg)

**Comment by gautam-paladiya** [comment]
@fx1738  how did you resolve the issue?

**Comment by wkille** [comment]
I am also wondering about this.
```
const conn = await mysql.createConnection(DB_URL)
conn.config.idleTimeout = 3000 // has no effect
```

**Comment by rogerhlg** [comment]
same here... ;/ maybe i need to release() the connection to turn they iddle? i don't know...
