### ISSUE TITLE
threads dealing with sql slowing down the queries 

### ISSUE THREAD

**Issue by guypaskar** [sidorares/node-mysql2#203]
I wrote a func. that handles many large (10k-100k rows) queries in parallel (say 20 threads)

It seems like it is not at all running in parallel , as I get the callbacks in seconds of delay and actually takes much much longer than the time it takes for each query to be done when doing it one by one and not in parallel.

Tried both pool and non pool.

Anyone has an idea?

**Comment by sidorares** [comment]
can you give an example of your code?

What do you mean by "in parallel"? Your js code runs in one thread, mysql server usually start new thread for each connection.

**Comment by guypaskar** [comment]
this is the concept:

there is a function doSql that uses a pool and your library.
I have a function that call doSql let's call it callDoSql.
I call callDoSql like that:

 for(var i = 0 ; i < streams.length;  i++){
                    //console.log(i);
                    var t = Threads.create();
                    t.eval(doSql);
                    });

So I have many threads (on a multicore machine) that call doSql in parallel.
And Indeed , I see that the calls for mysql are happening in parallel but the callbacks have really big delays...

Does that clear the issue?

**Comment by sidorares** [comment]
still not clear. What is `Threads`? Are you using single connection to mysql server?

**Comment by guypaskar** [comment]
No. I'm using a pool.

this is threads:
https://www.npmjs.com/package/webworker-threads

**Comment by sidorares** [comment]
can you show doSql?

**Comment by guypaskar** [comment]
doSql:function (stmt, callback, db, dontLog, maxDate, context) {
        if (!context) {
            context = this;
        }


        var pool;
        if(poolHashByDb[db]){
            pool = poolHashByDb[db];
        }else{
            pool  = mysql.createPool({
                connectionLimit : 10,
                host            : host,
                user            : user,
                password        : password,
                database        :db
            });
            poolHashByDb[db] = pool;

        }     

        pool.getConnection(function(err, connection) {
            // Use the connection
            connection.query(stmt, function(err, rows) {
                // And done with the connection.
                if (err != null) {
                    console.log(err);
                }
                connection.release();
                callback(rows, err);

                
            });
        });

**Comment by sidorares** [comment]
could you measure performance without `Threads`? Just do same `streams.forEach(doSql)`?

**Comment by guypaskar** [comment]
does not seem to work faster.

**Comment by sidorares** [comment]
I'm trying to understand what problem exactly you have. Issue title is "threads dealing with sql slowing down the queries" - can you post numbers comparing speed with threads to without? 100k rows is big result, and depending on row size I'd expect speed ~1 to 20 queries per second, which means if you happen to put 20 queries in one connection last callback might be called in 2 to 20 seconds. With 20 separate connections it might be same 1 to 1/10 second time depending on server, network, available cpu and lots of other factors

**Comment by sidorares** [comment]
hi @guypaskar - closing due to lack of input, please reopen if you wish
