### ISSUE TITLE
PoolConnection type error after update v3.3.4

### ISSUE THREAD

**Issue by matvejs16** [sidorares/node-mysql2#2059]
Getting error: TS2551: Property 'getConnection' does not exist on type 'PoolConnection'. Did you mean 'connection'?
```
const connection = await DB.Handle_Promise.getConnection()
```

**Comment by wellwelwel** [comment]
Hi @matvejs16, I'm gradually looking for typings.

The `PoolConnection` is the pool connection itself. After a lot tests in **JS** to get the conflicts between the types, always when I tried to get a connection from a Pool Connection, it gives me an error. Then, in **PR** #2053, I changed it to only the Pool can get a connection, as seen in the [documentation](https://github.com/sidorares/node-mysql2/blob/1a9972ddeb6561b0848eaedfcaf05f667ea180b4/README.md?plain=1#L157) and according with [./lib/pool_connection.js](https://github.com/sidorares/node-mysql2/blob/1a9972ddeb6561b0848eaedfcaf05f667ea180b4/lib/pool_connection.js), you can see that it doesn't have the the `getConnection` method.

If your code works in **JS** (ignoring the types), can you share a *basic repro* example?

**Comment by matvejs16** [comment]
Yep, JS is working ok
```
import mysql from 'mysql2'
import mysqlPromise from 'mysql2/promise'

interface DB {
    Handle: mysql.Pool | null,
    Handle_Promise: mysqlPromise.PoolConnection | null,
    Connect(callback: Function): void,
    escape(string: string | number | object | Array<any>): string | number | null,
    getPromiseConnection(): mysqlPromise.PoolConnection | undefined
}

const DB: DB = {
    Handle: null,
    Handle_Promise: null,
    Connect: function(callback: Function) {
        this.Handle = mysql.createPool({
            connectionLimit: 1000,
            host: 'IP',
            user: 'USER',
            password: 'PASS',
            database: 'DATABASE',
            debug: false,
            connectTimeout: 10000,
            multipleStatements: true
        })
        this.Handle.query('SET NAMES utf8mb4;');
        this.Handle.query('SET CHARACTER SET utf8mb4');
        this.Handle.query('SET COLLATION_CONNECTION="utf8mb4_general_ci"');
        this.Handle_Promise = this.Handle.promise()
        callback()
    },
    escape: function(string) {
        if (string == 'NULL') return string
        return mysql.escape(string)
    }
}

DB.Connect(function () {
    // @ts-ignore
    const connection = await DB.Handle_Promise.getConnection() as mysqlPromise.PoolConnection 
    await connection.beginTransaction()
   // RUN MySQL Query
   await connection.commit()
   connection.release()
})

**Comment by wellwelwel** [comment]
@matvejs16

So, I took a look at your example.

At first moment, I just commented the `getPromiseConnection` from `DB` Interface since it isn't being used. This resolved the `const DB: DB` missing `getPromiseConnection` type problem.

So, both the `Handle` and `Handle_Promise` can be `null`. To use some of their methods, you need before to check if they aren't `null`.

For example:

- Interface changes

```ts
interface DB {
    Handle: mysql.Pool | null;
    Handle_Promise: mysqlPromise.Pool | null; // Now, it's Pool 🙋🏻‍♂️
    Connect(callback: Function): void;
    escape(string: string | number | object | Array<any>): string | number | null;
    // getPromiseConnection(): mysqlPromise.PoolConnection | undefined;
}
```

- Then

```ts
DB.Connect(async function () {
    const pool = DB.Handle_Promise;

    /**
     * Checking if pool isn't `null` will allow to use the pool methods.
     * Note that now, the `Handle_Promise` is a Pool and not a PoolConnection as previously
     */
    if (pool === null) return;

    const connection = await pool.getConnection();
    await connection.beginTransaction();
   // RUN MySQL Query
   await connection.commit();
   connection.release();
});
```

**Comment by wellwelwel** [comment]
@matvejs16 

So, in this example code that I do, you can test it and see after the `null` check, every method from `pool` will be available now and then, the `const connection` is a `PoolConnection`.

In fact, PoolConnection doesn't have the methods `getConnection` and `releaseConnection`. These methods are from `Pool`.

**Comment by matvejs16** [comment]
> @matvejs16
> 
> So, in this example code that I do, you can test it and see after the `null` check, every method from `pool` will be available now and then, the `const connection` is a `PoolConnection`.
> 
> In fact, the `PoolConnection` doesn't have the methods `getConnection` and `releaseConnection`. These methods are from `Pool`.

Error is here:
![image](https://github.com/sidorares/node-mysql2/assets/74150728/e8388142-a93b-4b8c-a6ac-802eb0ceedbd)

**Comment by matvejs16** [comment]
> > @matvejs16
> > So, in this example code that I do, you can test it and see after the `null` check, every method from `pool` will be available now and then, the `const connection` is a `PoolConnection`.
> > In fact, the `PoolConnection` doesn't have the methods `getConnection` and `releaseConnection`. These methods are from `Pool`.
> 
> Error is here: ![image](https://user-images.githubusercontent.com/74150728/245261712-e8388142-a93b-4b8c-a6ac-802eb0ceedbd.png)

In this error code
```
this.Handle.promise()
```

Is returning type: mysqlPromise.PoolConnection

**Comment by wellwelwel** [comment]
@matvejs16, you right! I got this error after perform a `tsc --init`.

The `.promise()` still returning `PoolConnection` instead `Pool`.

Thanks for report 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
@matvejs16, can you check this in `^3.3.5` version?

**Comment by matvejs16** [comment]
> @matvejs16, can you check this in `^3.3.5` version?

Sure, but now now, after I wake up 😉

**Comment by matvejs16** [comment]
> @matvejs16, can you check this in `^3.3.5` version?

After updating I got strange error.
```
Error: connect ETIMEDOUT
    at PoolConnection._handleTimeoutError (webpack://socketio-admin-backend/./node_modules/mysql2/lib/connection.js?:205:17)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true
}
```

**Comment by matvejs16** [comment]
> > @matvejs16, can you check this in `^3.3.5` version?
> 
> After updating I got strange error.
> 
> ```
> Error: connect ETIMEDOUT
>     at PoolConnection._handleTimeoutError (webpack://socketio-admin-backend/./node_modules/mysql2/lib/connection.js?:205:17)
>     at listOnTimeout (node:internal/timers:569:17)
>     at process.processTimers (node:internal/timers:512:7) {
>   errorno: 'ETIMEDOUT',
>   code: 'ETIMEDOUT',
>   syscall: 'connect',
>   fatal: true
> }
> ```

Sorry, my fault!
On v3.3.5 everything works good
