### ISSUE TITLE
DateTime type auto convert to localtime

### ISSUE THREAD

**Issue by minhvu7896** [sidorares/node-mysql2#2062]
I use mysql2 (Express.js) to connect to MySQL in RDS AWS.
In the database, createdAt: 2023-06-13 04:29:24.
In the query result, createdAt: 2023-06-12T21:29:24.000Z.

I don't know why it automatically converts to local time when I call the query statement.

Thank you.
Vu

**Comment by sidorares** [comment]
Do you pass anything as `timezone` [config parameter](https://github.com/sidorares/node-mysql2/blob/dc61b50cc42fdeabfb91d143822ead14d5131b8a/lib/connection_config.js#L133)? By default the value is 'local'.

The client has to perform _some_ conversion as typically mysql datetime columns do not contain any TZ information, `2023-06-13 04:29:24` is what literally stored in DB

**Comment by minhvu7896** [comment]
Thank you, I pass timezone to config parameter and it's good.
I apologize for not reading the document carefully.
