### ISSUE TITLE
session gtids track

### ISSUE THREAD

**Issue by sanglt** [sidorares/node-mysql2#2068]
How can we track the session gtids return?

I see the defination from the code: https://github.com/sidorares/node-mysql2/blob/master/lib/constants/session_track.js#L6
I also make some change to https://github.com/sidorares/node-mysql2/blob/master/lib/packets/resultset_header.js#L71 but can't make it work because some extra binary bytes data.

The `package.dump()` return this data on my test, `44363f02-0b5f-11ee-9dc7-0242ac110003:26` is the correct gtid value from server.

```
[
  "4\x00\x00\x01\x00\x01\x12\x02@\x00\x00\x00+\x03)\x00'44363f02-0b5f-11ee-9dc7-0242ac110003:26"
] <Buffer 34 00 00 01 00 01 12 02 40 00 00 00 2b 03 29 00 27 34 34 33 36 33 66 30 32 2d 30 62 35 66 2d 31 31 65 65 2d 39 64 63 37 2d 30 32 34 32 61 63 31 31 30 ... 6 more bytes> 56 1
```

Thanks,

**Comment by sidorares** [comment]
I had no idea of what gtid is, link for the people like me: https://dev.mysql.com/doc/refman/8.0/en/replication-gtids-concepts.html

**Comment by sanglt** [comment]
Thanks @sidorares,

My use case is we have a MySQL servers with [session_track_gtids](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_session_track_gtids) enable. So MySQL servers return extra information (In this case, GTID valus) into the return package.

mysql2 package already see the value in the package, so my request is to have a function to get it. When I use `package.readString` function atm, the return value still have binary value `\x00'44363f02-0b5f-11ee-9dc7-0242ac110003:26`

**Comment by sidorares** [comment]
looks like ( not 100% sure, need to find some other reference for gtid deserealisation ) that you need to read 2 length coded string, one is empty in your example ( not sure what is it ), the other is id itself.

SessionInfo block with the comments

0x2b - total length of session info - 43 bytes
0x03 - gtid sessionInfo
0x29 - 41 bytes follows
0x00 - not sure what is that, could be a zero length string
27 34 34 33 36 33 66 30 32 2d 30 62 35 66 2d 31 31 65 65 2d 39 64 63 37 2d 30 32 34 32 61 63 31 31 30 30 30 33 3a 32 36 - 39 char length string

```js
else if (type === sessionInfoTypes.STATE_GTIDS) {
    const something = packet.readLengthCodedString(encoding);
    const gtid = packet.readLengthCodedString(encoding);
    stateChanges.gtid = gtid;
}
```

Maybe it just follows the same format variableName:lengthCodedString,variableValue:lengthcodedString as in `SYSTEM_VARIABLES` and name is just ignored for the gtid?

Do you know if it's exactly one id that can come? ( e.g should the api be `{ stateChanges: { gtid: '44363f02-0b5f-11ee-9dc7-0242ac110003:26' }` or if multiple `{ stateChanges: { gtid: ['44363f02-0b5f-11ee-9dc7-0242ac110003:26'] }`)

**Comment by sidorares** [comment]
Happy to see a PR with the above added @sanglt

**Comment by sanglt** [comment]
Thanks @sidorares, this is the defination of MySQL GTID set: `A GTID set is a set comprising one or more single GTIDs or ranges of GTIDs`, so return array is safer option.
