### ISSUE TITLE
What's about JSON data type support?

### ISSUE THREAD

**Issue by mamekudz** [sidorares/node-mysql2#207]
Is there a plan to extend type.js?

**Comment by sidorares** [comment]
what exactly do you mean? Can you give examples / links to mysql documentation?

**Comment by mamekudz** [comment]
Please have a look at https://dev.mysql.com/doc/refman/5.7/en/json.html

**Comment by sidorares** [comment]
thanks, I'll have a look

**Comment by sidorares** [comment]
hi @mamekudz - you can track progress in json-type branch

**Comment by mamekudz** [comment]
Thank you! Looks good...
