### ISSUE TITLE
`maxIdle` confusion

### ISSUE THREAD

**Issue by GingerAdonis** [sidorares/node-mysql2#2070]
There are 2 problems with the following description of `maxIdle`.

1. It's not the minimum number of idle connections, but a maximum.
2. The default is the same as `connectionLimit` option, not 10.

```js
/**
* The minimum number of idle connections. (Default: 10)
*/
maxIdle?: number;
```

**Comment by wellwelwel** [comment]
According to documentation:
- https://github.com/sidorares/node-mysql2/blob/fefe036512624b384d48c926b11e7a986f7ae57c/README.md#L137

And confirming the default value as `connectionLimit` in practice:
- https://github.com/sidorares/node-mysql2/blob/fefe036512624b384d48c926b11e7a986f7ae57c/lib/pool_config.js#L18-L20

<hr />

@GingerAdonis, thanks for report it.

For now, I will change that description in PR #2067 (waiting for a third review by the community).
In case it isn't merged until the next release, I can change that description separately 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
@GingerAdonis, can you check it in version `^3.4.0`?
