### ISSUE TITLE
TypeScript: PoolConnection .execute() method is wrongly typed to return a Query

### ISSUE THREAD

**Issue by mattwoolford** [sidorares/node-mysql2#2083]
The `.execute()` method on a `PoolConnection` should return the same as the `.execute()` method on a `Pool` in an async/await context:

`Promise<[RowDataPacket[][] | RowDataPacket[] | OkPacket | OkPacket[] | ResultSetHeader>, FieldPacket[]]>` *not* `Query`

For example:

```typescript
const connection = mysql.createPool(...).promise().getConnection(); // Type: PoolConnection
const [rows,] = await connection.execute("SELECT * FROM table WHERE col=?", ["foo"]); // No longer compiles since v3.3.0

/**

TypeScript compiler throws error on `[rows,]`
because the 'Query' type does not match an [ ]

TS2488: Type 'Query' must have a '[Symbol.iterator]()'
method that returns an iterator.

**/
```

**Comment by wellwelwel** [comment]
@mattwoolford, the `getConnection()` from the `promise` method is a `Promise<PoolConnection>`.

Using your example, the `connection` is a `Promise<PoolConnection>`, so you can use the `await` to "turn" it into a `PoolConnection`. For example:

```ts
import mysql from 'mysql2';

const connection = await mysql.createPool({}).promise().getConnection();
const [rows] = await connection.execute("SELECT * FROM table WHERE col=?", ["foo"]);
```

**Comment by wellwelwel** [comment]
In [test/tsc-build/mysql/createPool/promise/execute.ts](https://github.com/sidorares/node-mysql2/blob/a0e94001397220efef2f03d9a07b933252d80c37/test/tsc-build/mysql/createPool/promise/execute.ts) you can see some use cases in **TypeScript** for the `execute` from `promise` method, like:

https://github.com/sidorares/node-mysql2/blob/a0e94001397220efef2f03d9a07b933252d80c37/test/tsc-build/mysql/createPool/promise/execute.ts#L42

https://github.com/sidorares/node-mysql2/blob/a0e94001397220efef2f03d9a07b933252d80c37/test/tsc-build/mysql/createPool/promise/execute.ts#L52-L53

**Comment by mattwoolford** [comment]
Hi, thanks, I missed out `await` in my example.

Here's a use case where I still encounter a TypeScript compilation error on a PoolConnection:
<img width="957" alt="image" src="https://github.com/sidorares/node-mysql2/assets/57449285/47bf5e3f-531e-4328-bdee-a56f6abae2d3">

Maybe an issue in the exported interface? Or am I still using this incorrectly?

**Comment by wellwelwel** [comment]
> Hi, thanks, I missed out `await` in my example.
> 
> Here's a use case where I still encounter a TypeScript compilation error on a PoolConnection: <img alt="image" width="957" src="https://user-images.githubusercontent.com/57449285/248142248-47bf5e3f-531e-4328-bdee-a56f6abae2d3.png">
> 
> Maybe an issue in the exported interface? Or am I still using this incorrectly?

Can you share it as a code (to copy)?
Knowing your **TypeScript** version can help.

**Comment by mattwoolford** [comment]
```typescript
import {PoolConnection} from "mysql2";

class Mysql2Test {

    /**
     * Generate a UUID
     * @static
     * @param {PoolConnection} providedConnection
     * @returns {Promise<string>}
     */
    public static async uuid(providedConnection: PoolConnection): Promise<string> {
        const [uuidRow,] = await providedConnection.execute("SELECT UUID() AS uuid;", []);
        if (uuidRow.length === 0) {
            throw new Error("No UUIDs available");
        }
        return uuidRow[0].uuid;
    }

}
```

Here you go 😁

**Comment by wellwelwel** [comment]
@mattwoolford, thanks 🙋🏻‍♂️

*So...*

1) If you want the *promise based* `PoolConnection`, you need to import it from `mysql2/promise`.
2) You need to check the type returned from `execute`.
> For convenience, I just used the `as` from **TS**

Note the `import`:
```ts
import mysql, { PoolConnection } from 'mysql2/promise';

export class Mysql2Test {
   /**
    * Generate a UUID
    * @static
    * @param {PoolConnection} providedConnection
    * @returns {Promise<string>}
    */

   public static async uuid(providedConnection: PoolConnection): Promise<string> {
      const [uuidRow] = (await providedConnection.execute('SELECT UUID() AS uuid;', [])) as mysql.RowDataPacket[];

      if (uuidRow?.length === 0) throw new Error('No UUIDs available');

      return uuidRow[0].uuid;
   }
}
```

**Comment by mattwoolford** [comment]
Thanks for your help! Yes, that clears the water! Had not realised there were two `PoolConnection`s!  🚀
