### ISSUE TITLE
bind parameters not working with multiple statements

### ISSUE THREAD

**Issue by KernelDeimos** [sidorares/node-mysql2#2097]
I'm trying to execute multiple statements in one go. I set `multipleStatements` to true.

```
console.log({ stmts, vals });
console.log('array?', Array.isArray(vals))
await this.db_primary.promise().execute(stmts, vals);
```

My output from the console.log statements is what I expect - `stmts` is a string of semicolon-separated statements, `vals` is an array of parameters to bind, and the number of values matches the number of question marks.

Am doing something wrong, or is this a bug?

**Comment by sidorares** [comment]
https://dev.mysql.com/doc/refman/8.0/en/sql-prepared-statements.html

> SQL syntax for prepared statements does not support multi-statements (that is, multiple statements within a single string separated by ; characters).

It's not supported, multiple statements are only allowed in `.query()`

**Comment by sidorares** [comment]
Curious what behaviour do you observe? Does server respond with the error? What's the error message?

**Comment by KernelDeimos** [comment]
The error message is definitely incorrect, I'm getting this:

```
Error: Bind parameters must be array if namedPlaceholders parameter is not enabled
```

**Comment by KernelDeimos** [comment]
Oops, actually I had another issue (`stmts` was an array instead of a string) that was making it give me that error instead. The error I actually get is this:
```
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELETE FROM fsentries WHERE uuid = ? LIMIT 1' at line 1
```

**Comment by KernelDeimos** [comment]
Query works brilliantly, thanks!

**Comment by sidorares** [comment]
What's in your 'vals' variable? The error comes from the client side validation before we even know what server thinks about the query
