### ISSUE TITLE
Error: Long is not a constructor 

### ISSUE THREAD

**Issue by awesome-space** [sidorares/node-mysql2#2101]
![image](https://github.com/sidorares/node-mysql2/assets/46969066/494bff44-a694-49fc-b4dd-2a1d70fad488)

**Comment by awesome-space** [comment]
version: "^3.4.3"

const pool: mysql.Pool = mysql.createPool({
  supportBigNumbers: true,
  bigNumberStrings: true,
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_DATABASE,
});


the error happend when i set supportBigNumbers and bigNumberStrings

**Comment by wellwelwel** [comment]
Hi @awesome-space, i tried to reproduce your error, but both in a basic project and a **NextJS** project, I don't catch it.

---

That's what I tried:
```json
"mysql2": "^3.4.3",
"next": "13.4.7",
```

`src/app/page.tsx`
```tsx
import mysql from 'mysql2/promise';

export default async function Home() {
  const pool = mysql.createPool({
    supportBigNumbers: true,
    bigNumberStrings: true,
    host: '',
    user: '',
    password: '',
    database: '',
  });

  const [eBig] = await pool.execute<mysql.RowDataPacket[]>('SELECT `big_number` FROM `tests`');
  const [qBig] = await pool.query<mysql.RowDataPacket[]>('SELECT `big_number` FROM `tests`');

  pool.end();

  return (
    <main>
      <h1>From execute</h1>
      { eBig.map((user) => <div key={user.big_number}>{user.big_number}</div>) }
      <hr />
      <h1>From query</h1>
      { qBig.map((user) => <div key={user.big_number}>{user.big_number}</div>) }
    </main>
  )
};

```

> Everything proceeds normally via `dev` and `build`.

**Comment by wellwelwel** [comment]
I got this error forcing the **NextJS** to version `^13.4.4`.

From **NextJS** version `13.4.5` on, it works normally.
Can you check it?

**Comment by awesome-space** [comment]
ok,it work ok when i upgrade 13.4.5,thank you
