### ISSUE TITLE
Performance on SELECT 1 is 30ms

### ISSUE THREAD

**Issue by zLevii** [sidorares/node-mysql2#2142]
I've been using mysql2 for a long time however one thing I've noticed is that `SELECT 1;` takes around 25ms on average. This query is fairly simple and I don't think it should take that long however I could be wrong due to it being ran on Node.js. I've ran the code on DBeaver (SQL Client) and got 0ms.

I'm unsure as to what the issue is but I would appreciate anyone's assistance regarding this matter. Here's the code im running:

```js
const mysql = require('mysql2');

const connection = mysql.createPool({
    host: 'localhost',
    user: 'root',
    password: '',
    database: '',
    waitForConnections: true,
    connectionLimit: 10,
    maxIdle: 5,
    idleTimeout: 30000, 
    queueLimit: 0,
    enableKeepAlive: true,
    keepAliveInitialDelay: 0
});


(async () => {

    const timings = await Promise.all(Array.from({ length: 5 }).map(() => new Promise(resolve => {
        const start = Date.now();
        connection.query('SELECT 1', () => resolve(Date.now() - start));
    })));

    console.log(timings)

})()
```

Here's what I get: 
![problem](https://github.com/sidorares/node-mysql2/assets/44142585/56d5847d-a3a9-49e5-8870-7a4435f09a11)

**Comment by sidorares** [comment]
Your timing likely includes initial connection time (there are multiple roundtrips during the connection: tcp handshake, server hello, client response, ssl upgrade - [multiple more roundtrips](https://hpbn.co/transport-layer-security-tls/#tls-handshake), optionally server auth switch request, client auth switch response, server auth switch fast track ok, client confirm, server ok)

Can you try to measure it on a single connection? Alternatively try to pre-create connections in the pool, e.i run your test 2 times:

```js
(async () => {

    await Promise.all(Array.from({ length: 5 }).map(() => new Promise(resolve => {
        const start = Date.now();
        connection.query('SELECT 1', () => resolve(Date.now() - start));
    })));

    const timings = await Promise.all(Array.from({ length: 5 }).map(() => new Promise(resolve => {
        const start = Date.now();
        connection.query('SELECT 1', () => resolve(Date.now() - start));
    })));

    console.log(timings)

})()
```

**Comment by zLevii** [comment]
Yep you're correct!

Using a single connection reduces it back down to 1 or 0ms. ```js
(async () => {

    const timings0 = await Promise.all(Array.from({ length: 5 }).map(() => new Promise(resolve => {
        const start = Date.now();
        connection.query('SELECT 1', () => resolve(Date.now() - start));
    })));

    console.log(timings0)

    const timings = await Promise.all(Array.from({ length: 5 }).map(() => new Promise(resolve => {
        const start = Date.now();
        connection.query('SELECT 1', () => resolve(Date.now() - start));
    })));

    console.log(timings)

})()
```

This one is using a single connection: 
![image](https://github.com/sidorares/node-mysql2/assets/44142585/4bab5aca-0336-47b5-a72c-5618a8a1e7b3)

This one is using a connection pool:
![image](https://github.com/sidorares/node-mysql2/assets/44142585/a6eae8df-4551-408e-830d-5e71f26638b1)

Does this mean that using a single connection is preferred over a pool? I would assume having multiple connections would be much more efficient and better?

**Comment by sidorares** [comment]
> Does this mean that using a single connection is preferred over a pool? I would assume having multiple connections would be much more efficient and better?

really depends on how your application is using db, but I'd recommend pool in most cases.

You need to consider 1) the cost of establishing a new connection (main goal of the pool is to have this cost only once per connection and then share it over the life of the server) and 2) the fact that mysql protocol is sequential. For a single connection `await Promise.all(conn.query('SLEEP 5), conn.query('SLEEP 5))` would take around 10 seconds while with pool `await Promise.all(pool.query('SLEEP 5), pool.query('SLEEP 5))` would take approx 5 seconds ( as long as you have 2 idle connections in the pool or allow to create 2 more )

**Comment by zLevii** [comment]
Sounds perfect, thank you very much for your help.
