### ISSUE TITLE
Handling `infileStreamFactory` at connection-level

### ISSUE THREAD

**Issue by loozhengyuan** [sidorares/node-mysql2#2151]
The `infileStreamFactory` option only works when calling `connection.query()` or `connection.execute()`, which is [as documented](https://github.com/sidorares/node-mysql2/blob/master/documentation/en/Extras.md#sending-tabular-data-with-load-infile-and-local-stream).

However, if I set it on a connection-level [as suggested in #1080](https://github.com/sidorares/node-mysql2/issues/1080#issuecomment-588032567), the configuration is currently not propagated when calling `connection.query()` or `connection.execute()`. Since I am using Sequelize, which only exposes the connection configuration via `dialectOptions`, there is no other way I can set the `infileStreamFactory` option.

To help move this forward, I am keen to know where the change should be made:

1. To support the `infileStreamFactory` connection option in `mysql2` and pass it when calling `Commands.Execute()`/`Commands.Query()`; or
1. To make the change in Sequelize instead to expose these options at a query-level.

Any comments/feedback is deeply appreciated, thanks!

**Comment by sidorares** [comment]
hi @loozhengyuan I'm keen to have this fixed on mysql2 side, can we start with a simple repro example?
We might to change api slightly, if `infileStreamFactory` is set on a connection/pool level it probably needs to see the query text to be able to decide which file to return, maybe pass sql as a second parameter: `(path, fullQuery) => ReadableStream`

**Comment by sidorares** [comment]
the change looks ok. We might actually not need extra sql parameter. My thinking was more of a "virtual file system": given query X and a file name Y (from that query), return a way to read the data. But in reality most use cases is just a security gate / allowlist: an INFILE query wants a file XYZ, if it's a safe path read the file under the same name from fs

Feel free to open a PR. It's probably a minor version bump ( not patch ): clients using updated mysql2 library might not work with the version before your fix.
