### ISSUE TITLE
Error when bulk insert using execute mysql2

### ISSUE THREAD

**Issue by Alland112** [sidorares/node-mysql2#2168]
When I try to insert multiple rows with execute() method I get the error:

```
"error": {
        "message": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1",
        "code": "ER_PARSE_ERROR",
        "errno": 1064,
        "sql": "INSERT INTO test_number_transaction (number, action) VALUES ?",
        "sqlState": "42000",
        "sqlMessage": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1"
}
```

It works, when I use the query() method.

Here is my code:
<details>
<summary>Table</summary>
<br>
CREATE TABLE `test_number_counter` ( 
  `type` CHAR(4) NOT NULL COLLATE 'utf8mb4_unicode_ci', 
  `start_number` INT(10) NOT NULL, 
  `last_number` INT(10) NULL DEFAULT NULL, 
  PRIMARY KEY (`type`) USING BTREE 
) 
COLLATE='utf8mb4_unicode_ci' 
ENGINE=InnoDB;

INSERT INTO `test_number_counter` (`type`, `start_number`, `last_number`) 
VALUES ('TP1', 8000000, NULL); 
INSERT INTO `test_number_counter` (`type`, `start_number`, `last_number`) 
VALUES ('TP2', 1000000, NULL); 
 
CREATE TABLE `test_number_transaction` ( 
  `number` INT(10) NOT NULL, 
  `action` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_unicode_ci', 
  PRIMARY KEY (`number`) USING BTREE, 
  UNIQUE INDEX `number` (`number`) USING BTREE 
) 
COLLATE='utf8mb4_unicode_ci' 
ENGINE=InnoDB;
</details>

```
const mysql = require('mysql2/promise');

const pool = mysql.createPool({
  host: host,
  port: port,
  user: user,
  password: pass,
  database: dbName,

  connectionLimit: pool_max,
  maxIdle: 3,
  idleTimeout: pool_idl_to,
  queueLimit: 1,

  enableKeepAlive: true,
  waitForConnections: true,
});

const addData = async (payload) => {
    // dummy payload
    payload = {
        "type": "TP1",
        "total":  100,
        "action": "Insert 1"
    };

    const batchSize = 10;

    let connection;
    try {
        connection = await pool.getConnection();
        await connection.beginTransaction();

        const { type, total, action } = payload;

        // 1. check DB, is type exist and last number
        const [counterRows] = await connection.execute(`SELECT * FROM test_number_counter WHERE type = ?`, [type]);

        const tp = counterRows[0];
        if (!tp) return { message: 'type not exist' }

        const lastNumber = tp.last_number ? tp.last_number + 1 : tp.start_number;

        // 2. generate batchNumbers data
        const sql = 'INSERT INTO test_number_transaction (number, action) VALUES ?';
        
        for (let i = lastNumber; i < lastNumber + total;) {
            const batchNumbers = [ ];

            for (let j = 0; j < batchSize; j++) {
                const row = [i, action];
                i++;
                batchNumbers.push(row);
            }

            /* ex batchNumbers when total 2:
            const batchNumbers = [ [ 800000, 'Insert 1' ], [ 800001, 'Insert 1' ] ]
            */
            
            await connection.execute(sql, [batchNumbers]);
        }

        // Commit the transaction
        await connection.commit();

        return { message: 'Data inserted' }
    } catch (error) {
        // Rollback the transaction in case of an error
        console.error('Transaction rolled back:', error);
        await connection.rollback();
        return { code: 500, error, message: 'Failed' }
    } finally {
        // Release the connection back to the pool
        if (connection) {
            connection.release();
        }
    }
}
```

my goal, i want to use connection pool, transaction, and statement so it's safe from sql injection, async-await and insert it with batch for memory consideration if input total 10,000 rows, and can handle concurrent if happen.

stack used:
nodejs: v18.16.0
mysql  Ver 8.0.33 for macos13 on arm64

dependencies:
mysql2: ^3.5.2

note: first time posting a question, any suggestions appreciated, thank you.

**Comment by wellwelwel** [comment]
Hi, @Alland112.

You have two columns, but a single param (`?`). Can you test it using `(?, ?)` instead `?`?
For example:

```sql
INSERT INTO `test_number_transaction` (`number`, `action`) VALUES (?, ?);
```

**Comment by Alland112** [comment]
Hi, @wellwelwel thank you for your response.

<details>
<summary>Table</summary>
<br>
CREATE TABLE `test_number_counter` ( 
  `type` CHAR(4) NOT NULL COLLATE 'utf8mb4_unicode_ci', 
  `start_number` INT(10) NOT NULL, 
  `last_number` INT(10) NULL DEFAULT NULL, 
  PRIMARY KEY (`type`) USING BTREE 
) 
COLLATE='utf8mb4_unicode_ci' 
ENGINE=InnoDB;
 
INSERT INTO `test_number_counter` (`type`, `start_number`, `last_number`) 
VALUES ('TP1', 8000000, NULL); 
INSERT INTO `test_number_counter` (`type`, `start_number`, `last_number`) 
VALUES ('TP2', 1000000, NULL); 
 
CREATE TABLE `test_number_transaction` ( 
  `number` INT(10) NOT NULL, 
  `action` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_unicode_ci', 
  PRIMARY KEY (`number`) USING BTREE, 
  UNIQUE INDEX `number` (`number`) USING BTREE 
) 
COLLATE='utf8mb4_unicode_ci' 
ENGINE=InnoDB;
</details>

// ex batchNumbers when total 2:
const batchNumbers = [ [ 800000, 'Insert 1' ], [ 800001, 'Insert 1' ] ]

I have run:
```
INSERT INTO `test_number_transaction` (`number`, `action`) VALUES (?, ?);
```

returned reponse:
```
Transaction rolled back: Error: Malformed communication packet. at PromisePoolConnection.execute {
  code: 'ER_MALFORMED_PACKET',
  errno: 1835,
  sql: 'INSERT INTO test_number_transaction (number, action) VALUES (?, ?)',
  sqlState: 'HY000',
  sqlMessage: 'Malformed communication packet.'
}
```

**Comment by thelindat** [comment]
The execute method won't unpack an array into a list, so you have to be explicit.

```sql
INSERT INTO `test_number_transaction` (`number`, `action`) VALUES (?, ?), (?, ?);
```

Your example should work with query, which gets formatted by the client, but is somewhat less-secure against sql injection.

**Comment by wellwelwel** [comment]
@Alland112, debugging the `[batchNumbers]`, you are setting the params as:
```js
[
  [
    [ 8000000, 'Insert 1' ],
    [ 8000001, 'Insert 1' ],
    [ 8000002, 'Insert 1' ],
    [ 8000003, 'Insert 1' ],
    [ 8000004, 'Insert 1' ],
    [ 8000005, 'Insert 1' ],
    [ 8000006, 'Insert 1' ],
    [ 8000007, 'Insert 1' ],
    [ 8000008, 'Insert 1' ],
    [ 8000009, 'Insert 1' ]
  ]
  // ...
]

``` 

But for `execute`, you need to set the `?` according with the number of params.

---

Since you created it dynamically, you will need to create your query in the same way.

Here's a basic example:

> See the comments on code 🙋🏻‍♂️

```js
const sql = 'INSERT INTO test_number_transaction (number, action) VALUES';

for (let i = lastNumber; i < lastNumber + total; ) {
  const batchNumbers = [];

  /** Expect a "(?, ?)"" for each row */
  const prepareStatements = [];

  for (let j = 0; j < batchSize; j++) {
    i++;

    /** Push the params according to `execute` method */
    batchNumbers.push(i);
    batchNumbers.push(action);
    prepareStatements.push('(?, ?)');
  }

  const finalQuery = `${sql}${prepareStatements.join(', ')}`;
  await connection.execute(finalQuery, batchNumbers);
}

await connection.commit();

/** Checking for inserted rows */
const [intertedRows] = await connection.execute(
  'SELECT COUNT(*) AS `total` FROM `test_number_transaction`'
);

return { message: 'Data inserted', total: intertedRows[0].total };
```

That prints:
```js
{ message: 'Data inserted', total: 100 }
```

And for each `i` loop the `finalQuery` will be:
```sql
INSERT INTO test_number_transaction (number, action) VALUES(?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)
```

**Comment by sidorares** [comment]
+1 to @thelindat and @wellwelwel answers
For one off query prepared statements might not worth it ( depends on the data and your paranoia to a possible injection attack ). I'd probably suggest to just use `.query()`

**Comment by Alland112** [comment]
if it's not too much to ask, where in the source can i find this understanding, since i've been looking for this solution for 2 days, am i looking at the documentation in the wrong place or am i misunderstood the documentation, i want to make sure of this.

**Comment by Alland112** [comment]
> +1 to @thelindat and @wellwelwel answers
> For one off query prepared statements might not worth it ( depends on the data and your paranoia to a possible injection attack ). I'd probably suggest to just use `.query()`

Hi, @sidorares thank you for your response.
could you please provide an explanation or source to clarify this. because I can't seem to understand why this isn't worth it or why it's better to use .query().

any explanation or source is greatly appreciated.
thank you

**Comment by sidorares** [comment]
I can try explain the difference between `.query()` and `.execute()` and it's up to you to decide which is better

query: client interpolates parameters and expands `batchNumbers` into remaining part of sql INSERT query.
execute: client sends "prepare" command first ( with same number of ? parameter placeholders as you have simple data type values in your batch data ), server returns statement id
client then sends another "execute" command with id and all the values

The "prepare" step is cached and skipped if you have exactly the same query

**Comment by sidorares** [comment]
Pointers to the source:

query interpolation: https://github.com/mysqljs/sqlstring/blob/cd528556b4b6bcf300c3db515026935dedf7cfa1/lib/SqlString.js#L66-L70

.execute: https://github.com/sidorares/node-mysql2/blob/48c2b8de9010ac18954c2c39ade410ba45dfa29d/lib/connection.js#L670-L690

prepared statements cache: https://github.com/sidorares/node-mysql2/blob/48c2b8de9010ac18954c2c39ade410ba45dfa29d/lib/commands/prepare.js#L49-L52

Prepared statements execution and parameters serialisation: https://github.com/sidorares/node-mysql2/blob/48c2b8de9010ac18954c2c39ade410ba45dfa29d/lib/packets/execute.js#L197-L206

**Comment by Alland112** [comment]
@sidorares

Awesome, really appreciate the explanation.

**Comment by Alland112** [comment]
Also thank you to

@wellwelwel and @thelindat

**Comment by neoncube2** [comment]
In case it's helpful to anyone, here's a bulk insert function that uses `execute()` and automatically splits the number of rows into chunks with fewer parameters than the MySQL max limit:

```js
async function bulkInsert(dbConnection, rows, sqlBeginning, sqlEnd) {
    if (rows.length === 0)
        return;

    const numPlaceholders = rows[0].length;

    const placeholders = '(?' + ',?'.repeat(numPlaceholders - 1) + ')';

    // 65,536 is the maximum number of placeholders in a MySQL statement
    const chunkSize = Math.floor(65536 / numPlaceholders);

    for (let i = 0; i < rows.length; i += chunkSize) {
        let numRowsToProcess = Math.min(i + chunkSize, rows.length - i);

        await dbConnection.execute(
            `${sqlBeginning} ${placeholders} ${(',' + placeholders).repeat(numRowsToProcess - 1)} ${sqlEnd}`,
            rows.slice(i, i + numRowsToProcess).flatMap(row => row)
        );
    }
}

const insertData = [
   ['Tom', 178],
   ['Jane', 176]
];

// Example:
await bulkInsert(
    dbConnection,
    insertData,
    'INSERT INTO `people` (`name`, `height`) VALUES',
    'ON DUPLICATE KEY UPDATE id = id'
);

// A more simple example:
await bulkInsert(
    dbConnection,
    insertData,
    'INSERT INTO `people` (`name`, `height`) VALUES',
    ''
);
```

Here's also a version that uses `query()` instead of `execute()`.
```js
async function bulkInsert(dbConnection, rows, sqlBeginning, sqlEnd) {
    if (rows.length === 0)
        return;

    const numPlaceholders = rows[0].length;

    // 65,536 is the maximum number of placeholders in a MySQL statement
    const chunkSize = Math.floor(65536 / numPlaceholders);

    for (let i = 0; i < rows.length; i += chunkSize) {
        let numRowsToProcess = Math.min(i + chunkSize, rows.length - i);

        await dbConnection.query(
            `${sqlBeginning} ? ${sqlEnd}`,
            [rows.slice(i, i + numRowsToProcess)]
        );
    }
}
``
