### ISSUE TITLE
TypeScript: query callback still has deprecated type OkPacket

### ISSUE THREAD

**Issue by WenisOK** [sidorares/node-mysql2#2178]
```typescript
interface orderInitializeData {
  clientList?: RowDataPacket[] | ProcedureCallPacket | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | OkPacket;

}
pool.query('select xxx from xxx')
.then((resp) => {
    response.clientList = resp[0];
  });
```
if I remove the deprecated type `OkPacket[]` and `OkPacket`, the vscode eslint throw error: Type 'RowDataPacket[] | OkPacket | ProcedureCallPacket | ResultSetHeader[] | RowDataPacket[][] | OkPacket[]' is not assignable to type 'RowDataPacket[] | ProcedureCallPacket | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | undefined'.
  Type 'OkPacket' is not assignable to type 'RowDataPacket[] | ProcedureCallPacket | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | undefined'.
    Type 'OkPacket' is missing the following properties from type 'ResultSetHeader': info, warningStatusts(2322)

**Comment by wellwelwel** [comment]
Hi @WenisOK, can you show how are you using the `orderInitializeData` interface?

About the `OkPacket` and `OkPacket[]` interfaces, you can replace them with `ResultSetHeader` and `ResultSetHeader[]`.

---

For `SELECT` without multi statements, it's usually used like:
```ts
import mysql, { RowDataPacket } from 'mysql2/promise';

interface orderInitializeData extends RowDataPacket {
  clientList?: unknown;
}

const pool = mysql.createPool({});

pool.query<orderInitializeData[]>('select xxx from xxx').then(([resp]) => {
  resp[0].clientList;
});

```

---

Also, you can follow the **Query and Execute Types** documentation [here](https://github.com/sidorares/node-mysql2/blob/master/documentation/en/TypeScript-Examples.md#query-and-execute) 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
In addition, there are a few approaches to use in this case to better illustrate:

```ts
import mysql, { ResultSetHeader, RowDataPacket } from 'mysql2/promise';

type ClientList =
  | ResultSetHeader
  | ResultSetHeader[]
  | RowDataPacket[]
  | RowDataPacket[][];

const pool = mysql.createPool({});

// This won't work and will return the same error that you have reported
pool.query('select xxx from xxx').then((resp) => {
  const response: ClientList = resp[0];
});

// This will work, but it's common to avoid using `as` when possible
pool.query('select xxx from xxx').then((resp) => {
  const response = resp[0] as ClientList;
});

/** Recommended, when you need to check manually the types returned from your query */
pool.query<ClientList>('select xxx from xxx').then((resp) => {
  const response = resp[0];
});

```

**Comment by WenisOK** [comment]
hi, @wellwelwel , i am using `orderInitializeDate` interface in here:
```typescript
interface orderInitializeData {
  clientList?: RowDataPacket[] | ProcedureCallPacket | ResultSetHeader[] | RowDataPacket[][] | OkPacket[] | OkPacket;
}
const response: orderInitializeData = {} <-- initialize a interface variable 
pool.query('select xxx from xxx')
.then((resp) => {
    response.clientList = resp[0];          <-- assignment  to interface attribute
});
```

**Comment by wellwelwel** [comment]
You can do this by indicating the expected types on `query` command.

Here's a practical example for your case 🙋🏻‍♂️

```ts
import mysql, {
  ResultSetHeader,
  RowDataPacket,
  ProcedureCallPacket,
} from 'mysql2/promise';

const pool = mysql.createPool({});

type ClientList =
  | ResultSetHeader
  | ResultSetHeader[]
  | RowDataPacket[]
  | RowDataPacket[][]
  | ProcedureCallPacket;

interface orderInitializeData {
  clientList?: ClientList;
}

const response: orderInitializeData = {};

pool.query<ClientList>('select xxx from xxx').then((resp) => {
  response.clientList = resp[0];
});
```
