### ISSUE TITLE
createPool will always connect to wrong host address

### ISSUE THREAD

**Issue by morfies** [sidorares/node-mysql2#220]
Hi, I am having a wield problem.
I send createPool with host A, but when I failed with timeout err, the err message came out with connecting host B. 
Here is my creating Pool config:
```javascript
function getConnection() {
	var obj = {
		connectionLimit: 100,  //decided by DB-server-limit/client-number
		acquireTimeout: 10000,
		host: 'localhost',//config.mysql.host,
		port: config.mysql.port,
		user: config.mysql.user,
		password: config.mysql.password,
		database: config.mysql.database,
		dateStrings: true
	};
	console.log(obj);
	var pool = mysql.createPool(obj);
	pool.on('connection', function(conn) {
		console.log('mysql::::pool connection event fired');
	});
	pool.on('enqueue', function() {
		console.log('mysql::::Waiting for available connection slot');
	});
	return pool;
}
```
And the log on connection:
![image](https://cloud.githubusercontent.com/assets/10559010/11204658/f38ec5d0-8d3b-11e5-8877-f7ba9defd06a.png)

but with some time, it timeouted with err:
![image](https://cloud.githubusercontent.com/assets/10559010/11204670/11776610-8d3c-11e5-882c-7e0400893c58.png)

I don't know where this 100.99.144.233 ip is. 
Could you please give me some advice on this.

Thanks

**Comment by sidorares** [comment]
are you sure 100.99.144.233 is not your ip address?
Can you try with '127.0.0.1' instead?
Also check your /etc/hosts file ( or try `dig localhost` )

**Comment by morfies** [comment]
Hi, this is the info:
![image](https://cloud.githubusercontent.com/assets/10559010/11205311/ad0f7d92-8d41-11e5-843b-3b6278197a5c.png)

I also tried 127.0.0.1, but same error. 
BTW, I have other app running on this same server, with the same connection config file,  the others are fine.   I really don't know what's going on here.

**Comment by morfies** [comment]
Hi sorry, all my bad, I have accidentally deleted upper directory's node_modules which I thought was left there long time ago.   I should tend to exception log earlier.
It's all because I have deleted out one module I am actually using.
I am closing this. Sorry

**Comment by sidorares** [comment]
no problems, glad you resolved it :)
