### ISSUE TITLE
TypeError: (0 , _lib_db__WEBPACK_IMPORTED_MODULE_0__.default) is not a function

### ISSUE THREAD

**Issue by nk712001** [sidorares/node-mysql2#2203]
connecting with nextjs mysql2 is giving TypeError: (0 , _lib_db__WEBPACK_IMPORTED_MODULE_0__.default) is not a function
this error

**Comment by nk712001** [comment]
import mysql from "mysql2";

export async function excuteQuery({ query, values = [] }) {
  const connection = await mysql.createConnection({
    host: process.env.MYSQL_HOST,
    port: process.env.MYSQL_PORT,
    database: process.env.MYSQL_DATABASE,
    user: process.env.MYSQL_USER,
    password: process.env.MYSQL_PASSWORD,
    socketPath: "/Applications/MAMP/tmp/mysql/mysql.sock",
  });
  try {
    await connection.connect();
    const [results] = await connection.execute(query, values);
    connection.end();
    return results;
  } catch (error) {
    throw Error(error.message);
  }
}
//db.js

**Comment by wellwelwel** [comment]
@nk712001, I'm closing this Issue as *not planned*, but feel free to reopen it and ask anything 🙋🏻‍♂️
