### ISSUE TITLE
vitest hangs without typeCast

### ISSUE THREAD

**Issue by Cellule** [sidorares/node-mysql2#2206]
Okay I know this sounds super weird, bear with me.
We just started migrating from jest to vitest in our codebase.
The machines would just hang in the CI when running them. I couldn't for the life of me figure out why.
After a lot of trial and error I narrowed it down to 1 thing.

If I pass a typeCast (empty, just calling `next()`)=> Tests run fine everything is good
If I don't pass a typeCast => Tests hangs in CI and I can see a good extra consistent 10s additional teardown (from 7s to 17s to run a few files)

I suspect vitest doesn't like something here
https://github.com/sidorares/node-mysql2/blob/949353a7aed38cffbd87028e9c7c2cb75c5555c7/lib/parsers/text_parser.js#L168-L181

This is likely a vitest specific issue, but any insights I could get here would go a long way to help me open up an issue on their side to investigate.
Note: We're still on 2.3.3, but I confirmed the issue still happens on latest 3.6.1

For reference here's the parser with typecast and without

## With typeCast
```js
(function anonymous(wrap
) {
return ((function () {
  return class TextRow {
    constructor(fields) {
      const _this = this;
      for(let i=0; i<fields.length; ++i) {
        this[`wrap${i}`] = wrap(fields[i], _this);
      }
    }
    next(packet, fields, options) {
      this.packet = packet;
      const result = {};
      // "id": LONG
      result["id"] = options.typeCast(this.wrap0, function() { return packet.parseLengthCodedIntNoBigCheck() });
      // "auth_type": STRING
      result["auth_type"] = options.typeCast(this.wrap1, function() { return packet.readLengthCodedString(fields[1].encoding) });
      // "phone_number": VAR_STRING
      result["phone_number"] = options.typeCast(this.wrap2, function() { return packet.readLengthCodedString(fields[2].encoding) });
      // "email": VAR_STRING
      result["email"] = options.typeCast(this.wrap3, function() { return packet.readLengthCodedString(fields[3].encoding) });
      // "first_name": VAR_STRING
      result["first_name"] = options.typeCast(this.wrap4, function() { return packet.readLengthCodedString(fields[4].encoding) });
      // "last_name": VAR_STRING
      result["last_name"] = options.typeCast(this.wrap5, function() { return packet.readLengthCodedString(fields[5].encoding) });
      // "img": VAR_STRING
      result["img"] = options.typeCast(this.wrap6, function() { return packet.readLengthCodedString(fields[6].encoding) });
      // "created_at": TIMESTAMP
      result["created_at"] = options.typeCast(this.wrap7, function() { return packet.parseDateTime('local') });
      // "updated_at": TIMESTAMP
      result["updated_at"] = options.typeCast(this.wrap8, function() { return packet.parseDateTime('local') });
      // "activated_at": DATETIME
      result["activated_at"] = options.typeCast(this.wrap9, function() { return packet.parseDateTime('local') });
      // "last_visited_at": DATETIME
      result["last_visited_at"] = options.typeCast(this.wrap10, function() { return packet.parseDateTime('local') });
      // "last_invite_sent_at": DATETIME
      result["last_invite_sent_at"] = options.typeCast(this.wrap11, function() { return packet.parseDateTime('local') });
      return result;
    }
  };
})())
})
```

## Without typeCast
```js
(function anonymous(
) {
return ((function () {
  return class TextRow {
    constructor(fields) {
    }
    next(packet, fields, options) {
      this.packet = packet;
      const result = {};
      // "id": LONG
      result["id"] = packet.parseLengthCodedIntNoBigCheck();
      // "auth_type": STRING
      result["auth_type"] = packet.readLengthCodedString(fields[1].encoding);
      // "phone_number": VAR_STRING
      result["phone_number"] = packet.readLengthCodedString(fields[2].encoding);
      // "email": VAR_STRING
      result["email"] = packet.readLengthCodedString(fields[3].encoding);
      // "first_name": VAR_STRING
      result["first_name"] = packet.readLengthCodedString(fields[4].encoding);
      // "last_name": VAR_STRING
      result["last_name"] = packet.readLengthCodedString(fields[5].encoding);
      // "img": VAR_STRING
      result["img"] = packet.readLengthCodedString(fields[6].encoding);
      // "created_at": TIMESTAMP
      result["created_at"] = packet.parseDateTime('local');
      // "updated_at": TIMESTAMP
      result["updated_at"] = packet.parseDateTime('local');
      // "activated_at": DATETIME
      result["activated_at"] = packet.parseDateTime('local');
      // "last_visited_at": DATETIME
      result["last_visited_at"] = packet.parseDateTime('local');
      // "last_invite_sent_at": DATETIME
      result["last_invite_sent_at"] = packet.parseDateTime('local');
      return result;
    }
  };
})())
})
```

**Comment by sidorares** [comment]
hm, strange indeed. Could you try to reduce the issue to a smallest self contained example? That way I can try to debug it locally

**Comment by Cellule** [comment]
I'll give it a try, our project is pretty big so it's hard to know exactly what's causing the issue. I suspect maybe 1 particular data type of one of our MySQL table is at fault so I'll try to reduce that then see if I can get a minimal repro in a public repo

**Comment by Cellule** [comment]
Alright, so I think I managed to repro in a more isolated environment.
Somehow in that repo typeCast doesn't seem to make a difference like it does in my project, but maybe the issue is related.
I managed to repro in node without vitest, let me know if this helps.

https://github.com/Cellule/mysql2-vitest-hang-repro
You'll need to adjust the config to a mysql database in `src/db.js`

Then you can run `npm run cli-slow`
You should notice a long time to teardown the process somehow vs the `npm run cli-quick` one

<img width="423" alt="image" src="https://github.com/sidorares/node-mysql2/assets/4157103/faf25fab-10f2-44ab-afdd-498c5a9a358d">

**Comment by sidorares** [comment]
can't reproduce, both run cli-slow and cli-quick finish in a reasonable short time:

```
laplace@Andreys-MacBook-Pro mysql2-vitest-hang-repro % npm run cli-quick

> mysql2-vitest-hang-repro@1.0.0 cli-quick
> node src/hang-cli.js 200

Starting
execution: 383.165ms
Tearing Down
done: 4.221ms
laplace@Andreys-MacBook-Pro mysql2-vitest-hang-repro % npm run cli-slow 

> mysql2-vitest-hang-repro@1.0.0 cli-slow
> node src/hang-cli.js 250

Starting
execution: 458.581ms
Tearing Down
done: 2.396ms
laplace@Andreys-MacBook-Pro mysql2-vitest-hang-repro % npm run cli-slow

> mysql2-vitest-hang-repro@1.0.0 cli-slow
> node src/hang-cli.js 250

Starting
execution: 481.298ms
Tearing Down
done: 2.105ms
```

what's your node version? I wonder if this is related to https://github.com/sidorares/node-mysql2/issues/2090
Can you try running your example with `--noopt` ? ( see https://github.com/sidorares/node-mysql2/issues/2090#issuecomment-1612426932 )

**Comment by Cellule** [comment]
So I was running with node 16.10
I repro'd on node 18.17.1
I couldn't repro as-is on node 20.6.1 but if I increase the iteration count to about 500 it reproes there too

`--noopt` and `--max-opt=2` seems to fix the issue event at 10000 iterations

<img width="605" alt="image" src="https://github.com/sidorares/node-mysql2/assets/4157103/e24401cf-3832-496e-aae1-97341e150767">


I have also confirmed that `--noopt` solves the issue on my project as well

So I guess this issue is a duplicate of #2090 
You can close as duplicate in this case and I'll track the other issue

**Comment by sidorares** [comment]
@Cellule if you have capacity feel free at last 2 options. Unfortunately I don't have a lot of free time right now so to ETAs from my side, but happy to guide / review PRs if someone wants to help
