### ISSUE TITLE
Upgrade Amazon RDS CA Certificates for SSL Connections

### ISSUE THREAD

**Issue by jhbarrantes** [sidorares/node-mysql2#2212]
Recently Amazon upgraded the CA bundle for RDS Aurora Mysql. It will be great if this can be updated into the project.

Info: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

Latest global bundle, with all certificates: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem

Thanks!

**Comment by rxd90** [comment]
Having the same issue here, bumping for awareness.

**Comment by jonasduever** [comment]
Related:
- https://github.com/sidorares/node-mysql2/pull/2131
- https://github.com/sidorares/node-mysql2/issues/2172#issuecomment-1680802232

**Comment by scriptsure** [comment]
Bump

**Comment by sksethi25** [comment]
Thank you for this wonderful library. waiting for update on this

**Comment by Emiton** [comment]
Bumping this as well. Will #2131 be merged anytime soon. Or do additional changes need to be made? @sidorares. Is there anything we can do to help?

**Comment by HolyNitzan** [comment]
Any updates on this? 🤟

**Comment by dav-sap** [comment]
hey, looking for the same thing

**Comment by sidorares** [comment]
should be fixed with https://github.com/sidorares/node-mysql2/pull/2131
