### ISSUE TITLE
Bun pool getConnection() error object

### ISSUE THREAD

**Issue by melroy89** [sidorares/node-mysql2#2221]
When creating a pool connection (and the database is down), of course this fails to connect during the `getConnection()`.

However, the output of the error parameter of `getConnection()` (error object) is very different under Bun. Under TypeScript `err` is defined as type: `NodeJS.ErrnoException`.

Please, help me understand if this is an issue in mysql2 or in [mysqljs](https://github.com/mysqljs/mysql) (where I can't create an issue) or should it be fixed in Bun, then I will create an issue at the Bun project.

## Under Bun:

message: `Failed to connect`
errno: `0`
Printing err to console: 

```
ECONNREFUSED: Failed to connect
 syscall: "connect"
```

(I think the message doesn't contain enough info for instance. Nor is the output compatible with Node)

## Under NodeJS:

message: `connect ECONNREFUSED 127.0.0.1:3306`
errno: `-111`
Printing err to console: 

```
{
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true
}
```

**Comment by dougwilson** [comment]
The error comes from Node.js or Bun; this module is just passing it through.

**Comment by melroy89** [comment]
> The error comes from Node.js or Bun; this module is just passing it through.

OK so.. I think I should report this at https://github.com/oven-sh/bun/ instead. But `mysql2` can still update the types to be less NodeJS specific?

**Comment by dougwilson** [comment]
As far as the types go, that is fair. Should match whatever the platform error type is I assume.

**Comment by melroy89** [comment]
(as you might can see, I created an issue ticket at Bun as well)

**Comment by melroy89** [comment]
> As far as the types go, that is fair. Should match whatever the platform error type is I assume.

Yes, so now the type MySQL2 is saying is this: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3866583ca9244b47878fa0ac8cfdfb23eb2ef0c5/types/node/globals.d.ts#L222

I guess this need to be an "or" (`|`) with whatever the interface type definition of Bun might be... If any at this moment in time.

**Comment by sidorares** [comment]
not sure if mysql2 still relies on DefinitelyTyped definitions, we might have everything locally under `/typings` folder. I can't find any references to errno in the node documentation, it might be safer to use `code` instead in your logic ( which is consistent between bun/node )

Maybe @wellwelwel can help with the answer "what is the source of errno typings". My preference would be to remove it from types if the use is undocumented and discouraged

**Comment by wellwelwel** [comment]
@sidorares, this `ErrnoException` comes from **@types/node**, probably every time when an `Error` instance is created:

https://github.com/sidorares/node-mysql2/blob/001a18370462ab6c531995d576ddc3d9ae4ef358/lib/connection.js#L406-L409

That reflects on the types:
https://github.com/sidorares/node-mysql2/blob/001a18370462ab6c531995d576ddc3d9ae4ef358/typings/mysql/lib/Connection.d.ts#L360

> These events comes from `EventEmitter` (**@types/node**), that the `Connection` interface extends.

---

If there is any incompatibility in `Error` instances between **NodeJS** and **Bun**, I think this can be reported as a known **NodeJS** incompatibility.

---

> I guess this need to be an union type (|) with whatever the interface type definition of Bun

@melroy89, what would be the equivalent type of `NodeJS.ErrnoException` in **Bun**?

---

> Regardless, I'm not familiar with **Bun** 🙋🏻‍♂️

**Comment by melroy89** [comment]
> @melroy89, what would be the equivalent type of `NodeJS.ErrnoException` in **Bun**?

Uh what is the type you get back from Bun? 

I think it should be defined in this repo: https://github.com/oven-sh/bun/blob/main/packages/bun-types. I hope :)

**Comment by melroy89** [comment]
Seeing the [latest reply](https://github.com/oven-sh/bun/issues/5984#issuecomment-1732611465) maybe Bun will solve this fully at there side?

**Comment by wellwelwel** [comment]
At first, I tried to find the source of the `ErrnoException` in the **Bun** types, but it isn't declared there.

By looking at where the types come from (source files), I noticed that common **NodeJS** types (`net`, `os`, `stream`, etc.) come from `@types/node`.

An example can be seen here:
> https://github.com/oven-sh/bun/blob/43f092807bee13e036048f977172938ab2de331e/packages/bun-types/net.d.ts#L13

```ts
/**
 * @see [source](https://github.com/nodejs/node/blob/v18.0.0/lib/net.js)
 */
```

Also:
> https://github.com/oven-sh/bun/blob/43f092807bee13e036048f977172938ab2de331e/packages/bun-types/net.d.ts#L17

```ts
import { Abortable, EventEmitter } from "node:events";
```

---

Then, I think that **Bun** intends to maintain compatibility with **NodeJS** global types and this comment (https://github.com/oven-sh/bun/issues/5984#issuecomment-1732611465) seems to confirm that.

---

That said:
1. Since **Bun** also uses **@types/node** for **NodeJS** globals, it excludes the possibility to use union types.
2. I believe it's resolved from **MySQL2** side and the progress of this issue can be followed at https://github.com/oven-sh/bun/issues/5984.

**Comment by wellwelwel** [comment]
> Complementing

**Bun** has its own interface for `ErrnoException`:

> https://github.com/oven-sh/bun/blob/43f092807bee13e036048f977172938ab2de331e/packages/bun-types/globals.d.ts#L3019-L3024

```ts
interface ErrnoException extends Error {
  errno?: number | undefined;
  code?: string | undefined;
  path?: string | undefined;
  syscall?: string | undefined;
}
```

And this is the `ErrnoException` from **@node/types**:
```ts
interface ErrnoException extends Error {
  errno?: number | undefined;
  code?: string | undefined;
  path?: string | undefined;
  syscall?: string | undefined;
}
```

It confirms what I said bellow.

---

And as said in https://github.com/oven-sh/bun/issues/5984#issuecomment-1732611465: 
> we likely need to revisit the error printer for Bun to ensure these extra properties get shown.

@sidorares, I will close this issue as _not planned_.

**Comment by melroy89** [comment]
I understand let's see the outcome from bun. Farwellwelwel.
