### ISSUE TITLE
SSL issues with Bun + drizzle

### ISSUE THREAD

**Issue by Djboy08** [sidorares/node-mysql2#2227]
https://github.com/Djboy08/mysqldriver-issue/tree/main

This is the GitHub repo where I made a minimum viable issue.

When you have the DB_URL set up properly (in the readme) and you try to connect to the database with drizzle-orm using the bun runtime, the following error occurs:
![image](https://github.com/sidorares/node-mysql2/assets/34119605/647b0bcb-5af4-4ba8-8cba-bd5a764de3fc)

This seems to be happening due to the `ssl={"rejectUnauthorized":true}` at the end of the connection url.

Thanks!

**Comment by Djboy08** [comment]
May or may not relate to https://github.com/sidorares/node-mysql2/pull/1805

**Comment by sidorares** [comment]
@Djboy08 drizzle-kit bundles as a dependency old mysql2 ( v2.2.3, before Bun & ssl fixes ) - see https://www.npmjs.com/package/drizzle-kit?activeTab=code index.cjs

![image](https://github.com/sidorares/node-mysql2/assets/173025/8e0ea040-0a01-4ad3-a092-667b6e1f6f02)

the fix thus is on the drizzle side - bump mysql2 version, rebuild and publish

**Comment by sidorares** [comment]
I'm not sure if there is a way to create a connection in your code instead drizzle-kit managing it. If possible, similar to drizzle-orm maybe try that first:

```js
import { drizzle } from "drizzle-orm/mysql2";
import { sql } from 'drizzle-orm' 
import mysql from "mysql2/promise";
 
const connection = await mysql.createConnection({ uri: process.env.DB_URL }); 
const db = drizzle(connection);
const results = await db.execute(sql`select 1 + ${1} as result`);
console.log(results[0]);
connection.close();
```
 
the above example from drizzle docs works fine with planetscale DB_URL
