### ISSUE TITLE
how to bluebird promisifyAll mysql2

### ISSUE THREAD

**Issue by thewillhuang** [sidorares/node-mysql2#223]
Hello,
I'm in the process of converting my current implementation of node-mysql driver to mysql2 and fully utilize promises (bluebird). i figured the upgrade to mysql 2 should be a simple matter of changing 'mysql' to 'mysql2' but i am getting some errors and figured i'd ask for some help.

currently i have this setup  for node-mysql
```js
const Promise = require('bluebird');
const mysql = require('mysql');
const Pool = require('mysql/lib/Pool');
const options = { ... };
const Connection = require('mysql/lib/Connection');
Promise.promisifyAll([Pool, Connection]);
const pool = mysql.createPool(options);
module.exports = pool;
```
i tried
```js
Promise.promisifyAll(require('mysql2'));
```
i also tried
```js
const Promise = require('bluebird');
const mysql = require('mysql2');
const Pool = require('mysql2/lib/Pool');
const Connection = require('mysql2/lib/Connection');
Promise.promisifyAll([Pool, Connection]);
const options = { ... };
const pool = mysql.createPool(options);
module.exports = pool;
```
both gives me the error below.
```sh
TypeError: pool.getConnectionAsync is not a function
```
so the question is, how do i promisifyAll this module? Any help would be great, thanks!

**Comment by sidorares** [comment]
Hi!

I'm trying to keep file names lower case, and path to pool is `lib/lib/pool.js`, so you should be able to do 

```js
const mysql = require('mysql2');
const Pool = require('mysql2/lib/pool');
const Connection = mysql.Connection; // I should probably export mysql.Pool same way - see https://github.com/sidorares/node-mysql2/blob/master/index.js#L11 
```

**Comment by sidorares** [comment]
not sure where `getConnectionAsync` comes from, don't see it in node-mysql/lib/Pool.js

**Comment by thewillhuang** [comment]
hey, thank you for responding so fast, it was the caps that broke it!! thank you, the performance is amazing..

**Comment by thewillhuang** [comment]
```js
'use strict';

const Promise = require('bluebird');
const mysql = require('mysql2');
const options = { ... };
const Pool = require('mysql2/lib/pool');
const Connection = require('mysql2/lib/connection');
Promise.promisifyAll([Pool, Connection]);
// long stack trace for debug
Promise.longStackTraces();
const pool = mysql.createPool(options);
module.exports = pool;
```

working version

**Comment by sidorares** [comment]
:+1:

**Comment by minkesh** [comment]
@sidorares `getConnectionAsync` is created once you promisify the function. It will provide the same functionality as `getConnection` just that it will return the promise object than executing the callback.

**Comment by sidorares** [comment]
@minkesh you can use built-in promisified connection wrapper together with Bluebird

**Comment by minkesh** [comment]
@sidorares yeah, that can be used as well but it is fairly new, I was just answering your doubt about  `getConnectionAsync` function :)

**Comment by sidorares** [comment]
@minkesh it's just a thin wrapper, main flow logic still happens inside promise ( built-in or bluebird, up to you )
