### ISSUE TITLE
Net.connect is not a function

### ISSUE THREAD

**Issue by BorjaRuizReverter** [sidorares/node-mysql2#2231]
Dear Andrey,
I have been trying to connect my react app to a database that I host in planetscale using this node-mysql2 package, but there is no way. 

Everything works fine with a quick python script I made for that, but when I use mysql2 in javascript I have to deal with lots of issues, mostly regarding webpack. I manage to circumvent these webpack issues, but in the end I stumble upon the mysql.createConnection() method. 

In fact, a simple connection as you guys propose in the readme as this:
```js
var mysql = require('mysql2');

var conn = mysql.createConnection({
  host: "HOSTNAME",
  user: "USERNAME",
  password: "PASSWORD",
  database: "DATABASE",
  ssl: {
    rejectUnauthorized: true
  }
});
```
ends up in this kind of error (Net.connect is not a function). 

(This Net.connect() is found inside the class Connection inside mysql2/lib/connection.js)

![image_2023-10-04_184551416](https://github.com/sidorares/node-mysql2/assets/35275075/eb4df273-30b8-47f9-8a90-f47f2040862b)

**Comment by sidorares** [comment]
looks like the code is called from the browser runtime

Can you describe a bit more your enviroment/frameworks you are using? The main problem is outside of the scope of the library (mysql2 is supposed to run in node.js/bun/deno runtime, with access to module system and standard APIs like [net](https://nodejs.org/dist/latest-v20.x/docs/api/net.html)) but maybe I still can suggest the solution

**Comment by BorjaRuizReverter** [comment]
Yep... you are right, Andrey. 

Definitely, I cant use mysql2 in the front-end.

I suggest to explicitly comment about it in the Readme. Otherwise noobs in FE frameworks (like me) are going to suffocate you or the stackoverflow, lol...

It is all ok then. I know now what caused the problem and guess how to resolve it. 

Thanks indeed for your quick & kind support!
