### ISSUE TITLE
Error: Too many connections

### ISSUE THREAD

**Issue by dspencer926** [sidorares/node-mysql2#2239]
I have an app that's been deployed for 9 months with no issues.  All of a sudden it's not working and I'm getting:  

```
Error: Too many connections
at PromisePool.query (/opt/flow-reloaded/node_modules/mysql2/promise.js:351:22)
at /opt/flow-reloaded/node_modules/express-mysql-session/index.js:384:30
at new Promise (<anonymous>)
at MySQLStore.query (/opt/flow-reloaded/node_modules/express-mysql-session/index.js:381:10)
at /opt/flow-reloaded/node_modules/express-mysql-session/index.js:170:16
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I'm using express-mysql-session for user sessions, but I'm not sure that's the issue.  I originally had the DB pool set up like this:

```
const mysql = require('mysql2/promise');
const db = mysql.createPool({
  database: <db-name>,
  host: <hostname>,
  port: <port>,
  user: <user>,
  password: <password>,
});


module.exports = db;
```

And import it like `const db = require('../../db/config');`
in order to make queries, for example: `await db.query('SELECT * FROM products;');`

I'm assuming the too many connections issue has to do with the fact that I'm using a pool and maybe the connections aren't being closed.  So I added `connectionLimit: 10,` to the DB config, but I'm still getting the same issue.

Should I be closing these connections in my code?  Any help is appreciated!

**Comment by channaveer** [comment]
@dspencer926 Can you please share how were you able to resolve this issue. I am facing the same.

**Comment by zoobibackups** [comment]
same issue

**Comment by zoobibackups** [comment]
this is the same for me https://github.com/sidorares/node-mysql2/issues/2362#issuecomment-2506057653

**Comment by dspencer926** [comment]
> this is the same for me [#2362 (comment)](https://github.com/sidorares/node-mysql2/issues/2362#issuecomment-2506057653)

This was a while ago but I seem to remember it had something to do with a setting on the database side and so I had to contact the db administrator, and he had made some type of update that fixed it.  I wish I could help you more ... I'd try talking to the db administrator though
