### ISSUE TITLE
Error in pool.js

### ISSUE THREAD

**Issue by sapics** [sidorares/node-mysql2#226]
Thank you for your great work!
It's really fast!

Currently I am using node-mysql2 with pool feature.
I had an error `TypeError: this._allConnections.splice is not a function` at https://github.com/sidorares/node-mysql2/blob/master/lib/pool.js#L161
I guess that double-ended-queue api dose not have `splice` function, from https://github.com/petkaantonov/deque.

**Comment by sidorares** [comment]
yes, you are right ( and that needs to be fixed )

could you post full stack trace so I know who is calling `removeConnection` ?

**Comment by sapics** [comment]
Thank you for quick check!
This is my current log.
```console
TypeError: this._allConnections.splice is not a function
at Pool._removeConnection (/var/www/development/debug3/nodejs/node_modules/mysql2/lib/pool.js:161:28)
at PoolConnection._removeFromPool (/var/www/development/debug3/nodejs/node_modules/mysql2/lib/pool_connection.js:53:8)
at emitOne (events.js:82:20)
at PoolConnection.emit (events.js:169:7)
at PoolConnection.Connection._notifyError (/var/www/development/debug3/nodejs/node_modules/mysql2/lib/connection.js:167:16)
at Socket.<anonymous> (/var/www/development/debug3/nodejs/node_modules/mysql2/lib/connection.js:122:16)
at emitNone (events.js:72:20)
at Socket.emit (events.js:166:7)
at endReadableNT (_stream_readable.js:905:12)
at doNTCallback2 (node.js:441:9)
```

**Comment by sidorares** [comment]
ok, so it looks like it is called only if there is fatal error in connection ( like network is down )

Maybe mark it with some sort of  "skip when `.shift()` next time" flag instead of actually trying to remove from array/queue?

**Comment by sapics** [comment]
Sorry, i am not good at English :)
I have not undestood well, your writing looks good, but it seems complicated than before, isn't it?
For example, number of _allConnections are bigger than before, thus, we need to fix connectionLimit?

I have another worry about, `sort`, because there are not `sort` in `double-ended-queue`.
Thus, it needs `new Queue()` for sorting.

How about following?
```javascript
for (i = 0; i < this._allConnections.length; i++) {
  if (this._allConnections[i] === connection) {
    this._allConnections.splice(i, 1);
    break;
  }
}
```
to
```javascript
var cons = new Queue();
for (i = 0; i < this._allConnections.length; i++) {
  if (this._allConnections[i] !== connection) {
    cons.push(this._allConnections[i]);
  }
}
this._allConnections = cons;
```
or using array
```javascript
var arr = this._allConnections.toArray(),
    index = arr.indexOf(connection);
if (index === 0) {
  this._allConnections.shift();
} else if (index !== -1) {
  arr.splice(index, 1);
  this._allConnections = new Queue(arr);
}
```
or it might be also possible to use built-in array.

Sorry, my bad English.

**Comment by sidorares** [comment]
filtering is a possible way ( though it's slower than just setting a flag )
and yes, with flag solution we need to adjust number of open healthy connections by subtracting number of flagged as fatal

**Comment by sapics** [comment]
I am agree with you, your method would be faster :)

**Comment by sidorares** [comment]
I probably won't have time to look at this until weekend, feel free to try to implement yourself

**Comment by sapics** [comment]
I see! Thank you very much for your time!
