### ISSUE TITLE
Documentation missing simple examples. How to insert using variables etc ...

### ISSUE THREAD

**Issue by kevin-wad** [sidorares/node-mysql2#2263]
Documentation is missing simple examples. 
How to insert using variables etc ...
The mysql has much more documentation. If it was up to me I would stickwith npm mysql but for this specific project I have to use mysql2 and it is a real pain to implement!

**Comment by wellwelwel** [comment]
When you say "insert using variables", are you asking for an example like this, but with `INSERT`?

https://github.com/sidorares/node-mysql2/blob/fa47d0b0c46b3f5e79b7adae283bb78575298429/examples/simple-select.js#L23-L29

---

From **mysql2** documentation: "_MySQL2 is mostly API compatible with [mysqljs](https://github.com/mysqljs/mysql) and supports majority of features._".

Following this approach, [mysqljs](https://github.com/mysqljs/mysql) has this [example](https://github.com/mysqljs/mysql#escaping-query-values):
```js
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'
```

This example will work for both [mysqljs](https://github.com/mysqljs/mysql) and **mysql2** 🧙🏻

---

> Documentation is missing simple examples.

I think we can improve it, especially for `execute` and promise-based examples.

---

You can also compare some of the differences between them:
- [History and Why MySQL2](https://github.com/sidorares/node-mysql2#history-and-why-mysql2)
- [API and Configuration](https://github.com/sidorares/node-mysql2#api-and-configuration)

**Comment by sidorares** [comment]
> "MySQL2 is mostly API compatible with [mysqljs](https://github.com/mysqljs/mysql) and supports majority of features.".

When this line was added years ago mysqljs/mysql was way more popular than mysql2, and it made sense to "delegate" documentation in that way. Maybe it's time now to have full api docs in the readme. Good example: https://github.com/mscdex/ssh2

Also would be great to add [nextra](https://nextra.site/) or [docusaurus](https://docusaurus.io/) based documentation site (main api, same as in readme + examples / gotchas / common mistakes / best practices / FAQ etc )

**Comment by wellwelwel** [comment]
Hey @sidorares, how would it be to set up a website (*MDX*) in practice (same repository using a "`website`" directory, for example)?

Personally, I love the way how [docusaurus](https://github.com/facebook/docusaurus) does it and it naturally comes with a beautiful layout.

> I really believe that MySQL2 deserves it 🦖✨

**Comment by sidorares** [comment]
Yes, in the subfolder of the same repo, so that the docs are in sync with the code

**Comment by wellwelwel** [comment]
If you're okay with that, we can dedicate a separate branch to do it.

**Comment by sidorares** [comment]
> If you're okay with that, we can dedicate a separate branch to work on it.

Sure, I'm OK with that

**Comment by wellwelwel** [comment]
One approach I've considered interesting is using **tabs** to show the variations of a same section, for example:

`Installation (JavaScript) | Installation (TypeScript)`
`Some Method (Promise) | Some Method (Callback)`

---

The same idea for **sidebar**, for example in "Examples" section, we can use a parent `Queries`, then:
- Queries
  - `INSERT`
  - `SELECT`
  - `UPDATE`
  - etc.

---

Also, on the main page, keep it focused on documentation.

---

Here's a test using [docusaurus](https://github.com/facebook/docusaurus):

https://github.com/sidorares/node-mysql2/assets/46850407/518fb501-4530-4b31-9f8d-50f52a5c6141

---

**Notes:**
 
- Every page would be a **.md** or **.mdx** file in `website/docs` path.
  - This would allow pages to be created dynamically when a new file is added to the directory.
- We can use the current documentation and examples to start it.
  - Naturally, increasing more complete documentation in the long term.

---

What do you think? 🌞✨

**Comment by sidorares** [comment]
> What do you think? 🌞✨

😍

**Comment by sidorares** [comment]
#2279 fixes this

**Comment by wellwelwel** [comment]
> #2279 fixes this

---

**Just complementing:**

https://github.com/sidorares/node-mysql2/blob/323ab122331debebd8038e096a1bc18bdc3dca70/website/docs/examples/queries/prepared-statements/insert.mdx#L21-L32

- [sidorares.github.io/node-mysql2/docs/examples/queries/prepared-statements/insert](https://sidorares.github.io/node-mysql2/docs/examples/queries/prepared-statements/insert)

---

For now (#2337), there are examples of `INSERT`, `SELECT`, `UPDATE` and `DELETE` for both simple queries and using Placeholders / Prepared Statements, also for `createConnection`, `createPool` and `createPoolCluster` and its variations (such as connecting using URI string and options, SHA1, SSL, etc. for each connection) 🧙🏻
