### ISSUE TITLE
I can't install in my project on MacBook  please help me

### ISSUE THREAD

**Issue by methavee11** [sidorares/node-mysql2#2298]
npm-v = 9.8.1,node-v=v18.18.2
my project
[Red_TU.zip](https://github.com/sidorares/node-mysql2/files/13465718/Red_TU.zip)
-----------------------------------------------------

npm WARN tarball tarball data for @types/mysql2@git+ssh://git@github.com/types/mysql2.git#89378b2cb3974ea8cdd1d633b8f056e54e5d2384 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for @types/mysql@git+ssh://git@github.com/types/mysql.git#c26b1bc2bac17010081455e3127a90fb2eafcec9 (null) seems to be corrupted. Trying [again.]
npm WARN tarball tarball data for @types/mysql2@git+ssh://git@github.com/types/mysql2.git#89378b2cb3974ea8cdd1d633b8f056e54e5d2384 (null) seems to be corrupted. Trying again.
npm WARN tarball tarball data for @types/mysql@git+ssh://git@github.com/types/mysql.git#c26b1bc2bac17010081455e3127a90fb2eafcec9 (null) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall mkdir
npm ERR! path /path-to-tmp
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, mkdir '/path-to-tmp'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Log files were not written due to an error writing to the directory: /path-to-tmp/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal

**Comment by wellwelwel** [comment]
Hi @methavee11, looking the logs, are you trying to install the typings from `@types/mysql2`?

You can install mysql2 to use with TypeScript by running:

```bash
npm i mysql2
npm i -D @types/node
```

Please, see [documentation/en/TypeScript-Examples.md#installation](https://github.com/sidorares/node-mysql2/blob/master/documentation/en/TypeScript-Examples.md#installation) 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
Also, you may need to remove `@types/mysql2` from **package.json**:
```bash
npm uninstall @types/mysql2
```

**Comment by wellwelwel** [comment]
I'm closing this Issue, but feel free to reopen it and ask anything 🙋🏻‍♂️
