### ISSUE TITLE
Numeric / string query parameters

### ISSUE THREAD

**Issue by chrisveness** [sidorares/node-mysql2#231]
This seems so basic, I'm not sure I've not misunderstood something, but...

If I have a table with an integer field, and I call `yield db.query('select * from mytable where myid = ?', 'x')`, it seems it returns me the row where `myid` is 0, as if the string is being coerced to a zero.

It doesn't seem to me it should do this. Is it by design? Am I doing something dumb?

I'm using mysql-co@0.0.4 / mysql2@0.15.8.

**Comment by sidorares** [comment]
I think the problem is that you to pass array of parameters

```
yield db.query('select * from mytable where myid = ?', ['x'])
yield db.query('select * from mytable where myid = ? and otherid = ?', ['x', 'y'])
```

**Comment by dougwilson** [comment]
@chrisveness , I think you just may misunderstand how MySQL itself works. The string `'x'` casts to the number 0 in MySQL. Here is the expression you can use to see the behavior:
```
mysql> SELECT CONVERT('x', UNSIGNED);
+------------------------+
| CONVERT('x', UNSIGNED) |
+------------------------+
|                      0 |
+------------------------+
```

**Comment by sidorares** [comment]
oh, you are right @dougwilson Single parameter converted to array, that was not an issue

**Comment by chrisveness** [comment]
OMG, I never realised that

    select * from mytable where myid = "somestring"

will return

    +------+-------------+
    | myid | otherfield  |
    +------+-------------+
    |    0 | other value |
    +------+-------------+

Live and learn!

However, I think I'm still a bit confused. Am I correct in finding that

    yield db.query('select * from mytable where myid = ?', Number('x'));

will throw "You have an error in your SQL syntax ... near '?' at line 1", and that

    yield db.query('select * from mytable where myid = ?', [ Number('x') ]);

will throw "Unknown column 'NaN' in 'where clause'"?

(Unless my tests are going wrong, it's late here!)

**Comment by sidorares** [comment]
could you try test with vanilla non-co library? Parameters hadnling might be different in -co one, I'll double check there as well

**Comment by sidorares** [comment]
the behaviour you see is because of the line https://github.com/sidorares/node-mysql2/blob/v0.15.8/lib/connection.js#L396

```js
var rawSql = this.format(options.sql, options.values || []);
```
because NaN is falsy it is replaced with `[]` ( as if there is no parameters )

**Comment by sidorares** [comment]
@dougwilson do you have tests in node-mysql with NaN as parameter ? I think at the moment both node-mysql and node-mysql2 format `"select ? as a", [ NaN ]` as "select NaN as a" which does not make much sense from mysql point of view

**Comment by dougwilson** [comment]
Hi @sidorares :

https://github.com/felixge/node-mysql/blob/0b4518aaead856d443b78db3b30e524ab3c86afe/test/unit/protocol/test-SqlString.js#L128

and behavior is documented in https://github.com/felixge/node-mysql#escaping-query-values

**Comment by sidorares** [comment]
Thanks @dougwilson - haven't seen that documented.

> MySQL does not support these, and trying to insert them as values will trigger MySQL errors until they implement support.

I would argue that it's better to return callback with error immediately so that if I print stack trace it'll point to my code that generated NaN parameter, rather than wait response from server which is going to be error anyway

**Comment by dougwilson** [comment]
Hi @sidorares , the behavior was there from before I even started maintaining the module, haha, I was just pointing out it was definitely done intentionally. Just glancing in a few other SQL libraries, ones that handle `NaN` and `Infinity` send them to the database as `NULL`.

**Comment by sidorares** [comment]
yes, I know this :)

I don't think converting NaN and Infinity to NULL is right solution, but what we have ( insert NaN as part of sql string ) seems wrong to me

**Comment by dougwilson** [comment]
Well, the reason they convert to `NULL` is because you can actually insert `NaN` into the column from a procedure, but it ends up as `NULL`, because internally if you manage to get a IEEE `NaN` in the column, MySQL will treat it like `NULL` for most operations (except replication).

**Comment by dougwilson** [comment]
Here is a simple example of how MySQL thinks of these values:
```
mysql> SELECT 0/0;
+------+
| 0/0  |
+------+
| NULL |
+------+

mysql> SELECT CAST('-1e500' AS DECIMAL(10,6));
+---------------------------------+
| CAST('-1e500' AS DECIMAL(10,6)) |
+---------------------------------+
|                    -9999.999999 |
+---------------------------------+

mysql> SELECT CAST('1e500' AS DECIMAL(10,6));
+--------------------------------+
| CAST('1e500' AS DECIMAL(10,6)) |
+--------------------------------+
|                    9999.999999 |
+--------------------------------+
```

Basically, `NaN` = `NULL`, `Infinity` = the max value for the given type, `-Infinity` = the min value for the given type.

**Comment by sidorares** [comment]
Interesting, thanks for detailed explanation, with this in mind converting to `NULL` is probably a good option

**Comment by sidorares** [comment]
I wonder how 0/0 is set over binary protocol ( it is serialised as IEEE double there )

**Comment by dougwilson** [comment]
Yea, we should test that. `NaN`, `Infinity`, and `-Infinity` all have special representations in IEEE doubles, so it would be interesting to see exactly what happens when those are sent over the binary protocol. Could even test to see if MySQL thinks there is a different between a quiet NaN and a signaling NaN.

**Comment by sidorares** [comment]
nope, it's not preserved, NaN is returned as single byte '0xfb' - mysql NULL, not as <Buffer 00 00 00 00 00 00 f8 7f> double

```
Add command: Connection
Add command: query
0 undefined ==> Connection#handshakeInit(0,,76)
 raw: 0a352e372e382d726300660000007b4b461a743a277300fff7080200ff8115000000000000000000002e516d28354b4a7255485829006d7973716c5f6e61746976655f70617373776f726400
Server hello packet: capability flags:-2113931265=(long password, found rows, long flag, connect with db, no schema, compress, odbc, local files, ignore space, protocol 41, interactive, ignore sigpipe, transactions, reserved, secure connection, multi statements, multi results, ps multi results, plugin auth, remember options)
Sending handshake packet: flags:193487=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results)
0 102 <== Connection#handshakeInit(1,,67)
0 102 ==> Connection#handshakeResult(2,maybeOK,7)
 raw: 00000002000000
        Sending query command: select 0/0 as test
0 102 <== query#start(0,,23)
0 102 ==> query#resultsetHeader(1,,1)
 raw: 01
        Resultset header received, expecting 1 column definition packets
0 102 ==> query#readField(2,,26)
 raw: 036465660000000474657374000c3f0007000000f68000040000
        Column definition:
          name: test
          type: 246
         flags: 128
        Compiled text protocol row parser:


(function() { return function TextRow(packet) {
  // "test": NEWDECIMAL
  this["test"] = packet.readLengthCodedString(); //246 63
};})()


0 102 ==> query#fieldsEOF(3,EOF,5)
 raw: fe00000200
0 102 ==> query#row(4,,1)
 raw: fb
0 102 ==> query#row(5,EOF,5)
 raw: fe01000200
null [ TextRow { test: null } ] [ { catalog: 'def',
    schema: '',
    name: 'test',
    orgName: '',
    table: '',
    orgTable: '',
    characterSet: 63,
    columnLength: 7,
    columnType: 246,
    flags: 128,
    decimals: 4 } ] 1
```

**Comment by sidorares** [comment]
oops, that was test protocol, sorry, ignore ^^^, I'll post new results

**Comment by sidorares** [comment]
For some reason "select 0/0 as test" is returned as NEWDECIMAL. Maybe need to add type cast to query

```
Add command: Connection
Add command: prepare
0 undefined ==> Connection#handshakeInit(0,,76)
 raw: 0a352e372e382d726300670000004154307041024a3c00fff7080200ff811500000000000000000000396d086f4c10261c431e673c006d7973716c5f6e61746976655f70617373776f726400
Server hello packet: capability flags:-2113931265=(long password, found rows, long flag, connect with db, no schema, compress, odbc, local files, ignore space, protocol 41, interactive, ignore sigpipe, transactions, reserved, secure connection, multi statements, multi results, ps multi results, plugin auth, remember options)
Sending handshake packet: flags:193487=(long password, found rows, long flag, connect with db, odbc, local files, ignore space, protocol 41, ignore sigpipe, transactions, reserved, secure connection, multi results)
0 103 <== Connection#handshakeInit(1,,67)
0 103 ==> Connection#handshakeResult(2,maybeOK,7)
 raw: 00000002000000
0 103 <== prepare#start(0,,23)
0 103 ==> prepare#prepareHeader(1,maybeOK,12)
 raw: 000100000001000000000000
0 103 ==> prepare#readField(2,,26)
 raw: 036465660000000474657374000c3f0007000000f68000040000
0 103 ==> prepare#fieldsEOF(3,EOF,5)
 raw: fe00000200
Add command: executeStatement
0 103 <== executeStatement#start(0,,14)
0 103 ==> executeStatement#resultsetHeader(1,,1)
 raw: 01
        Resultset header received, expecting 1 column definition packets
0 103 ==> executeStatement#readField(2,,26)
 raw: 036465660000000474657374000c3f0007000000f68000040000
0 103 ==> executeStatement#fieldsEOF(3,EOF,5)
 raw: fe00000200
Compiled binary protocol row parser:
(function(){ return function BinaryRow(packet) {
  var statusByte = packet.readInt8();
  var nullBitmaskByte0 = packet.readInt8();
  // "test": NEWDECIMAL
  if (nullBitmaskByte0 & 4)
    this["test"] = null;
  else
    this["test"] = packet.readLengthCodedString();
}; })()
0 103 ==> executeStatement#row(4,maybeOK,2)
 raw: 0004
0 103 ==> executeStatement#row(5,EOF,5)
 raw: fe01000200
null [ BinaryRow { test: null } ] [ { catalog: 'def',
    schema: '',
    name: 'test',
    orgName: '',
    table: '',
    orgTable: '',
    characterSet: 63,
    columnLength: 7,
    columnType: 246,
    flags: 128,
    decimals: 4 } ] 1
```

**Comment by dougwilson** [comment]
I mean, `NEWDECIMAL` makes sense, as that would be just the default numeric type in the current version of MySQL.

**Comment by sidorares** [comment]
newdecimals are sent as strings in both text and binary protocols

**Comment by chrisveness** [comment]
I think I'm a bit out of my depth here, but if I understand well, converting to NaN to NULL seems potentially confusing.

Would that mean that if I issued `yield db.query('select * from mytable where somenumericfield = ?', NaN)` I would receive back all rows where somenumericfield was NULL?

Saying that, there doesn't seem to be much agreed about MySQL and NaN, perhaps that might be the best option, and even the behaviour users would expect. Would throwing an exception be an alternative? I guess that might have issues as well.

I think I'll put `isNaN()` checks in my models where relevant :)
