### ISSUE TITLE
Causing Too many connections error on mysql server

### ISSUE THREAD

**Issue by abisao1** [sidorares/node-mysql2#2360]
I after few http requests crushing my database server with error "Too many connections". Looks like database connections are not being closed properly. I am using NextJS.

Below is my my class code:

```ts
export class Database {
    private dbConnection: any

    private openDatabaseConnection = async () => {
        const access: ConnectionOptions = {
            host: process.env.MYSQL_HOST,
            database: process.env.MYSQL_DATABASE,
            user: process.env.MYSQL_USER,
            password: process.env.MYSQL_PASSWORD,
            port: process.env.MYSQL_PORT ? parseInt(process.env.MYSQL_PORT) : undefined
        };

         // Mysql DB Connection
         const dbConnection = await mysql.createConnection(access);

        return dbConnection;
    }

   ........

    public selectRecords = async (queryOptions: SelectQueryOptions) => {
        // Initiate connection to the database
        const dbConnection = await this.openDatabaseConnection();
    
        try {
    
            // Perform select operation
            const stmt: string     = this.generateSelect(queryOptions);
            const [ results ]: any = await dbConnection.execute(stmt, queryOptions.values);
            const response         = { ...ApiResponse.getResponse(200), data: queryOptions.firstRow ? results[0]:results }
            
            return response;
        } catch (error:any) {
            return { ...ApiResponse.getResponse(406), message: error.message };
        } finally {
            // Terminate connection to the database
            dbConnection.end;
        }
    }
}
```

Is there anything wrong with my code?

**Comment by smanask** [comment]
In the finally block, you are calling dbConnection.end, but it seems like there's a missing pair of parentheses (). It should be dbConnection.end() to actually invoke the method.

The correct code should be:

```javascript
finally {
    // Terminate connection to the database
    dbConnection.end();
}
``` 

Without them, it won't execute the method and the database connections may not be closed correctly, leading to "Too many connections".

You might also consider using pooling to manage database connections, especially in scenarios with multiple concurrent requests.

**Comment by Ejayz** [comment]
Hi is this problem solved ? I am also using nextjs with seperate ``db.ts`` file and i just call this file 
`"use strict";
import mysql from "mysql2/promise";
import * as dotenv from "dotenv";
dotenv.config();
const { DB_HOST, DB_USER, DB_PASSWORD, DB_NAME } = process.env;

 const Connection=async ()=>{
  return  mysql.createConnection({
    host: DB_HOST,
    user: DB_USER,
    password: DB_PASSWORD,
    database: DB_NAME,
    waitForConnections: true,
    connectionLimit: 10,
    idleTimeout: 5000,
    queueLimit: 0,
  });
 }

Connection().then((res)=>{
  console.log(res)
}
).catch((err)=>{
  console.log(err)
})
console.log( Connection());

export default Connection;
` But getting error too of too many connection after several queries . Have you checked the process and connection stats of your mysql if proccesses are being stopped ? 
![image](https://github.com/sidorares/node-mysql2/assets/32452006/ab3b892f-35ee-4aab-bda4-0de8d52e9535)
as you can see in the image it keeps on increasing the process but it is true that the connection is dropped . Will this be about me importing the ``db.ts`` file?

**Comment by abisao1** [comment]
> In the finally block, you are calling dbConnection.end, but it seems like there's a missing pair of parentheses (). It should be dbConnection.end() to actually invoke the method.
> 
> The correct code should be:
> 
> ```js
> finally {
>     // Terminate connection to the database
>     dbConnection.end();
> }
> ```
> 
> Without them, it won't execute the method and the database connections may not be closed correctly, leading to "Too many connections".
> 
> You might also consider using pooling to manage database connections, especially in scenarios with multiple concurrent requests.

The issue has been resolved. Thank thank you for the heads-up.

**Comment by abisao1** [comment]
> Hi is this problem solved ? I am also using nextjs with seperate `db.ts` file and i just call this file
> 
> ```
> import mysql from "mysql2/promise";
> import * as dotenv from "dotenv";
> dotenv.config();
> const { DB_HOST, DB_USER, DB_PASSWORD, DB_NAME } = process.env;
> 
>  const Connection=async ()=>{
>   return  mysql.createConnection({
>     host: DB_HOST,
>     user: DB_USER,
>     password: DB_PASSWORD,
>     database: DB_NAME,
>     waitForConnections: true,
>     connectionLimit: 10,
>     idleTimeout: 5000,
>     queueLimit: 0,
>   });
>  }
> 
> Connection().then((res)=>{
>   console.log(res)
> }
> ).catch((err)=>{
>   console.log(err)
> })
> console.log( Connection());
> 
> export default Connection;
> ```
> 
> But getting error too of too many connection after several queries . Have you checked the process and connection stats of your mysql if proccesses are being stopped ? ![image](https://private-user-images.githubusercontent.com/32452006/296440766-ab3b892f-35ee-4aab-bda4-0de8d52e9535.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMzcwNzMsIm5iZiI6MTcwNTEzNjc3MywicGF0aCI6Ii8zMjQ1MjAwNi8yOTY0NDA3NjYtYWIzYjg5MmYtMzVlZS00YWFiLWJkYTQtMGRlOGQ1MmU5NTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDA5MDYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNzcxMjk1NWYzMWY0NmRhODQ2MjcyZjkxODU0MTBmNDhlMjI4NjY0OTVlZTZhMjE4MmZhZTJmNGY2OGQ5NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kYBKw9sKlT_FPqpvGDz05n8oKGoaLbz_UnbYJV84Bxw) as you can see in the image it keeps on increasing the process but it is true that the connection is dropped . Will this be about me importing the `db.ts` file?

Yes it has been resolved. Thanks!

**Comment by wellwelwel** [comment]
> Hi is this problem solved ? I am also using nextjs with seperate db.ts file and i just call this file

@Ejayz, it looks like you're already following this _thread_ on #2362 🕵🏻

**Comment by Ejayz** [comment]
> > Hi is this problem solved ? I am also using nextjs with seperate db.ts file and i just call this file
> 
> @Ejayz, it looks like you're already following this _thread_ on #2362 🕵🏻

Both actually lol. But yea . my issue is fixed also .
