### ISSUE TITLE
Cannot delete rows using WHERE IN

### ISSUE THREAD

**Issue by YannickFuereder** [sidorares/node-mysql2#2364]
Select work perfectly fine but when i try to delete values in my table i get this error

**"Truncated incorrect INTEGER value: '[1]'"**

```js
const [rows, _] = await con.promise().query("SELECT * FROM exampleTable WHERE id IN (?)", [[1]]);

console.log(rows);

//throws error here
await con.promise().execute("DELETE FROM exampleTable WHERE id IN (?)", [[1]]);

```

Edit:
i dont get this exception when using the query function for th delete operation

**Comment by wellwelwel** [comment]
@YannickFuereder, when using `execute`, you will need to be explicit in your params:

```js
await con.promise().execute("DELETE FROM exampleTable WHERE id IN (?)", [1]);
```

An example using more params:
```js
await con.promise().execute("DELETE FROM exampleTable WHERE id IN (?, ?, ?)", [1, 5, 9]);
```

---

Related:
- #2168

**Comment by wellwelwel** [comment]
These comments can help to understand it better:
- https://github.com/sidorares/node-mysql2/issues/2168#issuecomment-1672510939
- https://github.com/sidorares/node-mysql2/issues/2168#issuecomment-1672621824

---

> I'm closing this issue, but feel free to ask anything 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
@sidorares, I believe documenting the differences between `query` and `execute` could be a good **FAQ**.

**Comment by sidorares** [comment]
Yes definitely, this makes a big portion of questions, especially the `IN (?)` scenario
