### ISSUE TITLE
server proxy feature not work well with Sequel Pro

### ISSUE THREAD

**Issue by chaoliu** [sidorares/node-mysql2#242]
hi all & @sidorares

Recently, I met a trouble with node-mysql2 server proxy feature.

I run the example  example/mysqlproxy.js . It works well with mysql origin console client ,  but not with
Sequel Pro (Sequel Pro is a fast, easy-to-use Mac database management application for working with MySQL databases.    http://www.sequelpro.com/ ) .

I tried a number of ways，for example, using wireshark packet analysis， or debug Sequel Pro source（https://github.com/sequelpro/sequelpro）.

Please help me

**Comment by sidorares** [comment]
Hi!
what exactly does not work? `example/mysqlproxy.js` example proxies query commands only, and Sequel Pro probably expects more command types to work

**Comment by chaoliu** [comment]
Yes, your judgment is right . Sequel Pro expects more command types to work .It send a SLEEP command after handshake successfully，but lib/commands/server_handshake.js  dose not handle this. So  I add this to ServerHandshake.prototype.dispatchCommands. 
``` JavaScript
ServerHandshake.prototype.dispatchCommands = function(packet, connection) {
    ……
    case CommandCode.SLEEP:
         connection.writeOk();
         break;
    ……
}
```

Then Sequel Pro send some query (show fileds , show databases …)， but all failed  which raising a reconnecting .  



what exactly does not work?  -- just  can not  connect  in  connecting  interface

I think it  should be ok ，Sequel Pro ’ s  connector is using OC wrap libmysql . I will continue to try to solve it  and  thank you for your reply

**Comment by sidorares** [comment]
thanks for details, feel free to add more events to dispatcher (maybe with some reasonable default behavior if no handlers set up, similar to ping command handler) - happy to accept PRs

**Comment by vogievetsky** [comment]
Just wanted to say that I too love Sequel Pro and will be looking into this.

**Comment by vogievetsky** [comment]
@sidorares @chaoliu any idea what the packet `0x0000000e000000034b494c4c205155455259203100` can be? That is the "SLEEP" command that is being sent. No idea why it starts with `0000000e0000000` any direction appreciated.

**Comment by sidorares** [comment]
maybe we should add "unknown_packet" event so at least proxy implementation would be able to pass it as is?

```js
   conn.on('unknown_packet', (p) => { remote.writePacket(p) })
```

**Comment by vogievetsky** [comment]
That is Great idea. Definitely better than not having it even if not making
a proxy.

**Comment by sidorares** [comment]
actually I'd rather call event just `'packet'` and emit it even when there are handlers for "known" packets

**Comment by sidorares** [comment]
@vogievetsky 

```
> Buffer('0000000e000000034b494c4c205155455259203100', 'hex')
<Buffer 00 00 00 0e 00 00 00 03 4b 49 4c 4c 20 51 55 45 52 59 20 31 00>
> Buffer('0000000e000000034b494c4c205155455259203100', 'hex').toString()
'\u0000\u0000\u0000\u000e\u0000\u0000\u0000\u0003KILL QUERY 1\u0000'
```

looks like it's sleep initially and because no OK response to sleep Sequel Pro is sending KILL query ( 0x03 earlier is COM_QUERY and "0e 00 00 00" looks like packet header )

**Comment by sidorares** [comment]
@vogievetsky if you keen to contribute more I'm happy to add you as collaborator to github / add publish rights at npm. There is plenty of work here I would like to finish but don't have enough time :)

**Comment by vogievetsky** [comment]
@sidorares I am very interested in contributing in particular I would like to make the server side bullet proof.

regarding the packet `00 00 00 0e 00 00 00 03 4b494c4c205155455259203100` am I correct in understanding that there can be several commands in a single packet?

So it it `COM_SLEEP COM_SLEEP COM_SLEEP COM_PING COM_SLEEP COM_SLEEP COM_SLEEP COM_QUERY("KILL QUERY 1")` ?

What should the server reply to that? `OK OK OK OK OK OK OK TEXT_ROW` ?

**Comment by sidorares** [comment]
no, should not be that way, clients must wait for previous response before sending new command. Not sure if that's a bug in Sequel Pro. Where did you get that `00 00 00 0e 00 00 00 03 4b494c4c205155455259203100` @vogievetsky ? is that dump from server while connecting with Sequel Pro? Also, all commands are prefixed with 4-byte header ( length + sequence number ) - http://dev.mysql.com/doc/internals/en/mysql-packet.html

**Comment by sidorares** [comment]
`0e 00 00 00` looks like header for `034b494c4c205155455259203100` - 14 bytes payload, sequence number 0 ( packet sequence is 0-based starting at each command )

**Comment by vogievetsky** [comment]
@sidorares ok, that is what I thought originally, then started doubting myself. I am getting these buffers by adding a `debug: true` to the connection:

![image](https://cloud.githubusercontent.com/assets/177816/14947970/f1a6e7fc-0fef-11e6-9cce-057fd55e1d7a.png)

Basically this looks like a PING that starts with 3 zero bytes for no reason

![image](https://cloud.githubusercontent.com/assets/177816/14947976/0c67d0c4-0ff0-11e6-9da0-e44b135903c7.png)

this is the Kill query with 3 leading zero bytes.

I looked at how Sequel Pro connects to a real MySQL server

![image](https://cloud.githubusercontent.com/assets/177816/14948016/655bf214-0ff0-11e6-9198-c7c515433962.png)

And it sends the same thing and gets some reply over. Wireshark thinks the packet is malformed.

I am going to play later with the 'packet' event. I was just wondering if maybe there is some secret protocol extension or something that I could not find in the docs.

**Comment by sidorares** [comment]
even `SLEEP` command is marked as "internal" in [official mysql docs](http://dev.mysql.com/doc/internals/en/com-sleep.html), so ¯\_(ツ)_/¯ why Sequel Pro is using it in the first place. I'm going to install it and play a bit as well

**Comment by vogievetsky** [comment]
That is what I am saying. It never uses sleep. It just adds zeros to other
commands (ping and query) :-p

**Comment by vogievetsky** [comment]
`capabilityFlags = 0xffffff - 0x20  // allow compress` works. the extra zeros are from the compression protocol: https://dev.mysql.com/doc/internals/en/compressed-packet-header.html

**Comment by sidorares** [comment]
@chaoliu so the resolution is : the behaviour you see is because Sequel Pro switches to [compressed protocol](https://dev.mysql.com/doc/internals/en/compressed-packet-header.html) which server incorrectly advertises as supported via `capabilityFlags = 0xffffff`

Possible solutions:
  - don't advertise compression support ( `capabilityFlags = 0xffffff - 0x20` )
  - disable compression in Sequel Pro ( https://github.com/sequelpro/sequelpro/issues/2122#issuecomment-126113804 )
  - wait for #299 to fixed
