### ISSUE TITLE
NULL timestamp should return null instead of invalid date

### ISSUE THREAD

**Issue by mike-marcacci** [sidorares/node-mysql2#244]
It looks like the [TIMESTAMP handling](https://github.com/sidorares/node-mysql2/blob/773f75ef43ceee6ac26d06b36ef025706241f9ca/lib/packets/packet.js#L185) doesn't account for the `null` possibility, and instead returns an invalid date, which breaks compatibility with node-mysql and is probably not intended.

**Comment by sidorares** [comment]
thanks, fixed!

**Comment by mike-marcacci** [comment]
Wow, that was fast! Thanks!

**Comment by sidorares** [comment]
I have huge (and growing) pile of changes I want to include into 1.0 release, so not sure when this change is going to be in npm. Maybe I'll to another 0.15 release with what I already have ( need to review first if this is possible semver-wise )
