### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'createPool')

### ISSUE THREAD

**Issue by 0xMALVEE** [sidorares/node-mysql2#2441]
```js
import "dotenv/config";
import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import * as schema from "./schemas/schema";

export const drizzleProvider = "DATABASE_CONNECTION_DRIZZLE";

export const databaseProvider = [
  {
    provide: drizzleProvider,
    useFactory: async () => {
      const poolConnection = mysql.createPool({
        uri: process.env.DATABASE_URL,
      });

      const db = drizzle(poolConnection, { schema, mode: "planetscale" });

      return db;
    },
  },
];
```

---

![image](https://github.com/sidorares/node-mysql2/assets/35369563/4e61cca7-bd16-4d13-8de9-966b5b370853)

---

<details>
<summary>
Original
</summary>

![image](https://github.com/sidorares/node-mysql2/assets/35369563/bcf34b64-a63f-4b4c-8ccc-d4e13ba3f58e)

</details>

**Comment by 0xMALVEE** [comment]
idk why mysql2 is saying it's undefined. I rm -r node_modules and install again same thing.

**Comment by 0xMALVEE** [comment]
@sidorares @wellwelwel @jmordica

**Comment by wellwelwel** [comment]
Hey @0xMALVEE, can you share a basic repro as text/code block? Knowing more about your context can help 🙋🏻‍♂️

**Comment by 0xMALVEE** [comment]
> Hey @0xMALVEE, can you share a basic repro as text/code block?
> 
> Knowing more about your context can help (some practical usage for `databaseProvider` and `useFactory` or where they are called, for example) 🙋🏻‍♂️

Basically a nest js mono repo. it only doing problem with mysql2 , all other npm packages work just fine. Even I put it on main.ts same giving undefined other then useFactory. 
![image](https://github.com/sidorares/node-mysql2/assets/35369563/eddd21d4-1b14-4906-8b1a-f5098ebd16c5)

**Comment by wellwelwel** [comment]
When isolating **NestJS** and **MySQL2**, do you get the same error? If so, please share it. With a repro, I can get the same error to test it.

> Sorry @0xMALVEE, I can't reproduce your code as an image 😕

**Comment by 0xMALVEE** [comment]
> When isolating **NestJS** and **MySQL2**, do you get the same error? If so, please share it. With a repro, I can get the same error to test it.
> 
> > Sorry @0xMALVEE, I can't reproduce your code as an image 😕

aight let me prepair for you.

**Comment by 0xMALVEE** [comment]
@wellwelwel hey I posted in nest js discord as well. just checked seems like they gave a solution , was a problem with my import. it's working now. had to import * as . but in drizzle docs they didn't mention this seems out outdated drizzle docs.
![image](https://github.com/sidorares/node-mysql2/assets/35369563/44e69a32-ee8c-4446-9f82-9054f9ab820d)

![image](https://github.com/sidorares/node-mysql2/assets/35369563/1a3f1a51-199d-4fe1-b863-781444d1138f)

**Comment by 0xMALVEE** [comment]
import problem. drizzle docs outdated.

**Comment by wellwelwel** [comment]
@0xMALVEE, thanks to show your solution 🙋🏻‍♂️

---

Just bringing it from **MySQL2** documentation for **TypeScript**:

https://github.com/sidorares/node-mysql2/blob/db134682ce926221037cb9a0ebea69fc222495a1/website/docs/documentation/typescript-examples.mdx#L21-L37

**Comment by 0xMALVEE** [comment]
> @0xMALVEE, thanks to show your solution 🙋🏻‍♂️
> 
> Just bringing it from **MySQL2** documentation for **TypeScript**:
> 
> https://github.com/sidorares/node-mysql2/blob/db134682ce926221037cb9a0ebea69fc222495a1/website/docs/documentation/typescript-examples.mdx#L21-L37

@wellwelwel thanks. I didn't knew that tsconfig property exists haha. 🤯

**Comment by prometheus-alien** [comment]
> [@wellwelwel](https://github.com/wellwelwel) hey I posted in nest js discord as well. just checked seems like they gave a solution , was a problem with my import. it's working now. had to import * as . but in drizzle docs they didn't mention this seems out outdated drizzle docs. ![image](https://github.com/sidorares/node-mysql2/assets/35369563/44e69a32-ee8c-4446-9f82-9054f9ab820d)
> 
> ![image](https://github.com/sidorares/node-mysql2/assets/35369563/1a3f1a51-199d-4fe1-b863-781444d1138f)

Thx，it works.
