### ISSUE TITLE
Can't get the database name after use db command

### ISSUE THREAD

**Issue by deepakaggarwal7** [sidorares/node-mysql2#2451]
Consider the following code:

 ```js
   const dbPool = mysql2.createPool({
      host: process.env.MYSQL_HOST,
      user: process.env.MYSQL_USER,
      password: process.env.MYSQL_PASSWORD,
    });
    await dbPool.query("create database test3");
    await dbPool.query("use test3");
    console.log((await dbPool.getConnection()).config.database);
    await dbPool.query("create table student(id int, name varchar(100))"); //always undefined
    await dbPool.query("drop database test3");
```

    `console.log((await dbPool.getConnection()).config.database); ` is undefined but all further queries properly work which means pool is aware of the database. But, then why config.database is undefined. How can I get that value?

**Comment by Sergiussupa** [comment]
```
const mysql2 = require('mysql2/promise');    
    
const dbPool = mysql2.createPool({    
  host: process.env.MYSQL_HOST,    
  user: process.env.MYSQL_USER   
  password: process.env.MYSQL_PASSWORD,
});    
    
async function queryDatabases() {    
  try {    
    await dbPool.query("create database test3");           
    await dbPool.query("USE test3");      
    // Query to get the name of the current database    
    const [rows] = await dbPool.query("SELECT DATABASE() AS currentDb;");    
    console.log(rows[0].currentDb); // Outputs the name of the current database    
    await dbPool.query("create table student(id int, name varchar(100))"); //always undefined    
    await dbPool.query("drop database test3");      
  } catch (err) {        
    console.log(err);    
  }    
}    
    
queryDatabases(); 
```

## Did you need this?
![Снимок экрана от 2024-03-20 23-02-21](https://github.com/sidorares/node-mysql2/assets/52793979/63bb7587-4b01-427a-8f71-89f9c8156737)

**Comment by sidorares** [comment]
@deepakaggarwal7 `"create table"` command returns a generic info packet, similar to "INSERT INTO" and does not have db name in the result. You can use `"SELECT DATABASE()"` query as suggested by @Sergiussupa

**Comment by deepakaggarwal7** [comment]
> ```
> const mysql2 = require('mysql2/promise');    
>     
> const dbPool = mysql2.createPool({    
>   host: process.env.MYSQL_HOST,    
>   user: process.env.MYSQL_USER   
>   password: process.env.MYSQL_PASSWORD,
> });    
>     
> async function queryDatabases() {    
>   try {    
>     await dbPool.query("create database test3");           
>     await dbPool.query("USE test3");      
>     // Query to get the name of the current database    
>     const [rows] = await dbPool.query("SELECT DATABASE() AS currentDb;");    
>     console.log(rows[0].currentDb); // Outputs the name of the current database    
>     await dbPool.query("create table student(id int, name varchar(100))"); //always undefined    
>     await dbPool.query("drop database test3");      
>   } catch (err) {        
>     console.log(err);    
>   }    
> }    
>     
> queryDatabases(); 
> ```
> 
> ## Did you need this?
> ![Снимок экрана от 2024-03-20 23-02-21](https://private-user-images.githubusercontent.com/52793979/314655531-63bb7587-4b01-427a-8f71-89f9c8156737.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMjc5MjYsIm5iZiI6MTcxMTAyNzYyNiwicGF0aCI6Ii81Mjc5Mzk3OS8zMTQ2NTU1MzEtNjNiYjc1ODctNGIwMS00MjdhLThmNzEtODlmOWM4MTU2NzM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEzMjcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTAzOTZiNTE5NWFmZWJiYzM3MzE3MTNmYjkyNmViNzgzYTg5NDQ0MzhhMTZiZmJmYzZlZWM3OGQ1M2I5ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aeeViU8UIOHfJJ1gGxkxxXd6w83hy_gqk36MYDsKGsM)

Great Thank you!
