### ISSUE TITLE
Question: Client IP when in Server Mode.

### ISSUE THREAD

**Issue by digipigeon** [sidorares/node-mysql2#249]
If I have node-mysql2 setup as a server. Then a client connects to it, how can I get the IP address of the connecting client from the conn object?

**Comment by sidorares** [comment]
Hi! In `connection` event handler ( https://github.com/sidorares/node-mysql2/blob/dd2558aac6c45e1056f3c376e66c7e99225ee9b8/lib/server.js#L20 ) you access `connection.config.stream` object and use `remoteAddress()` function ( https://nodejs.org/api/net.html#net_socket_remoteaddress )

```js
server.on('connection', function(conn) {
  var ip = conn.config.stream.remoteAddress();
});
```

**Comment by digipigeon** [comment]
Thanks, I was able to get this with conn.config.stream.remoteAddress as a property (not as a function), but its working now, thank you.

**Comment by sidorares** [comment]
oh, of course. I'll edit my example
