### ISSUE TITLE
Timeout since 3.9.4

### ISSUE THREAD

**Issue by Xenope** [sidorares/node-mysql2#2580]
Hello,

My CI/CD chain just broke with the last version (3.9.4) that was released today. 
I'm using Sequelize with Mysql2 to connect to my Mysql server.

Everything works fine even with 3.9.3, but now i kept being stuck when my unit tests are launched.
All i got is a log for a query getting stuck and then a timeout with no feedback/error that could guide me to resolve this.

![image](https://github.com/sidorares/node-mysql2/assets/15614284/8b69dcfc-9955-4e41-9aab-e6c5678d4332).
![image](https://github.com/sidorares/node-mysql2/assets/15614284/36f9352c-67b8-4a89-a00e-8bce148064ca)

Any idea?

**Comment by wellwelwel** [comment]
Hi @Xenope, could you share a basic repro for this?

**Comment by Xenope** [comment]
Hi, 

after further investigation it looks like it is linked to the issue #2585 . 

Inside Sequelize there is a 

`if (result.hasOwnProperty(key)) 
`

that is now failing.
