### ISSUE TITLE
read ECONNRESET after upgrading

### ISSUE THREAD

**Issue by niels-van-den-broeck** [sidorares/node-mysql2#2599]
After introduction of https://github.com/sidorares/node-mysql2/pull/2043, our application seems to be getting the following error (seemingly at random):
```
"stack": "Error: read ECONNRESET\n    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)\n    at runInContextCb (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:1168:22)\n    at AsyncLocalStorage.run (node:async_hooks:335:14)\n    at AsyncLocalContextManager.runInContext (/usr/src/app/node_modules/newrelic/lib/context-manager/async-local-context-manager.js:65:36)\n    at Shim.applySegment (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:1158:25)\n    at TCP.wrapper (/usr/src/app/node_modules/newrelic/lib/shim/shim.js:1760:17)\n    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)\n    at MysqlConnection.executeQuery (/usr/src/app/node_modules/kysely/dist/cjs/dialect/mysql/mysql-driver.js:119:69)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /usr/src/app/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:37:28\n    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)\n    at async DefaultQueryExecutor.executeQuery (/usr/src/app/node_modules/kysely/dist/cjs/query-executor/query-executor-base.js:36:16)\n    at async SelectQueryBuilderImpl.execute (/usr/src/app/node_modules/kysely/dist/cjs/query-builder/select-query-builder.js:311:24)",
```

We use the mysql dialect for kysely which receives a pool created in this library.
the pool is created as follows: 
```
import { createPool } from 'mysql2';

const pool = createPool({
    host, // host ip string
    user, // user string
    database, // db string
    password, // password string
    port, // port
    timezone: 'Z',
  });
```

All versions before 3.3.5 work just fine. Right now this happens relatively often, but we can't seem to find a pattern of when/how it triggers.

Any potential help / input would be welcome.

**Comment by niels-van-den-broeck** [comment]
> does it help if you pass `enableKeepAlive: false` to connection config?

Unfortunately the error still occurs after adding it to the config.

**Comment by niels-van-den-broeck** [comment]
This is blocking us from updating to a version which no longer has security vulnerabilities. Is there any way we can look into what's causing this issue?

**Comment by niels-van-den-broeck** [comment]
After patching manually unfortunately that seemed to not be the issue. We've decided to roll down our versions 1 by 1, and the last one that seems to not have the issue was 3.3.1

So after updating to 3.3.2 we started seeing the issue again. 
Which when looking at release notes only introduced [this](https://github.com/sidorares/node-mysql2/pull/2016/files)

**Comment by asijoumi** [comment]
Hello!

I recently discussed issue [#10872: QueryFailedError: read ECONNRESET](https://github.com/typeorm/typeorm/issues/10872) with @niels-van-den-broeck. It appears that changes between the last version and version `3.3.1` have introduced an ECONNRESET error.

I haven't pinpointed the exact cause yet, but I conducted tests on both AWS RDS and an on-premise server. Interestingly, the error does not occur on AWS RDS, but it does manifest in the on-premise environment.

Could you help us understand what might be causing this discrepancy?

Thank you!

**Comment by niels-van-den-broeck** [comment]
@sidorares It seems like setting the default for` keepAliveInitialDelay` to 0 is what is causing this issue. 

[The node documentation](https://nodejs.org/api/net.html#socketsetkeepaliveenable-initialdelay) is also kind of vague about this default. (note the or previous part of the scentence).

Would it be ok if I'd create a PR to remove this default on the mysql2 side again?
As of right now it's not possible to pass in `undefined` since it's overwritten.

**Comment by benyaminl** [comment]
> Hello!
> 
> I recently discussed issue [#10872: QueryFailedError: read ECONNRESET](https://github.com/typeorm/typeorm/issues/10872) with @niels-van-den-broeck. It appears that changes between the last version and version `3.3.1` have introduced an ECONNRESET error.
> 
> I haven't pinpointed the exact cause yet, but I conducted tests on both AWS RDS and an on-premise server. Interestingly, the error does not occur on AWS RDS, but it does manifest in the on-premise environment.
> 
> Could you help us understand what might be causing this discrepancy?
> 
> Thank you!

Sorry for jumpin, we also face this problem on our on prem server (typeORM on nestjs), and we check that mysql2 thinks that the connection still alive even it's broken, so we resort with setting `maxIdle: 0` on the typeORM layer to mysql2 config, so any open connection after used is closed. This make no error after that. I do know that it make a performance hit to the application as a roundtrip to re-establish connection to the DB takes time, but well.. that's what we can only think for now as we rely on the framework.

**Comment by niels-van-den-broeck** [comment]
Any feedback on this would be welcome

**Comment by sidorares** [comment]
> Would it be ok if I'd create a PR to remove this default on the mysql2 side again?
As of right now it's not possible to pass in undefined since it's overwritten.

Sorry, missed that message @niels-van-den-broeck . If thats the case this is probably a bug, feel fee to open a PR
