### ISSUE TITLE
Importing mysql2 causes source maps not working in project bundled with webpack

### ISSUE THREAD

**Issue by nolimitdev** [sidorares/node-mysql2#2703]
In project bundled with webpack we have working source maps. We just imported mysql2 by adding one line to project `import mysql2 from 'mysql2';` and source maps immediately are not working. 

Before importing we see e.g.:
```
webpack:///resources/server.js:2
console.log(someUndefVar);
            ^
ReferenceError: someUndefVar is not defined
```

After importing we see e.g.:
```
ReferenceError: someUndefVar is not defined
    at file:///....../distribute/server.js:25154:13
```

Package mysql2 is latest version 3.9.7. I have tested importing old package `mysql` https://www.npmjs.com/package/mysql (latest version [2.18.1](https://www.npmjs.com/package/mysql/v/2.18.1)) and source maps are working.

To reproduce in server.js it is enough to have just 2 lines e.g.
```
import mysql2 from 'mysql2';
console.log(someUndefVar );
```
and problem happens. If needed I will provide webpack configuration but I do not think that could be a problem. Workaround is only not bundling mysql2 by excluding it in webpack configuration `externals : {'mysql2' : 'mysql2'}` but we can not distribute single file app and installing mysql2 is needed. Any other packages used in project works well bundled except mysql2.

**Comment by wellwelwel** [comment]
Thanks @nolimitdev, I tried to reproduce this behavior, but it worked for me:

> Both scenarios provide the same output

<img width="789" alt="Screenshot 2024-05-24 at 20 55 20" src="https://github.com/sidorares/node-mysql2/assets/46850407/d70bbb47-5125-4832-8b8d-6eeb489de235">

**Comment by wellwelwel** [comment]
Complementing, I got this error when using **Node.js < 18**.

From **Node.js 18.x** onwards, all the maps worked:

```yml
services:
  node-mysql2:
    image: node:16-alpine
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    command: sh -c "npm run build && npm run server"
```

<img width="560" alt="Screenshot 2024-05-24 at 21 09 12" src="https://github.com/sidorares/node-mysql2/assets/46850407/c00c069e-e1cf-4ef3-a529-123c0ed5ce80">

**Comment by wellwelwel** [comment]
Trying to install random packages:

- Most sizable packages (especially those with sub dependencies), cause this behavior.
- Small packages (especially those with no dependencies) use the map correctly.

I suppose the error is related to the map generation itself, since the behavior isn't limited to **MySQL2**.
Please correct me if I'm mistaken.

**Comment by nolimitdev** [comment]
Yes, problem is only with nodejs < 18 and probably as you said it has nothing to do with mysql2 but globally with huge bundle. Thank you for investigation.
