### ISSUE TITLE
Building query for ORDER BY ? DESC/ASC doesn't seem to use the values

### ISSUE THREAD

**Issue by k3rne1pan1c** [sidorares/node-mysql2#2724]
```js
 let extraClause = "";
    if (extraFilters) {
        if (extraFilters.sorted) {
            if (extraFilters.sortOrder === "DESC") {
                extraClause += ' ORDER BY ? DESC';
            } else {
                extraClause += ' ORDER BY ? ASC';
            }
            whereValues.push(extraFilters.sorted);
        }
    }
    const query = 'SELECT p.*, GROUP_CONCAT(i.image_path SEPARATOR \',\') AS image_paths FROM post p LEFT JOIN Image i ON p.post_id = i.post_id' + (whereClause ? ' WHERE ' + whereClause : '') + ' GROUP BY p.post_id ' + (extraClause ? extraClause : '');

```

Value + Query 

```
[ 'created_at']
'SELECT p.*, GROUP_CONCAT(i.image_path SEPARATOR \',\') AS image_paths FROM post p LEFT JOIN Image i ON p.post_id = i.post_id GROUP BY p.post_id  ORDER BY ? DESC LIMIT ?'
```

It only works when it look like this:

`..."ORDER BY ? DESC" inside of the query constant`

It doesn't work with preparing the statement beforehand. I feel like that they add DESC as a string and then mysql doesn't recognizes it. The SQL is correct in any way, but it doesn't filter.

Executing the statement like this:

```
 const [rows] = await pool.query<Post[]>(query, whereValues);
```

**Comment by sidorares** [comment]
hi @k3rne1pan1c , what do you mean by "doesn't work"? Do you get error response from myqsl server? a local error?

Can you also post actual query and parameters after all conditions? Overall I feel your question is not specific to mysq2 library
