### ISSUE TITLE
connection.execute() not working for me

### ISSUE THREAD

**Issue by codecowboy** [sidorares/node-mysql2#274]
I am trying to use a prepared statement using connection.execute(). the PREG_CAPTURE function is a user defined function in MySQL. I'm using an ES6 multiline string.

Can anyone see why this is not working. Please note this is not intended to be production code so is a little rough.

```js
var getGalleryForPostIDSql = `SELECT gallery_id, ID
FROM (SELECT PREG_CAPTURE( '/(\\[ngg.+id=)([0-9]+)+/' , post_content,2) as gallery_id, post_content,ID, post_type FROM wp_posts p) as t1
WHERE gallery_id IS NOT NULL AND post_type="post" AND ID = ?;`;

connection.connect();

var firstPromise = getVideos(videoSql);

firstPromise.then(function(results){
   //these results are definitely available
    var galleryIds = [];

    //console.log(results[0]);
    results.forEach(function(item,index,results){

        console.log(item); // is populated
        connection.execute(getGalleryForPostIDSql,item.ID, function(err, rows,fields){
            if(err) {
                console.log(err);
                process.exit();
            }
    console.log(rows);// logs an empty array

       });

    });
    return results;

}).then(function(results){
    console.log('next then method call');
}).then(function(){

}).catch(function (e) {
    console.log(e);
});
```

**Comment by sidorares** [comment]
Hi @codecowboy ! Do you get error in the callback? What does `console.log(err)` print?

Also, `execute()` parameters must be an array ( even when there is just one parameter ) - try to change code to be 

```js
connection.execute(getGalleryForPostIDSql,item.ID, function(err, rows,fields){
  //...
})
```

**Comment by sidorares** [comment]
also note that your `return results;` happens after sql commands queued for execution bun before any results return back from db

**Comment by codecowboy** [comment]
@sidores thanks, I think you mean `[item.ID]` ? Also, results is coming from further up in the promise chain so is already available if that makes sense.

**Comment by sidorares** [comment]
Oops, yes, I meant `[item.ID]`. Do you get any rows back with is change? Why do you think empty result is incorrect?

**Comment by codecowboy** [comment]
@sidorares thanks. I think I have come to the conculsion that the empty resul is actually correct as I have flaws in my logic elsewhere. Thanks for your help - it got me a little further. You can  close this issue now.
