### ISSUE TITLE
bigNumberStrings: true is not return type number

### ISSUE THREAD

**Issue by thanathip41** [sidorares/node-mysql2#2775]
```js
import mysql, { PoolOptions } from 'mysql2'; // version 3.1.0

const options = {
  user: 'test',
  database: 'test',
  // .......
  supportBigNumbers: true,
  bigNumberStrings: true
};
const pool = mysql.createPool(options);
// when i use 
pool.query("SELECT count(*) as total FROM users WHERE `users`.`deleted_at` IS NULL LIMIT 3")
```

The total return type string 

Thank you

**Comment by yshrsmz** [comment]
> Returns a count of the number of non-NULL values of expr in the rows retrieved by a [SELECT](https://dev.mysql.com/doc/refman/8.0/en/select.html) statement. The result is a [BIGINT](https://dev.mysql.com/doc/refman/8.0/en/integer-types.html) value.

https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_count

According to the official document, `COUNT()` function's return type is BIGINT, so this behavior seems to be correct.

**Comment by wellwelwel** [comment]
Thanks, @yshrsmz 🤝
