### ISSUE TITLE
Missing support for multipleStatements

### ISSUE THREAD

**Issue by noamw** [sidorares/node-mysql2#28]
Server returns format error on 'SELECT 1 v; SELECT 2 b;'

**Comment by sidorares** [comment]
actually, there is no way to have multiple statements in "execute" (mysql server does not allow this). However you can get multiple results in binary protocol. see #157

**Comment by cheshirecatalyst** [comment]
Is there a plan to have this on a per query basis similar to namedPlaceholders? Or is this a mysql session variable that has to be set? I ask because i would like to arbitrarily pull a connection from the pool, as i have one spot in code where i need to make multiple statements.

**Comment by sidorares** [comment]
afaik when you do `execute(options, cb)` all options are merged into config. I'll try to double check, but it should be consistent across all options

**Comment by dougwilson** [comment]
The enablement of multi statements is part of the actual underlying MySQL protocol connection (part of the flags like if it's the 4.1 protocol or not), so AFAIK it's not possible to turn it on or off once a connection has been established.

**Comment by sidorares** [comment]
@dougwilson thanks, that is actually correct
@cheshirecatalyst - you need to know upfront if you going to use multi statements or not

**Comment by cheshirecatalyst** [comment]
So i would need to create two pools? one For multi statements, one for regular transactions then? Correct?

**Comment by sidorares** [comment]
If you want some security enforcement on regular stream than yes, but you just may use one single connection for multi statement queries and regular queries
