### ISSUE TITLE
1.0.0 release?

### ISSUE THREAD

**Issue by felixfbecker** [sidorares/node-mysql2#282]
I would like to know when 1.0.0 will be released, what the release blockers are.
Or maybe #216 can get a patch release?

**Comment by sidorares** [comment]
mostly my time, unfortunately.

biggest blocker is #270 - need to test solution from comment, add unit test etc
#216 can definitely go into 1.0.0, I'll try to review tomorrow

my plan is to release another rc and if all goes well, v1.0.0 after
