### ISSUE TITLE
awsCaBundle not working as intended for import RDS cert

### ISSUE THREAD

**Issue by mrajasekar-godaddy** [sidorares/node-mysql2#2869]
Hi Team,

Currently We are using _promise-mysql_ which is a wrapper function of _mysqljs_

Currently when I use ssl: awsCaBundle to pull in the new cert in 2 possible ways

`host: response.host,
    port: response.port,
    user: response.username,
    password: response.password,
    timezone: 'Z',
    ssl: {
      ca: awsCaBundle.ca,
    },
    database: 'Hub'
 }`

and 

`host: response.host,
    port: response.port,
    user: response.username,
    password: response.password,
    timezone: 'Z',
    ssl: awsCaBundle,
    database: 'Hub'
 }`

Both doesn't work and it fails to connect to the Database. 

Can someone help on this ? Is there is an issue with the imports ? or the way it's accessed. 

CC: @wellwelwel For visibility

**Comment by mrajasekar-godaddy** [comment]
@wellwelwel Steps for reproduction

`const mysql = require('promise-mysql');
const awsCaBundle = require('aws-ssl-profiles');

const connection = await mysql.createConnection{(
    host: response.host,
    port: response.port,
    user: response.username,
    password: response.password,
    timezone: 'Z',
    ssl: await awsCaBundle
})`

If you use this way to connect to an RDS instance, it won't connect. Please let me know if you any additional details

**Comment by wellwelwel** [comment]
Hi, @mrajasekar-godaddy 🙋🏻‍♂️

> Currently I'm using promise-mysql which is a wrapper function of mysqljs

At first, I thought that `promise-mysql` was a typo of `mysql2/promise`, then I realized that this package does exist. Sorry for not noticing before.

So, everything works for me:

```js
import mysql from 'promise-mysql';
import ssl from 'aws-ssl-profiles';

const connection = mysql.createConnection({
  host: '***',
  user: '***',
  password: '***',
  database: '***',
  timezone: 'Z',
  ssl,
  // ssl: {
  //   ca: ssl.ca,
  //   rejectUnauthorized: false,
  // },
});

connection.connect((err) => {
  if (err instanceof Error) console.log(err.message);
});

connection.query('SELECT 1 + 1 AS `total`', function (_, rows) {
  console.log(rows);
});

connection.end();
```

About **aws-profiles-ssl**, it just exports an array of strings.

The error seems to come from a `query`, not a connection: `ER_BAD_FIELD_ERROR: Unknown column 'PJ.tier' in 'field list'`.
Unfortunately, **promise-mysql** no longer seems to be maintained: https://github.com/CodeFoodPixels/node-promise-mysql/issues/172.

**Comment by mrajasekar-godaddy** [comment]
@wellwelwel Thanks for checking it and getting back. Appreciate it

But, I'm using CJM where I use `const awsCaBundle = require('aws-ssl-profiles')` and when I use it, I am not able to establish the connection. 

Correct, this `ER_BAD_FIELD_ERROR: Unknown column 'PJ.tier' in 'field list'.` is a query error. But, the error which I get now is related to connection. i.e

`errorMessage: 'Quit inactivity timeout',
  errorCode: 'PROTOCOL_SEQUENCE_TIMEOUT',
  errorDetail: {},
  errorStack: 'Error: Quit inactivity timeout\n' +`

**Comment by mrajasekar-godaddy** [comment]
Also, Thanks for sharing that the **'promise-mysql'** library is no longer active.

**Comment by wellwelwel** [comment]
- Closing in favor of https://github.com/sidorares/node-mysql2/pull/2857#issuecomment-2243146285.

@mrajasekar-godaddy, If you can share your solution approach, that would be great 🙋🏻‍♂️
