### ISSUE TITLE
Feature request: Update query result does not contain changedRows value.

### ISSUE THREAD

**Issue by hauboldj** [sidorares/node-mysql2#288]
felixge/node-mysql returns a property `changedRows` for update queries that contains the number of rows affected by an update statement.

**Comment by sidorares** [comment]
https://github.com/sidorares/node-mysql2/blob/7ab1f8416fd845e0e7064ac68d2001be4a76d247/lib/packets/resultset_header.js#L11

I'll double check if `affectedRows` is the same and if yes make `changedRows` alias for it

**Comment by plusmancn** [comment]
The affectedRows is not same as changedRows (which the row value is actually changed).
The affectedRows is equal to 'selected rows' when i use update statement.

**Comment by sidorares** [comment]
this is what mysql documentation saying: https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html - there is only one "affected rows" field

@plusmancn I don't think there is "changedRows" value doing what you described ( e.i if I have table with 3 ids > 10 and I do `update foo set baz=1 where id>10` affectedRows will be 3 no matter how much baz columns had value 1 before ( and there is no such flag to get this value - you need to do `select count(*) where baz !=1` beforehand to get this )

**Comment by sidorares** [comment]
ok @plusmancn you kind of right, I was looking from protocol point of view

https://github.com/mysqljs/mysql/blob/1720920f7afc660d37430c35c7128b20f77735e3/lib/protocol/packets/OkPacket.js#L25

`changedRows` is result of parsing free-form text message from server that might (or might not) contain the number of rows that actually changed as result of the query

**Comment by sidorares** [comment]
@hauboldj feel free to add this if you need, or I might add later (there are more important feature requests for this library on my list)

**Comment by plusmancn** [comment]
@sidorares Can i make a pr for you ?

**Comment by sidorares** [comment]
of course!

**Comment by sidorares** [comment]
note that currently we don't read message at all, and I'd like eventually support full [spec for OK packet](https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html), including session info update and session_state_changes flags (if supported by server) - see #388

**Comment by sidorares** [comment]
example if de-serialising based on server capabilities flags: https://github.com/sidorares/node-mysql2/blob/973112f3da4c8ccaecbd3545ad2b3df41e8ba4ad/lib/packets/change_user.js#L37-L54

probably need to pass server capabilities flags to packet in constructor

**Comment by plusmancn** [comment]
[PR#400](https://github.com/sidorares/node-mysql2/pull/400)

**Comment by sushantdhiman** [comment]
Closed in https://github.com/sidorares/node-mysql2/commit/5f10b4ac358221572de3fc58f33e3e8b5b735d32
