### ISSUE TITLE
`connection.stream` does not close in Bun

### ISSUE THREAD

**Issue by steelywing** [sidorares/node-mysql2#2884]
I cannot confirm this is Bun bug or mysql2 bug

Reproduce:

```js
// Get the client
import mysql from 'mysql2/promise';

// Create the connection to database
const connection = mysql.createConnection({
    host: 'localhost',
    user: 'test',
    password: 'password',
    database: 'test',
});

try {
} catch (err) {
    console.log(err);
} finally {
    // this does not call `connection.stream.end()` in Bun
    await connection.end();
}

console.log("end");

// if comment out this line, `stream.end()` does not be called in Bun, 
// so Bun will not exit, but node.js will exit normally
connection.connection.close();
```

the doc says we only need to call `connection.end()`, but that function does not end the net stream in Bun

Related: https://github.com/oven-sh/bun/issues/11414

**Comment by wellwelwel** [comment]
Hi, @steelywing. Thanks for the report.

This issue is reflected in **MySQL2** tests too:

https://github.com/sidorares/node-mysql2/blob/3659488d8736da0e7e5a5178811d50155e1a8155/test/integration/connection/test-select-ssl.test.cjs#L17-L29

> Note the `process.exit(0)`.

---

I haven't had time to check whether this should be an error to be reported in **Bun** or handled directly in **MySQL2**.

However, in the short research I've done, this seems to be related to the way **Bun** handles callbacks.

**Comment by Tanavya** [comment]
Is this related to my issue? https://github.com/oven-sh/bun/issues/12155

**Comment by wellwelwel** [comment]
Related:

- #2387

**Comment by wellwelwel** [comment]
Unfortunately, I can't see which version of Bun started this, but this error was introduced later (before some specific version, it worked normally).

Looking at what has changed in this version could help clarify what happened.

**Comment by steelywing** [comment]
I found the cause is if socket is FIN from the other side, the `Socket` will not exit.

I have a question from this code, is it better call `end()` even if it is client:

https://github.com/sidorares/node-mysql2/blob/ac76a5d9196312a11d4ac8e5d258fbfd4db46585/lib/connection.js#L894

**Comment by wellwelwel** [comment]
@steelywing, it seems that **Bun** has fixed this bug in https://github.com/oven-sh/bun/pull/13212.

After they release it, I'll revisit **MySQL2** tests 🚀
