### ISSUE TITLE
  deleted: Buffer(1) [ 0 ],

### ISSUE THREAD

**Issue by YANGLEDUO1** [sidorares/node-mysql2#2906]
```js
const queryResult = await mysql_util().query("select id, created_by createdBy, created_date createdDate, deleted from trade_staff_transaction limit ?,?",
      [index * 20000, 20000]
    );
    if (Array.isArray(queryResult)) {
      console.log(queryResult[0])
      return
    } 
```

result: 
```JSON
{
  id: "0000152bb1894ad199e6a06078698ea1",
  createdBy: "em1631001122502CVT",
  createdDate: 2024-05-13T08:52:05.000Z,
  deleted: Buffer(1) [ 0 ],
  lastModifiedBy: null,
  lastModifiedDate: null
}
```
why boolean is Buffer

**Comment by wellwelwel** [comment]
Hi, @YANGLEDUO1. Can you share a minimal repro (if possible, with a minimal schema)?

**Comment by sidorares** [comment]
@YANGLEDUO1 or maybe to start can you share a schema? ( `show create table trade_staff_transaction` )?

**Comment by YANGLEDUO1** [comment]
> @YANGLEDUO1 or maybe to start can you share a schema? ( `show create table trade_staff_transaction` )?

CREATE TABLE `trade_staff_transaction` (
  `id` varchar(50) NOT NULL,
  `created_by` varchar(100) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `deleted` bit(1) NOT NULL,
  `last_modified_by` varchar(100) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

**Comment by YANGLEDUO1** [comment]
I used bun

**Comment by YANGLEDUO1** [comment]
> Hi, @YANGLEDUO1. Can you share a minimal repro (if possible, with a minimal schema)?

mini repro https://github.com/YANGLEDUO1/2906.git

**Comment by YANGLEDUO1** [comment]
Brother. Is there a recurrence

**Comment by YANGLEDUO1** [comment]
> @YANGLEDUO1 or maybe to start can you share a schema? ( `show create table trade_staff_transaction` )?

Brother. Is there a recurrence
