### ISSUE TITLE
Times parsed in local time make test fail

### ISSUE THREAD

**Issue by vogievetsky** [sidorares/node-mysql2#296]
This line of code: https://github.com/sidorares/node-mysql2/blob/master/lib/packets/packet.js#L192

Makes this assert: https://github.com/sidorares/node-mysql2/blob/master/test/unit/packets/test-datetime.js#L19 fail for me

This is because `new Date(...)` will parse the time as a local time.
Should we convert this to `new Date(Date.UTC(...))` and always parse the time in UTC? seems safer.

**Comment by sidorares** [comment]
yes, or not convert to timestamp and check only with `d.getYear()` etc

**Comment by sidorares** [comment]
should be fixed with 49fe4023c0925b0e322a4cbedf67cc42662faf6a
