### ISSUE TITLE
Canary Version

### ISSUE THREAD

**Issue by wellwelwel** [sidorares/node-mysql2#2996]
Hey @sidorares, what about a canary version? 🙋🏻‍♂️

We could publishing to **npm** a canary tag for every merge in `master` branch that isn't a release. Then we could keep the current **release-please** behavior, releasing _officially_ when we feel safe.

Critical updates could be released instantly, while refactoring, general fixes and new features could wait a week, for example.

**Comment by wellwelwel** [comment]
Taking the occasion, I'm using the `provenance` option to publish my projects and I think this would also be of great value for **MySQL2**.

A real example:

<img width="795" alt="Screenshot 2024-08-29 at 10 53 19" src="https://github.com/user-attachments/assets/8181450f-be58-45df-a0be-58e523465dda">

**Comment by sidorares** [comment]
currently its mainly dependabot PRs that don't trigger npm releases. It's probably a good idea to publish immediately to canary. What would be the version on that case? canary + sha?

**Comment by wellwelwel** [comment]
Based on what **Bun** is like, it usually predicts the likely new version. For example:

- Current version: `3.11.0`
- Next predicted canary version: `3.11.1-canary-hash1`
- Next predicted canary version: `3.11.1-canary-hash2`

If the new stable version is `3.12.0` instead of `3.11.1`, then:

- Next predicted canary version: `3.12.1-canary-hash`

---

> currently its mainly dependabot PRs that don't trigger npm releases

We can also filter based on commit message to avoid unnecessary commits, e.g., bots, CI and documentations 🙋🏻‍♂️

**Comment by wellwelwel** [comment]
An interesting approach is to use the short hash of the commit that is generating the canary version, e.g.:

<img width="764" alt="Screenshot 2024-09-04 at 07 54 58" src="https://github.com/user-attachments/assets/7083a2b1-f3e5-43ae-938e-9196d4515b30">

**Comment by wellwelwel** [comment]
Hey @sidorares, from **npm** after #3029 ✅✨

<img width="787" alt="Screenshot 2024-09-10 at 06 56 30" src="https://github.com/user-attachments/assets/11bc1844-7872-4287-a1c0-75c494a7aeb3">
<img width="787" alt="Screenshot 2024-09-10 at 06 56 04" src="https://github.com/user-attachments/assets/93af6f68-8101-4a7d-8e58-6e3bf835572d">
