### ISSUE TITLE
mysql2 reports EPIPE error instead of ER_BAD_FIELD_ERROR

### ISSUE THREAD

**Issue by diversario** [sidorares/node-mysql2#301]
I'm using `mysql2` in `knex`, which in turn is used in a `bookshelf` model.

When I attempt to insert a model that has a field that doesn't exist in the table `mysql2` returns this error:

```
{ [Error: insert into `test_table` (`create_time`, `text1`, `text2`, `text3`, `text4`, `nonexistent_column`, `text5`) values ('2016-05-04 15:52:17.174', 'http://google.com', '2016-05-04 15:52:11.512', 'http://yahoo.com', 2, 3, 1
) - This socket has been ended by the other party] code: 'EPIPE', fatal: true }
```

However, given the exact same scenario but using `mysql` instead the error is:

```
[Error: insert into `test_table` (`create_time`, `text1`, `text2`, `text3`, `text4`, `nonexistent_column`, `text5`) values ('2016-05-04 16:05:54.726', 'http://google.com', '2016-05-04 16:05:46.093', 'http://yahoo.com', 2, 3, 1
) - ER_BAD_FIELD_ERROR: Unknown column 'nonexistent_column' in 'field list']
```

This is incredibly misleading and I'm not sure why EPIPE is returned by `mysql2` (or maybe it's knex?).

`mysql2` version is 1.0.0-rc.1.
`mysql` version is 2.10.2

**Comment by sidorares** [comment]
Thanks for report! 
Are you able to provide simple example to replicate? ( with schema creation, no knex, just "create table" + "insert" ), that would help me a lot

**Comment by diversario** [comment]
Sure!

The table is as follows:

```sql
CREATE TABLE `test_table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `text5` int(10) unsigned NOT NULL,
  `text4` int(10) unsigned NOT NULL,
  `text1` text,
  `text3` text,
  `text2` datetime NOT NULL,
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_text5` (`text5`),
  KEY `ix_text4` (`text4`),
  KEY `ix_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4
```

and data being inserted is
```
{
  text5: 1,
  text4: 2,
  text1: 'http://google.com',
  text3: 'http://yahoo.com',
  nonexistent_column: 3,
  text4: new Date()
}
```

**Comment by diversario** [comment]
Oh, and `text2` is being defaulted to `new Date()` by the model.

**Comment by sidorares** [comment]
can't reproduce, getting error "Error: Column count doesn't match value count at row 1", code: 'ER_WRONG_VALUE_COUNT_ON_ROW', errno: 1136

```js
var c = mysql.createConnection({ })
c.query('drop table test_table ', (err, rows, fields) => console.log(err, fields, rows))
c.query(`
  CREATE TABLE test_table (
    id int(10) unsigned NOT NULL AUTO_INCREMENT,
    text5 int(10) unsigned NOT NULL,
    text4 int(10) unsigned NOT NULL,
    text1 text,
    text3 text,
    text2 datetime NOT NULL,
    create_time datetime NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY ux_text5 (text5),
    KEY ix_text4 (text4),
    KEY ix_create_time (create_time)
  ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4
`, (err, rows, fields) => console.log(err, fields, rows))

c.query('insert into test_table values(?)', [{
  text5: 1,
  text4: 2,
  text2: new Date(),
  text1: 'http://google.com',
  text3: 'http://yahoo.com',
  nonexistent_column: 3,
  text4: new Date()
}], (err, rows, fields) => console.log(err, fields, rows))
```

**Comment by sidorares** [comment]
with query from your example:

```js
var query = "insert into `test_table` (`create_time`, `text1`, `text2`, `text3`, `text4`, `nonexistent_column`, `text5`) values ('2016-05-04 15:52:17.174', 'http://google.com', '2016-05-04 15:52:11.512', 'http://yahoo.com', 2, 3, 1)"
c.query(query, (err, rows, fields) => console.log(err, fields, rows));
```

error is `Error: Unknown column 'nonexistent_column' in 'field list', code: 'ER_BAD_FIELD_ERROR', errno: 1054, sqlState: '#42S22'`

**Comment by diversario** [comment]
The second part is what I'd expect. Maybe it's knex?

**Comment by diversario** [comment]
Maybe this helps: I see this error if I try to insert `null` into a `text` field (like `text1` in the schema).

**Comment by sidorares** [comment]
could you try to reproduce it without knex? ( or post single reproducible script with knex )

**Comment by sidorares** [comment]
still same ( expected ) error when I insert null - `Error: Unknown column 'nonexistent_column' in 'field list'`

**Comment by diversario** [comment]
I'll come up with a gist but in the meantime could you try inserting a `null` into of the `text` type fields? Without the `nonexistent_column`, that is.

**Comment by sidorares** [comment]
```js
var query = "insert into `test_table` (`create_time`, `text1`, `text2`, `text3`, `text4`, `text5`) values ('2016-05-04 15:52:17.174', null, '2016-05-04 15:52:11.512', 'http://yahoo.com', 2, 3)"
c.query(query, (err, rows, fields) => console.log(err, fields, rows));
```
outputs 

```
null undefined ResultSetHeader {
  fieldCount: 0,
  affectedRows: 1,
  insertId: 1,
  serverStatus: 2,
  warningStatus: 0 }
```

**Comment by diversario** [comment]
Damn. Alright, I'm going to try reproducing this without knex.

**Comment by diversario** [comment]
I tried using just `mysql2`.

Inserting an invalid field gives back `ER_BAD_FIELD_ERROR`, inserting a null works just fine. Must be something with `knex` 😔

**Comment by diversario** [comment]
FYI, this what it turned out to be https://github.com/felixge/node-mysql/issues/1411

Connection was lost due to db failover and the pool library that `knex` uses didn't reacquire one automatically.
