### ISSUE TITLE
Exposed .escape() functions exposes but don't cover the MySQL original typing

### ISSUE THREAD

**Issue by ScrapsPrograms** [sidorares/node-mysql2#3030]
During some experimentation, I found that the type definition of the `.escape(value: any)` function isn't correct. Currently, for all locations, it's described as `.escape(value: any): string`.

The function exposed by the package, however, has a different interface: `.escape(value: any, stringifyObjects: boolean, timeZone: string | "local")`. From what I've found so far, this applies only to the loose exposed function, not to any of the class defined methods, which seem to wrap this function by abstraction. 

For reference, the classes with a `.escape(value: any)` method are in Pool and Connection.

I'm willing to put a PR for this, if you agree the typing information should be updated, or if an abstraction should be applied to the loose exposed function similar to the class defined `.escape` methods.

**Comment by wellwelwel** [comment]
Thanks for the report, @ScrapsPrograms 🙋🏻‍♂️

> I'm willing to put a PR for this, if you agree the typing information should be updated, or if an abstraction should be applied to the loose exposed function similar to the class defined `.escape` methods.

Please, feel free to contribute 🤝

**Comment by wellwelwel** [comment]
> .escape(value: any, stringifyObjects: boolean, timeZone: string | "local")

Just a tip:

Instead of `string | 'local'`, you can use `'local' | string & {}`. It will allow using a dynamic string, keeping the auto suggestion support, e.g.:

<img width="641" alt="Screenshot 2024-09-10 at 05 43 04" src="https://github.com/user-attachments/assets/0f5fe9d4-66bd-4932-8274-144d1d0b4c6f">
