### ISSUE TITLE
weak hashing algorithm used 

### ISSUE THREAD

**Issue by amitagarwal-dev** [sidorares/node-mysql2#3031]
Mysql2 version: 3.11.0

I am writing this to raise an issue regarding weak hashing algorithm (SHA1) used in the mysql2 code.  
This vapt is raised by the CISO team and we are seeking for a fix/patch for this issue.  
Please provide your comment on this!  

![image](https://github.com/user-attachments/assets/44b304df-a521-4cb0-bef1-a0673cadb1e7)   
  
`CODE`  
  
path: mysql2/lib/auth_41.js  

```js
function sha1(msg, msg1, msg2) {
  const hash = crypto.createHash('sha1');
  hash.update(msg);
  if (msg1) {
    hash.update(msg1);
  }

  if (msg2) {
    hash.update(msg2);
  }

  return hash.digest();
}
```

**Comment by wellwelwel** [comment]
Closing in favor of #3045.
