### ISSUE TITLE
Add linting rules

### ISSUE THREAD

**Issue by gajus** [sidorares/node-mysql2#307]
It is extremely hard to contribute to the codebase when there are no linting rules/ code style is inconsistent between files.

I suggest to use one of the existing style guides, https://github.com/dustinspecker/awesome-eslint#configs:

* Canonical is the most strict of them all (I am biased though, since it is the package that I maintain).
* AirBnb is the most popular.
* Standard while popular, is very loose

@sidorares Do you agree that linting rules need to be added? Do you have preference for which style guide to use?

**Comment by sidorares** [comment]
yes, agree 100%

I started integrating eslint in https://github.com/sidorares/node-mysql2/tree/eslint but did not finish yet, can you have a look at what's there first?

**Comment by sidorares** [comment]
https://github.com/sidorares/node-mysql2/pull/268
