### ISSUE TITLE
What is the correct syntax for including SQL values and rowsAsArray option in a query?

### ISSUE THREAD

**Issue by millerbryan** [sidorares/node-mysql2#3094]
I've looked at all the examples in the docs which use `rowsAsArray` and it isn't clear how to specify it in a query (rather than in the connection).  Is this possible?

```
// simplified code
const sql = "select county_name from static_web_data.state_counties where state_name = ?";
const state = "TX"

        try {
          const [rows, fields] = await pool.query({sql, [state], rowsAsArray: true});
          if (rows) {
            return rows;
          }
        } catch (err) {
          console.log(err);
        }
```

**Comment by wellwelwel** [comment]
Hi, @millerbryan 🙋🏻‍♂️

You can set it in both `connection` and `query`/`execute` levels:

https://github.com/sidorares/node-mysql2/blob/d02aa7c9a0cd6d91a3df25d768420cf83b044bbd/website/docs/index.mdx#L452-L457

https://github.com/sidorares/node-mysql2/blob/d02aa7c9a0cd6d91a3df25d768420cf83b044bbd/website/docs/index.mdx#L481-L491
