### ISSUE TITLE
typeCast Next type appears to be incorrect

### ISSUE THREAD

**Issue by bbugh** [sidorares/node-mysql2#3122]
# Problem

The current return type of `Next` is `void`. This led to a bug in the code because as currently typed, the return value of `next` appears to be unnecessary. 

https://github.com/sidorares/node-mysql2/blob/9ba3706d4726fd951b83dfcec2280705875cbae2/typings/mysql/lib/parsers/typeCast.d.ts#L52-L54

I discovered in my code that unless `next()` was returned, this function would result in many `undefined` values. However, in every case that I can find it, `next` is called as `return next()`. If it is not returned, the result is empty data.

```ts
// bad, results in all `undefined` values:
typeCast: (field, next) => { next() }

// good, returns expected results
typeCast: (field, next) => { return next() }
```

Additionally, typescript-eslint correctly raises an error on this with the `@typescript-eslint/no-confusing-void-expression` rule:

**Example 1**
<img width="927" alt="Pasted_Image_10_15_24__1_49 PM" src="https://github.com/user-attachments/assets/c763861c-eb23-44a1-8942-45c8c5a37216">

**Example 2**
<img width="792" alt="image" src="https://github.com/user-attachments/assets/a494eea4-e5a2-4925-b000-f60865f78955">

# Proposed solution

Since the return value is required, but the type is not known, the `unknown` type seems like the most correct option here. I tested and this resolves the issue.

```diff
mysql2/typings/mysql/lib/parsers/typeCast.d.ts
-export type Next = () => void;
+export type Next = () => unknown;
```

I can submit a PR if requested (and it will be accepted).

**Comment by wellwelwel** [comment]
> ```ts
> // good, returns expected results
> typeCast: (field, next) => { return next() }
> ```

@bbugh, could you help with a basic debug _(if you can't, I'll try to check it out later)_?

What would `console.log(next())` return in general or when would it return something other than `void | undefined`?

**Comment by bbugh** [comment]
`console.log(next())` will print whatever the value of the field is. I don't think it should ever be `void`:

```
"a3adef49-a125-5e83-bc84-0a9f57f5b167"
"5b455423-7961-53b7-a627-93db69ab295c"
"ac4233ad-b60e-5ce9-9185-3d366815348c"
4
```

---

Here is further demonstration of the issue. The console output of the following code when typeCast `next` return value is not or is returned:

```ts
const [rows] = await connection.query(sql, values);
console.log(rows);
```

❌ Without returning `next`, no fields have values

```ts
typeCast: (field, next) => { next(); }, // notice no "return"
```

```
{
  id: undefined,
  projectId: undefined,
  taskId: undefined,
  status: undefined,
},
{
  id: undefined,
  projectId: undefined,
  taskId: undefined,
  status: undefined,
}
```

✅ With returning `next`, it returns the field values

```ts
typeCast: (field, next) => { return next() },
```

```
{
  id: "a3adef49-a125-5e83-bc84-0a9f57f5b167",
  projectId: "5b455423-7961-53b7-a627-93db69ab295c",
  taskId: "ac4233ad-b60e-5ce9-9185-3d366815348c",
  status: 4,
},
{
  id: "cf483a80-52a0-5f53-8b24-03dc9d6dc60c",
  projectId: "01b821bf-e4a8-5953-8d59-72d1a28b4543",
  taskId: "2a803da9-b6c6-5746-989b-ca07832d0a72",
  status: 2,
}
```

**Comment by wellwelwel** [comment]
Thanks for the debug, @bbugh 🤝

> I can submit a PR if requested (and it will be accepted).

Please, feel free to contribute 🚀
