### ISSUE TITLE
Query callback never called when values is an empty array

### ISSUE THREAD

**Issue by ctlajoie** [sidorares/node-mysql2#318]
If I do a query like `pool.query('select * from settings', [], function(err, result){})` then the callback function never gets called. This works fine in node-mysql.

**Comment by sidorares** [comment]
I believe this is fixed in master - see #270

Could you test with version from master?

**Comment by ctlajoie** [comment]
Yeah master works way better. Also solved a couple other weird things I was experiencing that I thought weren't related. I humbly recommend publishing a new version. The current one is broken in a subtle but significant way...

**Comment by sidorares** [comment]
I really want to finish some semver major changes before publishing final 1.0.0

Published current master as v1.0.0-rc.2

Thanks for feedback @ctlajoie !
