### ISSUE TITLE
New errors after switching from mysql module

### ISSUE THREAD

**Issue by forty** [sidorares/node-mysql2#3190]
I'm trying to upgrade a large and old codebase using the mysql module to mysql2. I managed to have things compiling (we use TS) and kind of working (yeah!)

To limit the possible number of trouble, I added
```
    decimalNumbers: true,
    jsonStrings: true
```
to my config. 

Now we have lot of failing test with mostly the following errors:
- ER_BAD_NULL_ERROR
- ER_WARN_DATA_OUT_OF_RANGE

Those seem to be legitimate comptains but as this is tests, I don't really mind those wrong queries for now. It seems it was ignore with mysql library. Is it possible to get the same behavior with mysql2?
I suspect this has to do with sql_mode, but I could not find anything that either library would do with this parameter, so I'm a bit lost.

Thanks!

**Comment by wellwelwel** [comment]
Hey @forty, I use labels to organize the issues, but I usually comment too (in that case, I would ask for a minimal reproduction, if possible) 🙋🏻‍♂️

> Ignore everything I said, sorry for the spam :/

No worries, feel free to ask questions, report errors and contribute to the project 🤝

**Comment by forty** [comment]
Haha no worries, no comment was needed here, I actually saw the label when I came back to post my previous message, and thought it was spot on :) thank you!
