### ISSUE TITLE
⨯ TypeError: Cannot read properties of undefined (reading 'escape')

### ISSUE THREAD

**Issue by Waylon-Firework** [sidorares/node-mysql2#3213]
When using the "next": "15.0.3", in the docker, there is an error.

```
 ⨯ TypeError: Cannot read properties of undefined (reading 'escape')
    at <unknown> (/app/.next/server/chunks/736.js:5:59233)
    at 6764 (/app/.next/server/chunks/736.js:5:59370)
    at t (/app/.next/server/webpack-runtime.js:1:143)
    at 2786 (/app/.next/server/app/myshopify/api/oauth/user/route.js:1:3913)
    at t (/app/.next/server/webpack-runtime.js:1:143)
    at 6759 (/app/.next/server/chunks/400.js:1:9253)
    at t (/app/.next/server/webpack-runtime.js:1:143)
    at 8794 (/app/.next/server/chunks/400.js:1:1449)
    at t (/app/.next/server/webpack-runtime.js:1:143)
    at 1354 (/app/.next/server/app/welcome/page.js:1:3698)
```

package.json

```
{
  "name": "auth",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev -p 7310",
    "build": "next build",
    "start": "next start -p 7310",
    "lint": "next lint"
  },
  "dependencies": {
    "moment": "^2.30.1",
    "mysql2": "^3.11.4",
    "next": "15.0.3",
    "next-auth": "5.0.0-beta.24",
    "react": "^18",
    "react-dom": "^18",
    "snowflake-uuid": "^1.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "15.0.3",
    "typescript": "^5"
  }
}

```

DockerFile

```
FROM node:23-alpine AS base
```

**Comment by lemurki** [comment]
We have the same error when trying to connect to the database from server action.

`"dependencies": {
    "@reduxjs/toolkit": "^2.3.0",
    "@web/utils": "^0.0.21",
    "jose": "^5.9.6",
    "maxmind": "^4.3.22",
    "mysql2": "^3.11.4",
    "next": "^15.0.3",
    "next-share": "^0.27.0",
    "nodemailer": "^6.9.16",
    "prop-types": "^15.8.1",
    "react": "^19.0.0-rc.1",
    "react-dom": "^19.0.0-rc.1",
    "react-redux": "^9.1.2",
    "sass": "^1.80.6"
  },`

**Comment by lemurki** [comment]
@Waylon-Firework You can try this one https://nextjs.org/docs/app/building-your-application/optimizing/package-bundling#opting-specific-packages-out-of-bundling-1 . This solved the problem for me.

**Comment by ck-euan** [comment]
I also encountered the issue when upgrading to Next 15.0.3. Similarly the issue only happens when running the app in docker and using mysql2 in a server action.

Adding mysql2 to the `serverExternalPackages` as suggested above caused this error in the docker build:

`ERROR: failed to solve: cannot copy to non-directory: /var/lib/docker/overlay2/8y2nl96kmjrftisoamjn8x8c1/merged/app/node_modules/mysql2` @lemurki do you know how to solve this?

**Comment by lemurki** [comment]
@ck-euan Hello, I'm not sure if I can help with this.
We deploy next.js without docker, so I didn't have this exact problem. 

Unfortunately I don't have much experience with docker. But maybe you should try adding mysql2 to the Dockerfile dependencies as well.

**Comment by Waylon-Firework** [comment]
@lemurki Thank you. I tried and there is no error now.

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "standalone",
  reactStrictMode: false,
  serverExternalPackages: ['mysql2'] // this line
};

export default nextConfig;

```

**Comment by Waylon-Firework** [comment]
But it seems that the sql statement cannot be executed normally.

**Comment by Waylon-Firework** [comment]
Not sure if this is a problem with nextjs or a problem with mysql2

**Comment by Waylon-Firework** [comment]
Oh, sorry, it works fine. 

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "standalone",
  reactStrictMode: false,
  serverExternalPackages: ['mysql2'] // this line
};

export default nextConfig;
```
