### ISSUE TITLE
[BUG]query with ? placeholder got worng result

### ISSUE THREAD

**Issue by dsonet** [sidorares/node-mysql2#323]
I tested the exact same query, mysql works well. mysql2 doesn't.
pool.query('UPDATE table SET col1=?,col2=? WHERE Id = ?', [1,'http://domain.com/?query=', 3])

It will produce `1, http://domain.com/1query=`
It replace the ? in the value instead of parameter.

But test both mysql.format and mysql2.format they out put the same. That very strange.

**Comment by sidorares** [comment]
which version of mysql2 are you using? Can you post complete code I can reproduce ( with schema etc )?

**Comment by sidorares** [comment]
ouch, I think I see the problem in https://github.com/dsonet/node-mysql2/commit/662cd7f7579638d3d64cbe7b0007119ffa3d6f1a, thanks. Would you be able to add test as well?

**Comment by dsonet** [comment]
Thanks for your reply. Sure. Where to put the test?

**Comment by sidorares** [comment]
probably at the same level as  `/test/integration/connection/test-named-paceholders.js` - have a query containing "?" value in a parameter and use it from pool. Should fail without your change and pass with. Thanks!
