### ISSUE TITLE
Performance Discrepancy in Stored Procedure Execution: Local vs. Node.js

### ISSUE THREAD

**Issue by kapilsharma-gts** [sidorares/node-mysql2#3267]
Solved

**Comment by kapilsharma-gts** [comment]
![image](https://github.com/user-attachments/assets/98d55f34-01e9-40b6-9295-f91dab32eff9)
![image](https://github.com/user-attachments/assets/5c90787f-3398-4d54-933b-2f1b82fab4f3)
please also you check ss

**Comment by wellwelwel** [comment]
@kapilsharma-gts, could you create a minimal repository using only **MySQL2** with a minimal database (`.sql`) to reproduce it locally?
