### ISSUE TITLE
How to return the promise for further usage.

### ISSUE THREAD

**Issue by EduardJS** [sidorares/node-mysql2#328]
Hello! 

I'm somewhat new to promises and stuff regarding this so.. I did a small `DB` module which I'm importing wherever I need it.

```javascript
var DB = function() {
	this.pool = require('mysql2').createPoolPromise({ host: '', user: '', password: '', database: '' });
}

DB.prototype.query = function( sql, format ) {
	this.pool.getConnection().then( conn => {
		var result = conn.query( sql , format );
		conn.release();
		return result;
	}).catch( err => {
		console.log( err );
	});
}

module.exports = new DB();
```

Now, in another module, I'm requiring the `DB.js` module as follows

```javascript
var db = require( './controllers/DB.js' );
```

How I would like to use it is as follows:
```javascript
db.query( 'SELECT * FROM users WHERE id = ? LIMIT 1', [ 5 ] ).then( result => {
     console.log( result );
});
```

Though everything "seems" to be working, I'm having an error as follows:
```javascript
TypeError: Cannot read property 'then' of undefined
```

What am I doing wrong ? I guess that the `result` var is not a Promise type of object ? If so, what should I return in order to `chain` the result in other modules.

Thank you

**Comment by EduardJS** [comment]
My bad. Forgot to use `return` for `this.pool.getConnection()` in `DB.prototype.query`.

**Comment by sidorares** [comment]
@EduardJS there are also `pool.query()` and `pool.execute()` helpers ( promise version as well ) that do the same as your helper:

```js
require('mysql2').createPoolPromise({ host: '', user: '', password: '', database: '' })
  .query('select * FROM users WHERE id = ? LIMIT 1', [ 5 ] )
  .then( ([rows, columns]) => {
     console.log(rows); // or result[0] without destructuring
  })
  .catch( err => console.log(err) );
```

**Comment by EduardJS** [comment]
So I wasted my whole day trying to understand `Promises` even trying to use `asying / await`... now you tell me I could have done that in 3 lines of code.. #feelsbadman.

**Comment by sidorares** [comment]
it's not wasted, you still learned something :)

**Comment by EduardJS** [comment]
@sidorares I am bugging you with one last small thing. I have managed replacing most of my callbacks with nice and readable promises thanks to you.

One thing I just don't get my head around with is.. how to deal with the repetitive structures... consider the following:

```javascript
db.query( 'SELECT * FROM merchants WHERE id = 5' )
	.then( ([ rows, columns ]) => {
		return rows[0];
	})
	.then( merchant => {
		db.query( 'SELECT * FROM shops WHERE merchantID = ?', [ merchant.id ] ).then( ([ shops, columns ]) => {
			for ( let i = 0; i < shops.length; i++ )
			{
				var shop = shops[i];
				// get products for iterated shop
				db.query( 'SELECT * FROM products WHERE shopID = ? ORDER BY name ASC', [ shop.id ] ).then( ([ products, columns ]) => {
					for ( let i = 0; i < products.length; i++ )
						shop.products.push( product[i] );
				});
				// get orders for iterated shop
				db.query( 'SELECT * FROM orders o INNER JOIN products p ON p.id = o.productID WHERE p.shopID = ?', [ shop.id ] ).then ( ([ orders, columns ]) => {
					for ( let i = 0; i < orders.length; i++ )
						shop.orders.push( order[i] );
				});
				merchant.shops.push( shop );
			}
			cb( merchant );
		});
	});
```

I'm yet to figure this one out... does mysql2 handle stuff like this as well or do I need to use some other `Promises` library with `Promise.all` support.

At first I thougt about "queue-ing" into `conn` then `execute` but I don't think it works like that.
Can you please advise ? Thank you !

**Comment by sidorares** [comment]
first of all I suspect that inner loop might be removed with some kind of join

if you want to call `cb( merchant );` only after all inner loop promises are resolved you can use something like this

```js
db.query( 'SELECT * FROM merchants WHERE id = 5' )
    .then( ([ rows, columns ]) => {
        var merchant = rows[0];
        merchant.shops = [];
        return merchant;
    })
    .then( merchant => {
         var products = [];
         var orders = [];
         db.query( 'SELECT * FROM shops WHERE merchantID = ?', [ merchant.id ] )
          .then([shops] => {
              products = shops.map( shopId => db.query( 'SELECT * FROM products WHERE shopID = ? ORDER BY name ASC', shopId );
              orders = shops.map( shopId => db.query( 'SELECT * FROM products WHERE shopID = ? ORDER BY name ASC', shopId );
             Promise.all(products)
                .then( products => /* do something with products */ )
                .then( () => {
                     Promise.all(orders).then(
                        // all ready, call callback?
                     );
                 }


          });

```

there might be better solution, I personally prefer traditional callbacks or async library and not very experienced in promise patterns

also instead of using loops to append array I'd use something like this

```js
    var arr1 = [1, 2, 3];
    var arr2 = [3, 4, 5];
    console.log(arr1.concat(arr2)); // instead of for (var i=0; i < arr2l ++i) { arr1.push(arr2[i]); }
```
