### ISSUE TITLE
rows[0][0] is a must ?

### ISSUE THREAD

**Issue by EduardJS** [sidorares/node-mysql2#329]
Hello! I'm using the Pool Promise implementation and whenever I return a result of a query it comes assembled as a two-part `Array`, `rows[0]` being the actual result, and then `rows[1]` seems to be some `Buffer` thing.

My question is, if I try returning only `conn.query( SQL )[0]` as the promise, it does not work. Thus, in `.then( result => { ... }` I always have to do `rows = rows[0];`.

Is that necessary or am I missing something ?

**Comment by sidorares** [comment]
it mirrors non-promise version: `conn.query(sql, params, (err, rows, columns) => { /*... */ } );`
the promise resolves to `[rows, columns]` when successful or rejects to `err` value

You can use destructuring arguments in your `.then` handler:

`promiseConn.query(sql, params).then([rows] => { console.log(rows) })`

**Comment by EduardJS** [comment]
Got it chief. Appreciate the fast reply at this hour.
