### ISSUE TITLE
Error using prepared statements

### ISSUE THREAD

**Issue by sandlerr** [sidorares/node-mysql2#330]
Hi there,
We're struggling to figure out how to use `connection.execute()` - we're having a promise rejected with `Error: Incorrect arguments to mysqld_stmt_execute`.

Code:

```js
const mysql = require('mysql2/promise');
mysql.createConnection({
	host		: process.env.MYSQL_HOST,
	user		: process.env.MYSQL_USER,
	password	: process.env.MYSQL_PASSWORD,
	database	: db_name
}).then((conn) => conn.execute('select 1+? as sum'), ['1'])
```

package.json has `"mysql2": "^1.0.0-rc.5"`

Mysql is 5.7.13 from homebrew on OSX.

@zz85

**Comment by sidorares** [comment]
Looks like you call `conn.execute('select 1+? as sum')` without parameters, note the order of parenthesis. Should it be

```js
const mysql = require('mysql2/promise');
mysql.createConnection({
    host        : process.env.MYSQL_HOST,
    user        : process.env.MYSQL_USER,
    password    : process.env.MYSQL_PASSWORD,
    database    : db_name
}).then((conn) => conn.execute('select 1+? as sum', ['1']))
```

?

**Comment by sidorares** [comment]
hope that helped @sandlerr , please reopen if you need more information!

**Comment by sandlerr** [comment]
Thanks, that's the problem!
