### ISSUE TITLE
None Working Server Implamentation

### ISSUE THREAD

**Issue by frank-dspeed** [sidorares/node-mysql2#332]
Hello my Frind trying to get this running on ubuntu 16.04 nodejs 6.2.1 main problem is all test fail

Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client

i am wondering what that means

mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper

is this only compatible to mysql 5.6 ?

**Comment by sidorares** [comment]
Currently this library does not support so called "Insecure auth", and looks like the user in your test is configured to have it. Are you controlling that user? Is it migrating to 4.1 auth an option for you @frank-dspeed ?

I'm not sure if insecure auth is going to be supported out of the box by this module ( though it'll be easy to have it client side when plugin auth support landed - see https://github.com/sidorares/node-mysql2/pull/331

You can read more about "Old password" / "New secure auth" here - https://dev.mysql.com/doc/internals/en/authentication-method.html

**Comment by frank-dspeed** [comment]
i readed it all but i still dont understand what to do because i am not as familary with the mysql protocoll it self :(.
but ok its not a issu its my fail so we can close this.
Thx a lot for the information

**Comment by sidorares** [comment]
Your options right now are
1) Convert user to have 4.1 auth ( recommended )
2) Wait until node-mysql2 support insecure auth (directly or via plugin)
3) Switch to node-mysql

Here is documentation for option 1: https://dev.mysql.com/doc/refman/5.6/en/account-upgrades.html
