### ISSUE TITLE
Wait for all queries to complete?

### ISSUE THREAD

**Issue by mnpenner** [sidorares/node-mysql2#334]
I'll start with an example:

``` js
const mysql = require('mysql2/promise');

let pool = mysql.createPool({
    user: dbVars.login,
    password: dbVars.password,
    host: 'dev-sql',
    connectionLimit: 10,
    namedPlaceholders: true,
});

let fullStruct = {
    server: {},
    databases: {},
};

pool.query("SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP) offset").then(([timeOffsetRows]) => {
    fullStruct.server.timeOffset = timeOffsetRows[0].offset;
});


pool.query("SELECT IF(@@session.time_zone = 'SYSTEM', @@system_time_zone, @@session.time_zone) timeZone").then(([timeZoneRows]) => {
    fullStruct.server.timeZone = timeZoneRows[0].timeZone;
});

await pool.end();
console.log(fullStruct);
```

This results in an error:

> Error: Pool is closed.

I believe this happens because I'm closing the pool/connection before one of the queries has started. Now I can fix this by pushing each of those query promises into an array and then calling `Promise.all` before `pool.end`, but littering my code with `queries.push(...)` is kind of gross. 

Does mysql2 not track the queries internally? Is there no way for me to just say "wait for everything to complete before closing"?

**Comment by sidorares** [comment]
> Does mysql2 not track the queries internally? Is there no way for me to just say "wait for everything to complete before closing"?

It does, but in your example `pool.end()` is called before first connection is acquired from pool

`pool.end()` sets "closing" flag immediately on pool but then waits for all connections to finish processing queries. I'm not sure what's the best solution to handle this more naturally, but that's the type of async problems you have to deal with

```js
let pool = mysql.createPool({
    user: dbVars.login,
    password: dbVars.password,
    host: 'dev-sql',
    connectionLimit: 10,
    namedPlaceholders: true,
});

let fullStruct = {
    server: {},
    databases: {},
};

[ [fullStruct.server.timeOffset] ] = await pool.query("SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP) offset");
[ [fullStruct.server.timeZone] ] = await pool.query("SELECT IF(@@session.time_zone = 'SYSTEM', @@system_time_zone, @@session.time_zone) timeZone");
await pool.end();
```

**Comment by mnpenner** [comment]
The awaits prevent the queries from running concurrently though, don't they?

What if I put `pool.end` inside `process.nextTick` -- would that work, or no?

I can find a way to deal with this on my end, I'm just trying to figure out if the library offers anything convenient for this pattern. 

I'm writing a script that's going to perform a ton of queries and I want it to run as fast as possible.

**Comment by sidorares** [comment]
with await you could have something like this (maybe not in one line and without crazy destructuring ):

```js
  [  [ [fullStruct.server.timeOffset] ], [ [fullStruct.server.timeZone] ] ] =
      await Promise.all([ 
        pool.query("SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP) offset"),
        pool.query("SELECT IF(@@session.time_zone = 'SYSTEM', @@system_time_zone, @@session.time_zone) timeZone") ]);         
```

process.nextTick might be not enough - when Promise is returned the promise handler itself might be called in different tick ( can't tell for sure ), so you have race between promise handlers in `.query()` and `.end()` + query() internally is doing `getConnection()` + `connection.query()` asynchronously, so it becomes really hard to tell for sure if [this line](https://github.com/sidorares/node-mysql2/blob/c487f542f7f4416f9759319225197c383b4937fb/lib/pool.js#L24) is called before [this one](https://github.com/sidorares/node-mysql2/blob/c487f542f7f4416f9759319225197c383b4937fb/lib/pool.js#L131) regardless on the original order of high level api calls.

**Comment by mnpenner** [comment]
What I ended up doing was writing a wrapper to track the promises myself, and then I pop them off at the end of the script and await each of them to make sure they're completed before I call `pool.end()`.

The only issue I'm having now is that when there's an SQL error, that connection seems to die; the query promise after it never resolves.

```js
let pool = mysql.createPool({ 
             connectionLimit: 1,
});

let queries = [];

const query = (sql, params) => {
    let promise = new Promise((resolve, reject) => {
        pool.query(sql, params, (err, rows, fields) => {
            if(err) {
                reject(err);
            } else {
                resolve(rows);
            }
        });
    });
    queries.push({sql,params,promise});
    return promise;
};

query("select 1").then(rows => {  ... }); // runs fine
query("select 2").then(rows => {  ... }); ; // runs fine
query("select @#x$!").then(rows => {  ... }); ; // errors as it should
query("select 4").then(rows => {  ... }); // hangs because the connection is now dead??

while(queries.length) {
    let query = queries.shift();
    console.log(queries.length,_.truncate(query.sql.replace(/\s+/g,' ').trim(),{length:50}),query.params);
    try {
        await query.promise;
    } catch(err) {
        console.log(err);
    }
}

pool.end();
```

I'll try to debug this more later to see what's going on.

**Comment by sidorares** [comment]
Thanks, I'll try to investigate.

**Comment by sidorares** [comment]
@mnpenner I suspect this has been fixed recently. Do you still have the code around to try?

**Comment by mnpenner** [comment]
@sidorares Which has been fixed? `pool.end()` will now wait for all queries to complete, or queries won't hang after there's been an error?

I tried my example from [this post](https://github.com/sidorares/node-mysql2/issues/334#issuecomment-229705421) again. The program *does* terminate now... but it turns out `select @#x$!` is *not* a syntax error, hah! I failed and making an error. Changed to `select !./*-`. Program does what I'd expect now -- shows there was a syntax error, and then runs the next query. 

Tried using the promise version too,

```js
const mysql = require('mysql2/promise');
const _ = require('lodash');

const fs = require('fs');

async function __main__() {

	let pool = mysql.createPool({
		user: 'root',
		password: '',
		host: 'dev1',
		connectionLimit: 10,
		namedPlaceholders: true,
	});

	let queries = [];

	const query = (sql, params) => {
		let promise = new Promise((resolve, reject) => {
			pool.query(sql, params, (err, rows, fields) => {
				if(err) {
					reject(err);
				} else {
					resolve(rows);
				}
			});
		});
		queries.push({sql,params,promise});
		return promise;
	};


	await pool.query("select 1").then(rows => {  console.log('aaa',rows); }); // runs fine
	await pool.query("select 2").then(rows => {  console.log('bbb',rows); }); // runs fine
	try {
		await pool.query("select !./*-").then(rows => {
			console.log('ccc', rows);
		}); // errors as it should
	}catch(err) {
		console.log('le error');
	}
	await pool.query("select 4").then(rows => {  console.log('ddd',rows); }); // hangs because the connection is now dead??

	pool.end();

}

__main__().catch(dump);
```

Which spits out

```
aaa [ [ TextRow { '1': 1 } ],
  [ { catalog: 'def',
      schema: '',
      name: '1',
      orgName: '',
      table: '',
      orgTable: '',
      characterSet: 63,
      columnLength: 1,
      columnType: 8,
      flags: 129,
      decimals: 0 } ] ]
bbb [ [ TextRow { '2': 2 } ],
  [ { catalog: 'def',
      schema: '',
      name: '2',
      orgName: '',
      table: '',
      orgTable: '',
      characterSet: 63,
      columnLength: 1,
      columnType: 8,
      flags: 129,
      decimals: 0 } ] ]
le error
ddd [ [ TextRow { '4': 4 } ],
  [ { catalog: 'def',
      schema: '',
      name: '4',
      orgName: '',
      table: '',
      orgTable: '',
      characterSet: 63,
      columnLength: 1,
      columnType: 8,
      flags: 129,
      decimals: 0 } ] ]
```

Just like I'd expect. So, everything appears to be in order.

I still think it'd be nice to have a `pool.waitForAllQueriesToTerminate()` function, but maybe that's too specific to my scenario? It's nice for scripts where you just need to run a bunch of queries and don't really care about the ordering.

**Comment by sidorares** [comment]
>  Which has been fixed?

This one:

> It doesn't appear to be releasing the connection when there's an error
