### ISSUE TITLE
Packet length causes issues with bn.js 

### ISSUE THREAD

**Issue by sheeley** [sidorares/node-mysql2#336]
Hey, I'm not certain whether this is actually an issue here or with bn.js, but I figured I'd throw this at you to see what your thoughts are.

In our codebase, using knex and mysql2, I get this stacktrace when running our seeds:
```
/Users/jsheeley/git/lumen/api/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
              ^

Error: Assertion failed
    at assert (/Users/jsheeley/git/lumen/api/node_modules/bn.js/lib/bn.js:6:21)
    at BN.iaddn (/Users/jsheeley/git/lumen/api/node_modules/bn.js/lib/bn.js:2121:5)
    at Packet.readLengthCodedNumberExt (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/packets/packet.js:145:37)
    at Packet.readLengthCodedNumber (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/packets/packet.js:114:15)
    at new ResultSetHeader (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/packets/resultset_header.js:12:28)
    at Query.resultsetHeader (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/commands/query.js:87:12)
    at Query.Command.execute (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/commands/command.js:38:20)
    at Connection.handlePacket (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/connection.js:263:28)
    at PacketParser.onPacket (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/connection.js:95:66)
    at PacketParser.executeStart (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/packet_parser.js:44:12)
    at Socket.<anonymous> (/Users/jsheeley/git/lumen/api/node_modules/mysql2/lib/connection.js:97:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

For a quick fix, I've swapped our client to use node-mysql, which seems to handle things just fine when I include `supportBigNumbers: true` in the config. Using that config with mysql2 doesn't seem to affect this issue. Any thoughts? Happy to help contribute here, but I'm ignorant of the inner workings, so being pointed in some direction would be helpful. :)

**Comment by sidorares** [comment]
Hi!
would you be able to include output if you connect with `debug: true` flag?

Also could you log `word1` and `word0` values just before lib/packets/packet.js:145 ?

**Comment by sidorares** [comment]
Also, what's expected big number value?

**Comment by sheeley** [comment]
thanks for the quick response! i'm whipping up a sample repo to try and demonstrate the behavior now. we aren't working with any data that should be bignum, so i don't have an expected output; it seems to be that mysql is returning a large number in response to bulk inserts.

my temporary workaround was to go in and comment out the assertion in `bn.js` and everything went fine. hopefully i'll be able to provide you with a sample shortly.

**Comment by sheeley** [comment]
The final query before it fails:
```
{ method: 'raw',
  sql: '\nINSERT INTO exp_type_lkp(exp_type_id, exp_type_nm, ins_user)\nVALUES\n(-999, \'Unknown\', \'seed-data\')\n\nON DUPLICATE KEY UPDATE\nins_user = values(ins_user);\n',
  bindings: undefined,
  options: {} }
/Users/jsheeley/git/lumen/bad-api/node_modules/bn.js/lib/bn.js:6
    if (!val) throw new Error(msg || 'Assertion failed');
```
(Working on getting you something actually useful, but have a lot of proprietary data to sift through, sorry).

The values: 
```
word0: 4294966297
word1: 4294967295
```

Anything else I can help with? I'll keep poking and see if I can get it down to something that's a fully-shareable program.

**Comment by sidorares** [comment]
Thanks!

do you have auto increment field on that table? Response to insert query contains that value which might cause problems. If so, can you give just that value ( + associated schema type ) by using some other client ( command line or workbench or anything )

**Comment by sheeley** [comment]
Yeah, the table looks like 
```sql
CREATE TABLE audience_lkp (
  aud_id                INT                NOT NULL PRIMARY KEY AUTO_INCREMENT,
  aud_nm                VARCHAR(50)        NOT NULL,

  ins_ts                TIMESTAMP          DEFAULT CURRENT_TIMESTAMP,
  ins_user              VARCHAR(80)        NOT NULL,
  upd_ts                TIMESTAMP          ON UPDATE CURRENT_TIMESTAMP,
  upd_user              VARCHAR(80)
)
```

Running the query
```sql
INSERT INTO audience_lkp(aud_id, aud_nm, ins_user)
VALUES
(-999, 'Unknown', 'seed-data')

ON DUPLICATE KEY UPDATE
ins_user = values(ins_user);
```

just gives me:
```sql
1 row(s) affected
```

If I `select LAST_INSERT_ID();`, that returns `0`. 

I suspect you're asking for more, but I'm not familiar enough - do you have additional steps I could take to provide more information?

**Comment by sidorares** [comment]
`-999` is this intended ( negative value for auto increment ) ?

**Comment by sheeley** [comment]
Yeah - we use negative values to indicate missing data or other special cases rather than `null`. Thanks for taking a look!

**Comment by sidorares** [comment]
http://dev.mysql.com/doc/refman/5.7/en/innodb-auto-increment-handling.html

> Assigning a negative value to the AUTO_INCREMENT column
In all lock modes (0, 1, and 2), the behavior of the auto-increment mechanism is not defined if you assign a negative value to the AUTO_INCREMENT column.

**Comment by sidorares** [comment]
https://bugs.mysql.com/bug.php?id=35285

**Comment by sidorares** [comment]
might be related: https://github.com/mysqljs/mysql/issues/1371

**Comment by sidorares** [comment]
and this https://github.com/mysqljs/mysql/issues/1205#issuecomment-136912550

**Comment by sheeley** [comment]
That final comment looks spot on - perhaps our big number flag isn't being respected for some reason? I did notice that `mysql2` uses a different bignum lib than `mysql`, but the flags should be identical, correct?

OH! I just saw the code and noticed that `bigNumberStrings` doesn't appear to be toggled when `supportBigNumbers` is; let me flip that and test again.

**Comment by sheeley** [comment]
Nope, still failed. :( 

I think I failed to mention earlier - commenting out this assertion in `bn.js` caused things to work properly: https://github.com/indutny/bn.js/blob/master/lib/bn.js#L2121

But that seemed quite silly. If you think the issue is actually with that assert, happy to continue downstream and check with them; I figured that it might be a `mysql2` issue because `mysql` handles it fine somehow.

**Comment by sidorares** [comment]
No, I think 64 bit ints are handled incorrectly here ( especially 2-complement unsigned ), I'll be able to look in more details later today. I think I'm going to replace bn.js here with https://github.com/dcodeIO/long.js  ( you can try to do that yourself - `new Long(word1, word2, isUnsigned)` - https://github.com/dcodeIO/long.js#new-longlow-high-unsigned

**Comment by sheeley** [comment]
I can give that a shot - if it works, I'll shoot you a pr!

**Comment by sidorares** [comment]
thanks!
insertId-related code is here - https://github.com/sidorares/node-mysql2/blob/7b4f535f5977537e639785f822fd88ab7cb9aaa2/lib/packets/resultset_header.js#L11-L12

readLengthCodedNumber never has more than 64 bit precision so I think long.js should be used there ( and maybe bn.js in DECIMAL type where you can have ay big number. Note that conversion to number is there for performance reason because in node/V8 it's much faster to do code like `(buffer[0]-48)*10 + (buffer[1]-48)*100 ...` compared to `parseInt(buffer.toString(0,1)`. Maybe we should always return potentially big numbers as string. In text protocol ( e.i not using prepared statements ) numbers that are in the result rows come to us as strings over the wire ( but not insertId which is special field in the header packet )
