### ISSUE TITLE
DATE columns return invalid date

### ISSUE THREAD

**Issue by techana** [sidorares/node-mysql2#339]
A column of type DATE with a value of '2016-07-**03**' for example is retrieved by node-mysql2 as '2016-07-**02**T21:00:00.000Z'

I could not find a good reason for this behaviour. I only found this in the change log:
>   - output milliseconds in date type                         #107 

It would be much better to return only the date value as one would expect.

**Comment by sidorares** [comment]
Can you give an example to reproduce? Note that mysql date type does not have any knowledge about timezone, so you have to manually apply timezone offset

**Comment by techana** [comment]
Oops, I think I spoke too soon!

Thank you for the hint. I did something like this and it worked well:

`select DATE_FORMAT(convert_tz(start_day,@@session.time_zone,'+03:00') ,'%Y-%m-%d') as start_day FROM db.tbl_x;`
