### ISSUE TITLE
How to use transaction in connection pool?

### ISSUE THREAD

**Issue by Tagliatti** [sidorares/node-mysql2#345]
Hello, I'm using a connection pool promise and would like to use transactions, but is not working, you could give me an example?
Tks.

```
let mysql = require('mysql2/promise');

global.db = mysql.createPool({
    database: config.database.schema,
    user: config.database.user,
    password: config.database.password
});

// Transaction
db.getConnection(conn => {
    conn.query("insert into tb_test set name = 'test'")
            .then(r => {
                conn.release();
                console.log(r[0]);
            })
            .catch(err => {
                conn.release();
                console.log(err);
            });
});
```

**Comment by sidorares** [comment]
promise version of `pool.getConnection` does not accept callback parameter and returns promise:

```js
db.getConnection().then( conn => {
conn.query("insert into tb_test set name = 'test'")
            .then(r => {
                conn.release();
                console.log(r[0]);
            })
            .catch(err => {
                conn.release();
                console.log(err);
            });
});
```

**Comment by Tagliatti** [comment]
Yes, I was wrong in the example. But I want to know how to use transacton with promise pool. Could you show me an example?
Tks.

**Comment by sidorares** [comment]
@Tagliatti not sure what's the question. If you are talking about https://github.com/mysqljs/mysql#transactions - these helpers are currently not exist for promise version of connection, but you can use sql instead - 'beginTransaction()` only makes a query `begin transaction` - see https://github.com/sidorares/node-mysql2/blob/b534e15faa0dbeefe466ad5a53e4e7fdf378aee8/lib/connection.js#L501-L511

Just do 'start transaction' query, then your sql, then 'commit' query and then release connection.
