### ISSUE TITLE
Properly catching invalid connection init level errors 

### ISSUE THREAD

**Issue by sushantdhiman** [sidorares/node-mysql2#355]
`createConnection` connect with database as soon its called. So you can query directly like

```js
let connection = mysql2.createConnection({});

connection.query('SELECT 1+1');
```

But this pose an issue, say when you pass invalid credentials. It will throw an async error which cannot be caught unless we use `process.uncaughtException` or `domains`.

Is there any way we can handle this error properly without using hacks. This is also a deviation 
from `node-mysql` API, which allow creating connections without actually connecting.

May be we should add a version of `createConnection` which does not connect with server unless we explicitly call `connect`. So if `connect` fails we can handle any errors properly.

**Comment by sidorares** [comment]
right now you need to attach error event handler to connection. In general, it's still unavoidable as there may be underlying network errors before initial handshake, or between commands

```js
let connection = mysql2.createConnection({});
connection.on('error', (err) => { /* handle */ });
connection.query('SELECT 1+1');
```

But I agree that this difference in behaviour can be a problem to some users. My logic in having handshake to be enqueued immediately was "connection = network connection + auth" so it's easier to understand when things happen. If you don't want it to connect immediately, you don't create connection. Also, `connection.connedt(cb)` is trying to mimic node-mysql behaviour: handshake error is routed to `connect()` callback

**Comment by sushantdhiman** [comment]
is there any event indicating successful connection ?

**Comment by sushantdhiman** [comment]
I found `connect` event, Let me try this

**Comment by sushantdhiman** [comment]
Thanks @sidorares. It was so simple, I should have realized it sooner :( . I was using promise wrapper and expecting errors to go in `.catch` :)

One point to note, using `once` will still throw errors at process level, but using `on` will allow me to catch errors properly without throwing uncaught exception. Is there any check in code which check for `on.error` and don't throw in those cases, we should consider adding `once.error` events there too.

**Comment by sidorares** [comment]
I try to re-emit network errors as connection 'error' event. Is that what you asking?

**Comment by sushantdhiman** [comment]
Please check this test case https://github.com/sidorares/node-mysql2/pull/356
