### ISSUE TITLE
Never Ending DB Connection

### ISSUE THREAD

**Issue by techana** [sidorares/node-mysql2#370]
I'm writing a crontab using node-mysql2 and the script does not exit after completing all its tasks. It's the mysql connection that keeps the script running even after completing all callbacks and releasing the connection.

The only way to force releasing the connection is to use connection.destroy(), which is unusable in case there are many async callbacks using the same connection.

Here is a sample script:

```js
 #!/usr/bin/env node
'use strict';
var db = require(__dirname + '/config/db');
// connect to the MySQL pool
db.connect(db.MODE_PRODUCTION, function(err) {
  if (err) {
    console.error('CRON15: Unable to connect to MySQL.');
    process.exit()
  }
  db.get(db.READ, function(err, connection){
  	connection.query('SELECT 1', function (err, rows) {
      connection.release();
      //connection.destroy(); //unsafe!
      console.log(rows)
    })
  })
})
```

**Comment by sidorares** [comment]
when connection released back to pool it is remained open (that's the main purpose of pool - allow to re-use connections later). If you know that you finished using your connections you can call `pool.end()` - see https://github.com/mysqljs/mysql#closing-all-the-connections-in-a-pool
