### ISSUE TITLE
Option connectTimeout not working

### ISSUE THREAD

**Issue by marco-jantke** [sidorares/node-mysql2#376]
When there is no connection possible to the database server, e.g. through a wrong URL configuration, the connectTimeout does not abort the connection after the configured timespan but rather it waits until it gets a TCP connection timeout after approximately 60 seconds. See the following error message:

    Error: connect ETIMEDOUT x.x.x.x:3306
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

Do I understand the connectTimeout parameter wrong or is this a bug?

**Comment by sidorares** [comment]
`connectTimeout` is not supported yet by this client. It's relatively easy to add, l'll keep this as a tracking issue for connectTimeout support.
