### ISSUE TITLE
Connection's query() vs execute()

### ISSUE THREAD

**Issue by hezjing** [sidorares/node-mysql2#382]
Hi

What is the difference between `execute` and `query`? The following statements,

`connection.execute('INSERT INTO documents SET ?', { name: 'john' })`
will throw an error `{"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"#42000"}`

However, `connection.query('INSERT INTO documents SET ?', { name: 'john' })` works fine.

**Comment by sidorares** [comment]
execute prepares statement first and then executes it ( or next time you use same query it's not prepared but reused). Main difference is that with `query` parameters are interpolated on the driver side, while with `execute()` they are interpolated on server. 

Query:

```
   driver -> server: query "INSERT INTO documents SET name='john'" 
   server => driver: ok, insertId, ...
 
   driver -> server: query "INSERT INTO documents SET name='smith'" 
   server => driver: ok, insertId, ...

```

Execute:

```
     driver -> server: prepare "INSERT INTO documents SET name=?"
     server -> driver: statement id = 1

     driver -> server:   execute 1, parameters: 'john'
     server -> driver: ok, insertId, ...

     driver->server: execute 1, parameters: 'smith'
     server -> driver: ok, insertId, ...
```

**Comment by hezjing** [comment]
But from the [documentation](https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md), the `execute()` will prepare the statement internally.

**Comment by sidorares** [comment]
"internally" = transparently to user, you don't need to make two prepare+execute calls. The statement is prepared by mysql server

**Comment by AthithyaIthayan** [comment]
@sidorares I did work over execute and now the MYSQL 8.0 throws `MAX_PREPARED_STMT_COUNT` 
I never closed my connection and every statement is `.execute()` Statement .
can this be resolved by converting everything into `.query()` statements.

**Example**
`
db.execute("select * from ${code}_buses")
.then(res=>{
...
})
.catch(error=>{
...
})
`
to
`
db.query("select * from ${code}_buses")
.then(res=>{
...
})
.catch(error=>{
...
})
`

**Comment by sidorares** [comment]
@AthithyaIthayan `.execute()` meant to be used with parametrised data, not the code ( sql )

**Comment by AthithyaIthayan** [comment]
@sidorares  then should I make my code completely move to `.query()` ?

**Comment by sidorares** [comment]
depends on your db design, how many tables do you have? Are you sure you need that many?

**Comment by AthithyaIthayan** [comment]
@sidorares  tables are less just a 3 tables but its a real time data so is updated every second so I need to `.query()` it rather `.execute()` ?

**Comment by sidorares** [comment]
Are you saying there are just 3 possible values for code?

**Comment by AthithyaIthayan** [comment]
@sidorares No I mean I have data coming from a mobile device to the server the data is sent to every second and is updated there its a fully designed server so the values are updated very regularly but it pops `MAX_PREPARED_STMT_COUNT` reached on `.execute()` so I asked will it be solved on `.query()`

**Comment by sidorares** [comment]
Your tables use code as pard of the name, looks like you have much more than 3 tables

**Comment by AthithyaIthayan** [comment]
@sidorares  3 fr now but tables are created dinamically as it goes (currently just in testing phase)

**Comment by sidorares** [comment]
Yeah either change that part of design ( avoid dynamic tables ) or use query

**Comment by AthithyaIthayan** [comment]
@sidorares  Its better to update docs about the error caused due to prepares statement ... If its ok I will work on docs?

**Comment by sidorares** [comment]
Yes, I'd like to have some explainer docs on how `.execute()` works ( prepare PS if not cached, cache result, call execute using PS id + parameters ), what are the limitations and what are common examples that are possible with `.query()` and not possible with execute ( `IN` expressions, dynamic tables etc )

**Comment by AthithyaIthayan** [comment]
where can i find the docs related folder so that I can work on it ??

**Comment by sidorares** [comment]
Currently this is all we have: https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md
