### ISSUE TITLE
multiple statements in PoolConnection?

### ISSUE THREAD

**Issue by costa974** [sidorares/node-mysql2#386]
I'm trying to insert and select with multiple statements, something like:

'INSERT INTO posts (post_text, user_id, post_type_id, post_status_id, json_data) VALUES (?, ?, ?, ?, ?);' + 
'SELECT * FROM posts WHERE post_id = LAST_INSERT_ID();'

{ [Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT * FROM posts WHERE post_id = LAST_INSERT_ID()' at line 1] code: 'ER_PARSE_ERROR', errno: 1064, sqlState: '#42000' }

the connection pool is defined like:
dbpool = mysql.createPool({
    connectionLimit: 1000,
    host: 'localhost',
    user: 'xxxx',
    password: 'xxxx',
    database: 'xxxx',
    supportBigNumbers: true,
    bigNumberStrings: false,
    multipleStatements: true,
    debug: false
});

and the query is executed with:
dbpool.execute(query, data, function (err, res) { ..... });

Any idea?

**Comment by sidorares** [comment]
PoolConnection has it's own config which might ignore `multipleStatements` flag - if this is the case, it's a bug and needs to be fixed

**Comment by sidorares** [comment]
oh, actually no.

You can't prepare query with multiple statements. Split it in two or use non-prepared statements api ( `dbpool.query(...)` )

**Comment by sidorares** [comment]
http://dev.mysql.com/doc/refman/5.7/en/prepare.html

> Statement names are not case sensitive. preparable_stmt is either a string literal or a user variable that contains the text of the SQL statement. **The text must represent a single statement, not multiple statements**. Within the statement, ? characters can be used as parameter markers to indicate where data values are to be bound to the query later when you execute it. The ? characters should not be enclosed within quotation marks, even if you intend to bind them to string values. Parameter markers can be used only where data values should appear, not for SQL keywords, identifiers, and so forth.

**Comment by costa974** [comment]
ok... with query method dbpool.query(...) it works.
Thanks
