### ISSUE TITLE
custom typeCast handlers in generated parser

### ISSUE THREAD

**Issue by danielsantiago** [sidorares/node-mysql2#39]
The typeCast function in ConnectionConfig is not been called. I need this to automatically cast some VARBINARY and BINARY columns to hexadecimal. Another use case is that I have an application that query more than 2,000 calendar events and converting DATETIME fields to Date objects is too much for me, with typeCast I was omitting this.

PS: Good jobs with the SSL implementation, thanks.

**Comment by sushantdhiman** [comment]
Implemented in https://github.com/sidorares/node-mysql2/pull/351
