### ISSUE TITLE
Reconnecting in pool

### ISSUE THREAD

**Issue by Kamil93** [sidorares/node-mysql2#390]
Mysql2 pool keeps unused connections (they appear in SHOW PROCESSLIST; as in Sleep state)
but what will happen when one of these connection gets broken? mysql2 pool will remove them or reconnect?

**Comment by sidorares** [comment]
yes, the connection is [removed](https://github.com/sidorares/node-mysql2/blob/ac28fb6516c48a060c778759210207c992bbd3cb/lib/pool_connection.js#L17-L22) if it can't be reused ( network error, server forcibly closed, client ended connection etc ). Unused connections are obviously not disconnected (this is the whole point of pool) but we might add an option "disconnect unused connection if idle for more than certain time" - see #321

Currently there is no option to keep pool in "pre-heated" state (minimum number of open connections)  - you have at most `connectionLimit` connections open, zero initially and the number of open connections may grow (if you ask for connection and all currently open connections are in use) or decrease (if connection dies)

**Comment by sytpb** [comment]
if the server forcibly closed, what happen of Mysql2 pool , what should we do in code  to keep the query or insert normal ?
or maybe we shouldn't do anything ,  Mysql2 pool will manage it ?

**Comment by sidorares** [comment]
> if the server forcibly closed, what happen of Mysql2 pool , what should we do in code to keep the query or insert normal ? or maybe we shouldn't do anything , Mysql2 pool will manage it ?

any active connections will be closed in that case ( and unfinished commands with end with error ). Next time you'll try to get connection from the pool it'll try to connect a new one
