### ISSUE TITLE
prepared statements and joins with overlapping column name

### ISSUE THREAD

**Issue by pourquoi42** [sidorares/node-mysql2#399]
I was delighted when I found mysql2. I really don't get why one would want to live without prepared statements. Great job.

My problem: I want to do join query with a prepared statement. Normally, coulmn with the same name are overwritten. In mysqljs/mysql, there is a switch to preserve the information about the tables where column names are originating from:
https://github.com/mysqljs/mysql#joins-with-overlapping-column-names

As far as I can see, this doesn't work on prepared statements. Is there any chance to make that work or to offer a similar mechanism? The workaround to alias each and every columnname in my query is not at all an option.

**Comment by sidorares** [comment]
hi @pourquoi42 

This is the part which does this in non-prepared statements case:

https://github.com/sidorares/node-mysql2/blob/8dad6a7944aec9c4aa0a381dcb966a829f2a537e/lib/compile_text_parser.js#L51-L59

and

https://github.com/sidorares/node-mysql2/blob/8dad6a7944aec9c4aa0a381dcb966a829f2a537e/lib/compile_text_parser.js#L66-L72

I can see similar code in binary parser as well, it might be that option is just not passed, I'll try to check that 

Corresponding code for prepared statements: https://github.com/sidorares/node-mysql2/blob/8dad6a7944aec9c4aa0a381dcb966a829f2a537e/lib/compile_binary_parser.js#L27-L35

**Comment by pourquoi42** [comment]
Hi @sidorares sidorares,

I just experimented and simply set `options["nestTables"]=true` while debugging into the execute call. It works ! You are right, the options simply are not passed. A fix should be super easy :)

**Comment by sidorares** [comment]
looks like it's passed correctly when you use like `conn.execute({ nestTables: true, sql: 'select * from ...'})` but not when used in connection options

**Comment by pourquoi42** [comment]
Yes, works. awesome. For me that fixes it already. However, it would be great to add a note in the docu about prepared statements that the parameter "sql" in fact can be an options object.

**Comment by sidorares** [comment]
turned out that it newer worked as global config parameter even for non-prepared statements. Pushed fix to master
