### ISSUE TITLE
Last inserted ids?

### ISSUE THREAD

**Issue by killmenot** [sidorares/node-mysql2#435]
Hi,

What is the way of getting last inserted ids after bulk insert?

The way I use now is:
```
const start = result[0].insertId
const end = result[0].insertId + result[0].affectedRows

const lastInsertedIds = return _.range(start, end).map(x => x + 1)
```

Do anyone have thoughts / improvements about it?

**Comment by sidorares** [comment]
Hi @killmenot 

I don't think it's possible. You'll have to do extra query to get ids or make a stored procedure that accept bulk list and returns resultset with ids. If you absolutely sure that increments are +1 and exactly _ affectedRows_ number of rows inserted ( not inserted + updated ) than your code is probably correct, but there might be some other edge cases (like other connection inserting data in parallel if table is not locked)

**Comment by killmenot** [comment]
@sidorares All conditions are fine except parallel query. That's the reason why I'm asking. Anyway, thank you for the reply.

**Comment by sidorares** [comment]
no problems @killmenot. At protocol layer inly one insert id is returned for bulk insert so if you really need all Ids returned you need to do something in sql as I mentioned (stored procedure or something)

**Comment by killmenot** [comment]
The way we resolved this issue is the following. We mark inserted bulk data with some group identifier and then use this identifier to select inserted ids. Of course, it adds additional field to the table and a query to retrieve ids but we escape from table locks

**Comment by sidorares** [comment]
@killmenot my main concern was extra query/roundtrip but It's still better than doing lots of individual inserts
