### ISSUE TITLE
Wrapping a Bluebird promise around execute causes a node warning

### ISSUE THREAD

**Issue by ignasbernotas** [sidorares/node-mysql2#441]
I'm using Bluebird (v3.4.6) promise library and I can't figure out why it's throwing me a warning when I'm using a promise with the execute method. The warning (which isn't helpful at all):
```
node:12403) Warning: a promise was created in a handler at internal/process/next_tick.js:103:7 but was not returned from it, see http://goo.gl/rRqMUw
```

The docs state: 
> This usually means that you simply forgot a return statement somewhere which will cause a runaway promise that is not connected to any promise chain.

Which doesn't make sense to me since there's no usage of an underlying promise in mysql2. I've looked through pretty much all posts that referenced this issue on google, but still couldn't figure it out.

I tried the mysql2/promise implementation, but the result is the same since essentially it's what I'm doing. Just to note, it all works, the promise resolves correctly, but I want to understand why this is happening.

Similar issue on [Bluebird repo](https://github.com/petkaantonov/bluebird/issues/508).

Here's my code:

```javascript  
// method definition
query (query, parameters) {
    return new Promise((resolve, reject) => {
      this.connection.execute(query, parameters, function (error, data) {
        if (error) {
          return reject(error)
        }

        resolve(data)
      })
    })
  }
```

```javascript
// calling context
con.query('SHOW DATABASES').then((databases) => {
    console.log('db', databases)
}).catch((error) => {
    console.log(error)
})
```

**Comment by sushantdhiman** [comment]
If you want to use bluebird for promisification you could pass `Promise` prop to do that, like
```js
// get the client
let mysql = require('mysql2/promise');

// get the promise implementation, we will use bluebird
let bluebird = require('bluebird');

// create the connection, specify bluebird as Promise
let connection = await mysql.createConnection({host:'localhost', user: 'root', database: 'test', Promise: bluebird});

// query database
let [rows, fields] = await connection.execute('SELECT * FROM `table` WHERE `name` = ? AND `age` > ?', ['Morty', 14]);
```

May be you are not retuning the new Promise you just created ? Seems like a userland problem to me

**Comment by sidorares** [comment]
As far as I can see bluebird wants `then` handler to return next promise:

```js
con.query('SHOW DATABASES').then((databases) => {
    console.log('db', databases);
    return conn.query('select 1+1');
}).then((res1) => {
    console.log(res1);
    return conn.query('select 2+2');  
}).then((res2) => {
    console.log(res2);
    return conn.end();     
}).catch((error) => {
    console.log(error)
})
```

**Comment by ignasbernotas** [comment]
Yeah.. The problem was that I wasn't returning the query promise to the connection promise. My bad :)

Adding a return statement, fixed it.

```javascript
connection.connect().then((con) => {
  return con.getDatabases().then((databases) => {
    console.log('got databases', databases)
    return con.query('select 2+2')
  }).catch((error) => {
    console.log(error)
  })
}).catch((error) => {
  console.log(error)
})
```
