### ISSUE TITLE
Huge memory use when loading huge data (compared to the old version)

### ISSUE THREAD

**Issue by NijiharaTsubasa** [sidorares/node-mysql2#458]
I'm loading some static text from database into memory in my app booting process:
select * from some_huge_table_with_600_records_with_about_25_MB_of_text;

Sorry I can't provide the table content. It's a table with two columns, one VARCHAR(255) as primary key, and one MEDIUMTEXT.

Using mysql2@0.15.8: about 20MB+ of memory use
After updated to mysql2@^1.0.0: **740MB** of memory use (Out of memory in one of my user's sever)

**Comment by sushantdhiman** [comment]
Try against `master` and report if you see same high memory usage

**Comment by NijiharaTsubasa** [comment]
Tested:
1.1.1
1.0.0
master
All have high memory usage

**Comment by sidorares** [comment]
@NijiharaTsubasa would you be able to use git bisect to find exact commit?

@sushantdhiman iconv maybe?

**Comment by NijiharaTsubasa** [comment]
709719426d74f8da09a553dd3ff47ce9923b1562 is the first bad commit
commit 709719426d74f8da09a553dd3ff47ce9923b1562
Author: Sushant <sushantdhiman@outlook.com>
Date:   Sat Aug 27 16:52:07 2016 +0530

    added Iconv-lite based parser

:040000 040000 d0682134bcd4268fbf57d92a4291a5473d4ebcfd f388d40ccc42f24f2a392448186692277a3dcff7 M  lib

**Comment by dougwilson** [comment]
Does removing the `ParserCache` stuff from that commit make it any better? I'm not sure you're supposed to be reusing the parsers after calling `.end()` like the string decoder is doing, especially because `.end()` does not reset any state in the decoder.

**Comment by sidorares** [comment]
thanks @NijiharaTsubasa !

can you try to put `return new StringParser(encoding, options);` as first line in `prepareParser` so that ParserCache is not used?  https://github.com/sidorares/node-mysql2/commit/709719426d74f8da09a553dd3ff47ce9923b1562#diff-43063f93e383632dfd77260c2666c141R18

**Comment by sushantdhiman** [comment]
@sidorares It seems iconv may be the issue and @dougwilson might be right. @NijiharaTsubasa if you can confirm https://github.com/sidorares/node-mysql2/issues/458#issuecomment-258658276 works then I can quickly throw in a PR with this fix

**Comment by sushantdhiman** [comment]
@sidorares If removing parser cache fix this, Please merge https://github.com/sidorares/node-mysql2/pull/459

**Comment by dougwilson** [comment]
@NijiharaTsubasa have you been able to try out that patch to see if it made a difference?

**Comment by NijiharaTsubasa** [comment]
Thanks for the fix!
Test with fix-458 branch: 70.6MB
Compared with the commit just before 709719426d74f8da09a553dd3ff47ce9923b1562: 55.2MB
Compared with v1.1.1: 751.4MB

**Comment by NijiharaTsubasa** [comment]
Thanks for the fix!
Test with fix-458 branch: 70.6MB
Compared with the commit just before 709719426d74f8da09a553dd3ff47ce9923b1562: 55.2MB
Compared with v1.1.1: 751.4MB

**Comment by sidorares** [comment]
@NijiharaTsubasa published as v1.1.2
