### ISSUE TITLE
The promise version of the API does not support events

### ISSUE THREAD

**Issue by Vinno97** [sidorares/node-mysql2#468]
The promise version of the API does not support events. 

Because of this, the following code throws an error that 'on' is not a function.
```js
pool = mysql.createPoolPromise(config);
pool.on('enqueue', function () {
  console.log('Waiting for available connection slot');
});
```

This is unnecessary because it is an easy fix. You can easily fix it by hooking it to the core pool:
```js
function createPool (opts) {
  var corePool = core.createPool(opts);
  var Promise = opts.Promise || global.Promise || require('es6-promise');

  var promisePool = {
    getConnection: function () {
      ...
    },

    query: function (sql, args) {
      ...
    },

    execute: function (sql, args) {
      ...
    },

    end: function () {
      ...
    },

    // This adds support for events
    on: corePool.on.bind(corePool)
  };

  
  return promisePool;
}
```

Now it works just as normal.

If people disagree with my solution, I think that it might be a good idea to make it possible to use the core pool from the promise version. This does not break anything, but allows developers to use the same pool in places where promises are not preferred.
Something like this:
```js
pool = mysql.createPoolPromise(config);
pool._internalPool.on('enqueue', function () {
  console.log('Waiting for available connection slot');
});
```

**Comment by sidorares** [comment]
I'm +1 on exposing `on` that is wired to core pool on. ( maybe even better to attach all EventEmitter methods )

**Comment by Vinno97** [comment]
Yes, I totally forgot about that. 

Can you think of a nice, clean way to do that than to attach all methods individually?

Best I could think of was
```js
var promisePool = {
  ...
}

for (var method in EventEmitter.prototype) {
  if (typeof EventEmitter.prototype[method] === 'function') {
    promisePool[method] = EventEmitter.prototype[method].bind(corePool);
  }
}

return promisePool;
```
