### ISSUE TITLE
Are there TypeScript definition files (d.ts) available for this project?

### ISSUE THREAD

**Issue by DirkWolthuis** [sidorares/node-mysql2#482]

**Comment by sidorares** [comment]
@DirkWolthuis - I don't know. If you find one I'm happy to link from readme or include in the project. Also would be useful for mysqljs/mysql since api is almost the same

**Comment by nros** [comment]
someone has created some typings with the project [Typings](https://www.npmjs.com/package/typings)

https://github.com/typings/registry/issues/778

**Comment by felixfbecker** [comment]
@sidorares FYI I wrote typings for mysql and mysql2, they are maintained in the types org and reuse interfaces from each other. If you want to add them to the library let me know
