### ISSUE TITLE
Struggling with re-connection logic.

### ISSUE THREAD

**Issue by bweston92** [sidorares/node-mysql2#483]
I am struggling with re-connections after the idle timeout has been reached. I have given my self a few options.

This application has very minimal requirements, consume a AMQP queue, get data from mysql and send an e-mail. How ever because it runs forever I hit this timeout.

- **Option A:** Have a dedicated connection per job.
- **Option B:** Have a set interval which will continuously ping, how ever when connection dies I cannot catch the exception still.
- **Option C:** Let the application die as I cannot catch the exception and re-spawn.

Example (option A):
```
/**
 * @param cb Call back to be called, first arg the connection
 *           second arg will be a callback to clean up.
 */
function withDatabaseConnection(cb) {
  const db = mysql.createConnection(config.mysql);

  cb(db, () => {
    db.end();
  });
}
```

Is there any way I can catch the exception to make option B work? Here is what I have tried:
```
setInterval(() => {
  try {
    db.ping();
  } catch (e) {
    paused = true;
    db.end(() => {
      db.connect(() => paused = false);
    });
  }
}, 5000);
```

But I get "uncaughtException: Connection lost: The server closed the connection."

**Comment by sidorares** [comment]
hi @bweston92 

the easiest option is to use connection pool and it'll handle all errors/dead connection removal.

this won't catch error at all, because it's thrown from another stack - `ping` is an async operation, it only adds command to the queue and immediately exits
 
```js
  try {
    db.ping();
  } catch (e) {
  }
```

If you don't want to use pool you could add `error` handler to connection object itself:

```js
let db = mysql.createConnection(config.mysql);
db.on('error', err => {
  console.log('reconnecting...')
  db = mysql.createConnection(config.mysql);
})
```

**Comment by dougwilson** [comment]
Another reason you may just want to use the pool provided here is that if you want to handle keeping the connections alive, reconnecting lost ones, you're just going to end up re implementing the pool already provided for you :)
