### ISSUE TITLE
Wierd issue when running with jest

### ISSUE THREAD

**Issue by danieljuhl** [sidorares/node-mysql2#489]
I know this is very little information, but I've encountered the following when executing some tests with Jest, which touches code that connects to MySQL using `node-mysql2`, but the code makes no queries.

Any ideas on what causes this issue? The code is fine, when executed directly.

```
PROJECT_FOLDER/node_modules/jest-runtime/build/index.js:439
    const wrapper = this._environment.runScript(script)[
                                                       ^

TypeError: Cannot read property 'Object.<anonymous>' of null
    at Runtime._execModule (PROJECT_FOLDER/node_modules/jest-runtime/build/index.js:439:56)
    at Runtime.requireModule (PROJECT_FOLDER/node_modules/jest-runtime/build/index.js:296:14)
    at Runtime.requireModuleOrMock (PROJECT_FOLDER/node_modules/jest-runtime/build/index.js:365:19)
    at Object.getCodec (PROJECT_FOLDER/node_modules/iconv-lite/lib/index.js:61:27)
    at Object.getDecoder (PROJECT_FOLDER/node_modules/iconv-lite/lib/index.js:118:23)
    at Object.<anonymous>.exports.decode (PROJECT_FOLDER/node_modules/mysql2/lib/parsers/string.js:19:23)
    at Packet.Object.<anonymous>.Packet.readNullTerminatedString (PROJECT_FOLDER/node_modules/mysql2/lib/packets/packet.js:371:23)
    at Function.Object.<anonymous>.Handshake.fromPacket (PROJECT_FOLDER/node_modules/mysql2/lib/packets/handshake.js:19:31)
    at ClientHandshake.Object.<anonymous>.ClientHandshake.handshakeInit (PROJECT_FOLDER/node_modules/mysql2/lib/commands/client_handshake.js:83:38)
    at ClientHandshake.Object.<anonymous>.Command.execute (PROJECT_FOLDER/node_modules/mysql2/lib/commands/command.js:39:20)
```

**Comment by sidorares** [comment]
looks like jest module system does not like for some reason dynamic require there:

```js
if (!iconv.encodings) {
         iconv.encodings = require("../encodings");
}
```

can you try as a work around to monkey patch iconv object? E.i somewhere earlier

```js
var iconv = require('iconv-lite')
iconv.encodings = {}; // probably need to put something here, like simple 1:1 decoder or encoder
```

**Comment by danieljuhl** [comment]
@sidorares I'll try that and get back

**Comment by danieljuhl** [comment]
@sidorares okay, I added the following lines early in my code, and the error went away:
```
import iconv from 'iconv-lite';
import encodings from 'iconv-lite/encodings';
iconv.encodings = encodings;
```

**Comment by sidorares** [comment]
looks like this is something worth reporting to jest, I'm closing for now but feel free to post updates here

**Comment by joelchu** [comment]
Hi the same problem. I am using Jest to test my yeoman generator. All test passed until last week (then I have not got the time to work on it) then start working again, run the test, the new editor files passed the test. But the other start failing randomly. 

`'use strict';
const path = require('path');
const assert = require('yeoman-assert');
const helpers = require('yeoman-test');

const serviceName = 'my-test-srv';

// const fs = require('fs-extra');

describe('generator-rtjs:service', () => {

    it('creates service files', () => {
        helpers.run(
            path.join(__dirname, '../generators/service')
        ).withArguments([
            serviceName
        ]).withOptions({
            'skip-import': 1
        }).then( () =>
        {
            assert.file([
                path.join('app' , 'scripts' , 'services' , serviceName + '.js')
            ]);
        });
    });

});`

The above script passed - then failed 

`
'use strict';
const path = require('path');
const assert = require('yeoman-assert');
const helpers = require('yeoman-test');

const tagName = 'my-new-tag';


describe('generator-rtjs:tag', () => {
    
    it('creates tag files', () => {

        helpers.run(
            path.join(__dirname, '../generators/tag')
        ).withArguments([
            tagName
        ]).then( () =>
        {
            assert.file([
                path.join('app' , 'scripts' , 'components' , tagName , tagName + '.tag')
            ]);
        });

    });
});
`
And this one always passed ... 

My installation 

"jest": "^20.0.4",
"jest-cli": "^20.0.4",

**Comment by sidorares** [comment]
@joelchu I'm afraid it's still too little information to debug. Does the error completely go away if mysql2 is not used?

**Comment by joelchu** [comment]
There is no mysql involved in my  script. They are simply just generate a file based on the answer it got from the prompt. 

At first I thought it might have something to do with the script link to a parent class. But the strange thing is - 3 script all link to different external classes, two passed and one didn't. Then the one that didn't pass - passed, and the other one start failing. There is no logic at all. 

I just want to know what is that error message means, and what is it doing. Thanks

**Comment by danieljuhl** [comment]
@joelchu then, why do you comment on an issue related to `mysql2` for `node`? 😄

**Comment by joelchu** [comment]
Hi , there was no mysql involved in my script at all. I just want to know what that piece of code is doing at the point in time. If you look at my script. That's using the yeoman-test and it might have something to do with it. 

The other thing is during the last few weeks, jest been updated (it was x19 now its x20) and broken the original test script. This is why I ask here first. Thanks

**Comment by danieljuhl** [comment]
@joelchu my this repo has nothing to do with `jest`. This is `node-mysql2` and this issue is about a combination of `jest` and `node-mysql2`. You should probably create an issue in the `jest` repo.

**Comment by opatut** [comment]
I found a **temporary workaround** for now, add this to your `setupTestFrameworkScriptFile`:

```
// Hack to make iconv load the encodings module, otherwise jest crashes. Compare
// https://github.com/sidorares/node-mysql2/issues/489
require('mysql2/node_modules/iconv-lite').encodingExists('foo');
```

Might look a bit different depending on your setup ;)

**Comment by tobiaslins** [comment]
@opatut s/o, is working for me :)

**Comment by rimiti** [comment]
Thanks @opatut

**Comment by victorschinaider** [comment]
> I found a **temporary workaround** for now, add this to your `setupTestFrameworkScriptFile`:
> 
> ```
> // Hack to make iconv load the encodings module, otherwise jest crashes. Compare
> // https://github.com/sidorares/node-mysql2/issues/489
> require('mysql2/node_modules/iconv-lite').encodingExists('foo');
> ```
> Might look a bit different depending on your setup ;)

In **typescript**, just do:

```typescript
// Hack to make iconv load the encodings module, otherwise jest crashes. Compare
// https://github.com/sidorares/node-mysql2/issues/489
import * as iconv from 'iconv-lite';
iconv.encodingExists('foo');
```
In my case, *foo* was **cp1252**

**Comment by JeganMurugan01** [comment]
i am facing same issue 
![image](https://github.com/sidorares/node-mysql2/assets/97842714/89a052cd-b1b4-4528-88a4-6a85539eb3d7)

**Comment by cvanputt** [comment]
As of version 2.x and later for mysql2:
`require('iconv-lite').encodingExists('foo');`
