### ISSUE TITLE
Unknown charset 'utf8mb4…'

### ISSUE THREAD

**Issue by denji** [sidorares/node-mysql2#492]
We used `mysqljs/mysql@stable` before, this is normal behavior when setting the encoding based utf8mb4 `mysql2` (sidorares/node-mysql2#374)?

createConnection({… charset: 'utf8mb4_unicode_520_ci' …})
---
- Unknown charset 'utf8mb4_unicode_520_ci'

createConnection({… charset: 'utf8mb4' …})
---
- Unknown charset 'utf8mb4'

Version `sidorares/node-mysql2@1.1.2`
---
```
at Function.getCharsetNumber (…/node_modules/mysql2/lib/connection_config.js:132:11)
at new ConnectionConfig (…/node_modules/mysql2/lib/connection_config.js:62:24)
at Object.module.exports.createConnection (…/node_modules/mysql2/index.js:7:34)
…
```

https://github.com/mysqljs/mysql/blob/v2.12.0/lib/protocol/constants/charsets.js
https://github.com/sidorares/node-mysql2/blob/v1.1.2/lib/constants/charsets.js

> [MySQL 8.0 will have much more complete unicode support based on Unicode 9.0](http://mysqlserverteam.com/the-mysql-8-0-0-milestone-release-is-available/)
> - xxx_unicode_520_ci collations are based on [UCA 5.2.0](http://www.unicode.org/Public/UCA/5.2.0/allkeys.txt) weight keys. Collations without the "520", are based on the older UCA 4.0.0. 
> - MySQL 5.7 already provide a much newer utf8mb4_unicode520_ci collation that handles characters. But in MySQL 8.0 we decided to take this a step further by introducing utf8mb4_0900_ai_ci, which is based on the latest Unicode standard, and we intend to set this collation as the default collation for utf8mb4.
> - This is part of a bigger effort to improve our UTF8 support MySQL 8.0. The overall goal is to change the default character set from latin1 to utf8mb4, and the default collation from latin1_swedish_ci to utf8mb4_0900_ai_ci.

* __utf8_unicode_ci__ & __utf8mb4_unicode_ci__ (_2003-11_) is based on [UCA 4.0.0](http://www.unicode.org/Public/UCA/4.0.0/allkeys-4.0.0.txt) weight keys.
* __utf8mb4_unicode_520_ci__ (_2009-09_) is based on [UCA 5.2.0](http://www.unicode.org/Public/UCA/5.2.0/allkeys.txt) weight keys.
* __utf8mb4_unicode_800_ci__ (_2015-02_)  is based on [UCA 8.0.0](http://www.unicode.org/Public/UCA/8.0.0/allkeys.txt) weight keys.
* __utf8mb4_unicode_0900_ci__ (_2016-05_) is based on [UCA 9.0.0](http://www.unicode.org/Public/UCA/9.0.0/allkeys.txt) weight keys.
```
├─ mysql2@1.1.2
│  ├─ cardinal@1.0.0
│  ├─ denque@^1.1.0
│  ├─ generate-function@^2.0.0
│  ├─ iconv-lite@^0.4.13
│  ├─ long@^3.2.0
│  ├─ lru-cache@^4.0.1
│  ├─ named-placeholders@1.1.1
│  ├─ object-assign@^4.1.0
│  ├─ readable-stream@2.2.2
│  ├─ safe-buffer@^5.0.1
│  ├─ seq-queue@0.0.5
│  └─ sqlstring@^2.2.0
```

**Comment by sidorares** [comment]
Hi @denji 
Yes, mysqljs list of constants is bigger and more relevant. Do you want to create pr and add them?

Note that there is also a mapping from mysql encoding to charset table ( iconv name ) - https://github.com/sidorares/node-mysql2/blob/master/lib/constants/encoding_charset.js and it might need to be updated as well

**Comment by dougwilson** [comment]
Yea, the `utf8mb4` is really just a short name compared to what the underlying protocol wants. Probably just cherry pick https://github.com/mysqljs/mysql/commit/fd28786cfa3bbdf44d603e7e2d07635508c12c7c into this module for those short cuts.

**Comment by sidorares** [comment]
#494 should fix this
