### ISSUE TITLE
promise wrapper `PromiseConnection` is missing `escape`

### ISSUE THREAD

**Issue by nros** [sidorares/node-mysql2#495]
The `Promise` based wrapper on `Connection` does not fully implement the interface of `Connection`. eg: it lacks `escape` and `escapeId`.

So the provided connection object can not be a drop-in replacement.
I would expect the following to print the same for normal and for `Promise` based `Connection`:

```

const mysql = require("mysql2");
const mysqlPromise = require("mysql2/promise");

var connection1 = mysql.createConnection({ host: "localhost", user: 'root'});
console.log("1: " + connection1.escape("encoded 'test' data"));

mysqlPromise.createConnection({host: "localhost", user: 'root'})
    .then(function (connection2) {
        console.log("2: " + connection2.escape("encoded 'test' data"));
    })
    .catch(function (err) {
        console.log("FAILED 2: " + err.message);
    })
;

```
Unfortunately the output is:
```
1: 'encoded \'test\' data'
FAILED 2: connection2.escape is not a function
```

**Comment by gajus** [comment]
`connection1.connection.escape` should work.

**Comment by sidorares** [comment]
It probably won't hurt to add all helper methods into wrapped promise connection

**Comment by nros** [comment]
I added the asynchronous functions manually and used a whitelist for the synchronous ones.

However, since I am convinced, that the Promise based version should be a drop-in replacement for the callback-based version - regarding the synchronous functions - I did not add a suffix of "Sync". I think it would impose too much code changes in case you switch to the Promise based version. It would be more helpful to add "Async" or something to the asynchronous functions. The code using these need to be changed anyway when switching to the Promise based library. 

What do you think?
