### ISSUE TITLE
Connection.beginTransaction Not Working

### ISSUE THREAD

**Issue by mhawila** [sidorares/node-mysql2#497]
As the ReadMe claims that this library is compatible to mysqljs I expected this function to available. Unfortunately trying to use it throws an error that the function does not exist.
My code is as simple as below.
```js 
 const mysql = require('mysql2/promise');
 mysql.createConnection(config).beginTransaction(err => {
   if(err) throw err;
   // Do what you have to do.
 });
```

**Comment by sidorares** [comment]
> As the ReadMe claims that this library is compatible to mysqljs I expected this function to available. 

Hi @mhawila , promise wrapper is extension of mysqljs api, mysqljs does not have it. It might have some bits missing or named completely different

Feel free to add pr with implementation though - `beginTransaction` i[nternally just does ](https://github.com/sidorares/node-mysql2/blob/ddb753bef7054ab65eff64c7d8a394d321402273/lib/connection.js#L647-L657)`query("start transaction")`. So where you use promise connection you could just do something like

```js
  await conn.query('START TRANSACTION')
  // Do what you have to do.
  // ... 
  await conn.query('COMMIT')
```

**Comment by mhawila** [comment]
Thanks @sidorares , I will just go with the approach you suggested. I don't see the advantage of wrapping that in another function since I am going to use it in async/await fashion anyway.

**Comment by divyenduz** [comment]
@sidorares : Can I wrap `await conn.query('COMMIT')` in try/catch ? Or Do I need to write a wrapper like this for it 

```
executeQuery: (connection, query, params) => {
        return new Promise((resolve, reject) => {
            connection.query(query, params, (error, results, fields) => {
                if (error) {
                    reject(error);
                }
                resolve(results);
            });
        });
    }
```

**Comment by sidorares** [comment]
yes, with async functions try/catch will capture normal runtime exceptions as well as rejected promises. async wrapper does basically the same as your example

**Comment by divyenduz** [comment]
But conn.query is not async right? Unless that is done via promise-ification or async-ification?

**Comment by sidorares** [comment]
@divyenduz  mysql2 has built in promisified client - https://github.com/sidorares/node-mysql2/blob/master/promise.js https://github.com/sidorares/node-mysql2/blob/master/documentation/Promise-Wrapper.md

**Comment by sidorares** [comment]
> Just to clarify, I am talking about node-mysql and not node-mysql2.

oh, in that case you need to wrap with promise manually or use existing promise wrapper

**Comment by divyenduz** [comment]
Thanks for the clarification.
