### ISSUE TITLE
Prepared statement

### ISSUE THREAD

**Issue by xcoder94** [sidorares/node-mysql2#519]
Hi, please help me!
I want to use prepared statements with custom format.

I'm used the next code:

```js

const mysql = require('mysql2'); 
const CNF = require('./Config');

connection = mysql.createConnection(CNF.DB);
connection .config.queryFormat = function (query, values) {
	if (!values) return query;
		return query.replace(/\:(\w+)/g, function (txt, key) {
	if (values.hasOwnProperty(key))
		return this.escape(values[key]);
		return txt;
	}.bind(this));
};
connection .connect();

connection.prepare('select :a + :b as tests', function (err, statement) {
	console.log(err);
  statement.execute({a: 1, b:2}, function (err, rows, columns) {
	console.log(rows[0]);
  });

  statement.close();
});
```

**Comment by sidorares** [comment]
`queryFormat` is only used with `query()` at the moment

for prepared statements we would need more sophisticated api: 1) function to convert query to '?'-based placeholders 2) turn parameters into array

**Comment by sidorares** [comment]
Also note - https://github.com/sidorares/node-mysql2/blob/63ff16b79ac776f0a369433021af7cfe544960bd/documentation/Extras.md#named-placeholders

**Comment by xcoder94** [comment]
Thanks!

**Comment by xcoder94** [comment]
Andrey, performance will differ much while inserting 100K via current driver statement prepared and compared to https://github.com/mysqljs/mysql ?

**Comment by sidorares** [comment]
I would expect mysql2 to be a bit faster, but for _inserting_ 100k rows of data there is very little work for driver. Selecting 100k rows is usually much faster with mysql2 compared to mysqljs/mysql. I suggest to try and benchmark ( post your numbers if you decide to do so! )
