### ISSUE TITLE
¿Should I use mysql or mysql2 module?

### ISSUE THREAD

**Issue by sant123** [sidorares/node-mysql2#535]
Hi, I want to use MySQL but I'm not sure which module use. Also I ask it for this in the README:

> MySQL2 team is working together with mysqljs/mysql team to factor out shared code and move it under mysqljs organisation.

Thank you!

**Comment by sidorares** [comment]
Hi @sant123 , have a look at https://github.com/sidorares/node-mysql2/pull/406#issuecomment-247912955

**Comment by sidorares** [comment]
actually not that one, wait a minute, I'll try to find discussion

**Comment by sidorares** [comment]
I'll find it later, in short: if you not sure probably better to pick up mysqljs/mysql, maybe later switch to mysql2 and you you have noticeable performance gain and no issues continue with mysql2

**Comment by sidorares** [comment]
https://github.com/sidorares/node-mysql2/issues/86

**Comment by sant123** [comment]
Thank you @sidorares! I really appreciate it. :smiley:
