### ISSUE TITLE
 The execute method is not working correctly

### ISSUE THREAD

**Issue by guigaoliveira** [sidorares/node-mysql2#538]
When I use the execute method to select something in my database (inside the table) and use a parameter (example: home =?) Later function is not "enabled", it only works if I take the parameter and leave only the function to execute.

**Comment by guigaoliveira** [comment]
Ps: I'm using a pool connection.

**Comment by sidorares** [comment]
sorry, not very clear. Can you give some code example? What are you doing, what you see and what you expect to see

**Comment by guigaoliveira** [comment]
Example: 

pool_connection.execute("SELECT * FROM table WHERE status = ?", [status], () => console.log("Executed")) 

So, nothing is appearing on the console, it was to appear even in case of error and would have to select "all values"

**Comment by sidorares** [comment]
is there any way you can post full code?

**Comment by guigaoliveira** [comment]
Something like this: 

const pool = require('mysql2/promise').createPool(MYSQL);
pool.getConnection()
  .then((conn) => console.log('Banco do MYSQL conectado!'))
  .catch((err) => {
    console.log(`Não foi possível conectado ao MYSQL, erro: ${err.code}`)
  })
  pool2.execute('SELECT * FROM `usuarios` WHERE `nome` = ? AND `senha` = ?', 
  ['teste','teste2'], 
  function (err, results, fields) {
  console.log(err);
  console.log(results); 
  console.log(fields); 
}); // not working 
// let [rows, fields] = await connection.execute('SELECT * FROM `usuarios` WHERE `nome` = ? AND `senha` = ?', ['teste','teste2']); this works

PS1: MYSQL is a object with Mysql configuration (I check this and it's correct) 
PS2: I'm brazilian, to ignore portuguese text haha.

**Comment by sidorares** [comment]
you are using 'promise wrapper', and the way it works by _returning_ Promise object, in comparison to CPS-style where you pass a callback as last parameter. Try one of these:

```js
const pool = require('mysql2/promise').createPool(MYSQL);
pool.getConnection()
  .then((conn) => {
     console.log('Banco do MYSQL conectado!')
  conn.execute('SELECT * FROM `usuarios` WHERE `nome` = ? AND `senha` = ?'
  ['teste','teste2']).then(
  function (err, results, fields) {
  console.log(err);
  console.log(results); 
  console.log(fields); 
}); 
   })
  .catch((err) => {
    console.log(`Não foi possível conectado ao MYSQL, erro: ${err.code}`)
  })

```

or 

```js
const pool = require('mysql2').createPool(MYSQL);
pool.execute('SELECT * FROM `usuarios` WHERE `nome` = ? AND `senha` = ?', 
  ['teste','teste2'], 
  function (err, results, fields) {
  console.log(err);
  console.log(results); 
  console.log(fields); 
}); 
```

**Comment by guigaoliveira** [comment]
Thanks, but...If I use the second option, how can I do error handling? Using try / catch  or what? Because the execute command comes after checking the connection and if it has no error (no need is in the ".then(conn) => {...}")

**Comment by lagden** [comment]
@sidorares 
I was testing your solution above (with some modifications) and I got it:

```js
const mysql = require('mysql2/promise')
const pool = mysql.createPool({
	connectionLimit : 3,
	host:'127.0.0.1',
	user: 'root',
	password: '',
	rowsAsArray: false,
	database: 'xxx'
})

pool
	.execute('SELECT id, name FROM test WHERE name = ? LIMIT 1', ['B'])
	.then((...args) => {
		console.log(args) // [ [ [], [ [Object], [Object] ] ] ]
		const [a, b] = args[0]
		console.log(a) // []
		console.log(b) // [ [{...schema: 'xxx', name: 'id'..}], [{...schema: 'xxx', name: 'name'..}] ]
	})
	.catch(err => {
		console.log(err.message);
	})
```

Where is the rows (`results`) values?

**Comment by sidorares** [comment]
result is [rows, fields], "a" in your case (that is, you have empty result from your select)

**Comment by lagden** [comment]
@sidorares you are right!!!
My table was empty... my falt! :sweat_smile:
