### ISSUE TITLE
how to start a transaction using promise version?

### ISSUE THREAD

**Issue by hiawui** [sidorares/node-mysql2#539]
Hope can support such function like below

    var conn = yield mysql.createConnection(cfg);
    yield conn.execute('begin');  // or yield conn.startTransaction();

but when I tried these code. I got error 'This command is not supported in the prepared statement protocol yet'.

**Comment by sidorares** [comment]
yes, you can't use transactions with prepared statements.

you should be able to use `yield conn.startTransaction();` with code from master ( landed in #531, not in npm yet ) or just `yeld conn.query('start transaction')` - beginTransaction() [does exactly the same](https://github.com/sidorares/node-mysql2/blob/29c105418f053fbae98f5ec1a6884369847c47e8/lib/connection.js#L647-L649) under the hood

**Comment by hiawui** [comment]
Thanks @sidorares , yield conn.query('start transaction') works for me.
