### ISSUE TITLE
doubt about end connection

### ISSUE THREAD

**Issue by lagden** [sidorares/node-mysql2#540]
I have this system...

**connection.js**
```js
const mysql = require('mysql2/promise')
async function connection(database) {
    return mysql.createConnection({
        host:'127.0.0.1',
        user: 'root',
        password: '',
        database,
        rowsAsArray: false
    })
}

module.exports = connection
```

**create.js**
```js
const connection = require('./connection')
async function create(data) {
	const q = `INSERT INTO example SET ?`
	const conn = await connection('mydb')
	const results = await conn.query(q, data)
	conn.end()
	return results
}

module.exports = create
```

**app.js**
```js
const create = require('./create')
async function crash() {
    try {
        // Force MySQL error
        const users = await Promise.all[create({id: 1, name: 'Lagden'}), create({id: 1, name: 'Lagden'})]
    } catch (err) {
        console.log(err.message) // Error: Duplicate entry '1' for key 'PRIMARY'
    }
}

crash()
```

In the system above, we will have a MySQL error...

My doubt are:
- Will my connection remain open?
- Do I have to handle it on `create` to avoid leaving opened connections?

**Comment by sidorares** [comment]
it'll remain open, you need to wrap the code in create with try/catch:

```js
async function create(data) {
  try {
	const q = `INSERT INTO example SET ?`
	const conn = await connection('mydb')
	const results = await conn.query(q, data)
   } finally {
	conn.end()
	return results
   }
}
```
or just use connection pool (this is always better default option, you should have a good reason not to use it)

**Comment by lagden** [comment]
@sidorares good point!!

Let me understand better the `connection pool`

if I do something like that:

**pool.js**
```js
const mysql = require('mysql2/promise')
const pool = mysql.createPool({
	connectionLimit : 3,
	host:'127.0.0.1',
	user: 'root',
	password: '',
	rowsAsArray: false,
	multipleStatements: true
})

module.exports = pool
```

**create.js**
```js
const pool = require('./pool')
async function create(data) {
	let r
	try {
		const [results] = await pool.query(`USE mydb; INSERT INTO example SET ?`, data)
		const [rUse, rIns] = results
		r = rIns
	} catch (err) {
		console.log(err.message)
	} finally {
		const {connection} = await pool.getConnection()
		connection.release()
	}
	return r || false
}

module.exports = create
```

**app.js**
```js
const create = require('./create')
async function multiple() {
	try {
		const users = await Promise.all([
			create({id: 1, name: 'A'}),
			create({id: 2, name: 'B'}),
			create({id: 3, name: 'C'}),
			create({id: 4, name: 'D'}),
			create({id: 5, name: 'F'}),
			create({id: 6, name: 'G'}),
			create({id: 7, name: 'H'}),
			create({id: 8, name: 'I'}),
			create({id: 9, name: 'J'}),
			create({id: 10, name: 'K'})
		])
		console.log(users)
	} catch (err) {
		console.log(err.message)
	}
}

multiple()

```

In **create.js**:
Is correct use the `connection.release` this way?

---

And the last one...

Using connection pool, will we always have 3 (`connectionLimit: 3`) connections?

---

Thanks for your attention!

**Comment by sidorares** [comment]
`pool.query()` is a helper that does getConnection + query + release internally, by the time you get data ( or error ) connections is back in the pool (or disposed if error like 'server closed connection' or 'network down') 

```js
const pool = require('./pool')
async function create(data) {
	let r
	try {
		const [results] = await pool.query(`USE mydb; INSERT INTO example SET ?`, data)
		const [rUse, rIns] = results
		r = rIns
	} catch (err) {
		console.log(err.message)
	}
}

module.exports = create
```

> Using connection pool, will we always have 3 (connectionLimit: 3) connections?

yes, at most 3 ( initially 0). with  `connectionLimit: 3` following will example probably take 2 seconds to finish:

```js
   await Promise.all([pool.query('sleep 1'),pool.query('sleep 1'), pool.query('sleep 1'), pool.query('sleep 1')]); 
```
- initially first 3 will go in parallel in it's own connection and one would be queued and start after one of first 3 finish

**Comment by lagden** [comment]
Awesome...

I fix the **create.js**
```js
const pool = require('./pool')
async function create(data) {
	try {
		const [results] = await pool.query(`USE mydb; INSERT INTO example SET ?`, data)
		const [rUse, rIns] = results
		return rIns
	} catch (err) {
		console.log('create error --->', err.message)
	}
	return false
}

module.exports = create
```

But I found a **possible bug***!! (Remember, we have 3 connections)

When we call `node app.js` in the first time, we trigger:

```js
const users = await Promise.all([create({id: 1, name: 'A'}), ..., create({id: 10, name: 'K'})
console.log(users) // [{...}, {...}] - Inserted 10 rows
process.exit() 
```

And the second time, the application is blocked...

**console**
```shell
create error ---> Duplicate entry '1' for key 'PRIMARY'
create error ---> Duplicate entry '2' for key 'PRIMARY'
create error ---> Duplicate entry '3' for key 'PRIMARY'
```

The `Promise.all` never ends!!

How can I continue?

**Comment by lagden** [comment]
I was looking in the source (https://github.com/sidorares/node-mysql2/blob/master/lib/pool.js#L143-L145), and realised that `conn.release` is never triggered in [case above](https://github.com/sidorares/node-mysql2/issues/540#issuecomment-292110753)...

So, I added in `lib/pool.js#L143-L145`:
```js
conn
  .query(cmdQuery)
  .on('result', function () {
    conn.release();
  })
  .on('end', function () {
    conn.release();
  });
```

And success!!!

**console output**
```
create error ---> Duplicate entry '4' for key 'PRIMARY'
create error ---> Duplicate entry '2' for key 'PRIMARY'
create error ---> Duplicate entry '5' for key 'PRIMARY'
create error ---> Duplicate entry '3' for key 'PRIMARY'
create error ---> Duplicate entry '7' for key 'PRIMARY'
create error ---> Duplicate entry '6' for key 'PRIMARY'
create error ---> Duplicate entry '9' for key 'PRIMARY'
create error ---> Duplicate entry '8' for key 'PRIMARY'
create error ---> Duplicate entry '10' for key 'PRIMARY'
results [ false, false, false, false, false, false, false, false, false, false ]
```

Anyway, I did not send the PR because I'm not sure about the workaround!!
I hope you know how to solve much better than me...

**Comment by tangxinfa** [comment]
The same problem to me: Duplicate entry error will cause connection leak, finally our server is no response, i doubt Command will not emit 'end' event if error occured, and the "conn" is leak.

pool.js

    Pool.prototype.query = function (sql, values, cb) {
      var cmdQuery = Connection.createQuery(sql, values, cb, this.config.connectionConfig);
      cmdQuery.namedPlaceholders = this.config.connectionConfig.namedPlaceholders;
    
      this.getConnection(function (err, conn) {
        if (err) {
          if (typeof cmdQuery.onResult === 'function') {
            cmdQuery.onResult(err);
          } else {
            cmdQuery.emit('error', err);
          }
          return;
        }
    
        conn.query(cmdQuery).once('end', function () {
          conn.release();
        });
      });
      return cmdQuery;
    };

**Comment by tangxinfa** [comment]
@lagden "result" event also fire when a row is comming, i don't think it's a good time to release connection.

**Comment by lagden** [comment]
@tangxinfa 

I'm using the [original](https://github.com/mysqljs/mysql) and created two scripts that solved the problems...

**pool.js**
```js
'use strict'

const mysql = require('mysql')
const config = require('./config/db.json')

const env = process.env.NODE_ENV || 'dev'

const pool = mysql.createPool(
	Object.assign(config.sql[env], {
		connectionLimit: 10,
		multipleStatements: true
	})
)

module.exports = pool
```

and **query.js**

```js
const pool = require('./pool')

function conn() {
	return new Promise((resolve, reject) => {
		pool.getConnection((err, connection) => {
			if (err) {
				reject(err)
			} else {
				resolve(connection)
			}
		})
	})
}

function query(q, data = []) {
	return conn()
		.then(connection => {
			return new Promise((resolve, reject) => {
				const query = connection.query(q, data, (err, results, fields) => {
					connection.release()
					if (err) {
						reject(err)
					} else {
						resolve({results, fields})
					}
				})
			})
		})
}

exports.conn = conn
exports.query = query
```

now, just use **query.js** in your app, like example below:

```js
'use strict'

const query = require('./query')

async function example() {
	const {results: [r]} = await query('SELECT 1 + ? as plus', [1])
	return r
}

example()
	.then(r => {
		console.log(r) // {plus: 2}
	})
	.catch(err => {
		console.log(err.code)
	})
```

I would like to thank you for your attention (@sidorares and @tangxinfa)

**Comment by tangxinfa** [comment]
There is two solutions:
1, Use "pool.execute" for update/delete/insert.
2, Still use "pool.query" but fix by emit "end" event if error occured and release connection on "error" event:
pool.js

    Pool.prototype.query = function (sql, values, cb) {
      var cmdQuery = Connection.createQuery(sql, values, cb, this.config.connectionConfig);
      cmdQuery.namedPlaceholders = this.config.connectionConfig.namedPlaceholders;
    
      this.getConnection(function (err, conn) {
        if (err) {
          if (typeof cmdQuery.onResult === 'function') {
            cmdQuery.onResult(err);
          } else {
            cmdQuery.emit('error', err);
          }
          return;
        }
    
        conn.query(cmdQuery).once('end', function () {
          conn.release();
        }).once('error', function () {
          conn.release();
        });
      });
      return cmdQuery;
    };

command.js

    Command.prototype.execute = function (packet, connection) {
      // TODO: hack
      if (!this.next) {
        this.next = this.start;
      }
    
      if (packet && packet.isError()) {
        var err = packet.asError();
        if (this.onResult) {
          this.onResult(err);
          this.emit('end');
        } else {
          this.emit('error', err);
        }
        return true;
      }
    
      // TODO: don't return anything from execute, it's ugly and error-prone. Listen for 'end' event in connection
      this.next = this.next(packet, connection);
      if (this.next) {
        return false;
      } else {
        this.emit('end');
        return true;
      }
    };

**Comment by tangxinfa** [comment]
This problem already have fix:  https://github.com/sidorares/node-mysql2/pull/508

**Comment by lagden** [comment]
Good!!
@sidorares it's the moment for new release!!
