### ISSUE TITLE
More examples using standard ES6 promises

### ISSUE THREAD

**Issue by rmullenix** [sidorares/node-mysql2#543]
I'm trying to figure out ways to use the ES6 promise API to chain together things like prepared statements and transactions.  The basic example is fine as a "Hello, World" placeholder, but it's not very instructive on how the API connects together.

For reasons beyond my control, I cannot use yield or async/await.

For instance, only the createConnection function seems to pass along the connection object.  How am I supposed to close it after performing a query?

**Comment by sidorares** [comment]
`connection.end()` ?

**Comment by rmullenix** [comment]
I dug around a little further into the promise test code to find some more examples.  This seems to be what I was looking for:
https://github.com/sidorares/node-mysql2/blob/master/test/integration/test-promise-wrappers.js#L35

Looks like the idea is to create an object outside the promise chain that can hold the object returned via the createConnection() call.  This can then be used throughout the promise chain if needed, and then after getting the results to end the connection.
