### ISSUE TITLE
Using prepared statements with bulk query() operations.

### ISSUE THREAD

**Issue by joejean** [sidorares/node-mysql2#549]
Hi There, 

From my understanding the following bulk insert does not use prepared statements:
```js
var mysql = require('mysq2');
var conn = mysql.createConnection({
    ...
});

var sql = "INSERT INTO Test (name, email, n) VALUES ?";
var values = [
    ['demian', 'demian@gmail.com', 1],
    ['john', 'john@gmail.com', 2],
    ['mark', 'mark@gmail.com', 3],
    ['pete', 'pete@gmail.com', 4]
];
conn.query(sql, [values], function(err) {
    if (err) throw err;
    conn.end();
});

```

I have two questions:
1- How safe are bulk operations with `query()`? Is there still room for sql injection attacks?
2- Would it be possible to make `execute()` support bulk operations just like `query()` while still using prepared statements?

**Comment by sidorares** [comment]
it's possible, but I guess not very efficient.
Have you tried `load data local infile`? Have a look at example at https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#sending-tabular-data-with-load-infile-and-local-stream
I suspect it's more efficient and less prone to sql injection compared to large string constructed from `INSERT INTO Test (name, email, n) VALUES` + data.
