### ISSUE TITLE
mysql_clear_password support.

### ISSUE THREAD

**Issue by shashi07** [sidorares/node-mysql2#550]
Hi , 
I am trying to connect to a Mariadb instance over SSL . And I get the error , client doesn't support the authentication protocol requested by server.

http://stackoverflow.com/questions/43448563/connecting-to-mariadb-with-nodejs-over-ssl-with-clear-text-password?noredirect=1#comment73953890_43448563

**Comment by sidorares** [comment]
related - #438 #332 

I think mysqljs/mysql does support old 323 auth but not mysql_clear_password. If the server supports plugin auth it's very easy to write your own mysql_clear_password plugin ( basically one liner ). Can you check if plugin based auth is an option? If so, try code from https://github.com/sidorares/node-mysql2/issues/438#issuecomment-255343793

**Comment by shashi07** [comment]
Thanks man, I was able to connect successfully.
