### ISSUE TITLE
BIGINT(20) Data Being Rounded

### ISSUE THREAD

**Issue by nathanewakefield** [sidorares/node-mysql2#564]
When I retrieve data from a column with format BIGINT(20), the value that the mysql2 library gives me is rounded to a nearby hundreds place. 

The reason I say nearby rather than nearest is because it seems to be **rounding at random**. Consider the following values:
636009965114711**235** is rounded to 636009965114711**300** (as if it goes through a ceiling function).
636009956139287**188** is rounded to 636009956139287**200** (as if either ceiling or just rounded to nearest).
636009964495742**861** is rounded to 636009964495742**800** (as if it goes through a floor function).

If more information is needed, I will do my best to provide it.

**Comment by sidorares** [comment]
have a look at `supportBigNumbers` and `bigNumberStrings`:

https://github.com/mysqljs/mysql#connection-options

basically it's a Javascript problem and you need to explicitly enable ways to work around ( try to do `console.log(636009965114711235)` in browser and you'll see same rounding )

**Comment by nathanewakefield** [comment]
Wow... Shows how thoroughly I checked the docs for a solution to this issue. Thanks
