### ISSUE TITLE
sql_mode/init commands

### ISSUE THREAD

**Issue by mnpenner** [sidorares/node-mysql2#565]
(Following from [here](https://github.com/mysqljs/mysql/issues/1401#issuecomment-301632929))

We need a way to set the [`sql_mode`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-setting) and/or init command(s) immediately upon connection. This is particularly useful for pools, where you don't know what connection you will get so you can't just run it at the start of your script.

**Comment by sidorares** [comment]
currently not possible with Promise version of pool. With non-promise:

```js
pool.on('connection', function(conn) {
  conn.query(`SET SESSION sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"`);
});
```

**Comment by mbaumgartl** [comment]
I have a similar problem: I want/need to run a couple of queries (e.g. set sql mode, set maximum execution time, etc.) before the connection is added to the pool. The queries are configurable and not hard coded. Therefore the connection should only be added to the pool if all init queries are executed successfully.

Do you see a possibility?

**Comment by sidorares** [comment]
@mbaumgartl would code from my previous comment work for you? Until `on('connection')` handler is finished no one else is able to use this connection, and queries in a single connection are queued and executed sequentially:

```js
   pool.on('connection', function(conn) {
      const cmd1 = conn.query(`[set sql mode command here]`);
      const cmd2 = conn.query(`[set execution time]`);
      // probably worth checking errors - via callbacks to query()
      // or using cmd1.on('error'), cmd2.on('error') handlers
   });
```

**Comment by sidorares** [comment]
also `on('connection')` is now available for promise wrapper as well, see #567

**Comment by mnpenner** [comment]
Looks like this is working perfectly. Thank you @sidorares !

**Comment by dashmug** [comment]
@sidorares Can this be used on a `connection` object returned by `.createConnection()`?
