### ISSUE TITLE
pool.query didn't release connection when query is error

### ISSUE THREAD

**Issue by victor0801x** [sidorares/node-mysql2#569]
@sidorares 
as titile, when query occur some sql error, it didn't release connecion
here is an example
![2017-05-29 00-21-50](https://cloud.githubusercontent.com/assets/4534038/26530285/e7271b4a-4404-11e7-8ae0-8b644fb5c7d2.png)
it will halt there...
![2017-05-29 00-23-28](https://cloud.githubusercontent.com/assets/4534038/26530303/3c2e5978-4405-11e7-9e6f-121ebf944583.png)
it seems promise's pool.query has the same problem
#551 #508 
hope next release can fix this issue, thank you

**Comment by liuxg** [comment]
i encountered the sam problem with version 1.3.2

**Comment by sidorares** [comment]
thanks @victor0801x  @liuxg I can reproduce, will have a look asap

simple code to reproduce this:

```js
const pool = require('mysql2').createPool({});

setInterval(
  () => {
    console.log('_allConnections: ', pool._allConnections.length);
    console.log('_freeConnections: ', pool._freeConnections.length);
    console.log('_connectionQueue: ', pool._connectionQueue.length);

    pool.query('some syntax error', (err, res) => {
      console.log(err, res);
    });
  },
  1000
);
```

default limit is 10, _allConnections goes up to 10 and then queue starts to grow
