### ISSUE TITLE
Warning about lint-staged

### ISSUE THREAD

**Issue by natesilva** [sidorares/node-mysql2#573]
After updating to 1.3.0, when running `npm install` our devs are seeing the message:

```
🚫💩 lint-staged installed! 
Do not forget to configure it. See https://github.com/okonet/lint-staged/blob/master/README.md
```

It seems like this should be an internal thing, not exposed to users of the mysql2 package.

**Comment by sidorares** [comment]
Thanks! `lint-staged` was in dependencies by mistake, moved to `devDependencies`. Published as v1.3.1
