### ISSUE TITLE
Promise wrapper issues for `prepare`

### ISSUE THREAD

**Issue by faazshift** [sidorares/node-mysql2#574]
The recently released promise wrapper for `prepare` doesn't accept any arguments, but instead passes a callback to the underlying `prepare` function. Additionally, the returned `statement` object doesn't get wrapped, preventing a workflow like `statement.execute(...).then()`.

See: https://github.com/sidorares/node-mysql2/blob/master/promise.js#L132-L143

**Comment by sidorares** [comment]
thanks for report @faazshift 
do you have time to provide a fix? seems fairly trivial. Also would be good to add tests

If not I'll try to do this over weekend

**Comment by faazshift** [comment]
@sidorares Done. I went ahead and fixed both of the issues I mentioned in PR #575.

**Comment by sidorares** [comment]
published as v1.3.2
