### ISSUE TITLE
custom stream error "Only SOCKS version 5 is supported"

### ISSUE THREAD

**Issue by jasonliao** [sidorares/node-mysql2#576]
hi, I'm connecting my database with custom stream follow your [docs](https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#connecting-using-custom-stream), but got an error `Only SOCKS version 5 is supported`.

```javascript
var SocksConnection = require('socksjs'),
    mysql = require('mysql2')

var socks_options = {
  port: 1234,
  host: 'socks_host',
  user: 'user',
  pass: 'pass'
}

var remote_options = {
  host: 'remote_host',
  port: 1234
}

var socksConn = new SocksConnection(remote_options, socks_options)

var connectionConfig = {
  user: 'user',
  password: 'password',
  database: 'database',
  stream: socksConn
}

var connection = mysql.createConnection(connectionConfig)

connection.query('select * from table where id=1', function (error, results, fields) {
  if (error) throw error
  console.log(results)
})
```

It looks like `socksjs` package issue instead yours, but it works fine with [`pg`](https://github.com/brianc/node-postgres), did I missing something or using your package wrong?

**Comment by sidorares** [comment]
it looks like a message from the socks server.
Have you tried to use  @mscdex  `socksv5` client? https://github.com/mscdex/socksv5

Should look similar to this:

```js
const socks = require('socksv5');

const streamFactory = cb => socks.connect({
  host: 'remote_host',
  port: 1234,
  proxyHost: 'socks_host',
  proxyPort: 1234,
  auths: [ socks.auth.UserPassword('user', 'password') ]
}, cb)

var connectionConfig = {
  user: 'user',
  password: 'password',
  database: 'database',
  stream: streamFactory 
}

const connection = mysql.createConnection(connectionConfig)

connection.query('select * from table where id=1', function (error, results, fields) {
  if (error) throw error
  console.log(results)
})
```

**Comment by jasonliao** [comment]
Still don't work. I think is my proxy server doesn't support socks5, but anyway, thanks for your reply :)

**Comment by sidorares** [comment]
There is also https://www.npmjs.com/package/socks that claims to support v4.

I think I misinterpreted original error message, I thought it's coming from server "hey, I want socks v5 only" but it's probably client reporting "I can do only v5, but server is v4"
