### ISSUE TITLE
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by aankur** [sidorares/node-mysql2#577]
Hi ,

i am using mysql2 with bluebird on nodejs 8.

as 

```javascript
const mysql = require('mysql2/promise');
const Promise = require("bluebird");
config.Promise = Promise;//plus database connection configuration
pool = mysql.createPool(config);

function  GetSqlConnection() {
    return  pool.getConnection().disposer(function(connection) {
        connection.release();
    });
};
```
after sometime i get hit by this warning,
i get , 11 end listeners added. 11 drain  listeners added etc ...

```javascript

at _addListener (events.js:281:19)
    at PoolConnection.addListener (events.js:298:10)
    at /home/test/servers/v6/project/node_modules/mysql2/promise.js:8:14
    at Array.forEach (native)
    at inheritEvents (/home/test/servers/v6/project/node_modules/mysql2/promise.js:7:6)
    at new PromiseConnection (/home/test/servers/v6/project/node_modules/mysql2/promise.js:37:3)
    at /home/test/servers/v6/project/node_modules/mysql2/promise.js:228:17
    at /home/test/servers/v6/project/node_modules/mysql2/lib/pool.js:36:14
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
---------------------------------------------
    at process.emitWarning (internal/process/warning.js:154:18)
    at _addListener (events.js:289:17)
    at PoolConnection.addListener (events.js:298:10)
    at /home/test/servers/v6/project/node_modules/mysql2/promise.js:8:14
    at Array.forEach (native)
    at inheritEvents (/home/test/servers/v6/project/node_modules/mysql2/promise.js:7:6)
    at new PromiseConnection (/home/test/servers/v6/project/node_modules/mysql2/promise.js:37:3)
    at /home/test/servers/v6/project/node_modules/mysql2/promise.js:228:17
    at /home/test/servers/v6/project/node_modules/mysql2/lib/pool.js:36:14
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
---------------------------------------------
    at Pool.getConnection (/home/test/servers/v6/project/node_modules/mysql2/lib/pool.js:35:20)
    at /home/test/servers/v6/project/node_modules/mysql2/promise.js:224:14
    at Promise._execute (/home/test/servers/v6/project/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/test/servers/v6/project/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/test/servers/v6/project/node_modules/bluebird/js/release/promise.js:79:10)
    at PromisePool.getConnection (/home/test/servers/v6/project/node_modules/mysql2/promise.js:223:10)
    at Db.GetSqlConnection (/home/test/servers/v6/project/db.js:34:23)
    at Db.verify (/home/test/servers/v6/project/db.js:254:31)
```

**Comment by sidorares** [comment]
thanks for report @aankur 

might be side effect of #567  @Myhlamaeus can you have a look?

**Comment by sidorares** [comment]
@aankur could you reduce your case to something completely self contained?

**Comment by aankur** [comment]
```javascript
"use strict";
const ini = require('ini');
const fs = require("fs");
const config = ini.parse(fs.readFileSync('./config.ini', 'utf-8'));
const Db = require("./db.js")(config.db);


async function test()
{
        for(let i=0;i<20;i++)
        {
                await Db.Verify("abcd");
        }
}

test();

```

db access file

```javascript
"use strict";
const Promise = require("bluebird");
const mysql = require('mysql2/promise');
const Db = function (config) {
    this.config = config;
    this.config.Promise = Promise;
    this.pool = mysql.createPool(this.config);
};

module.exports = function (config) {
    return new Db(config);
};

Db.prototype.GetSqlConnection = function () {
    return  this.pool.getConnection().disposer(function(connection) {
        connection.release();
    });
};

Db.prototype.Verify= function VerifyRoom(email)
{

    return Promise.using(this.GetSqlConnection(), async (connection) => {

        try {
            const [password] = await connection.execute("SELECT password from `user` where email=?",email);
            return password;
        }
        catch (ex)
        {
            return Promise.reject({exception : ex,error : new Error(ex)});
        }

    });
};

**Comment by hijaq** [comment]
Can confirm having the same error and it happens only when using bluebird's `using` with `disposer` method to release connections and `mysql2` 1.3.0+ package. The small code to reproduce:

```javascript
const Promise = require('bluebird');
const mysql = require('mysql2/promise');

const pool = mysql.createPool({
  connectionLimit: 1,
  host: 'localhost',
  port: 3306,
  user: 'user',
  password: 'password',
  database: 'dbname',
  Promise,
});

const conn = () => Promise.using(pool
  .getConnection()
  .disposer(c => {
    c.release();
    console.log(`release connection`);
  }), c => c);

const getUser = (uid) => conn().then(c => c
  .query('SELECT * FROM users WHERE user_id=?', [uid])
  .then(([rows]) => (rows.length === 1 ? rows[0] : Promise.reject('user not found'))));

Promise
  .all([...Array(10).keys()]
    .map(uid => getUser(uid)
      .catch(err => console.error(`Unable to get user ${uid}: ${err}`))))
  .then(profiles => profiles
    .forEach(profile => console.log(JSON.stringify(profile))))
  .then(() => pool.end());
```

result:
```
bash-3.2$ node index.js
release connection
release connection
release connection
release connection
release connection
release connection
release connection
release connection
(node:19740) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
release connection
(node:19740) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
release connection
Unable to get user 0: user not found
Unable to get user 5: user not found
Unable to get user 6: user not found
undefined
{"user_id":1,"username":"johndoe","avatar":"https://example.com/default.png","first_name":"John","last_name":"Doe"}
// other users ....
```

**Comment by sidorares** [comment]
thanks @aankur @hijaq will try to investigate

**Comment by thexeos** [comment]
I've opened the issue for this in different mysql project mysqljs/mysql#1742 by accident.

I got the traces with _--trace-warnings_ flag:

> [02/06/2017 23:39:30.414] [ERROR] (node:5875) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
>     at _addListener (events.js:262:19)
>     at PoolConnection.addListener (events.js:279:10)
>     at /appRoot/node_modules/mysql2/promise.js:8:14
>     at Array.forEach (native)
>     at inheritEvents (/appRoot/node_modules/mysql2/promise.js:7:6)
>     at new PromiseConnection (/appRoot/node_modules/mysql2/promise.js:37:3)
>     at /appRoot/node_modules/mysql2/promise.js:201:17
>     at /appRoot/node_modules/mysql2/lib/pool.js:36:14
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> [02/06/2017 23:49:30.550] [ERROR] (node:5875) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
>     at _addListener (events.js:262:19)
>     at PoolConnection.addListener (events.js:279:10)
>     at /appRoot/node_modules/mysql2/promise.js:8:14
>     at Array.forEach (native)
>     at inheritEvents (/appRoot/node_modules/mysql2/promise.js:7:6)
>     at new PromiseConnection (/appRoot/node_modules/mysql2/promise.js:37:3)
>     at /appRoot/node_modules/mysql2/promise.js:201:17
>     at /appRoot/node_modules/mysql2/lib/pool.js:36:14
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> [02/06/2017 23:49:30.554] [ERROR] (node:5875) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
>     at _addListener (events.js:262:19)
>     at PoolConnection.addListener (events.js:279:10)
>     at /appRoot/node_modules/mysql2/promise.js:8:14
>     at Array.forEach (native)
>     at inheritEvents (/appRoot/node_modules/mysql2/promise.js:7:6)
>     at new PromiseConnection (/appRoot/node_modules/mysql2/promise.js:37:3)
>     at /appRoot/node_modules/mysql2/promise.js:201:17
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> [02/06/2017 23:49:30.555] [ERROR] (node:5875) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
>     at _addListener (events.js:262:19)
>     at PoolConnection.addListener (events.js:279:10)
>     at /appRoot/node_modules/mysql2/promise.js:8:14
>     at Array.forEach (native)
>     at inheritEvents (/appRoot/node_modules/mysql2/promise.js:7:6)
>     at new PromiseConnection (/appRoot/node_modules/mysql2/promise.js:37:3)
>     at /appRoot/node_modules/mysql2/promise.js:201:17
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
> [02/06/2017 23:49:30.555] [ERROR] (node:5875) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 enqueue listeners added. Use emitter.setMaxListeners() to increase limit
>     at _addListener (events.js:262:19)
>     at PoolConnection.addListener (events.js:279:10)
>     at /appRoot/node_modules/mysql2/promise.js:8:14
>     at Array.forEach (native)
>     at inheritEvents (/appRoot/node_modules/mysql2/promise.js:7:6)
>     at new PromiseConnection (/appRoot/node_modules/mysql2/promise.js:37:3)
>     at /appRoot/node_modules/mysql2/promise.js:201:17
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

I am not using _bluebird_ however.

**Comment by aankur** [comment]
i am able to reproduce it without bluebird disposer

 ```javascript
Db.prototype.Verify= function Verify(email)
{
   
    const connection = await  this.pool.getConnection();
        try
        {
			
           const [password] = await connection.execute("SELECT password from `user` where email=?",email);           
            connection.release();
            return password;
        }
        catch(ex)
        {
		connection.release();
            return Promise.reject({exception : ex,error : new Error(ex)});
        }

    });
```

**Comment by thexeos** [comment]
The remaining question is: how should the pool behave when it is actively using 10+ connections. For example, when multiple queries are running in parallel to aggregate data or alter table. The event listeners should be present until the query is done executing.

Maybe some kind of a super-callback function that will only be attached once and then route and process events centrally. I can see situations when 50 or more connections will be managed by the pool at the same time, and they can all be in an active state at once. That would also mean 50 * 4 = 200 event listeners on one object.

**Comment by sidorares** [comment]
@thexeos EventEmitter warning is issued whan you attach more then 10 listeners per event to one target. Pool attaches event per connection: conn1.on('connect') => pool.emit('connect') conn2.on('connect') => pool.emit('connect') etc

**Comment by rlidwka** [comment]
I have the similar issue here, and that's how I reproduce it:

```js
let mysql = require('mysql2/promise')

let pool = mysql.createPool({
  host: '127.0.0.1',
  user: 'root',
  connectionLimit: 2
})

;(async function () {

  for (let i=0; i<15; i++) {
    let conn = await pool.getConnection()
    //console.log((await conn.query('SELECT NOW() as time'))[0][0].time)
    conn.release()
  }

})().catch(console.log)
```

Just create a pool, and repeatedly connect/release. After 10th connection a couple of warnings will appear:

```
(node:3716) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3716) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
(node:3716) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:3716) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
(node:3716) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 enqueue listeners added. Use emitter.setMaxListeners() to increase limit
```

Note that those 5 warnings are for different events: `error`, `end`, `drain`, `connect` and `enqueue` respectively.

Using `node v8.1.0`, `mysql2 v1.3.3`.

**Comment by sidorares** [comment]
@rlidwka #578 should fix this but I was going to have a look and maybe refactor original implementation - just creating pool should not set up any additional listeners, only when you do `pool.on('...`. Also currently events fire from non-promise pool and pass unwrapped pool / poolconnection as parameter

**Comment by thexeos** [comment]
@sidorares There are no `pool.on('...` in my code. My situation is very similar to @rlidwka's example:

```
queue.on('message', function(payload) {
    try {
        storePayload(payload)
    } catch (err) {
        // Error handling
    }
});

async function storePayload(payload) {
    let connection = await pool.getConnection();
    await connection.beginTransaction();

     try {
          let [rs] = await connection.execute("...", [ ... ]);
          await connection.commit();
     } catch (err) {
          await connection.rollback();
          throw err;
     }

    connection.release();
}
```

It works until it receives 10+ messages simultaneously. Then it prints the warnings.

**Comment by CharlotteDunois** [comment]
I have the same issue with v1.3.3+ and master. After a few times getting a connection from the pool, I first had max event listener warnings with 11 event listeners for drain, end, enqueue and connect and now I have 16 event listeners for each (I set max listeners to 15 for testing purpose and that's when I suddenly had 16 listeners).

I make a pool using this code
```js
Storagist._pool = await mysql.createPool({
    host: (config.mysql.host ? config.mysql.host : 'localhost'),
    user: config.mysql.user,
    password: config.mysql.password,
    database: config.mysql.database,
    Promise: Bluebird
});
```

and I retrieve a connection using this method
```js
static getDBConnection() {
    return Storagist._pool.getConnection();
}
```

When I set max listeners to 21 it doesn't seem like I get any warnings anymore.

I also tried attaching an error event listener for both a pool and a connection before, because when the server closed the connection, Node.js complained there is an unhandled error event and terminates process (but that's a different story...).

**Comment by bhstrifork** [comment]
Any news on this? I just ran into this myself using version 1.3.5

**Comment by sidorares** [comment]
@bhstrifork sorry didn't have time yet. #578 should fix this but I really wanted to refactor original cause and that fix would no longer be relevant

**Comment by CharlotteDunois** [comment]
@sidorares Well, meanwhile you can PR the fix, so we wont get spammed any errord anymore. You can still investigate the cause.

**Comment by odino** [comment]
Same issue right here -- any idea for a fix?

**Comment by karthick4in** [comment]
refer this this your issue related to this 
https://github.com/mysqljs/mysql/issues/979

**Comment by kodekameleon** [comment]
I'm still seeing this issue in 1.6.1
