### ISSUE TITLE
string parser looks up in NODE_ENCODING incorrectly

### ISSUE THREAD

**Issue by dolphin278** [sidorares/node-mysql2#582]
Is this a bug?

https://github.com/sidorares/node-mysql2/blob/master/lib/parsers/string.js#L15
https://github.com/sidorares/node-mysql2/blob/master/lib/parsers/string.js#L28

`NODE_ENCODING` here is an array, `encoding` function arguments receives string values like `binary`, `cesu8`, `utf8`, etc (at least, in `decode` function). They will never be found using `encoding` variable as array key. Looks like we should scan array using `.indexOf` for this to work properly.

Does triggering `Iconv` decoder for every charset could give significant performance penalty on parsing rows?

**Comment by sidorares** [comment]
Looks like it meant to be hash like

```js
var NODE_ENCODING = {
  'ascii': true,
  'utf8': true,
  'utf16le': true,
  'ucs2': true,
  'base64': true,
  'latin1': true,
  'binary': true,
  'hex': true
};

```

**Comment by sidorares** [comment]
> Does triggering Iconv decoder for every charset could give significant performance penalty on parsing rows?

probably not, I think it does similar check internally and falls back to built-in decoding. Even if not I don't expect huge difference in performance, but would be interesting to benchmark

**Comment by sushantdhiman** [comment]
It should be `.indexOf` :S

**Comment by dolphin278** [comment]
@sushantdhiman Made #583 to fix this.
