### ISSUE TITLE
connection.execute is not a function

### ISSUE THREAD

**Issue by mrdaano** [sidorares/node-mysql2#584]
Hello,

Every time when I use the promise wrapper I get the same error: **TypeError: connection.execute is not a function**
I use the same code as mentioned in the example:
```javascript
// get the client
const mysql = require('mysql2/promise');

// get the promise implementation, we will use bluebird
const bluebird = require('bluebird');

// create the connection, specify bluebird as Promise
const connection =  mysql.createConnection({host:'localhost', user: 'root', password: 'root', database: 'allecampingsin_db', Promise: bluebird});

// query database
const [rows, fields] =  connection.execute('SELECT * FROM `countries` WHERE `slug` = ?', ['frankrijk']);

console.log(rows);
```

I use node version 8.0.0
And the latest version of this package

**Comment by sidorares** [comment]
`createConnection` is async function, it returns Promise
you need to change to `const connection =  await mysql.createConnection(/* ... */)` or ` mysql.createConnection(/* ... */).then( connection => { /* .... */ })`

**Comment by aakash-prasad** [comment]
I handled it as a promise, still it's showing me the same error

**Comment by Bringfireh** [comment]
I have looked into this issue very well and discovered the following:
1. That this error occurred because the connection defined is not seen by the app.js project file.
2. That if the connection to database is written in another page, the Exports are not done properly.
An example of this is seen below:
File: database.js
const mysql = require('mysql2');

const pool = mysql.createPool({
                    host: 'localhost',
                    user: 'root',
                    database: 'school',
                    password: 'yesu'
                 });
module.export =pool.promise();

This will give the error db.execute is not a function.
Because the line
module.export is wrong. it should have been
**module.exports =pool.promise();**

This is an omission of s in exports. So in the app.js file this database would be required and everything will work but when the view for this database is rendered the error will be thrown.

**Comment by geraldombuthia** [comment]
This is how I solved this issue;

I had defined my connection string as followed:

`import mysql from 'mysql2/promise';

async function connect() {
    try {
        const connection = await mysql.createConnection({
            host: 'localhost',
            user: 'myadmin',
            password: "mysqlpass",
            database: "lipagastest3"
          });
        if (connection) {
            console.log('Database Connected');
            // console.log(connection);
        }
        return connection;
    } catch (error) {
        console.error('Error connecting to the database:', error);
        throw error;
    }
}

export default connect;
`

Note the export default below;

`import connect from '../database/mysqlConn.js';
const connection = await connect();

`

Now the connection variable can be used to do queries as:

`const query = `Select * from users;`
        const [rows, fields] = await connection.query('SELECT * FROM `users`');
        console.log(rows, fields);
`

This is weird but worked for me

**Comment by SuheylZ** [comment]
I'm having the same issue and I don't think what @geraldombuthia provided could be considered as a solution. 

I'm using typescript and I have a single file that has all functionality. I follow the steps and I have  connection that does what? no query() no execute(). so what should I do? break my simple work into multiple files for the sake of exporting a connection?

there is something terribly wrong with the exports in the package. I don't know but with the current connection, there is nothing much you can do except closing it.
