### ISSUE TITLE
How to join tables from two different databases using mysqlPool

### ISSUE THREAD

**Issue by jeffswitzer** [sidorares/node-mysql2#590]
I currently have two database pools

```
var mysqlPromise = require('mysql2/promise');

let db1Pool = mysqlPromise.createPool({
    connectionLimit : 20,
    host     : db1Host,
    user     : db1User,
    password : db1Password,
    database : db1Database,
    debug    :  false
});

let db2Pool = mysqlPromise.createPool({
    connectionLimit : 20,
    host     : db2Host,
    user     : db2User,
    password : db2Password,
    database : db2Database,
    debug    :  false
});
```

And I can query from each database using their respective pools successfully. For example

```
function getExampleDb1Data() {
    return new Promise((resolve, reject) => {
        let query = `SELECT * FROM some_table;`;
        db1Pool.getConnection().then(conn => {
            let result = conn.query(query);
            conn.release();
            return result;
        }).then(([rows, fields]) => {
            resolve(rows);
        }).catch(err => {
            reject(err);
        })
    });
}
```

My question is how do I perform a join using tables from both db1 and db2? I could move the join logic out of the query and into the js, but that seems wrong. Thanks for any help.

**Comment by sidorares** [comment]
You mean on the server? I don't think it's possible, connection exists in quite isolated contexts (you can use global session variables to some extent to leak information between them, but probably not for joins)

In some scenarios client-side (as in node client, not database server side) join might be an option - you just fetch both datasets and then perform your logic in javascript

**Comment by sidorares** [comment]
Just noticed that db1 and db2 not just different connections but different servers as well. In that case moving logic to js is the only option

**Comment by jeffswitzer** [comment]
The databases are on the same mysql server instance.

**Comment by sidorares** [comment]
still if you have 2 separate connections there is no way to join afaik. You need to query one single sql command to get joined data

**Comment by jeffswitzer** [comment]
Alright, thanks for the feedback. I have everything working doing the joins on the js side, just wanted to see if others knew of a better way.
