### ISSUE TITLE
MySQL client versus node-mysql2 to operate load infile CSV

### ISSUE THREAD

**Issue by calebeaires** [sidorares/node-mysql2#593]
Do LOAD INFILE with node-mysql2 has lower performance then `mysql` command line? On my app I use `mysql -h $1 -u $2 -p$3 $4 --port $5 -e "LOAD DATA LOCAL INFILE '$6' INTO TABLE $7 CHARACTER SET $8 FIELDS  TERMINATED BY '|' LINES TERMINATED BY '\n'"` to run via terminal, but what if I use node-mysql2? Do my app will loose bigger amount of performance?

**Comment by sidorares** [comment]
>  Do my app will loose bigger amount of performance?

probably not, there is not much for driver to parse, mostly is just streaming content of the file up to server and then just ok packet. Would be really good to see real benchmark though, you you have environment ready for this give it a try and post your numbers
