### ISSUE TITLE
Ability to log all queries

### ISSUE THREAD

**Issue by ghiden** [sidorares/node-mysql2#610]
Is there any easy way to log all queries?
mysqljs/mysql has a way to do this.
https://github.com/mysqljs/mysql/issues/1272

**Comment by sidorares** [comment]
there is no 'enqueue' event in mysql2 connection (though we could add it)

currently the best I can think of is monkey patching like this

```js
const oldQuery = connection.query;
connection.query = function(...args) {
  const queryCmd = oldQuery.apply(args);
  console.log(queryCmd.sql);
  return queryCmd;
}
```

'Query Command' is that thing - https://github.com/sidorares/node-mysql2/blob/592756261d7e288bc4f060c7f2d6e0ff21986d8b/lib/commands/query.js#L17-L33

this is what `connection.query()` or `pool.query()` return

**Comment by ghiden** [comment]
Thanks for your quick reply!

**Comment by alete89** [comment]
is this still the best way to log all queries?
