### ISSUE TITLE
prepared statement queries not calling callback when using promise

### ISSUE THREAD

**Issue by payosofavo** [sidorares/node-mysql2#621]
Mysql server : 5.7.17
Node : 8.1.2
Mysql2 : 1.3.6
Os : windows 7

prepared statements not calling callback when using promise, I have "mysql2/promise + createPool"

query:

```
connection.execute('SELECT * FROM `members` WHERE `id` = ?',['abc'], function(err, results,f) {
                console.log(err);
                console.log(results);
});
```

is not giving any error or result, connection is working when doing simple queries without preparing.

this works
```
connection.execute('SELECT * FROM `members`', function(err, results,f) {
                console.log(err);
                console.log(results);
 });
```

This works (mysql2 without promise + createPool)

```
pool.execute('SELECT * FROM `members` WHERE `id` = ?',['abc'], function(err, results,f) {
                console.log(err);
                console.log(results);
});
```
also this works (mysql2 without promise + createPool, query instead of execute):
```
pool.query('SELECT * FROM `members` WHERE `id` = ?',['abc'], function(err, results,f) {
                console.log(err);
                console.log(results);
});
```

**Comment by sidorares** [comment]
with promise wrapper you do `.then()` or `await` on result to get data, and looks like you expect it to use callback

```js
connection.execute('SELECT * FROM `members` WHERE `id` = ?',['abc']).then((results) => {
                console.log(err);
                console.log(results);
}).catch(err => {/*...*/})
```

**Comment by payosofavo** [comment]
So there is no way to get that callback when using promise, without "then" or "await"?

Thanks

**Comment by sidorares** [comment]
> So there is no way to get that callback when using promise, and get results without "then" or "await"?

no

> What is reason that prepared statement does not call callback, but simple queries do call?

https://stackoverflow.com/questions/22539815/arent-promises-just-callbacks
https://www.quora.com/Whats-the-difference-between-a-promise-and-a-callback-in-Javascript
https://softwareengineering.stackexchange.com/questions/302455/is-there-really-a-fundamental-difference-between-callbacks-and-promises
