### ISSUE TITLE
Getting back Buffers instead of strings, numbers after upgrade

### ISSUE THREAD

**Issue by mscdex** [sidorares/node-mysql2#625]
I'm not sure at what point this was changed, but after installing the latest `mysql2`, we're seeing Buffer objects for all column values. Here are the options we're setting:

```js
{
  host: 'host',
  user: 'user',
  password: 'password',
  database: 'db',
  typeCast: false,
  supportBigNumbers: true,
  bigNumberStrings: true
}
```

I do know though that 0.15.8 works fine.

**Comment by sushantdhiman** [comment]
try removing `typeCast: false`

**Comment by mscdex** [comment]
After digging in the code, I ended up just setting it to `null` instead. I believe the original reason for `false` was to prevent automatic/default typecasting (e.g. to js numbers).

**Comment by sushantdhiman** [comment]
Great :)

> prevent automatic/default typecasting (e.g. to js numbers).

`bigNumberStrings: true` should cover that

**Comment by mscdex** [comment]
That's only for big numbers though. I was referring to non-big numbers. `mysql` at one point must have been converting numeric column values like '2' to a javascript number `2` value instead of leaving as a string. By explicitly telling `mysql`/`mysql2` 'no' by setting `typeCast` to a false-y value, that would leave it as a string.

Oh well.... I guess I will close this for now.

**Comment by sidorares** [comment]
> After digging in the code, I ended up just setting it to null instead. 

o wow, is there something like `if (typeof opts.typeCast !== 'undefined')`? Setting it to false should have same effect as null imo

**Comment by mscdex** [comment]
@sidorares [Here](https://github.com/sidorares/node-mysql2/blob/5f0fb8f1f5035e2c0207490aa2f0b838dc82fdc2/lib/compile_text_parser.js#L98-L115)'s what `mysql2` is doing and [here](https://github.com/mysqljs/mysql/blob/54615730c60bf351b8013fa8d004dd2b7ee29d38/lib/protocol/packets/RowDataPacket.js#L32-L40)'s what `mysql` is doing.

`mysql2` explicitly checks for `false` and uses a Buffer in that case. If it's some other non-function and non-`false` value, then strings are used.

`mysql` only performs a truthy check and if the `typeCast` evaluates to `true`, then it converts the value according to the rest of the config values (e.g. `timezone`, `supportBigNumbers`, `bigNumberStrings`, etc.). If it evaluates to `false`, then the only time it will return a Buffer is if the charset for the column is `BINARY`, otherwise it returns a string.

**Comment by sidorares** [comment]
looks like this is intended feature, need to have this mentioned in the readme at least

**Comment by alexcroox** [comment]
Can someone explain how to disable this properly?

I'm creating an API and currently it means I'm sending back json like this:

```
"isProfileHidden": {
                "type": "Buffer",
                "data": [
                    0
                ]
            },
```
when I want to be sending `"isProfileHidden": 0`

**Comment by sidorares** [comment]
@alexcroox I think you need to alter column type for `isProfileHidden`, it's probably has binary charset

**Comment by alexcroox** [comment]
No combination of typeCast true/false resolved it, but this did:

```
typeCast: function castField(field, useDefaultTypeCasting) {

        // We only want to cast bit fields that have a single-bit in them. If the field
        // has more than one bit, then we cannot assume it is supposed to be a Boolean.
        if ((field.type === "BIT") && (field.length === 1)) {

          var bytes = field.buffer();

          // A Buffer in Node represents a collection of 8-bit unsigned integers.
          // Therefore, our single "bit field" comes back as the bits '0000 0001',
          // which is equivalent to the number 1.
          return (bytes[0] === 1);

        }

        return (useDefaultTypeCasting());

      }
```
although I now worry about all the other column types I'm going to have to manually map to make it suitable for a json API response :(
