### ISSUE TITLE
MySQL 8 Encoding error

### ISSUE THREAD

**Issue by Zaiban** [sidorares/node-mysql2#628]
Switching from 5.7 to 8.0 produces the following error when trying to run a `CREATE TABLE` query with this module:
```
backend_1       | /opt/app/node_modules/iconv-lite/lib/index.js:106
backend_1       |                 throw new Error("Encoding not recognized: '" + encoding + "' (searched as: '"+enc+"')");
backend_1       |                 ^
backend_1       | 
backend_1       | Error: Encoding not recognized: 'undefined' (searched as: 'undefined')
backend_1       |     at Object.getCodec (/opt/app/node_modules/iconv-lite/lib/index.js:106:23)
backend_1       |     at Object.getDecoder (/opt/app/node_modules/iconv-lite/lib/index.js:122:23)
backend_1       |     at Object.exports.decode (/opt/app/node_modules/mysql2/lib/parsers/string.js:9:23)
backend_1       |     at Packet.readString (/opt/app/node_modules/mysql2/lib/packets/packet.js:382:23)
backend_1       |     at new ResultSetHeader (/opt/app/node_modules/mysql2/lib/packets/resultset_header.js:90:24)
backend_1       |     at Execute.Query.resultsetHeader (/opt/app/node_modules/mysql2/lib/commands/query.js:93:12)
backend_1       |     at Execute.Command.execute (/opt/app/node_modules/mysql2/lib/commands/command.js:40:20)
backend_1       |     at Connection.handlePacket (/opt/app/node_modules/mysql2/lib/connection.js:515:28)
backend_1       |     at PacketParser.onPacket (/opt/app/node_modules/mysql2/lib/connection.js:94:16)
backend_1       |     at PacketParser.executeStart (/opt/app/node_modules/mysql2/lib/packet_parser.js:77:14)
```
MySQL 8 is not officially out yet so I guess this module might have not been tested with it? Thought of switching to 8 to use the new handy UUID functions, but maybe I should wait a bit longer..

**Comment by sidorares** [comment]
Thanks @Zaiban ! can you test using code from `extend-charset-mapping` branch? Not all tests currently pass when 8.x server is used but that particular error seems to be fixed. More work required to start officially support 8 in CI matrix

**Comment by Zaiban** [comment]
I found a workaround by using `--collation-server=utf8mb4_unicode_520_ci`-flag, so guess is that the default collation in `8.0.2` was not working. I'll see if I can find some spare time to do more testing later.

**Comment by sidorares** [comment]
for some reason default encoding reported by mysql 8 is 255 which was missing in encodings table. I set it to utf8
