### ISSUE TITLE
Connection#changeUser is not a method

### ISSUE THREAD

**Issue by seanmonstar** [sidorares/node-mysql2#63]
We use it to change databases.

https://github.com/felixge/node-mysql/blob/master/lib/Connection.js#L76

**Comment by sidorares** [comment]
also make sure that code from https://github.com/felixge/node-mysql/issues/806 is backported

**Comment by sidorares** [comment]
and https://github.com/felixge/node-mysql/commit/5e43c5c5be1199cccb0bd42735d83afafc75c389 as well ( or better, pull all latest Pool / PoolCluster changes  from node-mysql )

**Comment by sidorares** [comment]
landed, soon to be published as 0.15.0
