### ISSUE TITLE
Timezone seems not work

### ISSUE THREAD

**Issue by LichFaker** [sidorares/node-mysql2#633]
I create a mysql pool and set the timezone option to `Asia/Shanghai`,but it still differ for 8 hours when I use `DATE(exp)` in sql.
```
const pool = mysql.createPool({ 
    host: dbCfg.host, 
    user: dbCfg.userName, 
    password: dbCfg.password,
    database: dbCfg.databaseName,
    connectionLimit: dbCfg.limit,
    timezone: "+08:00", // also try: "UTC+8","Asia/Shanghai", "local" but nothing different
})
```
Is there something wrong in my code?

**Comment by sidorares** [comment]
looking at the code I don't see timezone applied at all anywhere

Note that this meant to be client side transformation, mysql DATE type does not have any tz info in it. You can emulate `timezone` config option with custom `typeCast` https://github.com/mysqljs/mysql#type-casting :

(haven't tested this)
```js
  typeCast: function (field, next) {
    if (field.type == 'DATETIME') {
      return new Date(field.string() + '+08:00')
    }
    return next();
  }
```

looks like timezone option from config need to be applied here - https://github.com/sidorares/node-mysql2/blob/5f0fb8f1f5035e2c0207490aa2f0b838dc82fdc2/lib/packets/packet.js#L606 called from function generated at https://github.com/sidorares/node-mysql2/blob/5f0fb8f1f5035e2c0207490aa2f0b838dc82fdc2/lib/compile_text_parser.js#L173

**Comment by LichFaker** [comment]
thx, `typeCast` not worked for me. 
However, I just find a simple way to [solve this issue:](https://stackoverflow.com/questions/23571110/nodejs-responded-mysql-timezone-is-different-when-i-fetch-directly-from-mysql) config `dateStrings : true`

**Comment by darksabrefr** [comment]
Why not adding the timezone option to known incompatibilities with node-mysql (https://github.com/sidorares/node-mysql2/tree/master/documentation#known-incompatibilities-with-node-mysql) ?

**Comment by sidorares** [comment]
good idea @darksabrefr . Do you want to submit PR with docs update?

**Comment by darksabrefr** [comment]
PR request submited here : https://github.com/sidorares/node-mysql2/pull/752

**Comment by wisetc** [comment]
Why not set `timezone: "+00:00"`, cause your mysql server default timezone set to `UTC` maybe @LichFaker intersting
