### ISSUE TITLE
timezone pain

### ISSUE THREAD

**Issue by magnusjt** [sidorares/node-mysql2#642]
The timezone option does not appear to do anything. If this package is supposed to be a dropin replacement for node-mysql, why isn't this at least mentioned somewhere? I've seen a few attempts at using the typeCast function instead, but this function doesn't work with pool (at least when I tried it). Are you planning on adding any of these soon?

The reason I need these is because my node application and the mysql server are running on different timezones, and I don't know what they are beforehand.

**Comment by ssypi** [comment]
typeCast does work in pool. Are you using .execute? typeCast seems only to work currently with .query as mentioned in #649

**Comment by magnusjt** [comment]
You're probably right about that.

In the meantime I've switched back to https://github.com/mysqljs/mysql

I'm using the timezone settings shown below:

````js
let config = {
	// ...
	timezone: 'UTC', // Interpret all received timestamps as UTC. Otherwise local timezone is assumed.
	dateStrings: [
		'DATE', // DATE's are returned as strings (otherwise they would be interpreted as YYYY-MM-DD 00:00:00+00:00)
		'DATETIME' // DATETIME's return as strings (otherwise they would interpreted as YYYY-MM-DD HH:mm:ss+00:00)
	]
};

let pool = mysql.createPool(config);
pool.on('connection', conn => {
	conn.query("SET time_zone='+00:00';", error => {
		if(error){
			throw error;
		}
	});
});
````

These settings work no matter what the client/server timezones are.

**Comment by magnusjt** [comment]
I didn't notice this was fixed until now. Just wanted to say, thanks for fixing it!
