### ISSUE TITLE
createConnection with no Database selected?

### ISSUE THREAD

**Issue by dantalksalot** [sidorares/node-mysql2#644]
How would you go about connecting to the server without the database argument?

`var connection = mysql2.createConnection({host: host, user: 'root' })`

**Comment by sidorares** [comment]
hi @dantalksalot yes this is the way to go. Did you try to connect like that? Any issues?

**Comment by dantalksalot** [comment]
Hahaha oh God I just forgot to use the actual database I created. Whoops.
