### ISSUE TITLE
Bad API design for PoolConnection.end

### ISSUE THREAD

**Issue by aikar** [sidorares/node-mysql2#650]
Re:
```javascript
PoolConnection.prototype.end = function() {
  console.warn(
    'Calling conn.end() to release a pooled connection is ' +
      'deprecated. In next version calling conn.end() will be ' +
      'restored to default conn.end() behavior. Use ' +
      'conn.release() instead.'
  );
```

This is bad design, as it now requires end users to know and care if a connection was pooled or not.

It is better design to treat a Pooled connection just like any other connection, and the end user code should not care if it is pooled or not. All it needs to declare is it's done.

See widely popular pool libraries like HikariCP.

**Comment by sidorares** [comment]
I'd probably disagree. Pooled connection is one managed by the pool and certain actions might be be restricted and only allowed to be performed by pool.

The api is as this mainly because of original pool implementation in mysqljs/mysql
