### ISSUE TITLE
Compatible methods between using mysql2 and mysql2/promise

### ISSUE THREAD

**Issue by bipvanwinkle** [sidorares/node-mysql2#657]
I've noticed that mysql2 and mysql2/promise do not have the same methods. It would be nice to be able to import a single package and use the synchronous and asynchronous methods. 

I don't want to add more a burden to your maintenance and I'm happy to help out, but I want to see if this is something that y'all would be okay with and is feasible.

**Comment by sidorares** [comment]
The api is different so two versions can't be 100% similar, but at the same time I want it to be easy to start for devs switching from callback style and for completely new devs

Can you first list here incompatibilities that you found? ( and propose design for missing methods )
