### ISSUE TITLE
pool events

### ISSUE THREAD

**Issue by kswope** [sidorares/node-mysql2#661]
Pool events seem to be unimplemented or just not working, add to docs

**Comment by sidorares** [comment]
Hi! Could you list events you expect to be there to simplify work required to cover this issue? ( You are probably right, mysql2 uses slightly modified copy/pasted pool code from mysqljs/mysql and it might be behind )

**Comment by kswope** [comment]
Hello, I guess I should have given my issue a little more context

Here 

https://github.com/sidorares/node-mysql2/tree/master/documentation 

```
Note : If you see any API incompatibilities with node-mysql, please report via github issue.

```

Pool events https://github.com/mysqljs/mysql#pool-events don't seem to be implemented and should be on that list.  Or maybe completely broken, or I completely screwed up.  Its not a big deal however, I was just using them for debugging a setup.

Also I don't think you mean "node-mysql", which seems to be a little used mod https://www.npmjs.com/package/node-mysql

**Comment by sidorares** [comment]
I'll update docs, thanks! That line is from time when mysqljs/mysql used to be felixge/node-mysql

If you can give some concrete examples of what's missing it would be easier to fix. I think we have pool events but not some recently added, need to double check. If you can provide simple self-contained example that works with `mysql` but breaks with `mysql2` that would be great help

**Comment by moberemk** [comment]
Any movement on this? It'd be nice to have these events set up so we can debug issues with our pooling logic.

**Comment by dvejmz** [comment]
I've just hit this issue too and am happy to provide as much detail as required. My use case is to export Prometheus metrics and also print out some logging statements for every connection pool lifecycle event. So I've got this code

```javascript
    let acquiredConnections = 0;
    let poolSize = 0;
    let queueSize = 0;

    const pool = mysql.createPool(poolOpts);

    pool.on('acquire', (connection) => {
        acquiredConnections += 1;
        metrics.gauge({
            name: 'connector_db_acquired_conns',
            help: 'Number of connections currently acquired from the pool',
            value: acquiredConnections,
        });
        logger.info('connector.DBConnection.acquire', { acquiredConnections });
    });

    pool.on('connection', (connection) => {
        poolSize += 1;
        // export more Prometheus metrics...
        logger.info('connector.DBConnection.connection', { poolSize });
    });

    pool.on('enqueue', (connection) => {
        queueSize += 1;
        // export more Prometheus metrics...
        logger.info('connector.DBConnection.enqueue', { queueSize });
    });

    pool.on('release', (connection) => {
        acquiredConnections -= 1;
        // export more Prometheus metrics...
        logger.info('connector.DBConnection.release');
    });
```

Then in the logs all I see is the pool connection events. I can't see any `acquire`s or `release`s whatsoever. I wouldn't expect to see any `enqueue`s because I've set the pool size to be 200 and my application barely uses a handful of connections anyway, although I presume this event wouldn't fire either.

This is an example of a piece of code that I would expect to trigger both a connection acquisition and a release event

```javascript
    function releaseConnection(connection) {
        connection.release();
    }

    function newConnection() {
        return new Promise((resolve, reject) => {
            pool.getConnection((err, connection) => {
                if (err) {
                    logger.error('connector.DBConnection.newConnection', err);
                    return reject(err);
                }

                return resolve(connection);
            });
        });
    }

    function query(sql, values = [], label) {
        const outputLabel = label || DEFAULT_OUTPUT_LABEL;
        return new Promise((resolve, reject) => {
            const startToken = timers.start();
            newConnection()  // 'acquire' EVENT SHOULD BE TRIGGERED HERE
                .then((connection) => {
                    connection.query(sql, values, (err, rows) => {
                        updateCounters();
                        const duration = timers.stop(startToken);
                        if (err) {
                            logger.error(`${outputLabel}.sql`, err);
                            connection.destroy();
                            return reject(err);
                        }
                        logger.info(`${outputLabel}.query.done`, {
                            duration,
                            count: rows.length,
                        });
                        releaseConnection(connection); // 'release' EVENT SHOULD BE TRIGGERED HERE
                        return resolve(rows);
                    });
                })
                .catch((err) => {
                    logger.error(`${outputLabel}.sql`, err);
                    reject(err);
                });
        });
    }
```

If you need more information, let me know. I'm very happy to help.

**Comment by dvejmz** [comment]
Now that https://github.com/sidorares/node-mysql2/pull/783 has been merged in, I believe node-mysql2 supports the same pool connection events than mysql-node so this issue can be closed. @sidorares @kswope
