### ISSUE TITLE
PromisePool doesn't proxy synchronous functions

### ISSUE THREAD

**Issue by c24w** [sidorares/node-mysql2#663]
For example:
```javascript
const {createPool} = require('mysql2/promise');
const pool = await createPool(options);
console.log(typeof pool.escape) // => 'undefined'
```
Presumably it could do something similar to [this](https://github.com/sidorares/node-mysql2/blob/8dc27c516472ad5068f136c28e70308f1e97640e/promise.js#L235-L273)?

**Comment by sidorares** [comment]
> Presumably it could do something similar to this?

yes, would be good to add them, probably in a similar way
