### ISSUE TITLE
connection.destroy() doesn't kill the socket instantly

### ISSUE THREAD

**Issue by scooper91** [sidorares/node-mysql2#670]
Currently, [`connection.destroy()`](https://github.com/sidorares/node-mysql2/blob/6288a4b335e2870f43cc3c44f73abae70ba3d4ee/lib/connection.js#L804) is an alias to `connection.close()` which gracefully closes the stream.

In mysqljs, [`connection.destroy()`](https://github.com/mysqljs/mysql/blob/e16c52da980e46012a391232be884b797b8af070/lib/Connection.js#L255) causes an immediate termination of the underlying socket.

It would be useful to have this functionality in mysql2, so I don't have to wait for the query to finish to kill the connection, and so it matches the mysqljs library.

**Comment by sidorares** [comment]
`connection.close()` unlike `connection.end()` does not wait all commands in the queue to finish.

If you look at the code what it does is:
1) do `stream.end()` immediately
2) clear timeouts
3) put connection into 'closing' state, and throw error if more commands are added on this connection

In contract, `connection.end()` basically adds `COM_QUIT` command to the end of the queue. Underlying connection usually is  closed by server
