### ISSUE TITLE
1.5.1 GEOMETRY returning NULL instead of empty Buffer is a breaking change

### ISSUE THREAD

**Issue by doublesharp** [sidorares/node-mysql2#686]
Just a heads up that returning `null` instead of an empty `Buffer` (one of the changes in 1.5.1) is a breaking change for `Sequelize` which is expecting an empty `Buffer`.

```
    value = value.buffer();

    // Empty buffer, MySQL doesn't support POINT EMPTY
    // check, https://dev.mysql.com/worklog/task/?id=2381
    if (value.length === 0) {
      return null;
    }
``` 

https://github.com/sequelize/sequelize/pull/8661

https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/data-types.js#L151

**Comment by sushantdhiman** [comment]
That change was actually fixing an incorrect behavior, but was breaking indeed.

Closing this issue as Sequelize will handle this change after  https://github.com/sequelize/sequelize/commit/6931c795a89ff70722c6718e6b151121edad5c94 i.e. v4.22.12
