### ISSUE TITLE
Usage in CF

### ISSUE THREAD

**Issue by swftvsn** [sidorares/node-mysql2#691]
Hi,

I'm wondering if I need to close the connections (or pool if I'm using one) when using this library in Google's Cloud Functions? If I  understand correctly, the node process will be killed after my code is done. 

It has proved tedious to close the pool by hand, and I'm wondering if I should do that at all? The question is, are connections closed properly, if the node process is simpy killed?

**Comment by PolymathWhiz** [comment]
`pool.query()` or `pool.execute()` closes it for you automatically. With `pool.getConnection()` you will have to end it yourself

**Comment by sidorares** [comment]
I don't now how GCF usage is billed but if it's per second of use it's better to close process as soon as you done your job. There is `pool.end(callback)` helper to class all connections in the pool. I guess for simple scripts when you don't need connections and already have all the data you wanted from db `process.exit(0)` is as good
