### ISSUE TITLE
"??" backtick substitution syntax doesn't seem to work

### ISSUE THREAD

**Issue by mondalaci** [sidorares/node-mysql2#694]
```
const [rows, fields] = await conn.execute(`SELECT * FROM ?? WHERE orderId=?`, [tableName, order.orderId]);

```

I'd expect the above code to substitute `??` with the content of `tableName` and escape it with backticks but it doesn't seem to work. Why?

```
  message: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'?? WHERE orderId=?\' at line 1',
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '#42000' }
```

**Comment by sidorares** [comment]
`execute()` placeholders are different from "client-side" `.query()` placeholders. You must use sql that makes valid prepared statement - see https://dev.mysql.com/doc/refman/5.7/en/sql-syntax-prepared-statements.html

Basically if your code does not work in cli with `PREPARE stmt1 FROM 'insert your sql here';` it won't work with `.execute()`

You can probably combine two if you really need:

```js
const SqlString  = require('sqlstring');

// ...
const sql = SqlString.format('SELECT * FROM ?? WHERE id = ?', [tableName]);
const [rows, fields] = await conn.execute(sql, [order.orderId]);
```

**Comment by mondalaci** [comment]
Thanks so much for the quick follow up, and the suggestions! Makes sense.
