### ISSUE TITLE
PromisePool execute can only use the native Promise

### ISSUE THREAD

**Issue by nasplachkov** [sidorares/node-mysql2#696]
Why isn't **execute** using the provided promises library instead of the native one? Is there a specific reason for that? 

I was expecting it to be like this:
https://github.com/sidorares/node-mysql2/blob/5f65614a0d61e4ea23d6b1ce0f75548205ba49f7/promise.js#L345

Instead it is like this:
https://github.com/sidorares/node-mysql2/blob/5f65614a0d61e4ea23d6b1ce0f75548205ba49f7/promise.js#L359

**Comment by sidorares** [comment]
no, this looks like a mistake ( not surfaced because most people use native Promises )

Can you submit PR with fix? Also would be great to add test that verifies custom Promises actually used

**Comment by nasplachkov** [comment]
Here it is: [https://github.com/sidorares/node-mysql2/pull/697](https://github.com/sidorares/node-mysql2/pull/697)

**Comment by aikar** [comment]
This issue can be closed since PR was pulled
@sidorares  @nasplachkov
