### ISSUE TITLE
Mysql#PoolCluster#query method missing

### ISSUE THREAD

**Issue by mariodu** [sidorares/node-mysql2#701]
Link to node-mysql doc:
https://github.com/mysqljs/mysql#poolcluster

like `pool.query(function (error, results, fields) {});`

mysql2 didn't implement it.

**Comment by mihai1voicescu** [comment]
Any news on this?

**Comment by sidorares** [comment]
I never used PoolCluster myself, unless somebody is able to offer quality PR to sync Pool/PoolCluster from mysqljs this is relatively low priority for me

**Comment by yuxizhe** [comment]
I made a PR to fix this.
