### ISSUE TITLE
Prepared statements - support escaped property names in JSON path 

### ISSUE THREAD

**Issue by amozh** [sidorares/node-mysql2#703]
We use prepared statements and named parameters everywhere in our project and it is really useful. Great job!

Additionally we have started actively using JSON and i have faced with an issue in next query:
```
SELECT * FROM table WHERE jsonColumn->>'$."propertyName"' = :p1
```
and parameters object:
```
{
  p1: 'propertyValue'
}
```
Parameter `p1` is never replaced by it's value and query gets executed in MySql as is, hence i get an  SQL syntax error near `:p1`.

The issue happens because `propertyName` is escaped with double quotes and `named-placeholders` library has some specific logic around double quotes here:
https://github.com/mysqljs/named-placeholders/blob/master/index.js#L36

I really need to escape property name in JSON object because it may contain special characters which break SQL query.

**Comment by sidorares** [comment]
hi @amozh thanks for report! moved to https://github.com/mysqljs/named-placeholders/issues/10
