### ISSUE TITLE
Advisory Lock returns `null`

### ISSUE THREAD

**Issue by scull7** [sidorares/node-mysql2#704]
When attempting to obtain an advisory lock:
https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_get-lock

I'm receiving a `null` response instead of the `0` or `1` as specified by the MySQL documentation and as seen when I issue the query through the MySQL client.

<img width="585" alt="screenshot 2018-01-05 16 50 37" src="https://user-images.githubusercontent.com/234352/34634400-9989c3be-f238-11e7-9330-a6128f35a775.png">

```javascript
import test from 'ava'

import mysql from 'mysql2'

const pool = mysql.createPool({
  connectionLimit: 10,
  host: 'localhost',
  user: 'root',
  port: 3306,
  database: 'test',
  password: '',
})

const foo = () => new Promise((resolve) => {
  resolve(1)
})

const multiQuery = () => new Promise((resolve, reject) => {
  const sql = `
    SELECT GET_LOCK('test2', -1) AS test3;
  `
  pool.query(sql, (err, res) => (err == null ? resolve(res) : reject(err)))
})

test(async (t) => {
  const response = await multiQuery()
  console.log(response)
  t.is(await foo(), 1)
})
```

Response:
<img width="261" alt="screenshot 2018-01-05 16 52 52" src="https://user-images.githubusercontent.com/234352/34634462-219887f4-f239-11e7-8dce-b6d48cfc6c46.png">

Is this expected?

**Comment by sidorares** [comment]
could you run with `debug: true` and/or console.log fields ( I wan't to see tfield ype returned by server ): `pool.query(sql, (err, res, fields) ...` ?

**Comment by scull7** [comment]
<img width="377" alt="screenshot 2018-01-05 17 42 17" src="https://user-images.githubusercontent.com/234352/34635110-d1600242-f23f-11e7-9579-603460e44cc3.png">

**Comment by scull7** [comment]
<img width="377" alt="screenshot 2018-01-05 17 42 17" src="https://user-images.githubusercontent.com/234352/34635267-f759cd78-f241-11e7-8d45-9455d2e6ef60.png">

**Comment by scull7** [comment]
Is that enough information?

**Comment by sidorares** [comment]
judging by `RowDataPacket` constructor name I'm pretty sure you are using mysqljs/mysql in your test, not mysql2. I see you opened similar issue there - https://github.com/mysqljs/mysql/issues/1912

I tried running this with both mysql and mysql2:

```js
var mysql =  require('mysql');

const conn = mysql.createConnection({
  user: 'root', password: 'tetris'
})

const sql = 'SELECT GET_LOCK("test2",-1) AS test3';

conn.query(sql, (err, res) => {
	console.log(res);
});
```

and getting `{ test3: 1 }` from both

**Comment by scull7** [comment]
I tried using both, modules, sorry for pasting the incorrect results. Here are my results with `mysql2`
<img width="360" alt="screenshot 2018-01-05 18 05 56" src="https://user-images.githubusercontent.com/234352/34635351-1b5c91a0-f243-11e7-9a59-192d67621ca8.png">

**Comment by scull7** [comment]
@sidorares I receive the following running your script:
<img width="422" alt="screenshot 2018-01-05 18 12 32" src="https://user-images.githubusercontent.com/234352/34635441-17d70c26-f244-11e7-8dbc-5fc9f093d29f.png">

**Comment by sidorares** [comment]
I'm getting 1, so it might be some difference in environment as you suggested

**Comment by scull7** [comment]
MariaDB version: 10.1.26-MariaDB-1~jessie
NodeJS version: 8.9.0
MySql (node) version: 2.15.0
MySql2 (node) version: 1.5.1
macOS: 10.13.2

**Comment by scull7** [comment]
It is an issue with MariaDB vs MySql.  MariaDB doesn't seem to support the negative timeout.  

From the [MySql Docs](https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_get-lock)
>A *negative* timeout value means infinite timeout. The lock is exclusive. While held by one session, other sessions cannot obtain a lock of the same name. 

The [MariaDB Docs](https://mariadb.com/kb/en/library/get_lock/) omit that line:
>Tries to obtain a lock with a name given by the string str, using a timeout of timeout seconds. Returns 1 if the lock was obtained successfully, 0 if the attempt timed out (for example, because another client has previously locked the name), or NULL if an error occurred (such as running out of memory or the thread was killed with mysqladmin kill).

I apologize, I did not notice the difference.

**Comment by scull7** [comment]
@sidorares thank you for your help
