### ISSUE TITLE
Prepared statements example in README is confusing

### ISSUE THREAD

**Issue by treefort** [sidorares/node-mysql2#710]
I was doing fine until I got to this example:

```
// execute will internally call prepare and query
connection.execute(
  'SELECT * FROM `table` WHERE `name` = ? AND `age` > ?',
  ['Rick C-137', 53],
  function(err, results, fields) {
    console.log(results); // results contains rows returned by server
    console.log(fields); // fields contains extra meta data about results, if available
  }
);
```

To be fair, you probably need to have a very high IQ to understand this example. The placeholder values are extremely subtle, and without a solid grasp of theoretical physics most of this will go over a typical programmer's head.

**Comment by sidorares** [comment]
missed this somehow. Can you suggest better example @treefort ? Feel free to reopen with suggestion ( or better do a pr), closing for now as old issue

**Comment by treefort** [comment]
Oh... lol, sorry. Not a real issue, just a Rick and Morty joke. :)
