### ISSUE TITLE
MultipleStatements in a pool with execute() ?

### ISSUE THREAD

**Issue by karbon15** [sidorares/node-mysql2#714]
Hello,

I am trying to define temporary variables as part of a multiple statements query.

```
const mysql = require('mysql2/promise');

...

constructor(in_dbParams) {
  this._dbParams = in_dbParams;
  this._dbParams.multipleStatements = true;
}

async init() {
  this._connectionPool = await mysql.createPool(this._dbParams);
}

.....

let [ result ] = await in_connection.execute('SET @test111 = 111; UPDATE key_values.......');
```

Despite using multipleStatements, I am getting an error:

```Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UPDATE key_values [..]' at line 1```

Everything seems to work fine without the SET statement.

Is multipleStatements compatible with execute() ?

**Comment by sidorares** [comment]
> Is multipleStatements compatible with execute() ?

Probably not.

anything you can `PREPARE` (  https://dev.mysql.com/doc/refman/5.7/en/prepare.html )  should work with execute, but I believe there is no way to prepare multiple queries into one statement. Possible workaround is to move those statements into stored procedure and then call it from `execute()`

**Comment by karbon15** [comment]
Ah!  Should have RTFM!

`SQL syntax for prepared statements does not support multi-statements (that is, multiple statements within a single string separated by ; characters).`

Thank you.
