### ISSUE TITLE
Prepared Statement Executes with undefined values

### ISSUE THREAD

**Issue by aikar** [sidorares/node-mysql2#715]
If you call 
```javascript
const result = await connection.execute("SELECT foo FROM bar where baz = ?", [undefined]);
```

then the Statement Execute will never finish, and forever hang.

The fix is pretty simple, in lib/packets/execute.js needs to use double equals instead of triple equals checks.

**Comment by sidorares** [comment]
I think this was fixed by #705

**Comment by aikar** [comment]
@sidorares yes it was, closing

**Comment by aikar** [comment]
though @sidorares we may need https://github.com/sidorares/node-mysql2/pull/689 still.

If the execute throws, least with that PR, it forwards the error as the result correctly.

The source of me reporting this issue was that my promise was never resolved, so im not sure even with the throws, ensuring we reject the pending promise.

The try/catch Pr looks good to help catch errors and relay the error as a result.

**Comment by sidorares** [comment]
merged @aikar  ! Probably unnecessary currently with all recent additions for undefined parameters but might help with future undiscovered issues
