### ISSUE TITLE
MYSQL2 silently dies on when a pool is initiated with incorrect connectionLimit values

### ISSUE THREAD

**Issue by NinnOgTonic** [sidorares/node-mysql2#721]
I had the joy of debugging this for a while. But apparently the mysql2 library appears to have a logic error that will cause it to silently die.

I tracked this down to the use of `Number` to init the variable for the pool config (found at https://github.com/sidorares/node-mysql2/blob/5f0fb8f1f5035e2c0207490aa2f0b838dc82fdc2/lib/pool_config.js ). If for example the variable is a string, such as `"FILL-ME-IN"` this will initialise the value to `NaN`, which will then lead to a logic error further down in the applications pool logic.

I was considering making a patch changing the usage to `parseInt` but you might have some maintainers might have other comments or preferences. This would by default throw on an "unparsable" integer.

Alternatively further checks could be defined to verify that the connectionLimit doesn't end up as `NaN`, or is something satisfying `connectionLimit > -1` or similar.

Example code that will stop silently, this was tested using node 9.3.0 and mysql2 version 1.5.1:

```
// @ts-check
const mysql = require('mysql2/promise')

function getSourceDatabaseConfig() {
    const {
        S_MYSQL_HOST = '127.0.0.1',
        S_MYSQL_PORT = '3306',
        S_MYSQL_USER = 'root',
        S_MYSQL_PASSWORD = 'sometestpw',
        S_MYSQL_DATABASE = 'somedb',
        S_MYSQL_CONNECTIONS = 'FILL-ME-IN'
    } = process.env

    return {
        host: S_MYSQL_HOST,
        port: S_MYSQL_PORT,
        user: S_MYSQL_USER,
        password: S_MYSQL_PASSWORD,
        database: S_MYSQL_DATABASE,
        connectionLimit: S_MYSQL_CONNECTIONS
    }
}

let sourcePool;

function getSourcePool() {
    if (sourcePool === undefined) {
        sourcePool = mysql.createPool(getSourceDatabaseConfig());
    }

    return sourcePool;
}


async function run() {
    console.log('Executing Data-Mirror')

    const sourcePool = getSourcePool()

    console.log('Checking connections - Source pool')
    const connSource = await sourcePool.getConnection()
    console.log('Connection verified')
}


process.on('uncaughtException', err => {
    console.error(err)
    process.exit(1)
})
process.on('unhandledRejection', reason => {
    console.error(reason)
    process.exit(1)
})

process.on('SIGINT', function () {
    console.error('Got SIGINT')
    process.exit(0)
})
process.on('SIGTERM', function () {
    console.error('Got SIGTERM')
    process.exit(0)
})

run()
    .then(() => {
        console.log('Exiting')
    })
    .catch((e) => {
        console.log(`Got error from run`, e)
    })


```

**Comment by sidorares** [comment]
Thanks for report @NinnOgTonic ! We should definitely be more defensive here.

Do you want to volunteer to fix that?  Should be done in connection_config as well
