### ISSUE TITLE
options.values (check for values containing undefined)

### ISSUE THREAD

**Issue by mathieumagalhaes** [sidorares/node-mysql2#730]
Updating from 1.4.2 to 1.5.2, I'm getting a
`options.values.forEach is not a Function`
in **lib/connection.js line 688**

As options.values is an Object (not an array) when I checked it out, 
for me a simple workaround would be:
`Object.values(options.values).forEach is not a Function`

But I do not know the possible side effect of this work around in the newer version.
Could someone inform me if this would have side effects?

**Comment by sidorares** [comment]
From a quick look - `values`  should always be array by this point. Can you show us how you call `execute()` ?

**Comment by mathieumagalhaes** [comment]
I was doing:
```
query = queryFormat(query, queryParams);
pool.execute(query, queryParams).then( ...
```

**Where for example:**

- **query**: a sql query `SELECT * FROM users WHERE id = '{@id}`
- **queryParams**: { id: 1 }
- **queryFormat**: is a custom sanitizer function (which uses the mysql2 escape function internally) for a custom use case, as I replace {@id} with the sanitized value of queryParams.id

Anyways, issue can be closed for me, as I can just simply use 
`pool.execute(query).then( ...`
Since query is already filled and sanitized and which does not return an error.

Still, passing an object to the .execute function as a second argument (values) throws an error though. Which did not throw an error in 1.4.2

But which is the expected behavior I assume from your previous comment?

**Comment by sidorares** [comment]
> Which did not throw an error in 1.4.2

I think in 1.4.2 it silently tried to execute with no params

Expected behaviour for execute is to only accept array of values or no values at all. With `execute` parameters are substituted on the server side and because of this we don't try to modify sql of the query.

What was behaviour you expected from object parameter? We can't do here `Objects are turned into key = 'val' pairs for each enumerable property on the object. If the property's value is a function, it is skipped; if the property's value is an object, toString() is called on it and the returned value is used.` as per sqlstring behaviour

**Comment by sidorares** [comment]
have you tried to use built-in named placeholders? https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#named-placeholders

**Comment by mathieumagalhaes** [comment]
Tried using the following:
```
pool.execute('SELECT :item AS test FROM dual', { item: 'success' }).then((result) => ...
```
Will return the same error (connection.js:688 options.values.forEach)

**Comment by dmfay** [comment]
I stumbled on the same issue after upgrading from 1.5.1 to 1.5.2 when passing an empty params array. This works (`method` is one of `query` or `execute`):

```
const args = [sql];

if (params) { args.push(params); }

instance[method].apply(instance, args).then(result => {...});
```
but I feel like the instance should be able to handle an empty array on its own.

**Comment by sidorares** [comment]
@mathieumagalhaes  this example works for me:

```js
async function main() {
  const mysql2 = require('mysql2/promise'); // with mysql this works...
  let mysql2Con = await mysql2.createConnection({
    user: 'root',
    password: 'password',
    namedPlaceholders: true
   });

  const [rows] = await mysql2Con.execute('select 1+:id as qqq', { id: 10 });
  console.log(rows);
}

main().catch(e => {
  console.log('Top level error!', e);
});
```

**Comment by mathieumagalhaes** [comment]
@sidorares I'm calling execute on a pool, does that make any difference?
```
const pool = require('mysql2/promise').createPool(mysqlConfig)
pool.execute(...)
```

**Comment by sidorares** [comment]
forks exactly the same for pool:

```js
async function main() {
  const pool = require('mysql2/promise').createPool({
    user: 'root',
    password: 'password',
    namedPlaceholders: true
  });

  const [rows] = await mysql2Con.execute('select 1+:id as qqq', { id: 10 });
  console.log(rows);
}

main().catch(e => {
  console.log('Top level error!', e);
});
```

Output: 

```
node test.js
[ BinaryRow { qqq: 11 } ]
```

**Comment by mathieumagalhaes** [comment]
Weird, still seeing the exact same issue using your code with mysql2@1.5.2
```
          const pool = require('mysql2/promise').createPool(mysqlConfig);
          const [rows] = await pool.execute('select 1+:id as qqq', { id: 10 });
          console.log(rows);
```
Will throw an exception for me:
```
uncaughtException exception detected TypeError: options.values.forEach is not a function
```

**Comment by sidorares** [comment]
yeah, it's off by default. I'll try to see what can be improved in error handling though, if we can't do same "Objects are turned into key = 'val' pairs" transformation for `execute` we should have error message explaining this
