### ISSUE TITLE
execute UPDATE SET ? error

### ISSUE THREAD

**Issue by farzher** [sidorares/node-mysql2#733]
`db.execute('update t set ? where id=?', [{a:97, b:98}, 1])`

This errors `​​You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? WHERE id = ?' at line 1​​`

Works fine if i use `db.query`
The `db.format` it generates looks fine

how does `SET ?` work? is that not supposed to be used with prepared statements?

**Comment by sidorares** [comment]
Everything that works with PREPARE command in cli should work in execute. Likely "set ?" is not allowed here

**Comment by aikar** [comment]
I think you need ?? here for column name place holders

SET ?? = ? WHERE id = ?

**Comment by sidorares** [comment]
no, ?? is not valid syntax for prepare, see https://dev.mysql.com/doc/refman/5.7/en/sql-syntax-prepared-statements.html

**Comment by aikar** [comment]
I thought that was handled at the client level, is that valid syntax for query as in the mysql server actually supports it?

**Comment by sidorares** [comment]
@aikar `.execute()` only does "named placeholder to unnamed" client side transform

**Comment by scull7** [comment]
It seems that this also fails:

```javascript
db.execute({
  sql: 'INSERT INTO test SET ?',
  values: [ { foo: "bar", baz: "buzz" } ],
  namedParameters: false,
}, console.log)
```
>ER_PARSE_ERROR (1064) - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1

however, this succeeds:
```javascript
db.query({
  sql: 'INSERT INTO test SET ?',
  values: [ { foo: "bar", baz: "buzz" } ],
  namedParameters: false,
}, console.log)
```

**Comment by sidorares** [comment]
@scull7 this is expected - see explanation in #742 . I guess we need good "Difference between cliend-side and server side parameters substitution" article. Not sure if anything can be done at api level, probably docs only issue

**Comment by sidorares** [comment]
I'll close this issue for now as it's basically duplicate of #742 

Maybe we should treat prepare and execute time errors slightly differently and have some pointer to `PREPARE` documentation - what is allowed in PS and what not

**Comment by scull7** [comment]
@sidorares Thank you for the explanation.
