### ISSUE TITLE
Serialize JSON like objects passed to `execute` as `key = 'val'` pairs?

### ISSUE THREAD

**Issue by maximedupre** [sidorares/node-mysql2#742]
await ctx.db.execute('INSERT INTO user SET ?', [{ email: body.email, password: hash }])

This throws an error, as JSON like objects are simply serialized as a JSON string. Is there a way to serialize as `key = 'val'` pairs? If not, what is the reason why?

https://github.com/mysqljs/mysql serializes JSON like objects like:

> Objects are turned into key = 'val' pairs for each enumerable property on the object. If the property's value is a function, it is skipped; if the property's value is an object, toString() is called on it and the returned value is used.

**Comment by sidorares** [comment]
> If not, what is the reason why?

No. "Execute" is for prepared statements, where code ("sql") and data separated. `key = 'val'` part is breaking this - it requires modification of sql query you want to execute.

If you really need this, you can use `.query()`. With prepared statement each placeholder must map 1:1 to input data (In case of mysql JSON type it can be an object, but it'll be serialized to string before transmitting - this is what you observe. We could add some warning if types are inherently incompatible (and we know in advance, which is usually but not always possible - we get this metadata from PREPARE)

**Comment by bigyonk** [comment]
I'm experiencing a similar problem:

```
  async addNewThing(req, res, next) {

    let data = req.body

    const queryString = 'INSERT INTO table SET ?'
    try {
      await db.execute(queryString, [data])
      res.status(201).json({
        message: 'Record inserted',
        data
      })
    } catch (error) {
      next(error)
    }
  }
```

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1


If i'm understanding the original answer correctly, you cannot use .execute with SET  if the parameter is an object?

**Comment by sidorares** [comment]
> If I'm understanding the original answer correctly, you cannot use .execute() with SET if the parameter is an object?

that's correct, if you can't `PREPARE` what's is in the execute query as is ( without any substitutions) you can't use it.

**Comment by bigyonk** [comment]
This is not exclusive to node-mysql2, but a general limitation of the MySQL language?
Thank you.

**Comment by sidorares** [comment]
yes, see more at https://dev.mysql.com/doc/refman/8.0/en/sql-syntax-prepared-statements.html#idm139827096954560

**Comment by bigyonk** [comment]
Found issue https://github.com/sidorares/node-mysql2/issues/553 which is more specific to my question, so I'll continue there.
