### ISSUE TITLE
Returning data from results when using JSON functions

### ISSUE THREAD

**Issue by feedbakr** [sidorares/node-mysql2#746]
Using node mysql2 I have a query on a JSON type column, it looks like this:
`conn.execute('SELECT json_extract(social_acct, "$.key2") from users where id = 3')`

The result is something that looks like this:
`[ [ BinaryRow {
  'json_extract(social_acct, "$.key2")': { social: { FB: [Object], twitter: [Object] } } } ...] ]`    

result[0][0] gives me an object that looks like this:
 `{ 'json_extract(social_acct, "$.key2")': { social: { FB: [Object], twitter: [Object] } } }
    }`

The return value for the query should be: `{ social: { FB: [Object], twitter: [Object] }`
But I can only retrieve it if I enter this key:  `json_extract(social_acct, "$.key2")`
Entering the query as the object key to get the resultant value does not seem correct to me.

How do you get the value out of results without having to enter the query  as the key?

**Comment by sidorares** [comment]
few options here;
1) set field in the query: `conn.execute('SELECT json_extract(social_acct, "$.key2") as social from users where id = 3')`
2) don't use field names at all in result:
`conn.execute({sql: 'SELECT json_extract(social_acct, "$.key2") from users where id = 3')`, rowsAsArray: true})`

By default field name is used as key in result row object, and `json_extract(social_acct, "$.key2")` is what mysql server reports as a name
