### ISSUE TITLE
reconnect issue

### ISSUE THREAD

**Issue by devguo** [sidorares/node-mysql2#749]
Thanks for the great library. 
I am working on an application using this library.  The app need to keep connection alive, so it can execute query in sequence.  But stuck in reconnect logic. I  search the issue list and can't find a solution.  Should I try to use connection pool ? if using pool, how can execute sql with sequence?

attache some code.

```js
    async start(){
            this.connection = await mysql.createConnection(this.cfg);
            this.connection.on('error',(err)=>{
                console.log("start",JSON.stringify(err));
            })
    }

    let mgr = new MysqlMgr(cfg);
    await mgr.start();

    const conn = mgr.connection;

    const sql = "select uid from userbase1 where uname = ? and businessid = ?;"
    try {
        const [results, fields] = await conn.execute(sql,["aaa","aa"]);
        if (results.length > 0) {
            return results[0].uid;
        }
        else if (results.length == 0) {
            return 0;
        }
    }
    catch (err) {
        console.log(err.fatal);
        console.log("execute sql error.",JSON.stringify(err));
    }
```

If restart Mysql, on（‘error’） triggered, and can write some reconnect logic there, but when execute query, and catch exception,  I've no idea whether to reconnect, err.fatal  is not work.

**Comment by sidorares** [comment]
Hi @devguo , yes, pool almost always preferred

Not sure I understand question `how can execute sql with sequence`

If this example query2 is executed only query1 is finished:

```js
   const pool = mysql.createPool(cfg);
   const [result1] = await pool.execute(query1);
   const [result2] = await pool.execute(query2);
```

**Comment by devguo** [comment]
Great, thanks for the help.  I misunderstood the way await work.
