### ISSUE TITLE
How do you print MySQL query statements with mysql2/promise?

### ISSUE THREAD

**Issue by finferflu** [sidorares/node-mysql2#754]
I can see that `node-mysql` offers the ability to print the statement by providing `query.sql`, however when I try that with native promises, it returns `undefined`, e.g.:

```javascript
connection.query('SELECT * FROM mytable WHERE id = 1')
.then(query => {
  console.log(query.sql)
})
```

returns `undefined`. Am I missing anything?

Thank you!

**Comment by sidorares** [comment]
at the moment this is not possible, promise api only gives you rows + fields
We could potentially return Query object as well so you would be able to do something like this

```js
   const [rows, fields, query] = await conn.query('select ? as test', [123]);
   console.log(query.sql);
```

I think right now recommended way would be create string first and later use it:

```js
  const sql = conn.format('select 1 as test', [123]);
  console.log(sql)
  const [rows] = await conn.query(sql);
```

**Comment by Hookyns** [comment]
@sidorares 
That's why I made this PR #555 a year ago.
[This](https://github.com/sidorares/node-mysql2/pull/555#issuecomment-297055472) comment (EDIT 4 part) is exactly what you're talking about. Any plans to implement?

**Comment by Api-gateway-crippling** [comment]
I cracked it—answer in hand https://nodejser.space/questions/leveraging-mysql-with-promises-in-a-nodejs-environment-is-a-game

**Comment by meszaros-lajos-gyorgy** [comment]
> I think right now recommended way would be create string first and later use it:
> 
>   const sql = conn.format('select 1 as test', [123]);
>   console.log(sql)
>   const [rows] = await conn.query(sql);

For anyone having a hard time debugging things as well here's a little info on the `.format()` method: it does not support `namedPlaceholders: true` setting, so you have to rely on `?` for variables in the SQL and an array of values as the 2nd parameter for `.format()`
