### ISSUE TITLE
A little feature of promise module

### ISSUE THREAD

**Issue by zumm** [sidorares/node-mysql2#758]
What about exporting of classes PromiseConnection, PromisePoolConnection and PromisePool from mysql2/promise module? It may be usefull if user needs a extending these classes.

```
module.exports.PromiseConnection = PromiseConnection;
module.exports.PromisePoolConnection = PromisePoolConnection;
module.exports.PromisePool = PromisePool;
```

**Comment by sidorares** [comment]
yes, why not. PR welcome :) ( ideally with test, otherwise it's easy to break feature that is rarely used )

**Comment by mdierolf** [comment]
This was actually implemented in pull request 810, as it was necessary to be able to wrap Connections/Pools with promises:
https://github.com/sidorares/node-mysql2/pull/810
