### ISSUE TITLE
Error: Incorrect arguments to mysqld_stmt_execute when trying to SET with .execute()

### ISSUE THREAD

**Issue by PaulKempf** [sidorares/node-mysql2#763]
Hi everyone,
Trying to wrap my head around async here. I've extracted my connection code using the following : 

```js
const mysql   = require('mysql2/promise');
const config  = require("./config");

/*
 * @sqlConnection
 * Creates the connection, makes the query and close it to avoid concurrency conflicts.
 */
var sqlConnection = async function sqlConnection(sql, values, next) {
    // It means that the values hasnt been passed
    if (arguments.length === 2) {
        next = values;
        values = null;
    }
    const connection = await mysql.createConnection(config.db);
    /*connection.connect(function(err) {
        if (err !== null) {
            console.log("[MYSQL] Error connecting to mysql:" + err+'\n');
        }
    });*/
    const [rows, fields] = await connection.execute(sql, values, function(err) {
      if (err) {
          throw err;
      }
      // Execute the callback
      next.apply(this, arguments);
    });
}
module.exports = sqlConnection;
```

I'm trying to insert into my database using the following : 

`var db_results = db_connection('INSERT INTO organisation (name, social, address, country, zip) VALUES (?,?,?,?,?)',
    {name: input.name, social: input.social, address: input.address, country: input.country, zip: input.zip},
    function (error, rows) {
      console.log(query.sql);
    });`

I've tried quite a few things, using SET, changing the number of ?, naming or not the query, yet I keep getting 

> Error: Incorrect arguments to mysqld_stmt_execute

Any insight ?

**Comment by sidorares** [comment]
I think this is unrelated to main question, but why are you using await and callback together?

**Comment by sidorares** [comment]
re main question: you must use one simple type value per ?:

```js
db_connection('INSERT INTO organisation (name, social, address, country, zip) VALUES (?,?,?,?,?)', [input.name, input.social, input.address, input.country, input.zip], function (error, rows) { 
   console.log(error, rows); 
});
```

**Comment by sidorares** [comment]
@PaulKempf see also explanation in #742

**Comment by PaulKempf** [comment]
Thanks, it doesn't throw the error anymore.
Regarding the callback, I'm most likely misunderstanding how await works. Still quite new to async calls (and it may explain why although it doesn't throw an error, my query doesn't seem to execute)

**Comment by sidorares** [comment]
> my query doesn't seem to execute

Is the record inserted with `INSERT INTO organisation ...` call? How do you check if it's executed?

**Comment by PaulKempf** [comment]
Well my bad, it actually is inserted in the DB.  It just doesn't seem to execute the `console.log(error, rows); ` part.

**Comment by sidorares** [comment]
closing for now. You need to review your code and use callback or async version appropriately, async version does not accept callbacks
