### ISSUE TITLE
tests hang until connection is ended

### ISSUE THREAD

**Issue by Wardevour** [sidorares/node-mysql2#767]
I want to be sure this is supposed to happen. If I write a [simple test](https://github.com/Wardevour/node-mysql2-tests/blob/master/test/test2.js) to run a query and run the test with mocha, the node process hangs until forcefully terminated. If I [end the connection after the test](https://github.com/Wardevour/node-mysql2-tests/blob/master/test/test1.js), the process exits just fine.

I thought that I didn't have to end a connection manually. Am I mistaken?

My test also hangs when I use a remote mysql server, even if I end the connection. I'm guessing this is unrelated and stems from a problem with the remote server. Any idea why the query works and the test passes but I am unable to end the connection and exit the process?

**Comment by sidorares** [comment]
> Am I mistaken?

yes.

node keeps process running as long as there are active handles in event loop such as open network sockets, files or timers ( you can see hood debug info on that using https://www.npmjs.com/package/why-is-node-running package

As alternative to closing connection you can just unref it - see https://nodejs.org/dist/latest-v9.x/docs/api/net.html#net_socket_unref

```js
var db = mysql.createConnection(config);
// ... later
db.stream.unref();
```

in case of mocha test i'd recommend closing connection using `.end()`

( also see my answer on SO on same topic - https://stackoverflow.com/questions/17960452/how-can-i-get-a-list-of-callbacks-in-the-node-work-queue-or-why-wont-node-ex/17960793#17960793 )

**Comment by Wardevour** [comment]
Any idea why I can't end the connection for a different server? I am pulling my hair out trying to figure out why the node process hangs during the test that ends the connection, but only when I use the production database.

**Comment by sidorares** [comment]
Try using `connection.close()`

`conn.end()` only sends `COM_QUIT` command to server, which normally should result in server closing tcp connection. If for some reason this does not happen client will keep waiting. Also `conn.end()` adds close command at the end of the command queue, and it only sent to server after all previous commands completed ( `conn.query('select sleep(1)'; conn.end()` closes connection in ~ 1 second )

`conn.close()` on the other hand immediately closes tcp connection and all current commands in te queue get error callback called

**Comment by Wardevour** [comment]
@sidorares thank you for your help. I tried `connection.close()` and got the same results. My local mysql server has no issues, but when I try the remote server the process still hangs. There must be something up with the IBM provided mysql server we're using.

**Comment by sidorares** [comment]
try to check if you can connect at all. Do you see results from some queries execution?

**Comment by Wardevour** [comment]
I tried [a test that creates a temporary table](https://github.com/Wardevour/node-mysql2-tests/blob/master/test/test3.js), using the remote server, and it passes. However, the process still hangs after the test is over.
