### ISSUE TITLE
SP returning multiple result set, only first result set has data.

### ISSUE THREAD

**Issue by gochinj** [sidorares/node-mysql2#769]
When running a stored procedure that returns multiple result sets, only the first result set returns data when using mysql2.  But, when running the stored procedure in the MySql workbench multiple result sets return data.

I have tried this with both mysql and mysql2 node modules.

What I am trying to do is pretty strait forward and your documentation says this is a supported operation.

Here is the results I get back from the call to connection.query. Result sets 1, 3, 5, and 6 should have data in them, but only result set 1 consistently returns data.

```js
[ [ TextRow {
      id: 3,
      title: 'Affidavit',
      path: '/hdocs/nationwide/Affidavit.html',
      group: 'Nationwide',
      DateCreated: 2017-06-09T00:46:06.000Z,
      ModifiedDate: 2017-07-19T19:59:36.000Z,
      CreatedBy: 1,
      ModifiedBy: 1,
      sop_document_template_type_id: 1 } ],
  [],
  [],
  [],
  [],
  [],
  ResultSetHeader {
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    info: '',
    serverStatus: 34,
    warningStatus: 0 } ]
```

**Comment by sidorares** [comment]
thanks for report @gochinj .

I'll need to replicate this somehow to debug. Are you able to prepare code that will create table, SP and insert data (just enough to see issue) - preferably all in one single file?

**Comment by sidorares** [comment]
Also - do you see same behaviour across mysql and mysql2?

**Comment by gochinj** [comment]
I do see the same issue in mysql and mysql2.  I tried mysql2 to see if it resolved the problem.  I will work on putting together a sample that can emulate what I am trying to do from the database.  But, here is the actually stored procedure.  Nothing special going on except that I am using JSON as my input parameters to the procedure. 

To be honest I am suspect of my returning those variable assignments without an "AS".  I will try a test where I use "AS" for them.

```sql
CREATE DEFINER=`root`@`%` PROCEDURE `sp_sop_new_hdoc`(indata json)
BEGIN
    DECLARE sid int;
    DECLARE tdid int;

    SET sid =  IF(IS_NULL_PROPERTY(indata, '$.sid'), null, JSON_EXTRACT(indata, '$.sic'));
    SET tdid =  IF(IS_NULL_PROPERTY(indata, '$.tdid'), null, JSON_EXTRACT(indata, '$.tdid'));

    SELECT * FROM sop_document_templates WHERE id = tdid; -- get hdoc template

    SELECT *, @cid  := sop_case_id,  @aid := assignee_id, @sccid := sop_company_contact_id, @ccid := sop_company_contact_id  FROM vw_service_summary WHERE id = sid;  -- get case id and company id
    
    SELECT * FROM vw_case_people WHERE sop_case_id = @cid; -- case people
    
    SELECT *, @coid := JSON_EXTRACT(`metadata`, '$.sop_company_id')  FROM hsl_users WHERE id = @cid; -- get server company id
    
    SELECT * FROM vw_company_contacts WHERE sop_company_contact_id = @ccid; -- requester
    
    SELECT * FROM vw_company_primary WHERE sop_company_id = @cid; -- primary contact
    
    
END
```

**Comment by sidorares** [comment]
> I do see the same issue in mysql and mysql2

Unless we have identical bugs in mysql and mysql2 likely it's a problem with data or SP. If you provide code to replicate happy to assist with debugging

**Comment by sidorares** [comment]
closing this issue for now, feel free to reopen if you think there is still incorrect driver behaviour
