### ISSUE TITLE
Docker mysql:latest keep mysql2 to authenticate with root user 

### ISSUE THREAD

**Issue by pierre-aurele-martin** [sidorares/node-mysql2#777]
Hello,

I've noticed that this [commit](https://github.com/docker-library/mysql/commit/2e4f2224f31e101d07c1e6a7c0da8245fde725c9?_pjax=%23js-repo-pjax-container)  on docker mysql image made all my tests failed :

```
-			SET PASSWORD FOR 'root'@'localhost'=PASSWORD('${MYSQL_ROOT_PASSWORD}') ;
+			ALTER USER 'root'@'localhost' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' ;

```
I was using Gitlab CI with *mysql:latest* and got this error : 

`Client does not support authentication protocol requested by server; consider upgrading MySQL client`

Everything ok with older version of mysql image. This happened with mysql2:1.5.3 (latest)

Might help other people understanding why CI tests are suddenly failing :)

**Comment by sidorares** [comment]
can you check what auth method is used for that user?

Also what is the mysql server version when you pull mysql:latest ?

**Comment by sidorares** [comment]
> Ver 8.0.11

likely it's changes in mysql 8

from https://github.com/mysqljs/mysql/pull/1962 :

> First of all, MySQL 8.0.4 introduces a new default authentication plugin - caching_sha2_pasword. This is a breaking change and it will affect the entire handshake process, which currently does not work for new user accounts created using this plugin or, most importantly, not using a specific plugin at all (since it's now the default option). User accounts created with the mysql_native_password plugin will still work though.

If you can convert your user to `mysql_native_password` that might be the easiest way, otherwise you'll need to wait until https://github.com/mysqljs/mysql/pull/1962 lands in mysqljs/mysql or somebody add implementation of `caching_sha2_pasword` here

**Comment by pierre-aurele-martin** [comment]
Ok, thanks :)

**Comment by ezk2410** [comment]
@sidorares It seems like the mysqljs/mysql#1962 still open and no resolution has been reached yet. Any updates ?
