### ISSUE TITLE
README needs a tiny fix.

### ISSUE THREAD

**Issue by itayronen** [sidorares/node-mysql2#786]
At the README file, in the promise section, in the "alternative promise library" section:
// query database
const [rows, fields] =  connection.execute('SELECT * FROM `table` WHERE `name` = ? AND `age` > ?', ['Morty', 14]);

'await' is missing. There are even 2 spaces waiting to hug it. Should be:
const [rows, fields] = await connection.execute('SELECT * FROM `table` WHERE `name` = ? AND `age` > ?', ['Morty', 14]);

**Comment by sidorares** [comment]
good catch @itayronen 
can you send us PR with the fix? ( if not no problem, I can change it myself a bit later )

**Comment by itayronen** [comment]
Sorry for the late response, my notification settings were off.
I Might want to add an equivalent for mysql.raw() anyway.
I couldn't find a contribution guidelines. Are there any? Or can I code as I see fit?

**Comment by itayronen** [comment]
#800

**Comment by sidorares** [comment]
Thanks, merged
