### ISSUE TITLE
support key value object place holder

### ISSUE THREAD

**Issue by muayyad-alsadi** [sidorares/node-mysql2#796]
please support something like

```
p.execute("INSERT INTO chat_alert_item SET ?", {col1: value1, col2: value2});
```

you can see similar example in the documentation of [npm mysql](https://www.npmjs.com/package/mysql)

```
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'
```

currently in your implementation it gives

```> TypeError: options.values.forEach is not a function
    at PoolConnection.execute (/usr/src/app/node_modules/mysql2/lib/connection.js:688:20)
    at /usr/src/app/node_modules/mysql2/lib/pool.js:180:29
    at /usr/src/app/node_modules/mysql2/lib/pool.js:36:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by sidorares** [comment]
please read this comments first: https://github.com/sidorares/node-mysql2/issues/476#issuecomment-264342349 and https://github.com/sidorares/node-mysql2/issues/742#issuecomment-369807007

Few options here for you:
1) just use `.query()`
2) use format + execute: `p.execute(mysql.format("INSERT INTO chat_alert_item SET ?", {col1: value1, col2: value2}))`
3) expand manually ( preferred way, maybe we should add helper to automate this?) 

```
p.execute('INSERT INTO chat_alert_item SET `col1` = ?, `col2` = ?
```

**Comment by muayyad-alsadi** [comment]
thank you for your suggestion

but from the readme of this project 

> MySQL2 project is a continuation of MySQL-Native... and api changed to match popular mysqljs/mysql.
> MySQL2 is mostly API compatible with Node MySQL. You should check their API documentation to see all available API options.
> If you find any incompatibility with Node MySQL, *Please report via Issue tracker*. We will fix reported incompatibility on priority basis.

this means if it works in mysqljs/mysql it should work here.
the code snippet is from their readme, it's not only a valid use case, but it's by the book.

> just use .query()

isn't `.query` is for select, while `.execute` for updates/insert?

> use format + execute: p.execute(mysql.format("INSERT INTO chat_alert_item SET ?", {col1: value1, col2: value2}))

then it `p.execute()` should use `mysql.format` internally

> expand manually ( preferred way, maybe we should add helper to automate this?)

yes, this is what I did

```
let cols = Object.keys(row).join('=?, ')+'=?';
pool.execute("INSERT INTO chat_alert_item SET "+cols, Object.values(row));
```

**Comment by sidorares** [comment]
> this means if it works in mysqljs/mysql it should work here. the code snippet is from their readme, it's not only a valid use case, but it's by the book.

mysqljs/mysql does not support prepared statements

> isn't .query is for select, while .execute for updates/insert?

No, this is not correct. You can use both for selects / updates. `.query()` implements so called 'text protocol' - you send your query as text together with parameters and receive results back pretty much as text.

`.execute()` is short for prepare + execute. "Prepare" sends sql as text and returns prepared statement id. "Execute" serialises parameters using binary protocol and serialises results back.

**Comment by yvele** [comment]
> use format + execute: `p.execute(mysql.format("INSERT INTO chat_alert_item SET ?", {col1: value1, col2: value2}))`

Hum.. yeah but `TypeError: _promise2.default.format is not a function`

I had to do `import { format } from "mysql2";`

**Comment by midnightcodr** [comment]
@sidorares would there be a vulnerability for sql injection if I use:
```
p.query("INSERT INTO chat_alert_item SET ?", {col1: value1, col2: value2});
```
assuming value1 and value2 are coming from user input.

**Comment by sidorares** [comment]
should be safe, see https://github.com/sidorares/node-mysql2/issues/553#issuecomment-437221838
