### ISSUE TITLE
mysql.raw() equivalent?

### ISSUE THREAD

**Issue by itayronen** [sidorares/node-mysql2#801]
Is there an equivalent for mysql.raw() function?

node-mysql readme:
```
var CURRENT_TIMESTAMP = mysql.raw('CURRENT_TIMESTAMP()');
var sql = mysql.format('UPDATE posts SET modified = ? WHERE id = ?', [CURRENT_TIMESTAMP, 42]);
console.log(sql); // UPDATE posts SET modified = CURRENT_TIMESTAMP() WHERE id = 42
```

**Comment by sidorares** [comment]
I don't think it's exported from main index.js ( feel free to add it! )
Main functionality resides in `sqlstring` module that both mysqljs/mysl and mysql2 share

You can do it right now manually like this (haven't tried but expect this to work):

```js
const sqlstring = require('sqlstring');
const CURRENT_TIMESTAMP = sqlstring.raw('CURRENT_TIMESTAMP()');

// this should probably also work for promise wrapper as well. Won't work in .execute() as parameters there are treated differently
mysql.query('UPDATE posts SET modified = ? WHERE id = ?', [CURRENT_TIMESTAMP, 42], callback);
```

this is commit in mysqljs/mysql where `.raw()` was added:https://github.com/mysqljs/mysql/commit/55c20da35969bb3102afea136e36e049142b506b

**Comment by itayronen** [comment]
Works perfectly.
It seems the types at `@types/sqlstring` is not aware of the raw() function.
I'm working with typescript but ignored the types and it worked.

Thank you :)
