### ISSUE TITLE
See actual produced query when debugging

### ISSUE THREAD

**Issue by ukasa** [sidorares/node-mysql2#806]
I have found this feature in https://github.com/mysqljs/mysql. We can do like this:

```js
...

const query = connection.query(query, params, callback);

console.log(query.sql); // e.g. SELECT `username`, `email` FROM `users` WHERE id = 1

...
```

Anyway, has node-mysql2 already support this?

**Comment by sidorares** [comment]
yes, this is supported. `connection.query()` returns instance of `Query` and it sets sql to contain string that is actually sent to server after all placeholders expanded ( see https://github.com/sidorares/node-mysql2/blob/224c74de8184f78c540f343c432c0f37986c8aea/lib/commands/query.js#L18 )

**Comment by YZirkind** [comment]
Is it possible to access this when using Promises?

**Comment by sidorares** [comment]
@YZirkind no, at the moment not possible directly. You need to do it in 2 steps - format + raw query in order to log generated sql
