### ISSUE TITLE
Unhandled Array as Prepared Statement Parameter

### ISSUE THREAD

**Issue by ukasa** [sidorares/node-mysql2#807]
I want to pass an array to a prepared statement, like this:

```
// I am using async await feature
const subjectIds = [1, 2, 3];

const query1 = 'SELECT * FROM subjects WHERE id IN (?)';
const query2 = 'SELECT * FROM subjects WHERE id IN (1,2,3)';

const [rows1] = await database.execute(query1, [subjectIds]);
const [rows2] = await database.query(query2);

console.log(rows1.length); // 0
console.log(rows2.length); // As expected :)
```

Any solution?

**Comment by sidorares** [comment]
duplicate of #742

see suggested solutions here https://github.com/sidorares/node-mysql2/issues/742#issuecomment-369807007 and here https://github.com/sidorares/node-mysql2/issues/796#issuecomment-397253582

**Comment by ukasa** [comment]
Thanks, dude. I think I prefer use `.query' instead. Anyway, can you give me suggestion to prevent sql injection when using `.query` method? (I really hop

**Comment by sidorares** [comment]
this should be safe:

```js
const query1 = 'SELECT * FROM subjects WHERE id IN (?)';
const [rows1] = await database.query(query1, [subjectIds]);
```

This is client side substitution of values ( js code makes 'SELECT * FROM subjects WHERE id IN (1,2,3)' out of your query and `[1, 2, 3]` array ) but it does all escaping
