### ISSUE TITLE
Erro in Promise Wrapper section example in README.md 

### ISSUE THREAD

**Issue by realphi** [sidorares/node-mysql2#816]
I copy and pasted the example below in a plain js file in project and when I run the file with node I get error "TypeError: pool.promise is not a function".

mysql2 version installed with npm 1.5.3
node 8.11.2
mysql 5.7.20

MySQL2 also exposes a .promise() function on Pools, so you can create a promise/non-promise connections from the same pool
```js
async function main() {
  // get the client
  const mysql = require('mysql2');
  // create the pool
  const pool = mysql.createPool({host:'localhost', user: 'root', database: 'test'});
  // now get a Promise wrapped instance of that pool
  const promisePool = pool.promise();
  // query database using promises
  const [rows,fields] = await promisePool.query("SELECT 1");
```

**Comment by realphi** [comment]
I've already tested mysql2 with promise and connecting and querying works with no problems. But I couldn't get pool with promise to work.

**Comment by realphi** [comment]
I updated the issue to reflect problem more clearly.

**Comment by sidorares** [comment]
the section in documentation you mentioned describes functionality that has not been published yet to npm

**Comment by realphi** [comment]
Oh thanks!
