### ISSUE TITLE
Unable to execute more than a query

### ISSUE THREAD

**Issue by mvaello** [sidorares/node-mysql2#832]
I'm trying to create two tables in the same execution, but looks like that it does only get just a single query for each execution. Is there any alternative for do that?

In my case, I'm trying to insert two tables with two drop tables before each.

Thanks.

**Comment by sidorares** [comment]
Can you show your code?

If you are using `.execute()` this is not possible:

> The text must represent a single statement, not multiple statements. Within the statement, ? characters can be used as parameter markers to indicate where data values are to be bound to the query later when you execute it. The ? characters should not be enclosed within quotation marks, even if you intend to bind them to string values. Parameter markers can be used only where data values should appear, not for SQL keywords, identifiers, and so forth.

https://dev.mysql.com/doc/refman/8.0/en/prepare.html

**Comment by mvaello** [comment]
Unfortunaltely I cannot show the code, but I can craft a example. 

// MyCreateTables.sql

´´´ sql
CREATE TABLE `dog` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(64) NOT NULL DEFAULT '', 
    PRIMARY KEY (`id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `cat` (
    `id` int(11) unsigned NOT NULL,
    `name` varchar(64) NOT NULL DEFAULT ''
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
´´´
All the file content above is passed to the query function:

connection.write.query(mySqlQuery)

Any clue or alternative?

Thanks.

**Comment by PolymathWhiz** [comment]
How do you expect it to be solved when you can't show the full code?
