### ISSUE TITLE
pool.releaseConnection not working as expected

### ISSUE THREAD

**Issue by orlleite** [sidorares/node-mysql2#835]
I have:

	require('dotenv').config();

	const mysql = require('mysql2');

	async function test()
	{
		var poolDB = mysql.createPool({
			host: process.env.DB_HOSTNAME,
			port: process.env.DB_PORT ? process.env.DB_PORT : 3306,
			user: process.env.DB_USER,
			password: process.env.DB_PASSWORD,
			database: process.env.DB_DATABASE,
			waitForConnections: true,
			connectionLimit: 4,
			queueLimit: 0
		});

		for( var i = 0; i < 5; i++ )
		{
			const conn = await poolDB.promise().getConnection();
			var [rows, fields] = await conn.execute("SELECT * FROM services");
			console.log( rows[0]['id'] );
			poolDB.releaseConnection( conn );
		}
		
		console.log( "finished" );
	}

	test();

I thought it should print 5 times the `row[0][id]` and at the end `finished`. But it's only running 4 times/connections. 

So, how should I let the connection, I'm using, freed for the next `getConnection` call?

**Comment by sidorares** [comment]
to me looks like the problem is because you mixing promise / non-promise versions of pool. We should probably add warning when someone tries to release connection pool is not aware

Try to change code to use `.conn.release()` or use `pool.execute()` 

```js
// 1
const conn = await poolDB.promise().getConnection();
var [rows, fields] = await conn.execute("SELECT * FROM services");
console.log( rows[0]['id'] );
conn.release();

// 2
const pool = await poolDB.promise();
var [rows, fields] = await pool.execute("SELECT * FROM services");
```

**Comment by orlleite** [comment]
Thanks, it's working fine now.

**Comment by Dadibom** [comment]
Spent hours troubleshooting this... a warning would be amazing but ideally, `pool` should be able to release `pool.promise().getConnection()`
