### ISSUE TITLE
Gulp + MySQL2 = Remote server crash (out of memory)

### ISSUE THREAD

**Issue by phimuskapsi** [sidorares/node-mysql2#839]
I have a need to run mysql queries within gulp to check certain fields in a table. I currently connect to a development server via ssh tunnel, which is opened via terminal so that my host is set to 'localhost'. When I execute a connection attempt, the tunnel crashes with: ### channel 4: open failed: connect failed: Connection refused

Then the server process crashes with an out of memory error. This is basically how we run an instance of GraphQL locally for testing, so it may be something specific to gulp (I'll be opening an issue there as well). 

Gulp Code:
![screen shot 2018-08-21 at 2 51 40 pm](https://user-images.githubusercontent.com/394826/44422642-ba388380-a551-11e8-9967-119646a5d99f.png)

If anyone has any insights I'd be much obliged.

**Comment by sidorares** [comment]
> Then the server process crashes with an out of memory error

what is server process? You mean mysql server?

**Comment by phimuskapsi** [comment]
Yeah. Completely crashes mysql server running on Ubuntu. Execute the command, the ssh tunnel crashes with a channel3/4 error, mysql runs out of memory. Takes 2-3 seconds from execution.

**Comment by sidorares** [comment]
so few options I can recommend to try:

1) instead of ssh cli tunnel use node-ssh2, see example here: https://stackoverflow.com/a/30669454/705115  https://stackoverflow.com/a/36608307/705115

2) try with mysqljs/mysql driver

3) try to upgrade mysql server ( I'd recommend this anyway, no server should crash even when clients send faulty data )

**Comment by phimuskapsi** [comment]
Will do! I'll give it a shot tomorrow and report back. Thanks for the prompt response!

**Comment by phimuskapsi** [comment]
This worked! Thank you very much! 

Might want to consider adding a note to docs, but either way, thanks again! You are a lifesaver!
