### ISSUE TITLE
Too many connections with connection pool

### ISSUE THREAD

**Issue by PolymathWhiz** [sidorares/node-mysql2#840]
I'm getting too many connections error when I make exactly 30 insert queries on my node app. 

I have a connect.js file like this:

```js
async function connection() {
  try {
    const mysql = require('mysql2');

    const pool = mysql.createPool({
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DATABASE,
      connectionLimit: 10,
      waitForConnections: true,
      queueLimit: 0
    });

    const promisePool = pool.promise();

    return promisePool;
  } catch (error) {
    return console.log(`Could not connect - ${error}`);
  }
}

module.exports = {
  connection
};
```

and another file that I import the `connect.js`like this:

`let connection = require('connect');`

`let db = await connection();`

then sql queries with `db.execute();` follows.

Please help. Thanks

**Comment by sidorares** [comment]
you are creating new pool each time instead of borrowing connection from the same pool. Change to something like this:

```js
function createPool() {
  try {
    const mysql = require('mysql2');

    const pool = mysql.createPool({
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DATABASE,
      connectionLimit: 10,
      waitForConnections: true,
      queueLimit: 0
    });

    const promisePool = pool.promise();

    return promisePool;
  } catch (error) {
    return console.log(`Could not connect - ${error}`);
  }
}

const pool = createPool();

module.exports = {
  connection: async () => pool.getConnection()
  execute: (...params) => pool.execute(...params)
};
```

```
const db = require('./db');
const conn = await db.connection();
const results = conn.execute('select 1+1');
conn.release();

// or
const results = db.execute('select 1 + 1');
```

**Comment by PolymathWhiz** [comment]
Thanks so much! It works with the second `result = db.execute('select 1 + 1');`. Nice work!

**Comment by rildomar** [comment]
`module.exports = {
  connection: async () => pool.getConnection()
  execute: (...params) => pool.execute(...params)
};` doesnt work for me..

if i export only pool `const pool = createPool();`, works fine.. however, will I have to use this on every page that I will use connection to?

**Comment by PolymathWhiz** [comment]
`function connection() {
  try {
    const mysql = require('mysql2');

    const pool = mysql.createPool({
      host: process.env.DB_HOST,
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      database: process.env.DATABASE,
      timezone: 'utc',
      connectionLimit: 10,
      waitForConnections: true,
      queueLimit: 0
    });

    const promisePool = pool.promise();

    return promisePool;
  } catch (error) {
    return console.log(`Could not connect - ${error}`);
  }
}

const pool = connection();

module.exports = {
  connection: async () => pool.getConnection(),
  execute: (...params) => pool.execute(...params)
};`


# In another file

`const db = require('../../../../config/db');`

# Then to run a query

const [query] = await db.execute(/*query here*/);

**Comment by aldovincenti** [comment]
@sidorares this example should be included in the documentation.

**Comment by domneedham** [comment]
How would I go about doing something like the following ? 

`const [users] = await db.execute("SELECT * FROM users where full_name LIKE %?%", [req.params.id]);`

**Comment by PolymathWhiz** [comment]
@domneedham 

`const id = `%${req.params.id}%`;`
`const [users] = await db.execute("SELECT * FROM users where full_name LIKE ?", [id]);`

**Comment by PolymathWhiz** [comment]
@domneedham 

`const id = "%" + req.params.id +"%";` // you can change this to backticks style concat

`const [users] = await db.execute("SELECT * FROM users where full_name LIKE ?", [id]);`

**Comment by Kennytian** [comment]
`SET GLOBAL wait_timeout = 60; `

run this command in mysql client command terminal, the timeout unit is seconds

**Comment by craigcosmo** [comment]
> `SET GLOBAL wait_timeout = 60; `
> 
> run this command in mysql client command terminal, the timeout unit is seconds

what does this do ?

**Comment by craigcosmo** [comment]
> ```js
> function createPool() {
>   try {
>     const mysql = require('mysql2');
> 
>     const pool = mysql.createPool({
>       host: process.env.DB_HOST,
>       user: process.env.DB_USER,
>       password: process.env.DB_PASSWORD,
>       database: process.env.DATABASE,
>       connectionLimit: 10,
>       waitForConnections: true,
>       queueLimit: 0
>     });
> 
>     const promisePool = pool.promise();
> 
>     return promisePool;
>   } catch (error) {
>     return console.log(`Could not connect - ${error}`);
>   }
> }
> 
> const pool = createPool();
> 
> module.exports = {
>   connection: async () => pool.getConnection()
>   execute: (...params) => pool.execute(...params)
> };
> ```

what supposed to be "./db"?

**Comment by reeZee3U** [comment]
This code gives me sql syntax error:
```
! async function() {
  var sql = {
    title: 'title',
    url: 'url',
    content: 'content'
  };
  const [query] = await db.execute("INSERT INTO content SET ?",[sql]);
  console.log(query)
}();
```
Is there a better solution then this?
`const [query] = await db.execute("INSERT INTO content SET title = ?, url = ?, content = ?",[sql.title, sql.title, sql.content]);`
