### ISSUE TITLE
set a = a + 1 but got 0

### ISSUE THREAD

**Issue by RifeWang** [sidorares/node-mysql2#841]
```
connection.query(
  'UPDATE `account` SET `used` = ? WHERE `id` = ?',
  [ 'used + 48933', 111 ],
  function(err, results) {
    console.log(results);
  }
);
```
the used field result is 0 .

Is this a bug , or I can't use like this ??

**Comment by sidorares** [comment]
resulting sql that is sent to server is `UPDATE `account` SET `used` = \'used + 48933\' WHERE `id` = 111`, I guess mysql casts string to 0 number

**Comment by RifeWang** [comment]
@sidorares  You are right . I have to parse sql to 
`'UPDATE `account` SET `used` = used + 48933 WHERE `id` = ?',  [ 111 ]`
