### ISSUE TITLE
Is there a way to see query te be executed?

### ISSUE THREAD

**Issue by alexvelickiy** [sidorares/node-mysql2#851]
Is there a way to see SQL-query to be executed with connection.execute() command before execution?

**Comment by sidorares** [comment]
not sure I understand the question. `execute()` is in fact two commands under the hood: 1 is "prepare", sql used is exactly the same that you pass. Result is cached and reused for subsequent `execute()` commands. And second step is "execute", where no sql is sent to server, just prepared statement id and parameters

**Comment by sidorares** [comment]
In your example query to be executed can be simulated by doing 

```sql
PREPARE stmt1 'SELECT * FROM table_name WHERE id = ?'`;
SET @pc = 1;
EXECUTE stmt1 USING @pc;
```

`SELECT * FROM table_name WHERE id = 1` is never actually executed. If you compare this to "eval" in javascript, `.query('select 1 + ?', [1])` is `eval('1+1')` while `execute('select 1 + ?', [1])` is `const stmt = eval('function(p1) { return 1 + p1 }'); stmt(1)`

**Comment by alexvelickiy** [comment]
Got it. Thank you)

**Comment by alexvelickiy** [comment]
Does this mean that I can get SQL-query to be executed when I use `.query()` instead of `.execute()`  ?

**Comment by ericuldall** [comment]
I feel like the accepted answer here is not a valid response to the question.

Recreating a prepared statement in mysql does not guarantee what this js code will do when .execute is called. Is there some way for this library to print the prepared sql?

This could allow developers to catch issues like: typos in the query, mismatch in passed vars, or some other errors created in code.
