### ISSUE TITLE
Date type and 0000-01-01

### ISSUE THREAD

**Issue by nanom1t** [sidorares/node-mysql2#857]
Hi,

I have a date field in MySQL table with 0000-01-01 default value. In MySQL it stores correctly, but when I execute a select query I get '1900-01-01T00:00:00.000Z' value. 
![screen shot 2018-10-09 at 10 41 30 am](https://user-images.githubusercontent.com/6481192/46653977-2f1e5600-cbb0-11e8-93bd-f34201952d5c.png)

I think this a bug, because `0000 != 1900`. I'm using this field for user birthday and age calculating. So when I'm trying to calculate a user age I get 118 years old. I handle zero values in my app and I think I should not handle `1900` value.

Thanks

**Comment by sidorares** [comment]
could you prepare small test to illustrate issue, including table creation + inserting record with  '0000-01-01' value

You can pass `dateStrings: false` connection config flag to prevent driver from converting values it receives as string to JS `Date` objects

**Comment by nanom1t** [comment]
The `dateStrings: false` option does not help. The creation and inserting operations work correctly. The problem only with selection.

```
const mysql = require('mysql2');

const connection = mysql.createConnection({
    host: '127.0.0.1',
    port: 3306,
    database: 'Test',
    user: 'test',
    password: 'test',
    supportBigNumbers: true,
    bigNumberStrings: true,
    dateStrings: false
});

// create
connection.query('CREATE TABLE `test` (\n' +
    '  `id` int(11) NOT NULL,\n' +
    '  `birthday` date NOT NULL DEFAULT \'0000-01-01\'\n' +
    ') ENGINE=InnoDB DEFAULT CHARSET=utf8;',
    function (err, results) {
        // insert
        connection.query('INSERT INTO `test` (id, birthday) VALUES (1, "0000-01-01")', function (err, results) {
            // select
            connection.query('SELECT birthday FROM `test` WHERE `id` = 1', function (err, results) {
                console.log(results);
            });
        });
    }
);
```
![screen shot 2018-10-09 at 11 33 06 am](https://user-images.githubusercontent.com/6481192/46656736-67756280-cbb7-11e8-94ad-83a3ada1c64a.png)

```
$ node test.js 
[ TextRow { birthday: 1900-01-01T00:00:00.000Z } ]
```

Thanks

**Comment by nanom1t** [comment]
MySQL2 version: 1.6.1

**Comment by sidorares** [comment]
Works as expected when I pass `dateStrings: true` ( sorry in my first comment I said it should be "false". Meaning of that flag is "don't try to construct js Date and just return the string as it's stored"

```
[ TextRow { birthday: '0000-01-01' },
  TextRow { birthday: '0000-01-01' },
  TextRow { birthday: '0000-01-01' },
  TextRow { birthday: '0000-01-01' } ]
```

When `dateStrings` is not set resulting date is built here: https://github.com/sidorares/node-mysql2/blob/0da580e52c3ae37832c8fde49dddd56fb88aa52b/lib/packets/packet.js#L541

`return new Date(y, m - 1, d);` - in your case y is 0, m is 1 and d is 1. I'd say `1900-01-01T00:00:00.000Z` is also expected in this case, that's the way js Date constructor interprets years

**Comment by nanom1t** [comment]
It works with `dateStrings: true`. Thank you!
