### ISSUE TITLE
prepared statements are not working as excepted

### ISSUE THREAD

**Issue by ericgoe** [sidorares/node-mysql2#864]
Hello, 

This prepared SQL statement `CREATE DATABASE ?` doesn't work. However the `SELECT`-Query as a prepared statement works. It seems like the escaping in the first statement fails.

I am using MySQL 5.7.
I have also checked the MySQL documentation. It says that `CREATE DATABASE` as prepared statement should work.

Kind Regards

**Comment by sidorares** [comment]
I'm pretty sure database or table name cannot be PS parameter, that is you are allowed to prepare `CREATE DATABASE test` statement but not `CREATE DATABASE ?`. This is server limitation and works same way across drivers / libraries. See docs of what is allowed and not here - https://dev.mysql.com/doc/refman/8.0/en/sql-syntax-prepared-statements.html

**Comment by ericgoe** [comment]
You are right. You cannot prepare the database argument. Thank you
