### ISSUE TITLE
1.6.0 is breaking change

### ISSUE THREAD

**Issue by sushantdhiman** [sidorares/node-mysql2#872]
I see you guys did some revamp work in https://github.com/sidorares/node-mysql2/pull/848 :+1: but unfortunately this also introduced some breaking changes due to use of object destruction which is not supported by Node 4.

This should have been treated as major release, nor minor. I suggest either do a breaking release or make 1.x branch compatible with Node 4 again by removing use of object destruction. Also Node v4 can be used in CI again to prevent such regressions.

**Comment by sidorares** [comment]
Agreed, making major version would have been wiser ( though I'd really like to only commit to support current line of node versions and v4 is way past end of life ). For those targeting old node versions there is mysqljs/mysql which still supports node 0.10

**Comment by SimonSchick** [comment]
Unfortunately the test matrix was already targeted to v6 prior this change, so this got through 😛

**Comment by sidorares** [comment]
Yeah, even that test matrix change should have triggered major version change. Not sure what's best way to fix that now, I guess we can make next version a major but it's already too late to unpublish 1.6.1 - 1.6.3

**Comment by SimonSchick** [comment]
@sidorares set the `latest` tag to the previous version I guess.

**Comment by sushantdhiman** [comment]
We can fix Node 4 incompatibilities instead and setup CI for Node 4 again. We can safely drop Node 4 (even 6) in next major version

**Comment by sidorares** [comment]
if the issue is easy to fix let's bring back v4 then

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sidorares/node-mysql2/commit/7c1d234bc6c9031922692009e6fc15ecb32845c8
