### ISSUE TITLE
The debug option stopped working in 1.6.2

### ISSUE THREAD

**Issue by dougwilson** [sidorares/node-mysql2#881]
It seems like version 1.6.2 broke the `debug: true` option from working. I was able to dissect it to the following change: https://github.com/sidorares/node-mysql2/commit/e0077c0892fa27fe4bd39334be4a29dfe1592d18

The commit adds `'use strict'` to [lib/connection.js](https://github.com/sidorares/node-mysql2/blob/e0077c0892fa27fe4bd39334be4a29dfe1592d18/lib/connection.js) but there is a debug log in there that uses [arguments.callee](https://github.com/sidorares/node-mysql2/blob/e0077c0892fa27fe4bd39334be4a29dfe1592d18/lib/connection.js#L471) which is an error under strict mode.

I'm not sure what the appropriate fix would be. A quick fix would be just to remove `'use strict'`, but not sure if there should be additional refactoring to just make it work under strict mode.

**Comment by sidorares** [comment]
Thanks Doug!
@SimonSchick while you are here can you have a look?

**Comment by SimonSchick** [comment]
Ok that one is slightly tricky, it wasn't tested and doesn't seem to work in strict mode at all and it's usage is considered harmful as it's not really supported in general anymore and prevents optimisations, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee etc.

I think it would be better to capture the stack instead and use that, assuming the debug trace format isn't strictly guaranteed.

The alternative is disabling strict mode (in that particular file) until you want to release a major version.

In general we should really look into getting rid of all `arguments.calle(er)` usage for reasons stated above.

**Comment by sidorares** [comment]
Yeah, I'm in favour in doing this via `(new Error()).stack`

**Comment by sidorares** [comment]
maybe with this helper https://www.npmjs.com/package/caller-path

**Comment by sidorares** [comment]
or this https://www.npmjs.com/package/error-stack-parser

**Comment by SimonSchick** [comment]
@sidorares do we want to extract the exact stack frame of the caller?
This would be `new Error().stack.split('\n')[2].trimLeft().replace('at ', '')` I don't think adding 1(+1 nested dependency) is worth it.

**Comment by SimonSchick** [comment]
Or if you want *just* the function name `new Error().stack.split('\n')[2].match(/at (.+) (.*?)/)[1]` in general v8 stack traces are fairly consistent in format, no need for package :)

**Comment by dougwilson** [comment]
Though I believe that would likely break when the user had ` \n` in their path anywhere above the installation.
```
$ mkdir $'foo\nbar'
$ cd $'foo\nbar'
$ echo 'console.log(new Error().stack)' > test.js
$ node test.js 
Error
    at Object.<anonymous> (/tmp/foo
bar/test.js:1:75)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by SimonSchick** [comment]
What about `new Error().stack.split('\n    at ')[2].match(/(.+) (?:.*?)/)[1]`?
I'm not sure if the error parsers would do any better, you can mangle stack traces pretty badly if done intentionally 😛

**Comment by dougwilson** [comment]
I mean, we should just use something that is robust and works reliability that users can't accidentally mess up, right?
```
$ mkdir $'foo is\n at bat'
$ cd $'foo is\n at bat'
$ echo "new Error().stack.split('\n at ')[2].match(/(.+) (?:.*?)/)[1]" > test.js
$ node test.js 
/tmp/foo is
 at bat/test.js:1
(function (exports, require, module, __filename, __dirname) { new Error().stack.split('\n at ')[2].match(/(.+) (?:.*?)/)[1]
                                                                                                  ^

TypeError: Cannot read property 'match' of undefined
    at Object.<anonymous> (/tmp/foo is
 at bat/test.js:1:99)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

**Comment by sidorares** [comment]
Yeah, if regexp works no need for extra dependency

**Comment by SimonSchick** [comment]
Actually, let me check one last option :)

**Comment by sidorares** [comment]
oh my, "what if user has directory with newline in the name". What type of person are you, @dougwilson ? :)

**Comment by dougwilson** [comment]
One who was burned hard on that in the past 😆

**Comment by SimonSchick** [comment]
```
function getCallerName() {
    const old = Error.prepareStackTrace;
    Error.prepareStackTrace = (_, stack) => stack;
    const stack = new Error().stack[1].getFunctionName() || 'Unknown';
    Error.prepareStackTrace = old;
    return stack;
}
```

This is _slow_ but since this is debug only performance shouldn't be an issue :)

**Comment by SimonSchick** [comment]
fyi this is what `caller-path` uses, but `caller-path` also has 3 dependencies (which is insane to me).

**Comment by dougwilson** [comment]
Does it work when someone has `NODE_OPTIONS='--stack-trace-limit=0'` in their environment variables? I think it needs to also set `Error. stackTraceLimit` to something higher and then back again.

**Comment by dougwilson** [comment]
It can still be broken when run under the `vm` module (inside a context in which the globals refer to the parent context's globals, as then `Error.prepareStackTrace` doesn't take affect within the VM context), where the `arguments.callee` doesn't break. The stack stuff I don't think can ever be as robust as `arguments.callee` is. I'm not saying to actually keep using `arguments.callee`, but perhaps just something adds the command name to the command so the debug logging can just echo that vs needing to look at stack to know which the command name is?

**Comment by dougwilson** [comment]
(that was in issue in Jest for a long time, for example).

**Comment by sidorares** [comment]
Maybe we over-automating things here. Add 'debugName' field to each command manually?

**Comment by SimonSchick** [comment]
> It can still be broken when run under the `vm` module (inside a context in which the globals refer to the parent context's globals, as then `Error.prepareStackTrace` doesn't take affect within the VM context), where the `arguments.callee` doesn't break. The stack stuff I don't think can ever be as robust as `arguments.callee` is. I'm not saying to actually keep using `arguments.callee`, but perhaps just something adds the command name to the command so the debug logging can just echo that vs needing to look at stack to know which the command name is?

As I said you can break anything if you really want to.
Maybe we should just use `cmd.constructor.name`.

**Comment by dougwilson** [comment]
Right, but `arguments.callee` wasn't breakable, unless you can say how? We shouldn't go backwards in letting the user break things.

**Comment by SimonSchick** [comment]
It would break if you run node with `--use_strict` :)

**Comment by dougwilson** [comment]
Good point :)

**Comment by dougwilson** [comment]
I still think the solution here shouldn't just keep trying to inspect the stack / caller / whatever anyway. It's one of the reasons why `use strict` killed `arguments.callee`, and if the goal of enabling `use strict`, changing to es6 classes, etc. is better, cleaner code, it feels like this stack introspection is contrary to those goals. That's just my own opinion. In the end, as long as `debug: true` gets back to working, that would be cool, and a way to catch future regressions like this would be icing.

**Comment by SimonSchick** [comment]
Aaanyways, that's beside the point so I think we can agree that you can always break stack inspection if you really want to 😛 
The 4 options are:
 - Disable/revert strict mode for that file
 - Use the (potentially fragile) Error.prepareStacktrace hook
 - Pass the debug name (constant overhead outside of debug mode)
 - Use `cmd.constructor.name` (will change output, but would be (subjectively) better, eg `RegisterSlave` vs. `_registerSlave`
 - (Some other option @dougwilson might come up with)

@sidorares pick your poison

**Comment by sidorares** [comment]
to me `cmd.constructor.name` is best, at least as short term solution. Debug output is for humans so slight change is ok and should not break anything afaik

**Comment by SimonSchick** [comment]
Created a minimalistic PR.
@dougwilson I enjoyed the discussion :)

**Comment by SimonSchick** [comment]
@sidorares Needs release I think?
