### ISSUE TITLE
f.ClientHandshake is not a constructor

### ISSUE THREAD

**Issue by BarthesSimpson** [sidorares/node-mysql2#890]
Hi,

When I use the package locally, everything works fine. However, when I use it inside an AWS Lambda function to connect to an RDS instance, I get this cryptic error:

```
TypeError: f.ClientHandshake is not a constructor
at new g (/var/task/index.js:275:62824)
at new o (/var/task/index.js:275:224046)
at e.exports.getConnection (/var/task/index.js:275:218705)
at e.exports.execute (/var/task/index.js:275:220197)
at /var/task/index.js:275:372341
at new Promise (<anonymous>)
at c.execute (/var/task/index.js:275:372308)
at /var/task/index.js:357:14189
at E (/var/task/index.js:316:24416)
at Generator._invoke (/var/task/index.js:316:24204)
```

Any idea what the issue is? I'm confident that the roles/security groups are all configured correctly.

Thanks

**Comment by sidorares** [comment]
Your code is packaged into one single file, right? What bundler are you using?

**Comment by BarthesSimpson** [comment]
Yes, I'm using Webpack to bundle it. I did just notice I get a warning during the packaging stage, but I'm not sure it's related:

```
WARNING in ./node_modules/mysql2/lib/helpers.js
Module not found: Error: Can't resolve 'cardinal' in '<...>/node_modules/mysql2/lib'


```

**Comment by BarthesSimpson** [comment]
I have an express server with two different wrappers: one for running locally, and the other for running in lambda. When I bundle the code with the local wrapper, it works (when run locally). If I run the bundled lambda code locally, it has the same `f.ClientHandshake is not a constructor` error that I see on the deployed lambda.

**Comment by BarthesSimpson** [comment]
When I inspect the stack trace locally, I also see this error: 


```
Error: Unexpected packet while no commands in the queue
```

**Comment by BarthesSimpson** [comment]
Well, after a day of trying everything, I disabled minification in Webpack and everything worked. Thanks for taking the time to answer!

**Comment by sidorares** [comment]
thanks for posting this, hope it'll hope others.

Bottom line: mysql2 is likely not compatible with webpack+minification

**Comment by Jones-S** [comment]
I have the same problem. But I also could not get it to work without minification. I am using nuxt.js, so maybe my I did something wrong with my webpack config, but it seems that disabling minificaiton does not help .
Is there an alternative how to use mysql and node with webpack?

**Comment by sidorares** [comment]
@Jones-S can you prepare a simple repo which reproduces the issue so It's easier for me to clone and debug?

**Comment by Jones-S** [comment]
Hey @sidorares thanks for your answer.
I just found out what was the problem:
I was actually using netlify lambda (https://www.npmjs.com/package/netlify-lambda) to write a lambda function where I needed the mysql. 
This all resides within a project where I have nuxt and a webpack config.

What I did not realize was:
The netlify lambda uses it's own webpack config to build and serve my node function. So I was always adding the config stuff into the wrong webpack config.
Now that I added it at the right place it worked. 🙈
thanks for your answer anyway!

**Comment by sidorares** [comment]
glad you solved it @Jones-S  :)

**Comment by Seiikatsu** [comment]
Hello @sidorares
As @astrobob said, the issue is still not solved and need to be fixed. On my current projects i use webpack to minify the production build and got the same error. I created a repository to reproduce this error:
https://github.com/Seiikatsu/node-mysql2-issue-890

I already discovered the problem, its the 'lib/commands/index' file, there u have a string with all file names, split them and iterate over it. Thats a problem for webpack as it does not "read" the code. Webpack will only include direct imported files (require / import). The result will be that all commands wont be included in the webpack build.
One solution would be to direct import all commands.

Would be nice if you could investigate on this issue again!

**Comment by sidorares** [comment]
thanks for repro @Seiikatsu , I'll have a look. Maybe we should replace index.js with something like "index.template.js" and populate "real" dynamic index.js as a prepublish step

**Comment by Seiikatsu** [comment]
@sidorares 
I investigated on this a bit more and found a solution what would work. For testing purpose i edited the 'lib/commands/index' like this:
`
'use strict';

const ClientHandshake = require('./client_handshake.js');
const ServerHandshake = require('./server_handshake.js');
const Query = require('./query.js');
const Prepare = require('./prepare.js');
const CloseStatement = require('./close_statement.js');
const Execute = require('./execute.js');
const Ping = require('./ping.js');
const RegisterSlave = require('./register_slave.js');
const BinlogDump = require('./binlog_dump.js');
const ChangeUser = require('./change_user.js');
const Quit = require('./quit.js');

module.exports = {
	ClientHandshake,
	ServerHandshake,
	Query,
	Prepare,
	CloseStatement,
	Execute,
	Ping,
	RegisterSlave,
	BinlogDump,
	ChangeUser,
	Quit,
};
`

This worked as expected without any errors. It doesn't look that fancy but works. However i encountered another problem: 
> Cannot read property 'fromPacket' of undefined

I'll checked that and saw the same dynamic import/export on the 'lib/packets/index' (and probably all around the project).

To check the whole repo and correct it to work this way with webpack would be a bit more work (i could do that if you want). If you have another idea / solution let me know!
Sadly i never published a package on NPM and don't know about the lifecycle hooks. Would it be more / less effort?

**Comment by jp928** [comment]
This is annoying in lambda. Please fix this.
