### ISSUE TITLE
Attempting to substitute ?? placeholder with * in a SELECT query

### ISSUE THREAD

**Issue by bigyonk** [sidorares/node-mysql2#891]
Below is a block of code which I'm using to dynamically construct a query based on query string parameters. Everything works as expected, however in the case where there is no "select" param present , I'm attempting to substitute the ??  placeholder with * and receiving the following error:

`"Unknown column '*' in 'field list'"`

```js
async getTemplates(req, res, next) {

    let queryString = 'SELECT ?? FROM templates'
    let filters = []
    let queryParams = Object.entries(req.query)

    if (!req.query.select) {
      filters.unshift('*')
    }

    queryString += ' WHERE'
    queryParams.forEach(([key, value]) => {
      if (key === 'select') {
        filters.unshift(`${value}`)
      } else {
        filters.push(`${key}`, `${value}`)
        queryString += ' ?? = ? AND'
      }
    })
    queryString = queryString.slice(0, -4)

    try {
      let results = await db.query(queryString, filters)
      if (!results || results == '') {
        res.status(404).json({ message: 'Templates not found' })
      } else {
        res.status(200).json(results)
      }
    } catch (error) {
      next(error)
    }
```

**Comment by mbrevda** [comment]
Dup of #1283? Either way, it would be good if this can be addressed in this package, as upstream doesn't seem interested in fixing

**Comment by sidorares** [comment]
@bigyonk can you try `SqlString.raw('*')` solution from linked discussion? That would stop sqlstring from adding backticks around `*`
