### ISSUE TITLE
uncatchable `uncaughtException` in `pool.execute` if `undefined` in query values

### ISSUE THREAD

**Issue by dr-js** [sidorares/node-mysql2#902]
`undefined` in query values will cause `TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null`

with `pool.execute`, is there a place to catch the error?

the simplified test script:
```js
// test-pool-execute-error.js

const Mysql = require('mysql2')

const CONFIG = {
  host: '127.0.0.1',
  port: 3306,
  user: 'root',
  database: 'mysql'
}

const testNormal = () => {
  console.log('[testNormal] start')
  const pool = Mysql.createPool(CONFIG)
  pool.execute(
    `SET @value = ?`,
    [ 0 ], // good value
    (error, resultList, fieldList) => console.log('[testNormal] from callback:', { error, resultList, fieldList })
  )
  setTimeout(() => pool.end(() => console.log('[testNormal] pool ended')), 1000)
}

const testError = () => {
  try {
    console.log('[testError] start')
    const pool = Mysql.createPool(CONFIG)
    pool.on('error', (error) => console.log('[testError] error from event', error))
    pool.execute(
      `SET @value = ?`,
      [ undefined ], // bad value
      (error, resultList, fieldList) => console.log('[testError] from callback:', { error, resultList, fieldList })
    )
    setTimeout(() => pool.end(() => console.log('[testError] pool ended')), 1000)
  } catch (error) { console.log('[testError] error from catch', error) }
}

process.on('uncaughtException', (error) => console.error('!!! error from uncaughtException', error))

testNormal()

setTimeout(() => { // wait first test pass
  testError()
}, 2000)
```

the output with `mysql2@1.6.4`: (testNormal pass, but testError throws and block the process exiting)
```
$ node test-pool-execute-error.js
[testNormal] start
[testNormal] from callback: { error: null,
  resultList:
   ResultSetHeader {
     fieldCount: 0,
     affectedRows: 0,
     insertId: 0,
     info: '',
     serverStatus: 2,
     warningStatus: 0 },
  fieldList: undefined }
[testNormal] pool ended
[testError] start
!!! error from uncaughtException TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at ...\node_modules\mysql2\lib\connection.js:609:17
    at Array.forEach (<anonymous>)
    at PoolConnection.execute (...\node_modules\mysql2\lib\connection.js:607:22)
    at ...\node_modules\mysql2\lib\pool.js:171:31
    at Pool.<anonymous> (...\node_modules\mysql2\lib\pool.js:68:18)
    at PoolConnection.<anonymous> (...\node_modules\mysql2\lib\connection.js:753:13)
    at Object.onceWrapper (events.js:273:13)
    at PoolConnection.emit (events.js:182:13)
    at ClientHandshake.<anonymous> (...\node_modules\mysql2\lib\connection.js:108:20)
    at ClientHandshake.emit (events.js:182:13)
```

**Comment by sidorares** [comment]
At the moment it's not possible to catch with `pool.execute()` because internally it does async `pool.getConnection()` + sync throw fromo `connection.execute()`.

I think you can catch this error if you split call in two, but I suggest fixing root cause first (filter / map parameters)

```js
 pool.getConnection((err, conn) => {
    try {
      conn.execute(
        `SET @value = ?`,
        [ undefined ], // bad value
        (error, resultList, fieldList) => console.log('[testError] from callback:', { error, resultList, fieldList })
      )
    } catch(e) {
      console.log('this is expected: ', e);
    }
})
```

**Comment by sidorares** [comment]
> but I don't know if extra try/catch will cause performance hit

it used to be a hit previously, maybe less so now with modern v8. I think the intention was to treat this kind of errors less like runtime and more like "design time" error when you forget some parameter or thinks like this, thus it's better to error hard and early

How you encountered error in your case? Did you try to pass `undefined` deliberately?

**Comment by dr-js** [comment]
It's a node server/worker for read&process data in mysql.

This was discovered during early testing with some loose data code.
I do agree `undefined` in data should be handled before the query, 
and the code will be added later..

In my case the server will crash&restart on `uncaughtException`/`unhandledRejection`,
so I try to add catch for most error.

**Comment by knoxcard** [comment]
@dr-js, go ahead and close the ticket, you are the one who is able to do that.

**Comment by damianobarbati** [comment]
Why was this closed? An unhandled rejection cause process exit/crash.
This is pretty serious; there's no way to catch this error, no matter where you put the try/catch .

@dr-js how did you solve?

**Comment by dr-js** [comment]
@damianobarbati this issue is closed for a while and things may be changed

As far I remember it's avoidable if you knew this and make sure the input value do not have `undefined`
Like add a wrapper function to do a value check

**Comment by theirongiant** [comment]
This isn't so straightforward when you're using namedParameters and passing in an object, you'd need to maintain a list of expected keys to check for each query. As far as I can tell ThatBean's fix works, if the difference is between killing the server vs a potential performance hit would it be possible to add an alternative safe version of execute so we can choose which to use?

**Comment by hktr92** [comment]
it just happened to me, too. in a project that is supposed to go live sooner or later.

more time is wasted to overcome this issue by this method (implementing a strict type conversion + restart policy for a fallback in business logic) rather than having a try / catch in the library itself... which can be further caught and handled properly.

if the intention is to report an issue, then **throw an error**, don't kill the process. it's bad design imho and raises uncertainty for production.

also, the error reported is pretty ambiguous and doesn't really tell what query caused this issue, which makes harder to debug + repair quickly (for reference, Doctrine (PHP library) reports which query failed in dev mode).

**Comment by fultonm** [comment]
In case it helps others, the issue described here can also be caused by incorrect SQL syntax, and Bind Parameters message can be a red herring.

Either way, it's odd that it would crash the whole server process instead of rejecting the Promise.

**Comment by yushuohuanxiu** [comment]
i used this script **catch the err** and **avoid the process exit**.
`
const mysql = require('mysql2/promise');
const pool = mysql.createPool(config.db);
async function insertTask() {
    let sql = ...;
    try {
        let conn = await pool.getConnection();
        await conn.execute(sql, [params]);
        await conn.release();
    } catch (err) {
        // do something.
    }
}
`

**Comment by RobertoGeuke** [comment]
@sidorares I'm currently also trying to catch this error, because I do not want to compare given arguments with the named placeholders in the query myself. An error being thrown because of the incorrect code is good enough for me (if it did not kill the process), because the fact that the error is being thrown will be enough information for our team to find the issue and resolve it.

I would like to ask you to reconsider closing this issue and maybe re-opening it.
