### ISSUE TITLE
DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated

### ISSUE THREAD

**Issue by kachar** [sidorares/node-mysql2#904]
I've just encountered the following error while switching from `mysql` to `mysql2` implementation

```
(node:43383) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
```

Related code:
```js
import mysql from 'mysql2/promise'

const pool = mysql.createPool({
  // ...
})

async handle() {
  let results = await pool.query('SELECT * FROM `domain` LIMIT 10')
  console.log(results)
}
```
I get the good db results, but also the warning shown above.

Any idea what triggers the problem?

Env:
```
$ node -v
v10.11.0
$ npm -v
6.5.0
$ uname -av
Darwin deepocean 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by kachar** [comment]
Seems the warning is triggered by `console.log` itself because of the existence of the method `inspect()` in the `ColumnDefinition` class https://github.com/sidorares/node-mysql2/blob/0c422dd9d88a211015ddf4fcc8531048de9b1340/lib/packets/column_definition.js#L56-L59

Closing the issue as it's not an actual development problem.

**Comment by sidorares** [comment]
yes, ideally I'd like to migrate to https://nodejs.org/api/util.html#util_util_inspect_custom but this is relatively low priority. Happy to merge PR though if you want to help with this, might help someone's time in the future and reduce noise
