### ISSUE TITLE
mysql.format returns object string instead of value

### ISSUE THREAD

**Issue by dan-willett** [sidorares/node-mysql2#905]
When using the format function to prepare a statement, if the data is an object, it is returning [object object] instead of stringifying the object.

for example:

    const mysql = require(mysql2/promise);
    
    let query = "INSERT INTO table (cola, colb, colc) VALUES ?";
    let data = [["text",0,{test1: "text", val1: 1 }]];
    let pquery = mysql.format(query,data);

Here is what mysql.format returns:  "INSERT INTO table (cola, colb, colc) VALUES ('text',0,'[object Object]')"

Here is what it SHOULD return:

"INSERT INTO table (cola, colb, colc) VALUES ('text',0,'{"test1":"text","val1":1}')

**Comment by sidorares** [comment]
`.format()` here calls directly same function from https://www.npmjs.com/package/sqlstring#formatting-queries so I suggest creating issue there. 

In your case just convert it to string yourself, `conn.query()` and `.format()` don't know DB schema here and can't assume that your table field is of type JSON

```js
let query = "INSERT INTO table (cola, colb, colc) VALUES ?";
let data = [["text",0,JSON.stringify({test1: "text", val1: 1 })]];
let pquery = mysql.format(query,data);
```

See docs on how `.format()` serialises input here: https://www.npmjs.com/package/sqlstring#escaping-query-values

**Comment by dan-willett** [comment]
I will look into raising the issue there...  as far as converting, I don't know ahead of time which fields will be objects, as I am copying from different tables that may or may not have a JSON type column.

The fact is, that response is an invalid response and a bug.   I raised the issue because it needs to be fixed.  I did make a function in my own project to deal with the issue, but I should not have to. I now pass the object to this function before passing it to format().

    function prepObjectArrayforMySQL(dataArray) {
    	if (Array.isArray(dataArray)) {
    		for (let i=0;i<dataArray.length;i++) {
    			if (Array.isArray(dataArray[i])) {
    				for (let j=0;j<dataArray[i].length;j++) {
    					if (Array.isArray(dataArray[i][j])) {
    						for (let k=0;k<dataArray[i][j].length;k++) {
    							if (typeof dataArray[i][j][k] === "object") {
    								dataArray[i][j][k] = JSON.stringify(dataArray[i][j][k]);
    							}
    						}
    					} else {
    						if (typeof dataArray[i][j] === "object") {
    							dataArray[i][j] = JSON.stringify(dataArray[i][j]);
    						}
    					}
    				}
    			} else {
    				if (typeof dataArray[i] === "object") {
    					dataArray[i] = JSON.stringify(dataArray[i]);
    				}
    			}
    		}
    	}
    	return dataArray;
    }

**Comment by sidorares** [comment]
Just couple of notes in addition to answer in https://github.com/mysqljs/sqlstring/issues/40

- `.format()` is only for text substitution in the query, it does not create prepared statement or tries fully parse SQL. 
- With "real" prepared statements we might know input type from prepare step but at the moment it's not used - see  https://github.com/sidorares/node-mysql2/issues/476#issuecomment-264342349 ( I'm pretty sure there was another discussion about tis but can't find it). Basically `prepare()` command returns list of input and output fields from server and this information is available for `execute()` but currently not used

**Comment by dan-willett** [comment]
I still contend that the best method would be to fix the underlying issue, which would be a simple fix to the sqlstring library, however I did come up with a better work around than the above function, and that is to override the prototype toString function as seen here:

    Object.prototype.toString = function() {
        if (this === null) return "null;
        else return JSON.stringify(this);
    }

**Comment by sidorares** [comment]
there are many scenarios when `JSON.stringify` is not possible or not desired option, and driver does not know that ( for example, if you have circular references in your object ). providing `.toString()` Is one way of telling how to serialize

**Comment by dan-willett** [comment]
After experimenting with replacing the prototype.toString, I have come to the conclusion that approach is not usable in production...

There is a simple fix for the escape() function that format() uses... and that is when converting an object to check if the return value is going to be "[object Object]" and if that is the case to use JSON.stringify instead of toString().

This will solve the entire problem without breaking any of the other functionality of the format() and escape() functions.

This will still use the custom defined functions when available and only use JSON.stringify if what is going to be returned is the non-value "[object Object]"

I would submit that when formatting a string for SQL that the return of "[object Object]" is NEVER the desired result.

And is a MAJOR problem when working with MySQL 5.7 and later when you are using JSON columns.

Here is a REAL life scenario where this is a problem:

When you are copying rows from a list of tables where the data types are not known and can change, reading in the row to copy, making changes to specific columns and then writing out the new rows.  If one of the columns is the JSON datatype, the data in the column gets converted to "[object Object]" causing the whole operation to fail.

**Comment by satdeveloping** [comment]
2024/12/05 - This is still an issue
