### ISSUE TITLE
MySQL 8 SHA256 Support

### ISSUE THREAD

**Issue by normano** [sidorares/node-mysql2#906]
Hey, I'm wondering if you still planned on adding mysql 8 support. I did find one branch on here that has your WIP changes for it and I wonder if you will continue with it? I might switch to mysqljs since they are close to merging support. I was trying to do it myself but I don't understand it enough! The first marker in the handsahake is 254 and then it comes back with 1 and data is 0x04 which I guess it wants the FullAuthentication to be performed.

**Comment by sidorares** [comment]
yes, I'm planning to work on this some time but if anyone would like to contribute that would be great

One way I want to implement this differently from https://github.com/mysqljs/mysql/pull/1962 is to have it part of auth plugin system and not treat specially. Unfortunately I discovered that auth plugin need big rewrite as well

I'm happy to answer any questions you have re auth plugins in general and sha256 particularily here @normano !

**Comment by normano** [comment]
Did you have any spec for the rewrite? I don't know enough about MySQL auth, but I'm curious to know where you are going with your client side plugin support.

I'm gonna try again today, maybe I can respond to the FullAuthentication request properly and make it work.

**Comment by sidorares** [comment]
I'll try to document more later, but here are few starting points:

Auth switch packet documentation: https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::AuthSwitchRequest

Current api: https://github.com/sidorares/node-mysql2/blob/master/documentation/Authentication-Switch.md implemented in https://github.com/sidorares/node-mysql2/blob/efec9d5cfc3496bb254f72d5a8d7258d797c2e3e/lib/commands/client_handshake.js#L162-L173

Problem with current api is that it's difficult to make plugin that supports multiple responses from server and maintains state

Also see https://github.com/sidorares/node-mysql2/issues/560

**Comment by normano** [comment]
Still trying to attempt this, but seems fullauthentication request (plugindata == 0x04) is requested then need to send clear text pass if ssl is not enabled.

```
if(authSwitchHandlerParams.pluginData.toString("hex") === "04") {
connection.writePacket(new Packets.ClearText(this.password).toPacket());
}
return null; // Not sure if this is correct
```

if fast path then I just return null currently.

Seems like the auth worked, but then get
Warning: got packets out of order. Expected 1 but received 5
Warning: got packets out of order. Expected 2 but received 1
Warning: got packets out of order. Expected 3 but received 2
Warning: got packets out of order. Expected 4 but received 3
Warning: got packets out of order. Expected 5 but received 4
Warning: got packets out of order. Expected 6 but received 5
Warning: got packets out of order. Expected 7 but received 6
Warning: got packets out of order. Expected 8 but received 7
Warning: got packets out of order. Expected 9 but received 8

:(

**Comment by normano** [comment]
So i modified the return null to instead return () => false; and now I can query

**Comment by normano** [comment]
Here are my changes: https://github.com/normano/node-mysql2/commit/2caf07bdab7c37646df5f9748b30b46aa845944c Definitely rough, but works for non ssl connection

**Comment by iblessedi** [comment]
How are things going now? Can I use this library with mysql 8 ?
