### ISSUE TITLE
how use mysql call procedure? 

### ISSUE THREAD

**Issue by skvarovski** [sidorares/node-mysql2#927]
Hi all,

i write procedure and insert to DB. 
$sql = "call myProcedure()";

nodejs say parse error. 

How i call my procedure in mysql2 lib?

**Comment by sidorares** [comment]
can you show sql you use to create `myProcedure`?

You can find some examples that call procedures in this test - https://github.com/sidorares/node-mysql2/blob/0c422dd9d88a211015ddf4fcc8531048de9b1340/test/integration/connection/test-binary-multiple-results.js

**Comment by skvarovski** [comment]
Thanks for answer.
my code 

```
const sqlProcedure = 'CALL alfaquery_v2();';
    pool.connect()
        .then(client => {
            return client.query(sqlProcedure)
                .then(res => {
                    client.release();
                    console.log(res.rows);
                    res.rows.forEach(function (item) {
                    console.log(item);
                    });
                    //resout.send('ok');
                })
                .catch(e => {
                    client.release();
                    console.log(e.stack)
                })
        });
```

**Comment by sidorares** [comment]
try without `;` otherwise you might need `multipleStatements: true` flag - see https://github.com/mysqljs/mysql#multiple-statement-queries

**Comment by skvarovski** [comment]
i am so sorry. i found bug in my connection, i have two connection :) issuse resolve.
