### ISSUE TITLE
Insert Multiple Rows in One Query

### ISSUE THREAD

**Issue by Orel-A** [sidorares/node-mysql2#928]
Didn't find it in the documentation, but is there such a thing?
Currently my query looks like this:
`db.query("INSERT INTO ipToCountry SET startAddress=INET6_ATON(?), endAddress=INET6_ATON(?), country=?", [
  startAddress,
  endAddress,
  country
]);`
Would I need to build the query myself or can I rely on mysql2 package?

EDIT: Okay so with further testing, I've built the query myself, then I got connection reset error.
So I assumed that there is a limit that can be batched together so I sent each query with 50 rows.
But now I have missing rows... And no errors. So it's hard to debug.
Any help?

EDIT2: I've done some more testing. Sending too many queries at once will result in "Error: connect ETIMEDOUT". However if I getConnection() from the pool execute the query then release, I won't get any errors.
Any idea why is that so? Do I need to increase connectionLimit or decrease?

**Comment by sidorares** [comment]
hard to tell without looking at the code. Would you be able to prepare full self contained example ( including schema creation etc ) so I can run locally?

**Comment by Orel-A** [comment]
[geoip.txt](https://github.com/sidorares/node-mysql2/files/2930751/geoip.txt)

The first 29 rows are getting "Error: connect ETIMEDOUT".
Today I've run the test around 4 times and got no errors, but then on the next tests it started to occur again.
The total rows count should be 412586.
