### ISSUE TITLE
Error in Promise Wrapper section in README, with a question that how to check whether success or not after connecting to databse

### ISSUE THREAD

**Issue by meloseven** [sidorares/node-mysql2#932]
In README,there is one code which has problem,see below:
```js
async function main() {
  // get the client
  const mysql = require('mysql2');
  // create the connection
  mysql.createConnection(
   {host:'localhost', user: 'root', database: 'test'},
   (err,con) => {
    con.promise().query("SELECT 1")
    .then( ([rows,fields]) => {
     console.log(rows);
    })
    .catch(console.log)
    .then( () => con.end());
   }
  );
```
I tried this, but can't go to callback.Then I check out the source code, find there is no second arguments in `createConnection`.If so, how can I check whether success or not after connecting to databse?

**Comment by meloseven** [comment]
I know how to do it after checking out the source code that is through the event of `connect` and `error` . :)

**Comment by sidorares** [comment]
Is is probably example demonstrating `.promise()` helper that returns promise wrapper from non-promise one. In that case code should look like this:

```js
 const mysql = require('mysql2');
  // create the connection
  const connection = mysql.createConnection(
   {host:'localhost', user: 'root', database: 'test'},
  )
  connection.promise().query("SELECT 1")
    .then( ([rows,fields]) => {
     console.log(rows);
    })
    .catch(console.log)
    .then( () => con.end());
```

**Comment by meloseven** [comment]
Right.

**Comment by sidorares** [comment]
Would you be able to make PR to fix this @meloseven ?

**Comment by meloseven** [comment]
Fine!

**Comment by sidorares** [comment]
Probably missed main question "how to check whether success or not after connecting to databse"

You are right re "connection" and "error" events on connection. In general I always recommend using pool for that reason, with single connection it's a bit more work to handle errors that occur before first result, with pool it's all handled automatically

Also promise wrapper behaves a bit differently:

```js
  const mysql = require('mysql2/promise');
  const conn = await mysq.createConnection(opts);
  // you only get to here after successful connection if performed
```

**Comment by meloseven** [comment]
Thx! I get it.
