### ISSUE TITLE
API incompatibility re aggregate functions sum and avg return string type instead of numeric

### ISSUE THREAD

**Issue by igolfs** [sidorares/node-mysql2#935]
SELECT SUM(amt), AVG(amt)
    FROM MYTABLE;

 mysqljs returns numeric columns but mysql2 returns strings.

**Comment by sidorares** [comment]
Is that using text binary or protocol ( `.query()` or `.execute()` ) ?

Also can you log field types? In your callback `function(err, rows, fields) {}` add `console.log(fields)`

**Comment by igolfs** [comment]
Here's my DDL:

    create table test (qty int);
    insert into test (qty) values (1), (2), (3), (4), (5);

I ran 3 other tests with MySQLjs.query, MySQL2.query and MySQL2.execute for:

    SELECT sum(qty), avg(qty) FROM test
Functions min(), max() and count() behave correctly and return numeric values in all 3 tests.

Results for sum() and avg():
 
    ======================================================================
    MySQLjs query
    ======================================================================
    Results: [ RowDataPacket { 'sum(qty)': 15, 'avg(qty)': 3 } ]
    FieldPacket {
      catalog: 'def',
      db: '',
      table: '',
      orgTable: '',
      name: 'sum(qty)',
      orgName: '',
      charsetNr: 63,
      length: 33,
      type: 246,
      flags: 128,
      decimals: 0,
      default: undefined,
      zeroFill: false,
      protocol41: true }
      FieldPacket {
      catalog: 'def',
      db: '',
      table: '',
      orgTable: '',
      name: 'avg(qty)',
      orgName: '',
      charsetNr: 63,
      length: 16,
      type: 246,
      flags: 128,
      decimals: 4,
      default: undefined,
      zeroFill: false,
      protocol41: true }
    
    ======================================================================
    MySQL2 query
    ======================================================================
    Results: [ TextRow { 'sum(qty)': '15', 'avg(qty)': '3.0000' } ]
    { catalog: 'def',
      schema: '',
      name: 'sum(qty)',
      orgName: '',
      table: '',
      orgTable: '',
      characterSet: 63,
      columnLength: 33,
      columnType: 246,
      flags: 128,
      decimals: 0 }
      { catalog: 'def',
      schema: '',
      name: 'avg(qty)',
      orgName: '',
      table: '',
      orgTable: '',
      characterSet: 63,
      columnLength: 16,
      columnType: 246,
      flags: 128,
      decimals: 4 }
    
    ======================================================================
    MySQL2 execute
    ======================================================================
    Results: [ BinaryRow { 'sum(qty)': '15', 'avg(qty)': '3.0000' } ]
    { catalog: 'def',
      schema: '',
      name: 'sum(qty)',
      orgName: '',
      table: '',
      orgTable: '',
      characterSet: 63,
      columnLength: 33,
      columnType: 246,
      flags: 128,
      decimals: 0 }
      { catalog: 'def',
      schema: '',
      name: 'avg(qty)',
      orgName: '',
      table: '',
      orgTable: '',
      characterSet: 63,
      columnLength: 16,
      columnType: 246,
      flags: 128,
      decimals: 4 }

**Comment by sidorares** [comment]
returned type here is `NEWDECIMAL`. The intention of this type is 'to store exact numeric values in the database'

http://www.mysqltutorial.org/mysql-decimal/
https://dev.mysql.com/doc/refman/5.7/en/precision-math-decimal-characteristics.html

The value is stored internally and transmitted over the wire as string, I just wanted to preserve this property in the driver, it's up to the user to decide what to do with that value ( If we convert to number immediately there can be easily loss of precision )

**Comment by igolfs** [comment]
It's illogical though that the result of a mathematical function is a
string. Since moving from mysqljs I've had to add an iteration over my
result set to convert each entry to numeric manually.

In any case, how would there be a loss of precision if there is only one
numeric type in java script?

**Comment by sidorares** [comment]
> how would there be a loss of precision if there is only one
numeric type in java script?

like this - https://dzone.com/articles/never-use-float-and-double-for-monetary-calculatio ( linked examples are in Java but JS uses same IEE754  double )

There is only one *built in* numeric type in java script ( well, now there is native [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) starting from node v10.4 ) so the problem we are discussing "should DECIMAL/NEWDECIMAL numbers be casted to js number automatically or it's up to user to decide how to store value - using JS number, one of bignumver libraries or something else"

**Comment by igolfs** [comment]
Thanks for the quick reply. I'll digest this in the morning as it's just
gone past midnight here. Wasn't aware of the new bigint in node.
Cheers

**Comment by sidorares** [comment]
Thanks for your feedback! It's difficult to design api that is flexible and does not have surprises at the same time, "sum()" returning a string is definitely surprise here but this is what current behaviour for DECIMAL/NEWDECIMAL - documented here https://github.com/sidorares/node-mysql2/tree/master/documentation#known-incompatibilities-with-node-mysql also see the flag to convert automatically ). Not sure if returning `BigInt`  ( native or through the library ) would be a less surprise

**Comment by igolfs** [comment]
Hi.
Thanks for the link. The flag to convert automatically solved it for me:

     decimalNumbers: true

I had read through the known list of incompatibilities. I suppose that I hadn't realised that the aggregation result was being returned as DECIMAL/NEWDECIMAL.

My code is now behaving as it did with MySQLjs, so thanks again!

**Comment by stskapilan** [comment]
Hi,
I'm trying to insert multiple rows to db,
```
connection.promise().query(query,[values],(err,results)=>{            
            if(err) console.log("error",err)
            resData = results
        })
```

In this above code I can achieve it. but in .execute() I'm not able to do it. 
**Can anyone explain it?**

```
connection.promise().execute(query,[values],(err,results)=>{            
            if(err) console.log("error",err)
            resData = results
        })
```

I'm getting error like this,

```
code: 'ER_PARSE_ERROR',
  errno: 1064,
  sql: 'INSERT INTO `user` (`User_Name`,`Password`,`Email`,`isAuthor`) VALUES ?;',
  sqlState: '42000',
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?' at line 1"
```

**Comment by JMTK** [comment]
> Hi. Thanks for the link. The flag to convert automatically solved it for me:
> 
> ```
>  decimalNumbers: true
> ```
> 
> I had read through the known list of incompatibilities. I suppose that I hadn't realised that the aggregation result was being returned as DECIMAL/NEWDECIMAL.
> 
> My code is now behaving as it did with MySQLjs, so thanks again!

This works for avg(), but max() still seems to return a string

**Comment by nolimitdev** [comment]
> Hi. Thanks for the link. The flag to convert automatically solved it for me:
> 
> ```
>  decimalNumbers: true
> ```
> 
> I had read through the known list of incompatibilities. I suppose that I hadn't realised that the aggregation result was being returned as DECIMAL/NEWDECIMAL.
> 
> My code is now behaving as it did with MySQLjs, so thanks again!

I do not understand. Old `npm mysql` here https://www.npmjs.com/package/mysql#string states that DECIMAL is returns as string and new `npm mysql2` here https://sidorares.github.io/node-mysql2/docs/documentation#known-incompatibilities-with-node-mysql states `DECIMAL and NEWDECIMAL types always returned as string unless...`. So when AVG() returns decimal there is no change/incompatibility mysql vs. mysql. So why that mention? Both returns result as string (unless decimalNumbers: true is used). Im missing something here?

**Comment by sidorares** [comment]
@nolimitdev msqljs/mysql sometimes casts NEWDECIMAL to number - https://github.com/mysqljs/mysql/blob/dc9c152a87ec51a1f647447268917243d2eab1fd/lib/protocol/packets/RowDataPacket.js#L105
