### ISSUE TITLE
Is .query() save for SQL Injection attacks

### ISSUE THREAD

**Issue by gretschann** [sidorares/node-mysql2#941]
Can i use ES6 Placeholders for formatting the query?

Example:
const sql = `INSERT INTO ${this.table}`

return db.query(sql)

**Comment by sidorares** [comment]
Your example just converts input to a string and concatenates with rest of sql. For trusted input and table name this is probably ok but if data is coming from users it's better to escape first to prevent sql injection

There are helper modules on npm that escape input automatically via tagged template literals, check out some of them: ( no endorsment from me, just few of the first quick search results)

https://www.npmjs.com/package/sql-template-strings
https://www.npmjs.com/package/sql-template-tag
https://www.npmjs.com/package/sql-tag
https://www.npmjs.com/package/sql-tagged-template-literal
https://www.npmjs.com/package/sql-mysql

**Comment by SimonSchick** [comment]
@sidorares you should probably mention bind parameters too 😛

**Comment by sidorares** [comment]
yeah @gretschann, best way to avoid sql injections is to completely separate code from data. With `.execute()` your query is sent first without arguments, and only after that parameters alone sent separately and it is the server which applies them to already processed sql statement - all with same syntax as `.query()` so no extra dev effort required
