### ISSUE TITLE
TypeCast seems doesnt work

### ISSUE THREAD

**Issue by shelru** [sidorares/node-mysql2#948]
```js
const mysql2 = require('mysql2');

const pool = mysql2.createPool({
    host:'localhost', user: 'admindb', database: 'tests',password:'password',charset:'UTF8MB4_UNICODE_CI',timezone:'Z',
    typeCast: (field, next) => {
        console.log('typeCast');
        if (field.type === "BIT") {
            console.log(field);
            console.log(field.buffer());
            return field.buffer()[0] == 1;
        }
        return next()
    }

});;
const promisePool = pool.promise();
export default {pool, promisePool}
```

Doesn't call with execute.
dup: https://github.com/sidorares/node-mysql2/issues/649 https://github.com/sidorares/node-mysql2/issues/347 

How i can turn <Buffer xx> to bool/int?
https://dev.mysql.com/doc/refman/8.0/en/bit-type.html

**Comment by shelru** [comment]
Is there typical pure c way's to convert to bool? like !!var.

**Comment by shelru** [comment]
![image](https://user-images.githubusercontent.com/9306996/56014185-2fd1a980-5d05-11e9-882d-5bba38fdcfef.png)
Seems doesn't work.

**Comment by sidorares** [comment]
yes, this is known problem. Unfortunately typeCast api is too low level and resullts for execurte come in different binary format, I haven't figured out yet good way of making typeCast work for execute with compatible api

**Comment by shelru** [comment]
@sidorares ok, so, how convert BinaryRow to json obj?

**Comment by sidorares** [comment]
Just do it in your code that consumes data? Not very central, but usually you have some mapping function anyway data -> model or view

**Comment by shelru** [comment]
So, i have only clear code. Without that.
And need payload for jwt.

**Comment by shelru** [comment]
```js
      console.log(rows[rows.length-1]);

BinaryRow {
  id: 1,
  name: 'dsad',
  surename: 'asdad',
  fname: 'd',
  login: 'abcd',
  password: 'qwdqwd',
  group: 1,
  type: 's',
  active: <Buffer 01>,
  login_changed: <Buffer 00> }
```

**Comment by sidorares** [comment]
```js
const lastRow = rows.slice(-1)
console.log(JSON.stringify({ ...lastRow, active: lastRow.actibe === 1, login_changed: lastRow.login_changed[0] === 1 }, null, 2));
```

**Comment by shelru** [comment]
Is that normal way?
```js
 let payload = JSON.parse(JSON.stringify(rows[rows.length-1]));
```

**Comment by shelru** [comment]
```js
const lastRow = rows[0];
      console.log(JSON.stringify({ ...lastRow, active: lastRow.active[0] === 1, login_changed: lastRow.login_changed[0] === 1 }, null, 2));
```
@sidorares thank's, that work perf.

**Comment by sidorares** [comment]
no need for `JSON.parse(JSON.stringify`

**Comment by shelru** [comment]
But i need it for let payload, no?
```js
      let payload = JSON.parse(JSON.stringify({ ...lastRow, active: lastRow.active[0] === 1, login_changed: lastRow.login_changed[0] === 1 }));
```

**Comment by sidorares** [comment]
```js
const payload = { ...lastRow, active: lastRow.active[0] === 1, login_changed: lastRow.login_changed[0] === 1 };
```

to avoid `delete payload.password`:

```js
const { password, ...payload } = { ...lastRow, active: lastRow.active[0] === 1, login_changed: lastRow.login_changed[0] === 1 };
```

**Comment by shelru** [comment]
Thx.

**Comment by jjeejj** [comment]
Now, Whether the feature(typeCast) is supported ?

**Comment by euglv** [comment]
I have the same issue. 
Are there any way to convert all `BIT(1)` fields to `boolean` in one place for all queries? Or the only option is not to use the prepared statements?
