### ISSUE TITLE
There is an intention to make an official @types for the API?

### ISSUE THREAD

**Issue by drachehavoc** [sidorares/node-mysql2#952]
Nowadays TypeScript is a very popular way to write robust JavaScript, I am an adept of this superset and am in a project that needs to connect to MySQL.

Going straight to the point:
1 - exsite an official @types npm for mysql2, which does not use the old typings?
2 - is there intention of creation?

**Comment by drachehavoc** [comment]
I found this types [https://github.com/types/mysql2](https://github.com/types/mysql2), but the npm install is not working properly, so I manually downloaded it and added it to my project.

It would be nice if the command `npm i --save-dev` @ type / mysql2 work

**Comment by sidorares** [comment]
Hi @drachehavoc , yes agree with you, would be good to improve typescript experience with node-mysql2
Would you be able to help with this?

**Comment by drachehavoc** [comment]
Sure! I will write some d.ts and share with you in next days.

I will be happy to help. ^^

**Comment by FredericLatour** [comment]
honestly, it would be better to have the typescript definition available as part of mysql2. 
Quite[ easy to do](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html): you just need one file '.d.ts' and a config entry in package.json.
Of course this implies that the definitions are maintained. However I don't think that the public API is changing that much and therefore, after the initial load, changes should be minimal.

**Comment by sidorares** [comment]
@FredericLatour  I'm happy to bundle it with the package and maintain. Do you know any tools that might assist in automatic "typings match what's in the code" check? Can you volunteer to add typings here?

**Comment by FredericLatour** [comment]
@sidorares Great to hear.  

Why not starting from the existing type definition (the one I'm using) available here: https://github.com/types/mysql2 (please note that this is not the DefinetelyTyped repo which make it difficult for people to know it exists). I can see that there was already a discussion on the possibility to include it in the repository.

Best approach if you ask me is that you include the files without waiting for a PR and then if something is missing people can PR to add/correct the definition in the repo.

**Comment by mapleeit** [comment]
@drachehavoc Any progress on this? If you have one version, maybe it's a good idea to make a PR first. So that we could improve it.

**Comment by RShadowhand** [comment]
Here to show support. +1 to this. Currently having to write my own interfaces for simple things.

**Comment by kirillgroshkov** [comment]
Came here as well for the typings..

**Comment by Cl00e9ment** [comment]
Adding manually the following entry in the `package.json` worked for me:

```json
{
  ...
  "devDependencies": {
    ...
    "@types/mysql2": "git+https://git@github.com/types/mysql2.git"
  }
}
```

But I agree that it would be better if the command `npm i -D @type/mysql2` worked.

**Comment by bentong95923** [comment]
thumbs up for making the @types prefix official which can standardize the package name to remove confusion while installing type def like me.

**Comment by larshp** [comment]
in the latest version the tyepscript types are shipped as part of the npm package, so no need for the @types or @type/mysql2 anymore

**Comment by richbai90** [comment]
It looks like most of the types were pulled straight from the old types package. This isn't a huge problem except that it doesn't contain a pool.promise method

**Comment by wellwelwel** [comment]
You can look at [typings/mysql](https://github.com/sidorares/node-mysql2/tree/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/typings/mysql) for the **MySQL2** types and its documentation in [documentation/en/TypeScript-Examples.md](https://github.com/sidorares/node-mysql2/blob/4ac6a8f0f908cfa7af1f2dddd17e4054af73e52f/documentation/en/TypeScript-Examples.md).
