### ISSUE TITLE
Events on mysql connection object

### ISSUE THREAD

**Issue by Xsmael** [sidorares/node-mysql2#966]
Hello, why are there no events for the connection Object ? (correct me if i'm wrong) i went through the docs, but couldn't find it. it exists only for pools, I think it would be very nice if we dont need pools to be able to have events such as connection disconnections.. on the connection object itself.

Thanks.

**Comment by sidorares** [comment]
There are: [connect](https://github.com/sidorares/node-mysql2/blob/791b19d3aed05eefe741b4c27ba66d21b7f3ee19/lib/connection.js#L105), [error](https://github.com/sidorares/node-mysql2/blob/791b19d3aed05eefe741b4c27ba66d21b7f3ee19/lib/connection.js#L212)

**Comment by Xsmael** [comment]
so there are no docs about it ? how about disconnected event ?  or is there a way to check the current state of the connection ?

**Comment by sidorares** [comment]
no docs, feel free to improve

>  how about disconnected event 

You'll listen for "error" to know about unexpected disconnect ( if you close connection yourself you know it's going to happen ). Probably worth adding more explicit event

> is there a way to check the current state of the connection ?

At the moment only by looking at `connection._closing` and `connection._fatalError` properties

**Comment by Xsmael** [comment]
alright thanks i got what i wanted.

> no docs, feel free to improve
 How do I do that?
