### ISSUE TITLE
Pool query/execute prevents script from exiting

### ISSUE THREAD

**Issue by monster1777** [sidorares/node-mysql2#973]
Using this:
**mysql.js**
```
function connection() {
	try {
		const mysql = require('mysql2');

		const pool = mysql.createPool({
			host: 'localhost',
			user: '',
			password: '',
			database: '',
			timezone: 'utc',
			connectionLimit: 100,
			waitForConnections: true,
			queueLimit: 0
		});

		const promisePool = pool.promise();

		return promisePool;
	} catch (error) {
		return console.log(`Could not connect - ${error}`);
	}
}

const pool = connection();

module.exports = {
	connection: async () => pool.getConnection(),
	execute: (...params) => pool.execute(...params),
	query: (...params) => pool.query(...params),
	escape: (...params) => pool.escape(...params)
};
```

script.js
```const db = require('./mysql');
async function testPromises() {
	test = [1, 2, 3, 4, 5, 6, 7, 3, 73, 7, 37, 7, 7];
	await db.query('SELECT * FROM test LIMIT 10');

console.log('after query');
}

testPromises();
```

Script never exits and keeps all records in memory indefinitely, however everything after the query executes too so it doesn't hang on this query.
How can I prevent that?
I also tried:

```
const db = require('./mysql');
async function testPromises() {
	connection = await db.connection();
	let test2 = await connection.query('SELECT * FROM test LIMIT 10');
	connection.release();
	console.log(test2);
}

testPromises();

**Comment by sidorares** [comment]
node process keeps running until there is no active handles in event queue - see some discussion here - https://stackoverflow.com/questions/17960452/how-can-i-get-a-list-of-callbacks-in-the-node-work-queue-or-why-wont-node-ex/17960793#17960793

In your example you need to make sure all network connections are closed. This can be done via `pool.end()`. Add it to your helper as `end: (...params) => pool.end(...params)` and in your script add `connection.end()`

**Comment by monster1777** [comment]
And if I'm running a http server continously, will pool.end() close the entire pool of connections?
Because that would make no sense to use pool then, right?
I've got some huge queries executed by pools and they take very much RAM after I'm done with them, but since the express server still runs it's process RAM usage goes higher and higher every minute.
What would be the alternative to release this one pool? for example
```// RAM usage: 35MB
await db.query('SELECT * FROM test');
// RAM usage: 600MB, doesn't release the data it's holding somewhere, not mysql I think because mysqld shows good ram usage, only the node process

// something like?
db.release();
// RAM usage: 35mb

// tried conn = await db.connection(); conn.query(...); conn.release(); <- doesn't free up the RAM 
```

I'm more concerned now about the RAM usage than node exiting the process - pool.end() works but if it works like I think it works then it wouldn't make sense if I implemented it after each heavy query, because if I think right it would need to recreate the pool and not get connections from existing one

**Comment by sidorares** [comment]
If you run http server you keep the pool open 

With regards to memory usage - you need to profile it and check first that there is no memory leak in your code. Also make sure you don'e fetch more data than you need and filter as much as possible on the mysql server ( don't use `select *`, limit max size, use pagination etc )

**Comment by izzymg** [comment]
For an HTTP server a common practice is to create a module which initializes the connection pool and exports it when it's required, making use of Node's [module caching](https://nodejs.org/api/modules.html#modules_caching) (effectively a singleton pattern). You can hook into something like `process.on("SIGINT", pool.end)` to try to gracefully quit.

**Comment by afwn90cj93201nixr2e1re** [comment]
I think pool already ended up with timeout if here no autostartup modules on server.
`finally`? Not nice solution for scoped variables.

**Comment by kaykhancheckpoint** [comment]
> 

Im having the same issues with RAM/memory constantly increasing, did you ever find out what this was ?

I have to pull in around 300m of memory from the db and proccess it per http requests. Im not doing a lot of these http request, they are generally adhoc. But if i do 3 or 4 in a row, the memory usage keeps increasing and rarely reclaims.

**Comment by kaykhancheckpoint** [comment]
> And if I'm running a http server continously, will pool.end() close the entire pool of connections? Because that would make no sense to use pool then, right? I've got some huge queries executed by pools and they take very much RAM after I'm done with them, but since the express server still runs it's process RAM usage goes higher and higher every minute. What would be the alternative to release this one pool? for example
> 
> ```
> await db.query('SELECT * FROM test');
> // RAM usage: 600MB, doesn't release the data it's holding somewhere, not mysql I think because mysqld shows good ram usage, only the node process
> 
> // something like?
> db.release();
> // RAM usage: 35mb
> 
> // tried conn = await db.connection(); conn.query(...); conn.release(); <- doesn't free up the RAM 
> ```
> 
> I'm more concerned now about the RAM usage than node exiting the process - pool.end() works but if it works like I think it works then it wouldn't make sense if I implemented it after each heavy query, because if I think right it would need to recreate the pool and not get connections from existing one

Im having the same issues with RAM/memory constantly increasing, did you ever find out what this was ?

I have to pull in around 300m of memory from the db and proccess it per http requests. Im not doing a lot of these http request, they are generally adhoc. But if i do 3 or 4 in a row, the memory usage keeps increasing and rarely reclaims.

**Comment by sidorares** [comment]
> I have to pull in around 300m of data from the db

@kaykhancheckpoint try to use streaming api with db, that way it might be possible to avoid keeping in memory the full copy of 300m of data ( you'd need to stream http response as well instead or preparing full JSON object and dumping it at the end )

**Comment by kaykhancheckpoint** [comment]
> > I have to pull in around 300m of data from the db
> 
> @kaykhancheckpoint try to use streaming api with db, that way it might be possible to avoid keeping in memory the full copy of 300m of data ( you'd need to stream http response as well instead or preparing full JSON object and dumping it at the end )

This is not going to work for my use case as i need the entire data to do some processing on it before is end it out.

**Comment by sidorares** [comment]
in that case not much you can do to reduce memory pressure. Maybe use separate pool with a small number of max open connections, that way it'll act as a semaphore reducing the maximum number of the simultaneous requests processing 300mb of data ( and maybe only release back connection when data processing is done, not after the data is received )
