### ISSUE TITLE
Question: MySQL 8 compatibility 

### ISSUE THREAD

**Issue by dublx** [sidorares/node-mysql2#975]
Hi, 
I'm using this module indirectly via dependency from https://github.com/fastify/fastify-mysql.
In there a disclaimer says that MySQL 8.x is not supported, althought I have been using it fine so far.
I raised this question there: https://github.com/fastify/fastify-mysql/issues/24, would be great to get a quick comment on that from the maintainers here.

Thanks!

**Comment by sidorares** [comment]
At the moment default mysql8 auth method is not yet supported ( there is some slow progress in fast-caching_sha2_password branch but last few months I'm quite busy with work and family and don't have much time to focus on this )

You can still use this driver with mysql8 server if you change auth protocol to `mysql_native_password`, the rest of the wire protocol is the same for mysql8, it's just default auth method is different

mysqljs/mysql alsois working on getting this auth supportred, you can track progress here: https://github.com/mysqljs/mysql/pull/1962

For this library as first step I want to add proper full support for auth plugins, and then later add caching_sha2_password as bundled plugin

**Comment by dublx** [comment]
Great, thanks for the quick reply!

**Comment by iblessedi** [comment]
how are things going now? Can I use mysql2 with mysql v.8 ?

**Comment by sidorares** [comment]
@iblessedi yes

**Comment by Shuvo-Hoque** [comment]
@iblessedi did you mean the version of MySQL–8.0?
