### ISSUE TITLE
dateStrings not implemented. 

### ISSUE THREAD

**Issue by JemiloII** [sidorares/node-mysql2#99]
``` js
mysql.createConnection({
    host        : 'localhost',
    user        : 'root',
    password    : 'pass',
    database    : 'dbname',
    dateStrings : 'DATE' //this does nothing
});
```

I tried the other dateStrings commands and they didn't work. So I just installed the original and the dateStrings method works just fine.

**Comment by kbsanders** [comment]
I really only want DATE fields to be treated as strings but not DATETIME fields. I see that [mysqljs/mysql](https://github.com/mysqljs/mysql) now supports an array of types for `dateStrings` in addition to a boolean value. Will we see the same option added to mysql2?

In their [Connection Options](https://github.com/mysqljs/mysql#connection-options):

> dateStrings: Force date types (TIMESTAMP, DATETIME, DATE) to be returned as strings rather than inflated into JavaScript Date objects. Can be true/false **or an array of type names** to keep as strings. (Default: false)

**Comment by sidorares** [comment]
wow, I missed that this was added to mysqljs/mysql

it's relatively simple change - would you like to try adding it @kbsanders ? Let me know if you need any help navigating the code

**Comment by kbsanders** [comment]
@sidorares Thanks for the quick reply. If I find time in the next few days I will submit a PR.

In the meantime, I'm using this workaround of providing a `typeCast` in the options:

```js
// NOTE: only works for .query() calls and not .execute() calls.
typeCast: function ( field, next ) {

    if ( field.type === "DATE" ) {
        return field.string();
    }
    
    return next();
}
```

Along the way I discovered that `typeCast` was only being called for `.query()` and not `.execute()` so I had to refactor my code to use `.query()`. I don't know if this is a limitation of the way prepared statements work or not, but I guess that is a topic for a new issue.

**Comment by sidorares** [comment]
> I don't know if this is a limitation of the way prepared statements work or not, but I guess that is a topic for a new issue.

see discussion in https://github.com/sidorares/node-mysql2/issues/649 and https://github.com/sidorares/node-mysql2/issues/717
