### ISSUE TITLE
How to get errors and results with async update? 

### ISSUE THREAD

**Issue by NealWalters** [sidorares/node-mysql2#999]
Question: The code below is called from another async function that gets the connection and does a query, then calls the UpdatePassword in  a loop.  It display the SqlUpdate variable, which I can run in another tool and it works fine.  

So none of the three is happening: 
 1) No data updated in database 
 2) No err thrown (neither errQuery or the catch err2 
 3) None of the console.logs after the 'await" are displayed. 

```js
async function UpdatePassword(connection, rowID) {
        ... code omitted ...
	console.log("SQL Update=" + sqlUpdate); 
	try 
	{
		var [rows, fields, errQuery] = await connection.query(sqlUpdate);
		if (errQuery) throw errQuery;
		console.log("Back from update");
		console.log("AffectedRows=" + rows.affectedRows);
        } catch (err2) 
         {
   	   console.log("*** Catch Error:") 
           console.log(err2.stack);
         }	
	console.log ("end function"); 
}

```

**Comment by sidorares** [comment]
Interesting. I'd expect at least one of "Back from update" or "*** Catch Error:" to be printed.

Note that `await query()` never returns 3 values, only `[rows, fields]` in case of select and `[insertResult]` for insert/update - see https://github.com/sidorares/node-mysql2/blob/d733583b8a37e54418ea3f0b0e23d0a366e37178/promise.js#L16

**Comment by sidorares** [comment]
Could you try adding try/catch around https://github.com/sidorares/node-mysql2/blob/d733583b8a37e54418ea3f0b0e23d0a366e37178/promise.js#L95-L99 to see it's not some runaway sync exception?

Also if possible can you share what's inside `sqlUpdate`?

**Comment by NealWalters** [comment]
Adding the try/catch didn't show anything (I put a console.log in that catch). 

Coming from Microsoft C#, it's confusing to me to have different return parms from .query; I'm used to running .executeQuery for updates and using dataSet.Fill or DataReader for queries.  I google for examples, and I think a lot of what I found was wrong or misleading. 

I cloned the WordPress wp_users table from an old WordPress site, and moving to AWS to build my own CMS.  So I'm resetting passwords with salt and pepper logic.  user_pass is varchar(255)  and user_pass_Salt is varchar(45).  Something looks wrong with the salt being in the hash, but working on that with bcrypt.

update wp_users 
set user_pass = '$2b$10$eIUVP/S8vxhatZypDXL0PuabFPR4VPJASZDRGWrPBlkj38O3qMTQq', user_pass_salt = '$2b$10$eIUVP/S8vxhatZypDXL0Pu' 
where ID = 1

I think this is a fairly common pattern.  Run a query to retrieve all the users. 
Look through each result (user) and update each row based on values in the row; specifically create a new random password, hash it,  and update the same row in the table with the hashed-password, and the salt field. 

So I'm already in an Async routine doing the query. I'm using ASync because I'm running this like a batch utility script; there is no user interaction. 


                var query = "select ID, user_nicename from wp_users limit 3 ";
		var [rows, fields] = await connection.query (query); 
		rows.map(row=>
		{
			console.log(); 
			console.log("*** ROW:" + row.ID + " " + row.user_nicename);
			
			UpdatePassword(connection, row.ID);
               }

If I try to put the update code inline above, (replace UpdatePassword with the full code), then because I'm in a "arrow function" it's apparently not async, even though started from an async function. 

>                                         var [rows, fields] = await connection.qu
> ery(sqlUpdate);
>                                                              ^^^^^
> SyntaxError: await is only valid in async function. 

Thanks
Neal

**Comment by sidorares** [comment]
> because I'm in a "arrow function" it's apparently not async, even though started from an async function.

Yes, your map callback is not async. The easiest way to perform async code on all rows sequentially is just to use for loop:

```js
for (let r=0; r < rows.length; ++r) {
  await UpdatePassword(connection, rows[r].ID);
}
```

**Comment by NealWalters** [comment]
Perfect, thanks!

**Comment by sidorares** [comment]
I'm still very curious what's causing original issue ( not reaching "Back from update" or "*** Catch Error:" ) - I could not reproduce it locally myself with similar setup

**Comment by sidorares** [comment]
One "functional" way to iterate sequentially similar to map ( imo slightly less readable then for loop ):

```js
await rows.reduce( async (previousPromise, row) => {
  await previousPromise;
  return UpdatePassword(row.ID);
}, Promise.resolve());
```
